GeoSPARQLSRSExtension: CoordinateSystem Class Reference
CoordinateSystem Class Reference
Public Member Functions
String toString ()
String toProj ()
JSONObject toProjJSON ()
String toWKT ()
Public Attributes
List< Axis > axisList =new LinkedList<Axis>()
String coordinateSystemType
Integer numberDimensions
Member Function Documentation
toProj()
String toProj ()
{
                 StringBuilder builder=new StringBuilder();
                 return builder.toString();
         }
toProjJSON()
JSONObject toProjJSON ()
{
                 JSONObject cs=new JSONObject();
                 cs.put("type", "CoordinateSystem");
                 cs.put("subtype", coordinateSystemType);
                 cs.put("axis", new JSONArray());
                 for(Axis axis:axisList) {
                         cs.getJSONArray("axis").put(axis.toProjJSON());
                 }
                 return cs;
         }
References CoordinateSystem.axisList, and CoordinateSystem.coordinateSystemType.
Referenced by CoordinateReferenceSystem.toProjJSON().
toString()
String toString ()
{
                 return "CoordinateSystem [axisList=" + axisList + ", coordinateSystemType=" + coordinateSystemType
                                 + ", numberDimensions=" + numberDimensions + "]";
         }
References CoordinateSystem.axisList, CoordinateSystem.coordinateSystemType, and CoordinateSystem.numberDimensions.
toWKT()
String toWKT ()
{
                 StringBuilder builder=new StringBuilder();
                 if(coordinateSystemType==null)
                         return builder.toString();
                 builder.append("CS["+System.lineSeparator());
                 if(coordinateSystemType.contains("CS:")) {
                         builder.append(coordinateSystemType.substring(coordinateSystemType.lastIndexOf(':')+1).trim()+System.lineSeparator());
                 }else {
                         builder.append(coordinateSystemType+System.lineSeparator());
                 }
                 builder.append(","+numberDimensions+"],");
                 for(Axis axis:axisList) {
                         builder.append(axis.toWKT()+",");
                 }
                 builder.delete(builder.length()-1, builder.length());
                 return builder.toString()+System.lineSeparator();
         }
References CoordinateSystem.axisList, CoordinateSystem.coordinateSystemType, and CoordinateSystem.numberDimensions.
Referenced by CoordinateReferenceSystem.toWKT().
Member Data Documentation
axisList
List<Axis> axisList =new LinkedList<Axis>()
Referenced by RDFCRSToWKT.downliftSytem(), CoordinateSystem.toProjJSON(), CoordinateSystem.toString(), and CoordinateSystem.toWKT().
coordinateSystemType
String coordinateSystemType
Referenced by RDFCRSToWKT.downliftSytem(), CoordinateSystem.toProjJSON(), CoordinateSystem.toString(), and CoordinateSystem.toWKT().
numberDimensions
Integer numberDimensions
Referenced by RDFCRSToWKT.downliftSytem(), CoordinateSystem.toString(), and CoordinateSystem.toWKT().