GeoSPARQL SRS Extension: LiteralUtils Class Reference
LiteralUtils Class Reference
Static Public Member Functions
static Wrapper rasterOrVector (NodeValue v)
static Double maxRasterValue (GridCoverage raster, Integer bandnum)
static Double arithmeticMeanRasterValue (GridCoverage raster, Integer bandnum)
static Double minRasterValue (GridCoverage raster, Integer bandnum)
static Boolean containsRasterValue (GridCoverage raster, Integer bandnum, Double value)
static Coordinate worldToRaster (GridCoverage raster, Double latitude, Double longitude) throws MismatchedDimensionException, TransformException
static Coordinate worldToRaster (CoverageWrapper wrapper, Double latitude, Double longitude) throws MismatchedDimensionException, TransformException
static GridCoverage cropRaster2 (GridCoverage raster, Double width, Double height, Double x, Double y) throws MismatchedDimensionException, TransformException
static NodeValue cropRaster (CoverageWrapper wrapper, Double width, Double height, Double x, Double y) throws MismatchedDimensionException, TransformException
static NodeValue createEmptyRaster (Double width, Double height, Double upperleftx, Double upperlefty, Double val)
static Geometry getCorrectVectorRepresentation (Wrapper wrapper)
static Geometry toGeometry (final Envelope2D envelope)
static Geometry toGeometry (final OctagonalEnvelope envelope)
static Geometry toGeometry (final Envelope envelope)
static Geometry toGeometry (final org.opengis.geometry.Envelope envelope)
static Geometry toGeometry (final Rectangle envelope)
static GeometryWrapper createGeometry (List< Coordinate > coordinates, String geomtype, GeometryWrapper geometry)
static GeometryWrapper createGeometry (Coordinate[] coordarray, String geomtype, GeometryWrapper geometry)
Member Function Documentation
arithmeticMeanRasterValue()
static Double arithmeticMeanRasterValue (GridCoverage raster, Integer bandnum) static
{
                 RenderedImage rendered=raster.render(null);
                 Double sum=0.,counter=0.;
         for(int i=0;i<rendered.getSampleModel().getWidth();i++) {
                 for(int j=0;j<rendered.getSampleModel().getHeight();j++) {
                         sum+=(double) rendered.getData().getSample(i, j, bandnum);
                         counter++;
                 }
         }
         System.out.println("MeanRasterVal: "+(sum/counter));
                 return (sum/counter);
         }
containsRasterValue()
static Boolean containsRasterValue (GridCoverage raster, Integer bandnum, Double value) static
{
                 RenderedImage rendered=raster.render(null);
                 for(int i=0;i<rendered.getSampleModel().getWidth();i++) {
                         for(int j=0;j<rendered.getSampleModel().getHeight();j++) {
                                 if(rendered.getData().getSample(i, j, bandnum)==value) {
                                         return true;
                                 }
                         }
                 }
                 return false;
         }
createEmptyRaster()
static NodeValue createEmptyRaster (Double width, Double height, Double upperleftx, Double upperlefty, Double val) static
{
                 Double pixelsize;
                 WritableRaster raster;
                 if(width.intValue()<=0 || height.intValue()<=0) {
                         raster = RasterFactory.createBandedRaster(DataBuffer.TYPE_FLOAT, 2, 2, 1, null);
                 }else {
                         raster = RasterFactory.createBandedRaster(DataBuffer.TYPE_FLOAT, width.intValue(), height.intValue(), 1, null);
                 }
                 for (int y = 0; y < height; y++) {
                         for (int x = 0; x < width; x++) {
                                 raster.setSample(x, y, 0, val);
                         }
                 }
                 //CoordinateReferenceSystem crs = CommonCRS.WGS84.defaultGeographic();
                 CoordinateReferenceSystem crss=null;
                 Envelope2D envelope=null;
                 try {
                         crss = CRS.forCode("EPSG:4326");
                         envelope = new Envelope2D(crss, 0, 0, 30, 30);
                 } catch (FactoryException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                         envelope = new Envelope2D(CommonCRS.WGS84.defaultGeographic(), 0, 0, 30, 30);
                 }
         GridExtent extent=new GridExtent(raster.getWidth(), raster.getHeight());
         GridGeometry gridgeom=new GridGeometry(extent, PixelInCell.CELL_CENTER, null, crss);
         List<SampleDimension> dimensions=new LinkedList<SampleDimension>();
         DefaultNameFactory fac=new DefaultNameFactory();
         for(int i=0;i<raster.getNumBands();i++) {
                 dimensions.add(new SampleDimension(fac.createGenericName(null,  "Dimension "+i),0.,new LinkedList<Category>()));
         }
         BufferedGridCoverage coverage=new BufferedGridCoverage(
                         gridgeom, dimensions, raster.getDataBuffer());
                 return CoverageWrapper.createCoverage(coverage, "EPSG:4326", HexWKBDatatype.URI.toString()).asNodeValue();
         }
References CoverageWrapper.asNodeValue(), CoverageWrapper.createCoverage(), and HexWKBDatatype.URI.
createGeometry() [1/2]
static GeometryWrapper createGeometry (Coordinate[] coordarray, String geomtype, GeometryWrapper geometry) static
{
                         return createGeometry(Arrays.asList(coordarray), geomtype, geometry);
                 }
References LiteralUtils.createGeometry().
createGeometry() [2/2]
static GeometryWrapper createGeometry (List< Coordinate > coordinates, String geomtype, GeometryWrapper geometry) static
{
                         switch(geomtype) {
                         case "Point":
                                 return GeometryWrapperFactory.createPoint(coordinates.get(0), geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "MultiPoint":
                                 return GeometryWrapperFactory.createMultiPoint(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "LineString":
                                 return GeometryWrapperFactory.createLineString(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "Polygon":
                                 return GeometryWrapperFactory.createPolygon(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "MultiLineString":
                                 List<LineString> list=new LinkedList<LineString>();
                                 list.add((LineString)GeometryWrapperFactory.createLineString(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI()).getXYGeometry());
                                 return GeometryWrapperFactory.createMultiLineString(list, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "MultiPolygon":
                                 List<Polygon> plist=new LinkedList<Polygon>();
                                 plist.add((Polygon)GeometryWrapperFactory.createPolygon(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI()).getXYGeometry());
                                 return GeometryWrapperFactory.createMultiPolygon(plist, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         default:
                                 return null;
                         }
                 }
References GeometryWrapper.getGeometryDatatypeURI(), and GeometryWrapper.getSrsURI().
Referenced by LiteralUtils.createGeometry().
cropRaster()
static NodeValue cropRaster (CoverageWrapper wrapper, Double width, Double height, Double x, Double y) throws MismatchedDimensionException, TransformException static
{
                  GridCoverage raster=wrapper.getXYGeometry();
                  Coordinate coord=worldToRaster(wrapper, x, y);
                  Coordinate coord2=worldToRaster(wrapper, x+width, y+height);
                  Double xx=coord.getX();
                  Double yy=coord.getY();
                  xx=Double.valueOf(xx.intValue())-1;
                  yy=Double.valueOf(yy.intValue())-1;
                  Double widthh=coord2.getX()-x;
                  Double heightt=coord2.getY()-y;
                  ParameterBlock pbSubtracted = new ParameterBlock();
              pbSubtracted.addSource(raster.render(null));
              pbSubtracted.add(xx.floatValue());
              pbSubtracted.add(yy.floatValue());
              pbSubtracted.add(widthh.floatValue());
              pbSubtracted.add(heightt.floatValue());
              System.out.println(raster.render(null).getWidth()+" "+raster.render(null).getHeight());
              System.out.println(xx+" "+yy+" "+widthh+" "+heightt);
              RenderedOp subtractedImage = JAI.create("crop",pbSubtracted);
              final SampleDimension sd =raster.getSampleDimensions().get(0);
                         List<SampleDimension>sds=new LinkedList<SampleDimension>();
                         sds.add(sd);
                 GridExtent extent=new GridExtent(subtractedImage.getWidth(), subtractedImage.getHeight());
                 GridGeometry gridgeom=new GridGeometry(extent, PixelInCell.CELL_CENTER, raster.getGridGeometry().getGridToCRS(PixelInCell.CELL_CENTER), raster.getCoordinateReferenceSystem());
                 List<SampleDimension> dimensions=new LinkedList<SampleDimension>();
                 DefaultNameFactory fac=new DefaultNameFactory();
                 for(int i=0;i<subtractedImage.getNumBands();i++) {
                         dimensions.add(new SampleDimension(fac.createGenericName(null,  "Dimension "+i),0.,new LinkedList<Category>()));
                 }
                 BufferedGridCoverage coverage=new BufferedGridCoverage(
                                 gridgeom, dimensions, subtractedImage.getData().getDataBuffer());
                         return CoverageWrapper.createCoverage((GridCoverage)coverage, wrapper.getSrsURI(), wrapper.getRasterDatatypeURI())
                                         .asNodeValue();
         }
References CoverageWrapper.asNodeValue(), CoverageWrapper.createCoverage(), and LiteralUtils.worldToRaster().
cropRaster2()
static GridCoverage cropRaster2 (GridCoverage raster, Double width, Double height, Double x, Double y) throws MismatchedDimensionException, TransformException static
{
                  Coordinate coord=worldToRaster(raster, x, y);
                  Coordinate coord2=worldToRaster(raster, x+width, y+height);
                  Double xx=coord.getX();
                  Double yy=coord.getY();
                  xx=Double.valueOf(xx.intValue())-1;
                  yy=Double.valueOf(yy.intValue())-1;
                  Double widthh=coord2.getX()-x;
                  Double heightt=coord2.getY()-y;
                  if(widthh==0)
                          widthh=1.;
                  if(heightt==0)
                          heightt=1.;
              RenderedImage rendered = raster.render(null);
                  ParameterBlock pbSubtracted = new ParameterBlock();
              pbSubtracted.addSource(rendered);
              pbSubtracted.add(xx.floatValue());
              pbSubtracted.add(yy.floatValue());
              pbSubtracted.add(widthh.floatValue());
              pbSubtracted.add(heightt.floatValue());
              System.out.println(rendered.getMinX()+" "+rendered.getMinY());
              System.out.println(rendered.getWidth()+" "+rendered.getHeight());
              System.out.println(xx+" "+yy+" "+widthh+" "+heightt);
              RenderedOp subtractedImage = JAI.create("crop",pbSubtracted);
                         final SampleDimension sd =raster.getSampleDimensions().get(0);
                         List<SampleDimension>sds=new LinkedList<SampleDimension>();
                         sds.add(sd);
                 GridExtent extent=new GridExtent(subtractedImage.getWidth(), subtractedImage.getHeight());
                 GridGeometry gridgeom=new GridGeometry(extent, PixelInCell.CELL_CENTER, raster.getGridGeometry().getGridToCRS(PixelInCell.CELL_CENTER), raster.getCoordinateReferenceSystem());
                 List<SampleDimension> dimensions=new LinkedList<SampleDimension>();
                 DefaultNameFactory fac=new DefaultNameFactory();
                 for(int i=0;i<subtractedImage.getNumBands();i++) {
                         dimensions.add(new SampleDimension(fac.createGenericName(null,  "Dimension "+i),0.,new LinkedList<Category>()));
                 }
                 BufferedGridCoverage coverage=new BufferedGridCoverage(
                                 gridgeom, dimensions, subtractedImage.getData().getDataBuffer());
                         return coverage;
         }
References LiteralUtils.worldToRaster().
getCorrectVectorRepresentation()
static Geometry getCorrectVectorRepresentation (Wrapper wrapper) static
{
                 if(wrapper instanceof GeometryWrapper) {
                         return ((GeometryWrapper) wrapper).getXYGeometry();
                 }else {
                         return toGeometry(((CoverageWrapper) wrapper).getParsingGeometry().getGridGeometry().getEnvelope());
                 }
         }
References LiteralUtils.toGeometry().
maxRasterValue()
static Double maxRasterValue (GridCoverage raster, Integer bandnum) static
{
                 RenderedImage rendered=raster.render(null);
                 Double maxVal=Double.MIN_VALUE;
         for(int i=0;i<rendered.getSampleModel().getWidth();i++) {
                 for(int j=0;j<rendered.getSampleModel().getHeight();j++) {
                         if(rendered.getData().getSample(i, j, bandnum)>maxVal) {
                                 maxVal=(double) rendered.getData().getSample(i, j, bandnum);
                         }
                 }
         }
         System.out.println("MaxRasterVal: "+maxVal);
         return maxVal;
         }
minRasterValue()
static Double minRasterValue (GridCoverage raster, Integer bandnum) static
{
                 RenderedImage rendered=raster.render(null);
                 Double maxVal=Double.MAX_VALUE;
                 for(int i=0;i<rendered.getSampleModel().getWidth();i++) {
                         for(int j=0;j<rendered.getSampleModel().getHeight();j++) {
                                 if(rendered.getData().getSample(i, j, bandnum)<maxVal) {
                                         maxVal=(double) rendered.getData().getSample(i, j, bandnum);
                                 }
                         }
                 }
         System.out.println("MinRasterVal: "+maxVal);
                 return maxVal;
         }
rasterOrVector()
static Wrapper rasterOrVector (NodeValue v) static
{
                 GeometryDatatype datatype=null;
                 try {
                         datatype=GeometryDatatype.get(v.getDatatypeURI());
                 }catch(Exception e) {
                         datatype=null;
                 }
                         if(datatype==null) {
                                 RasterDataType rdatatype=RasterDataType.get(v.getDatatypeURI());
                                 if(rdatatype==null) {
                                         throw new AssertionError("No valid raster or vector geometry definition given!");
                                 }else {
                                         return CoverageWrapper.extract(v);
                                 }
                         }else{
                                 return  GeometryWrapper.extract(v);
                         }
         }
References CoverageWrapper.extract(), GeometryWrapper.extract(), GeometryDatatype.get(), and RasterDataType.get().
toGeometry() [1/5]
static Geometry toGeometry (final Envelope envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMinY())
                 }), null);
     }
toGeometry() [2/5]
static Geometry toGeometry (final Envelope2D envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMinY())
                 }), null);
     }
Referenced by LiteralUtils.getCorrectVectorRepresentation().
toGeometry() [3/5]
static Geometry toGeometry (final OctagonalEnvelope envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMinY())
                 }), null);
     }
toGeometry() [4/5]
static Geometry toGeometry (final org.opengis.geometry.Envelope envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinimum(0), envelope.getMinimum(1)),
                     new Coordinate(envelope.getMaximum(0), envelope.getMinimum(1)),
                     new Coordinate(envelope.getMaximum(0), envelope.getMaximum(1)),
                     new Coordinate(envelope.getMinimum(0), envelope.getMaximum(1)),
                     new Coordinate(envelope.getMinimum(0), envelope.getMinimum(1))
                 }), null);
     }
toGeometry() [5/5]
static Geometry toGeometry (final Rectangle envelope) static
{
                 GeometryFactory gf = new GeometryFactory();
                 return gf.createPolygon(gf.createLinearRing(
                         new Coordinate[]{
                             new Coordinate(envelope.getMinX(), envelope.getMinY()),
                             new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                             new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                             new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                             new Coordinate(envelope.getMinX(), envelope.getMinY())
                         }), null);
             }
worldToRaster() [1/2]
static Coordinate worldToRaster (CoverageWrapper wrapper, Double latitude, Double longitude) throws MismatchedDimensionException, TransformException static
{
          GridCoverage raster=wrapper.getXYGeometry();
          GridGeometry gg2D = raster.getGridGeometry();
          MathTransform gridToCRS = gg2D.getGridToCRS(PixelInCell.CELL_CENTER);
          MathTransform crsToGrid = gridToCRS.inverse();
          DirectPosition realPos=new DirectPosition2D(latitude, longitude);
          DirectPosition gridPos = new DirectPosition2D();
          DirectPosition res=crsToGrid.transform(realPos, gridPos);
          Coordinate coord=new Coordinate(res.getCoordinate()[0],res.getCoordinate()[1]);
          return coord;
         }
worldToRaster() [2/2]
static Coordinate worldToRaster (GridCoverage raster, Double latitude, Double longitude) throws MismatchedDimensionException, TransformException static
{
          GridGeometry gg2D = raster.getGridGeometry();
          MathTransform gridToCRS = gg2D.getGridToCRS(PixelInCell.CELL_CENTER);
          MathTransform crsToGrid = gridToCRS.inverse();
          DirectPosition realPos=new DirectPosition2D(latitude, longitude);
          DirectPosition gridPos = new DirectPosition2D();
          DirectPosition res=crsToGrid.transform(realPos, gridPos);
          Coordinate coord=new Coordinate(res.getCoordinate()[0],res.getCoordinate()[1]);
          return coord;
         }
Referenced by LiteralUtils.cropRaster(), and LiteralUtils.cropRaster2().