GeoSPARQL SRS Extension: EncodedPolylineDatatype Class Reference
EncodedPolylineDatatype Class Reference
WKTDatatype class allows the URI "geo:wktLiteral" to be used as a datatype and it will parse that datatype to a JTS Geometry.
Public Member Functions
String unparse (Object geometry)
This method Un-parses the JTS Geometry to the WKT literal.
GeometryWrapper read (String geometryLiteral)
String toString ()
final GeometryWrapper parse (String lexicalForm) throws DatatypeFormatException
This method Parses the Geometry Literal to the JTS Geometry.
final GeometryWrapper parse (String lexicalForm, GeometryIndex targetIndex) throws DatatypeFormatException
Static Public Member Functions
static String encodePolyline (final LineString linestring)
Encodes a sequence of LatLngs into an encoded path string.
static List< Coordinate > decodePolyline (String polyline, int precision)
static final void registerDatatypes ()
static final GeometryDatatype get (RDFDatatype rdfDatatype)
static final GeometryDatatype get (String datatypeURI)
static final boolean checkURI (String datatypeURI)
static final boolean check (RDFDatatype rdfDatatype)
Static Public Attributes
static final String URI = SRSGeo.EncodedPolyline
The default WKT type URI.
static final EncodedPolylineDatatype INSTANCE = new EncodedPolylineDatatype()
A static instance of WKTDatatype.
Private Member Functions
EncodedPolylineDatatype ()
private constructor - single global instance.
Static Private Member Functions
static void encode (long v, StringBuffer result)
Static Private Attributes
static final Logger LOGGER = LoggerFactory.getLogger(EncodedPolylineDatatype.class)
static final TypeMapper TYPE_MAPPER = TypeMapper.getInstance()
static boolean isDatatypesRegistered = false
Detailed Description
WKTDatatype class allows the URI "geo:wktLiteral" to be used as a datatype and it will parse that datatype to a JTS Geometry.
Req 10 All RDFS Literals of type geo:wktLiteral shall consist of an optional URI identifying the coordinate reference system followed by Simple Features Well Known Text (WKT) describing a geometric value. Valid geo:wktLiterals are formed by concatenating a valid, absolute URI as defined in [RFC 2396], one or more spaces (Unicode U+0020 character) as a separator, and a WKT string as defined in Simple Features [ISO 19125-1].
Req 11 The URI
<http://www.opengis.net/def/crs/OGC/1.3/CRS84>
shall be assumed as the spatial reference system for geo:wktLiterals that do not * specify an explicit spatial reference system URI.
Constructor & Destructor Documentation
EncodedPolylineDatatype()
EncodedPolylineDatatype () private
private constructor - single global instance.
{
         super(URI);
     }
References EncodedPolylineDatatype.URI.
Member Function Documentation
check()
static final boolean check (RDFDatatype rdfDatatype) static inherited
{
         //Ensure that the registered datatypes from the type mapper are used.
         return checkURI(rdfDatatype.getURI());
     }
References GeometryDatatype.checkURI().
checkURI()
static final boolean checkURI (String datatypeURI) static inherited
{
         registerDatatypes();
         RDFDatatype rdfDatatype = TYPE_MAPPER.getTypeByName(datatypeURI);
         if (rdfDatatype != null) {
             return rdfDatatype instanceof GeometryDatatype;
         } else {
             throw new DatatypeFormatException("Datatype not found: " + datatypeURI + " Ensure that GeoSPARQL is enabled and Datatype has been registered.");
         }
     }
References GeometryDatatype.GeometryDatatype(), GeometryDatatype.registerDatatypes(), and GeometryDatatype.TYPE_MAPPER.
Referenced by GeometryDatatype.check(), and GeometryDatatype.get().
decodePolyline()
static List<Coordinate> decodePolyline (String polyline, int precision) static
      {
          List<Coordinate> coordinates = new ArrayList<Coordinate>();
          int index = 0, shift, result;
          int byte_;
          int lat = 0, lng = 0, latitude_change, longitude_change,
              factor = (int) Math.pow(10, precision);
          while (index < polyline.length()) {
              byte_ = 0;
              shift = 0;
              result = 0;
              do {
                  byte_ = polyline.charAt(index++) - 63;
                  result |= (byte_ & 0x1f) << shift;
                  shift += 5;
              } while (byte_ >= 0x20);
              latitude_change = ((result % 2 == 1) ? ~(result >> 1) : (result >> 1));
              shift = result = 0;
              do {
                  byte_ = polyline.charAt(index++) - 63;
                  result |= (byte_ & 0x1f) << shift;
                  shift += 5;
              } while (byte_ >= 0x20);
              longitude_change = ((result % 2 == 1) ? ~(result >> 1) : (result >> 1));
              lat += latitude_change;
              lng += longitude_change;
              coordinates.add(new Coordinate((double)lat / factor,(double)lng / factor));
          }
          return coordinates;
      }
Referenced by EncodedPolylineDatatype.read().
encode()
static void encode (long v, StringBuffer result) static private
{
         v = v < 0 ? ~(v << 1) : v << 1;
         while (v >= 0x20) {
             result.append(Character.toChars((int) ((0x20 | (v & 0x1f)) + 63)));
             v >>= 5;
         }
         result.append(Character.toChars((int) (v + 63)));
     }
Referenced by EncodedPolylineDatatype.encodePolyline().
encodePolyline()
static String encodePolyline (final LineString linestring) static
Encodes a sequence of LatLngs into an encoded path string.
Modified from https://gitlab.com/aceperry/androidmapsutil Apache License 2.0
{
         long lastLat = 0;
         long lastLng = 0;
         final StringBuffer result = new StringBuffer();
         for (final Coordinate point : linestring.getCoordinates()) {
             long lat = Math.round(point.x * 1e5);
             long lng = Math.round(point.y * 1e5);
             long dLat = lat - lastLat;
             long dLng = lng - lastLng;
             encode(dLat, result);
             encode(dLng, result);
             lastLat = lat;
             lastLng = lng;
         }
         return result.toString();
     }
References EncodedPolylineDatatype.encode().
Referenced by EncodedPolylineDatatype.unparse().
get() [1/2]
static final GeometryDatatype get (RDFDatatype rdfDatatype) static inherited
{
         registerDatatypes();
         //System.out.println(rdfDatatype);
         //Iterator it=TYPE_MAPPER.listTypes();
         /*while(it.hasNext()) {
                 System.out.println(it.next());
         }*/
         if (rdfDatatype instanceof GeometryDatatype) {
             return (GeometryDatatype) rdfDatatype;
         } else {
             throw new DatatypeFormatException("Unrecognised Geometry Datatype: " + rdfDatatype.getURI() + " Ensure that Datatype is extending GeometryDatatype.");
         }
     }
References GeometryDatatype.registerDatatypes().
Referenced by GeometryWrapper.asLiteral(), GeometryWrapper.extract(), GeometryDatatype.get(), GeometryWrapper.getGeometryDatatype(), and LiteralUtils.rasterOrVector().
get() [2/2]
static final GeometryDatatype get (String datatypeURI) static inherited
{
         checkURI(datatypeURI);
         RDFDatatype rdfDatatype = TYPE_MAPPER.getTypeByName(datatypeURI);
         return GeometryDatatype.get(rdfDatatype);
     }
References GeometryDatatype.checkURI(), GeometryDatatype.get(), and GeometryDatatype.TYPE_MAPPER.
parse() [1/2]
final GeometryWrapper parse (String lexicalForm) throws DatatypeFormatException inherited
This method Parses the Geometry Literal to the JTS Geometry.
Parameters
lexicalForm - the Geometry Literal to be parsed
Returns
geometry - if the Geometry Literal is valid.
empty geometry - if the Geometry Literal is empty.
null - if the Geometry Literal is invalid.
{
         return parse(lexicalForm, GeometryIndex.PRIMARY);
     }
References GeometryLiteralIndex.GeometryIndex.PRIMARY.
Referenced by GeometryWrapper.extract().
parse() [2/2]
final GeometryWrapper parse (String lexicalForm, GeometryIndex targetIndex) throws DatatypeFormatException inherited
{
         //Check the Geometry Literal Index to see if been previously read and cached.
         //DatatypeReader interface used to instruct index on how to obtain the GeometryWrapper.
         try {
             return GeometryLiteralIndex.retrieve(lexicalForm, this, targetIndex);
         } catch (IllegalArgumentException ex) {
             throw new DatatypeFormatException(ex.getMessage() + " - Illegal Geometry Literal: " + lexicalForm);
         }
     }
References GeometryLiteralIndex.retrieve().
read()
GeometryWrapper read (String geometryLiteral)
Reimplemented from GeometryDatatype.
{
             GeometryWrapper wrapper = GeometryWrapperFactory.createLineString(decodePolyline(geometryLiteral, 5), "<http://www.opengis.net/def/crs/EPSG/0/4326>", EncodedPolylineDatatype.URI);
             return wrapper;
     }
References EncodedPolylineDatatype.decodePolyline(), and EncodedPolylineDatatype.URI.
registerDatatypes()
static final void registerDatatypes () static inherited
{
         //System.out.println("Is")
         //if (!isDatatypesRegistered) {
             TYPE_MAPPER.registerDatatype(WKTDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GMLDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GeoJSONDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(KMLDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(WKBDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(TWKBDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(TopoJSONDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(GeobufDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(GeoHashDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(EncodedPolylineDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(HexWKBDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GeoURIDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(GPXDatatype.INSTANCE);
             isDatatypesRegistered = true;
         //}
     }
References EncodedPolylineDatatype.INSTANCE, GeoJSONDatatype.INSTANCE, GeoURIDatatype.INSTANCE, HexWKBDatatype.INSTANCE, KMLDatatype.INSTANCE, WKBDatatype.INSTANCE, GeometryDatatype.isDatatypesRegistered, and GeometryDatatype.TYPE_MAPPER.
Referenced by GeometryDatatype.checkURI(), and GeometryDatatype.get().
toString()
String toString ()
{
         return "EncodedPolylineDatatype{" + URI + '}';
     }
References EncodedPolylineDatatype.URI.
unparse()
String unparse (Object geometry)
This method Un-parses the JTS Geometry to the WKT literal.
Parameters
geometry - the JTS Geometry to be un-parsed
Returns
WKT - the returned WKT Literal.
Notice that the Spatial Reference System is not specified in returned WKT literal.
{
         if (geometry instanceof GeometryWrapper) {
             GeometryWrapper geometryWrapper = (GeometryWrapper) geometry;
             if(geometryWrapper.getXYGeometry().getGeometryType().equals("LineString")){
                 return encodePolyline((LineString)geometryWrapper.getXYGeometry());
             }else {
                 throw new AssertionError("Object passed to EncodedPolylineDatatype is not a LineString: " + geometry);
             }
         } else {
             throw new AssertionError("Object passed to EncodedPolylineDatatype is not a GeometryWrapper: " + geometry);
         }
     }
References EncodedPolylineDatatype.encodePolyline(), and GeometryWrapper.getXYGeometry().
Member Data Documentation
INSTANCE
final EncodedPolylineDatatype INSTANCE = new EncodedPolylineDatatype() static
A static instance of WKTDatatype.
Referenced by GeometryDatatype.registerDatatypes().
isDatatypesRegistered
boolean isDatatypesRegistered = false static private inherited
Referenced by GeometryDatatype.registerDatatypes().
LOGGER
final Logger LOGGER = LoggerFactory.getLogger(EncodedPolylineDatatype.class) static private
TYPE_MAPPER
final TypeMapper TYPE_MAPPER = TypeMapper.getInstance() static private inherited
Referenced by GeometryDatatype.checkURI(), GeometryDatatype.get(), and GeometryDatatype.registerDatatypes().
URI
final String URI = SRSGeo.EncodedPolyline static
The default WKT type URI.
Referenced by EncodedPolylineDatatype.EncodedPolylineDatatype(), EncodedPolylineDatatype.read(), and EncodedPolylineDatatype.toString().