GeoSPARQL SRS Extension: PolyshapeReader.XReader Class Reference
PolyshapeReader.XReader Class Reference
from Apache 2.0 licensed: https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/PolyUtil.java
Public Member Functions
XReader (final Reader input, GeometryFactory shpFactory) throws IOException
Coordinate[] readPoints () throws IOException
double readLat () throws IOException
double readLng () throws IOException
double readDouble () throws IOException
int peek ()
char readKey () throws IOException
boolean isData ()
boolean isDone ()
boolean isEvent ()
Package Functions
int readInt () throws IOException
Package Attributes
int lat = 0
int lng = 0
int head = -1
final Reader input
final GeometryFactory shpFactory
Detailed Description
from Apache 2.0 licensed: https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/PolyUtil.java
Constructor & Destructor Documentation
XReader()
XReader (final Reader input, GeometryFactory shpFactory) throws IOException
{
       this.input = input;
       this.shpFactory = shpFactory;
       head = input.read();
     }
References PolyshapeReader.XReader.head, PolyshapeReader.XReader.input, and PolyshapeReader.XReader.shpFactory.
Member Function Documentation
isData()
boolean isData ()
{
       return head >= '?';
     }
References PolyshapeReader.XReader.head.
Referenced by PolyshapeReader.XReader.readPoints().
isDone()
boolean isDone ()
{
       return head < 0;
     }
References PolyshapeReader.XReader.head.
isEvent()
boolean isEvent ()
{
       return head > 0 && head < '?';
     }
References PolyshapeReader.XReader.head.
peek()
int peek ()
                       {
       return head;
     }
References PolyshapeReader.XReader.head.
readDouble()
double readDouble () throws IOException
{
       return readInt() * 1e-5;
     }
References PolyshapeReader.XReader.readInt().
readInt()
int readInt () throws IOException package
     {
       int b;
       int result = 1;
       int shift = 0;
       do {
         b = head - 63 - 1;
         result += b << shift;
         shift += 5;
         head = input.read();
       } while (b >= 0x1f);
       return (result & 1) != 0 ? ~(result >> 1) : (result >> 1);
     }
References PolyshapeReader.XReader.head, and PolyshapeReader.XReader.input.
Referenced by PolyshapeReader.XReader.readDouble(), PolyshapeReader.XReader.readLat(), and PolyshapeReader.XReader.readLng().
readKey()
char readKey () throws IOException
{
       lat = lng = 0; // reset the offset
       char key = (char)head;
       head = input.read();
       return key;
     }
References PolyshapeReader.XReader.head, PolyshapeReader.XReader.input, PolyshapeReader.XReader.lat, and PolyshapeReader.XReader.lng.
readLat()
double readLat () throws IOException
{
       lat += readInt();
       return lat * 1e-5;
     }
References PolyshapeReader.XReader.lat, and PolyshapeReader.XReader.readInt().
Referenced by PolyshapeReader.XReader.readPoints().
readLng()
double readLng () throws IOException
{
       lng += readInt();
       return lng * 1e-5;
     }
References PolyshapeReader.XReader.lng, and PolyshapeReader.XReader.readInt().
Referenced by PolyshapeReader.XReader.readPoints().
readPoints()
Coordinate [] readPoints () throws IOException
{
       List<Coordinate> coords=new ArrayList<Coordinate>();
       while(isData()) {
           coords.add(new Coordinate(readLat(),readLng()));
       }
       return coords.toArray(new Coordinate[0]);
     }
References PolyshapeReader.XReader.isData(), PolyshapeReader.XReader.readLat(), and PolyshapeReader.XReader.readLng().
Member Data Documentation
head
int head = -1 package
Referenced by PolyshapeReader.XReader.isData(), PolyshapeReader.XReader.isDone(), PolyshapeReader.XReader.isEvent(), PolyshapeReader.XReader.peek(), PolyshapeReader.XReader.readInt(), PolyshapeReader.XReader.readKey(), and PolyshapeReader.XReader.XReader().
input
final Reader input package
Referenced by PolyshapeReader.XReader.readInt(), PolyshapeReader.XReader.readKey(), and PolyshapeReader.XReader.XReader().
lat
int lat = 0 package
Referenced by PolyshapeReader.XReader.readKey(), and PolyshapeReader.XReader.readLat().
lng
int lng = 0 package
Referenced by PolyshapeReader.XReader.readKey(), and PolyshapeReader.XReader.readLng().
shpFactory
final GeometryFactory shpFactory package
Referenced by PolyshapeReader.XReader.XReader().