GeoSPARQL SRS Extension: OSMDatatype Class Reference
OSMDatatype Class Reference
WKTDatatype class allows the URI "geo:wktLiteral" to be used as a datatype and it will parse that datatype to a JTS Geometry.
Classes
class WKBTextSRS
Public Member Functions
String unparse (Object geometry)
This method Un-parses the JTS Geometry to the WKT literal.
GeometryWrapper read (String geometryLiteral)
String toString ()
final GeometryWrapper parse (String lexicalForm) throws DatatypeFormatException
This method Parses the Geometry Literal to the JTS Geometry.
final GeometryWrapper parse (String lexicalForm, GeometryIndex targetIndex) throws DatatypeFormatException
Static Public Member Functions
static final void registerDatatypes ()
static final GeometryDatatype get (RDFDatatype rdfDatatype)
static final GeometryDatatype get (String datatypeURI)
static final boolean checkURI (String datatypeURI)
static final boolean check (RDFDatatype rdfDatatype)
Static Public Attributes
static final String URI = SRSGeo.OSM
The default WKT type URI.
static final OSMDatatype INSTANCE = new OSMDatatype()
A static instance of WKTDatatype.
Private Member Functions
OSMDatatype ()
private constructor - single global instance.
Static Private Attributes
static final Logger LOGGER = LoggerFactory.getLogger(OSMDatatype.class)
static final TypeMapper TYPE_MAPPER = TypeMapper.getInstance()
static boolean isDatatypesRegistered = false
Detailed Description
WKTDatatype class allows the URI "geo:wktLiteral" to be used as a datatype and it will parse that datatype to a JTS Geometry.
Req 10 All RDFS Literals of type geo:wktLiteral shall consist of an optional URI identifying the coordinate reference system followed by Simple Features Well Known Text (WKT) describing a geometric value. Valid geo:wktLiterals are formed by concatenating a valid, absolute URI as defined in [RFC 2396], one or more spaces (Unicode U+0020 character) as a separator, and a WKT string as defined in Simple Features [ISO 19125-1].
Req 11 The URI
<http://www.opengis.net/def/crs/OGC/1.3/CRS84>
shall be assumed as the spatial reference system for geo:wktLiterals that do not * specify an explicit spatial reference system URI.
Constructor & Destructor Documentation
OSMDatatype()
OSMDatatype () private
private constructor - single global instance.
{
                 super(URI);
             }
References OSMDatatype.URI.
Member Function Documentation
check()
static final boolean check (RDFDatatype rdfDatatype) static inherited
{
         //Ensure that the registered datatypes from the type mapper are used.
         return checkURI(rdfDatatype.getURI());
     }
References GeometryDatatype.checkURI().
checkURI()
static final boolean checkURI (String datatypeURI) static inherited
{
         registerDatatypes();
         RDFDatatype rdfDatatype = TYPE_MAPPER.getTypeByName(datatypeURI);
         if (rdfDatatype != null) {
             return rdfDatatype instanceof GeometryDatatype;
         } else {
             throw new DatatypeFormatException("Datatype not found: " + datatypeURI + " Ensure that GeoSPARQL is enabled and Datatype has been registered.");
         }
     }
References GeometryDatatype.GeometryDatatype(), GeometryDatatype.registerDatatypes(), and GeometryDatatype.TYPE_MAPPER.
Referenced by GeometryDatatype.check(), and GeometryDatatype.get().
get() [1/2]
static final GeometryDatatype get (RDFDatatype rdfDatatype) static inherited
{
         registerDatatypes();
         //System.out.println(rdfDatatype);
         //Iterator it=TYPE_MAPPER.listTypes();
         /*while(it.hasNext()) {
                 System.out.println(it.next());
         }*/
         if (rdfDatatype instanceof GeometryDatatype) {
             return (GeometryDatatype) rdfDatatype;
         } else {
             throw new DatatypeFormatException("Unrecognised Geometry Datatype: " + rdfDatatype.getURI() + " Ensure that Datatype is extending GeometryDatatype.");
         }
     }
References GeometryDatatype.registerDatatypes().
Referenced by GeometryWrapper.asLiteral(), GeometryWrapper.extract(), GeometryDatatype.get(), GeometryWrapper.getGeometryDatatype(), and LiteralUtils.rasterOrVector().
get() [2/2]
static final GeometryDatatype get (String datatypeURI) static inherited
{
         checkURI(datatypeURI);
         RDFDatatype rdfDatatype = TYPE_MAPPER.getTypeByName(datatypeURI);
         return GeometryDatatype.get(rdfDatatype);
     }
References GeometryDatatype.checkURI(), GeometryDatatype.get(), and GeometryDatatype.TYPE_MAPPER.
parse() [1/2]
final GeometryWrapper parse (String lexicalForm) throws DatatypeFormatException inherited
This method Parses the Geometry Literal to the JTS Geometry.
Parameters
lexicalForm - the Geometry Literal to be parsed
Returns
geometry - if the Geometry Literal is valid.
empty geometry - if the Geometry Literal is empty.
null - if the Geometry Literal is invalid.
{
         return parse(lexicalForm, GeometryIndex.PRIMARY);
     }
References GeometryLiteralIndex.GeometryIndex.PRIMARY.
Referenced by GeometryWrapper.extract().
parse() [2/2]
final GeometryWrapper parse (String lexicalForm, GeometryIndex targetIndex) throws DatatypeFormatException inherited
{
         //Check the Geometry Literal Index to see if been previously read and cached.
         //DatatypeReader interface used to instruct index on how to obtain the GeometryWrapper.
         try {
             return GeometryLiteralIndex.retrieve(lexicalForm, this, targetIndex);
         } catch (IllegalArgumentException ex) {
             throw new DatatypeFormatException(ex.getMessage() + " - Illegal Geometry Literal: " + lexicalForm);
         }
     }
References GeometryLiteralIndex.retrieve().
read()
GeometryWrapper read (String geometryLiteral)
Reimplemented from GeometryDatatype.
{
                 WKBTextSRS wkbTextSRS = new WKBTextSRS(geometryLiteral);
                 WKBReader wkbReader = new WKBReader();
                 Geometry geometry;
                         try {
                                 geometry = wkbReader.read(wkbTextSRS.getWkbText().getBytes());
                         GeometryWrapper wrapper = GeometryWrapperFactory.createGeometry(geometry, "<http://www.opengis.net/def/crs/EPSG/0/"+geometry.getSRID()+">", WKBDatatype.URI);
                         return wrapper;
                         } catch (ParseException e) {
                                 // TODO Auto-generated catch block
                                 e.printStackTrace();
                                 throw new RuntimeException();
                         }
             }
References OSMDatatype.WKBTextSRS.getWkbText(), and WKBDatatype.URI.
registerDatatypes()
static final void registerDatatypes () static inherited
{
         //System.out.println("Is")
         //if (!isDatatypesRegistered) {
             TYPE_MAPPER.registerDatatype(WKTDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GMLDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GeoJSONDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(KMLDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(WKBDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(TWKBDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(TopoJSONDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(GeobufDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(GeoHashDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(EncodedPolylineDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(HexWKBDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GeoURIDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(GPXDatatype.INSTANCE);
             isDatatypesRegistered = true;
         //}
     }
References EncodedPolylineDatatype.INSTANCE, GeoJSONDatatype.INSTANCE, GeoURIDatatype.INSTANCE, HexWKBDatatype.INSTANCE, KMLDatatype.INSTANCE, WKBDatatype.INSTANCE, GeometryDatatype.isDatatypesRegistered, and GeometryDatatype.TYPE_MAPPER.
Referenced by GeometryDatatype.checkURI(), and GeometryDatatype.get().
toString()
String toString ()
{
                 return "WKBDatatype{" + URI + '}';
             }
References OSMDatatype.URI.
unparse()
String unparse (Object geometry)
This method Un-parses the JTS Geometry to the WKT literal.
Parameters
geometry - the JTS Geometry to be un-parsed
Returns
WKT - the returned WKT Literal.
Notice that the Spatial Reference System is not specified in returned WKT literal.
{
                         /*OSMMemoryFeatureStoreFactory fac=new OSMMemoryFeatureStoreFactory();
                         OSMMemoryFeatureStore osmfeat=(OSMMemoryFeatureStore) fac.createDataStore(new java.net.URI(""));
                         OSMXMLWriter writer=new OSMXMLWriter();*/
                 if (geometry instanceof GeometryWrapper) {
                     GeometryWrapper geometryWrapper = (GeometryWrapper) geometry;
                     WKBWriter writerr=new WKBWriter();
                     return writerr.write(geometryWrapper.getXYGeometry()).toString();
                 } else {
                     throw new AssertionError("Object passed to WKBDatatype is not a GeometryWrapper: " + geometry);
                 }
             }
References GeometryWrapper.getXYGeometry().
Member Data Documentation
INSTANCE
final OSMDatatype INSTANCE = new OSMDatatype() static
A static instance of WKTDatatype.
isDatatypesRegistered
boolean isDatatypesRegistered = false static private inherited
Referenced by GeometryDatatype.registerDatatypes().
LOGGER
final Logger LOGGER = LoggerFactory.getLogger(OSMDatatype.class) static private
TYPE_MAPPER
final TypeMapper TYPE_MAPPER = TypeMapper.getInstance() static private inherited
Referenced by GeometryDatatype.checkURI(), GeometryDatatype.get(), and GeometryDatatype.registerDatatypes().
URI
final String URI = SRSGeo.OSM static
The default WKT type URI.
Referenced by OSMDatatype.OSMDatatype(), and OSMDatatype.toString().