GeoSPARQL SRS Extension: SRSInfo Class Reference
SRSInfo Class Reference
Public Member Functions
SRSInfo (String srsURI) throws SRSInfoException
SRSInfo (int srid) throws SRSInfoException
SRID will be converted to EPSG URI: http://www.opengis.net/def/crs/EPSG/0/srid.
String getSrsURI ()
URI of the Spatial Reference System
Identical values to SRID.
CoordinateReferenceSystem getCrs ()
OpenGIS Coordinate Reference System.
UnitsOfMeasure getUnitsOfMeasure ()
Units of Measure for the coordinate reference system.
Boolean isAxisXY ()
Check if axis is in XY order.
Boolean isSRSRecognised ()
Check if the SRS URI is recognised as a OpenGIS coordinate reference system.
Boolean isGeographic ()
Check if the SRS is geographic (i.e.
Boolean isWktDefault ()
Check if the SRS is default for WKT Literals.
Envelope getDomainEnvelope ()
Domain of validity in XY coordinate order.
double getDomainRangeX ()
Range of domain of validity in X axis.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static final Boolean checkAxisXY (CoordinateReferenceSystem crs)
static final Envelope buildDomainEnvelope (CoordinateReferenceSystem crs, Boolean isAxisXY)
static final String convertSRID (BigInteger srid)
static final String convertSRID (int srid)
static final SRSInfo getDefaultWktCRS84 (String srsURI) throws SRSInfoException
static final SRSInfo getUnrecognised (String srsURI) throws SRSInfoException
Unrecognised SRS URI are assumed to follow the default CRS84 so that operations do not error but may not complete as expected.
static SRSInfo resolveSRS (String srsURI, OntModel model)
static SRSInfo resolveSRS (String srsURI, String endpointURI)
Static Public Attributes
static final String DEFAULT_WKT_CRS84_CODE = "CRS:84"
static final SRSInfo DEFAULT_WKT_CRS84 = getDefaultWktCRS84(SRS_URI.DEFAULT_WKT_CRS84)
Private Member Functions
SRSInfo ()
SRSInfo (String srsURI, CoordinateReferenceSystem crs, boolean isSRSRecognised)
Private Attributes
String srsURI =""
CoordinateReferenceSystem crs =null
UnitsOfMeasure unitsOfMeasure =null
Boolean isAxisXY =null
Boolean isGeographic =null
Boolean isSRSRecognised =false
Boolean isWktDefault =false
Envelope domainEnvelope =null
Double domainRangeX =null
Static Private Attributes
static final List< AxisDirection > OTHER_Y_AXIS_DIRECTIONS = Arrays.asList(AxisDirection.NORTH_EAST, AxisDirection.NORTH_WEST, AxisDirection.SOUTH_EAST, AxisDirection.SOUTH_WEST, AxisDirection.NORTH_NORTH_EAST, AxisDirection.NORTH_NORTH_WEST, AxisDirection.SOUTH_SOUTH_EAST, AxisDirection.SOUTH_SOUTH_WEST)
Constructor & Destructor Documentation
SRSInfo() [1/4]
SRSInfo (String srsURI) throws SRSInfoException
{
         this.srsURI = srsURI;
         try {
             this.crs = CRS.forCode(srsURI);
             this.isAxisXY = checkAxisXY(crs);
             this.unitsOfMeasure = new UnitsOfMeasure(crs);
             this.isSRSRecognised = true;
             this.isGeographic = crs instanceof GeographicCRS;
             this.isWktDefault = srsURI.equals(SRS_URI.DEFAULT_WKT_CRS84);
             this.domainEnvelope = buildDomainEnvelope(crs, isAxisXY);
             this.domainRangeX = Math.abs(domainEnvelope.getMinX()) + Math.abs(domainEnvelope.getMaxX());
         } catch (FactoryException ex) {
             throw new SRSInfoException("Unrecognised SRS URI code: " + srsURI + " - " + ex.getMessage(), ex);
         }
     }
References SRSInfo.buildDomainEnvelope(), SRSInfo.checkAxisXY(), SRSInfo.crs, SRSInfo.domainEnvelope, SRSInfo.isAxisXY, and SRSInfo.srsURI.
SRSInfo() [2/4]
SRSInfo (int srid) throws SRSInfoException
SRID will be converted to EPSG URI: http://www.opengis.net/def/crs/EPSG/0/srid.
Parameters
srid
{
         this(convertSRID(srid));
     }
References SRSInfo.convertSRID().
SRSInfo() [3/4]
SRSInfo () private
                       {
     }
Referenced by SRSInfo.equals(), SRSInfo.getDefaultWktCRS84(), SRSInfo.getUnrecognised(), and SRSInfo.resolveSRS().
SRSInfo() [4/4]
SRSInfo (String srsURI, CoordinateReferenceSystem crs, boolean isSRSRecognised) private
{
         this.srsURI = srsURI;
         this.crs = crs;
         this.isAxisXY = checkAxisXY(crs);
         this.unitsOfMeasure = new UnitsOfMeasure(crs);
         this.isSRSRecognised = isSRSRecognised;
         this.isGeographic = crs instanceof GeographicCRS;
         this.isWktDefault = srsURI.equals(SRS_URI.DEFAULT_WKT_CRS84);
         this.domainEnvelope = buildDomainEnvelope(crs, isAxisXY);
         this.domainRangeX = Math.abs(domainEnvelope.getMinX()) + Math.abs(domainEnvelope.getMaxX());
     }
References SRSInfo.buildDomainEnvelope(), SRSInfo.checkAxisXY(), SRSInfo.crs, SRSInfo.domainEnvelope, SRSInfo.isAxisXY, SRSInfo.isSRSRecognised, and SRSInfo.srsURI.
Member Function Documentation
buildDomainEnvelope()
static final Envelope buildDomainEnvelope (CoordinateReferenceSystem crs, Boolean isAxisXY) static
{
         org.opengis.geometry.Envelope crsDomain = CRS.getDomainOfValidity(crs);
         DirectPosition lowerCorner = crsDomain.getLowerCorner();
         DirectPosition upperCorner = crsDomain.getUpperCorner();
         int xAxis;
         int yAxis;
         if (isAxisXY) {
             xAxis = 0;
             yAxis = 1;
         } else {
             xAxis = 1;
             yAxis = 0;
         }
         double x1 = lowerCorner.getOrdinate(xAxis);
         double y1 = lowerCorner.getOrdinate(yAxis);
         double x2 = upperCorner.getOrdinate(xAxis);
         double y2 = upperCorner.getOrdinate(yAxis);
         Envelope envelope = new Envelope(x1, x2, y1, y2);
         return envelope;
     }
References SRSInfo.crs, and SRSInfo.isAxisXY.
Referenced by SRSInfo.resolveSRS(), and SRSInfo.SRSInfo().
checkAxisXY()
static final Boolean checkAxisXY (CoordinateReferenceSystem crs) static
{
         AxisDirection axisDirection = crs.getCoordinateSystem().getAxis(0).getDirection();
         if (axisDirection.equals(AxisDirection.NORTH) || axisDirection.equals(AxisDirection.SOUTH)) {
             return false;
         } else if (axisDirection.equals(AxisDirection.EAST) || axisDirection.equals(AxisDirection.WEST)) {
             return true;
         } else {
             return !OTHER_Y_AXIS_DIRECTIONS.contains(axisDirection);
         }
     }
References SRSInfo.crs, and SRSInfo.OTHER_Y_AXIS_DIRECTIONS.
Referenced by SRSInfo.resolveSRS(), and SRSInfo.SRSInfo().
convertSRID() [1/2]
static final String convertSRID (BigInteger srid) static
Parameters
srid
Returns
srsURI using SRID
{
         return convertSRID(srid.intValue());
     }
Referenced by SRSInfo.SRSInfo().
convertSRID() [2/2]
static final String convertSRID (int srid) static
Parameters
srid
Returns
srsURI using SRID
{
         return EPSG_BASE_SRS_URI + srid;
     }
equals()
boolean equals (Object obj)
{
         if (this == obj) {
             return true;
         }
         if (obj == null) {
             return false;
         }
         if (getClass() != obj.getClass()) {
             return false;
         }
         final SRSInfo other = (SRSInfo) obj;
         if (Double.doubleToLongBits(this.domainRangeX) != Double.doubleToLongBits(other.domainRangeX)) {
             return false;
         }
         if (!Objects.equals(this.srsURI, other.srsURI)) {
             return false;
         }
         if (!Objects.equals(this.crs, other.crs)) {
             return false;
         }
         if (!Objects.equals(this.unitsOfMeasure, other.unitsOfMeasure)) {
             return false;
         }
         if (!Objects.equals(this.isAxisXY, other.isAxisXY)) {
             return false;
         }
         if (!Objects.equals(this.isGeographic, other.isGeographic)) {
             return false;
         }
         if (!Objects.equals(this.isSRSRecognised, other.isSRSRecognised)) {
             return false;
         }
         if (!Objects.equals(this.isWktDefault, other.isWktDefault)) {
             return false;
         }
         return Objects.equals(this.domainEnvelope, other.domainEnvelope);
     }
References SRSInfo.crs, SRSInfo.domainEnvelope, SRSInfo.domainRangeX, SRSInfo.equals(), SRSInfo.isAxisXY, SRSInfo.isGeographic, SRSInfo.isSRSRecognised, SRSInfo.isWktDefault, SRSInfo.SRSInfo(), SRSInfo.srsURI, and SRSInfo.unitsOfMeasure.
Referenced by SRSInfo.equals().
getCrs()
CoordinateReferenceSystem getCrs ()
OpenGIS Coordinate Reference System.
Returns
Coordinate Reference System
{
         return crs;
     }
References SRSInfo.crs.
Referenced by CoverageWrapper.getCRS(), GeometryWrapper.getCRS(), SRSRegistry.getCRS(), and GeometryWrapper.getUTMZoneURI().
getDefaultWktCRS84()
static final SRSInfo getDefaultWktCRS84 (String srsURI) throws SRSInfoException static
Parameters
srsURI Allows alternative srsURI to be associated with CRS84.
Returns
SRSInfo using default setup for WKT but alternative srsURI.
{
         try {
             CoordinateReferenceSystem crs = CRS.forCode(DEFAULT_WKT_CRS84_CODE);
             return new SRSInfo(srsURI, crs, true);
         } catch (FactoryException ex) {
             throw new SRSInfoException("Unrecognised SRS code: " + DEFAULT_WKT_CRS84_CODE + " - " + ex.getMessage(), ex);
         }
     }
References SRSInfo.crs, SRSInfo.DEFAULT_WKT_CRS84_CODE, SRSInfo.SRSInfo(), and SRSInfo.srsURI.
Referenced by SRSRegistry.setupDefaultSRS().
getDomainEnvelope()
Envelope getDomainEnvelope ()
Domain of validity in XY coordinate order.
Returns
Bounding box of valid values.
{
         return domainEnvelope;
     }
References SRSInfo.domainEnvelope.
getDomainRangeX()
double getDomainRangeX ()
Range of domain of validity in X axis.
Returns
Difference between min and max values in X axis.
{
         return domainRangeX;
     }
References SRSInfo.domainRangeX.
Referenced by GeometryWrapper.translateXYGeometry().
getSrsURI()
String getSrsURI ()
URI of the Spatial Reference System
Identical values to SRID.
Returns
SRS URI
{
         return srsURI;
     }
References SRSInfo.srsURI.
Referenced by GeometryWrapper.boundary(), GeometryWrapper.buffer(), GeometryWrapper.checkTransformSRS(), GeometryWrapper.convexHull(), GeometryWrapper.difference(), GeometryWrapper.envelope(), CoverageWrapper.getSRID(), GeometryWrapper.getSRID(), CoverageWrapper.getSrsURI(), GeometryWrapper.getSrsURI(), GeometryWrapper.intersection(), GeometryWrapper.symDifference(), GeometryWrapper.transform(), and GeometryWrapper.union().
getUnitsOfMeasure()
UnitsOfMeasure getUnitsOfMeasure ()
Units of Measure for the coordinate reference system.
Returns
Units of Measure
{
         return unitsOfMeasure;
     }
References SRSInfo.unitsOfMeasure.
Referenced by GeometryWrapper.buffer(), GeometryWrapper.distanceEuclidean(), CoverageWrapper.getUnitsOfMeasure(), GeometryWrapper.getUnitsOfMeasure(), SRSRegistry.getUnitsOfMeasure(), and SRSRegistry.setupDefaultSRS().
getUnrecognised()
static final SRSInfo getUnrecognised (String srsURI) throws SRSInfoException static
Unrecognised SRS URI are assumed to follow the default CRS84 so that operations do not error but may not complete as expected.
Parameters
srsURI
Returns
SRSInfo with default setup for WKT without SRS URI
{
         try {
             CoordinateReferenceSystem crs = CRS.forCode(DEFAULT_WKT_CRS84_CODE);
             return new SRSInfo(srsURI, crs, false);
         } catch (FactoryException ex) {
             throw new SRSInfoException("Unrecognised SRS URI code: " + srsURI + " - " + ex.getMessage(), ex);
         }
     }
References SRSInfo.crs, SRSInfo.DEFAULT_WKT_CRS84_CODE, SRSInfo.SRSInfo(), and SRSInfo.srsURI.
Referenced by SRSRegistry.storeSRS().
hashCode()
int hashCode ()
{
         int hash = 7;
         hash = 59 * hash + Objects.hashCode(this.srsURI);
         hash = 59 * hash + Objects.hashCode(this.crs);
         hash = 59 * hash + Objects.hashCode(this.unitsOfMeasure);
         hash = 59 * hash + Objects.hashCode(this.isAxisXY);
         hash = 59 * hash + Objects.hashCode(this.isGeographic);
         hash = 59 * hash + Objects.hashCode(this.isSRSRecognised);
         hash = 59 * hash + Objects.hashCode(this.isWktDefault);
         hash = 59 * hash + Objects.hashCode(this.domainEnvelope);
         hash = 59 * hash + (int) (Double.doubleToLongBits(this.domainRangeX) ^ (Double.doubleToLongBits(this.domainRangeX) >>> 32));
         return hash;
     }
isAxisXY()
Boolean isAxisXY ()
Check if axis is in XY order.
Returns
True if XY order.
{
         return isAxisXY;
     }
References SRSInfo.isAxisXY.
isGeographic()
Boolean isGeographic ()
Check if the SRS is geographic (i.e.
latitude, longitude on a sphere).
Returns
True if a Geographic SRS, e.g. WGS84.
{
         return isGeographic;
     }
References SRSInfo.isGeographic.
isSRSRecognised()
Boolean isSRSRecognised ()
Check if the SRS URI is recognised as a OpenGIS coordinate reference system.
Returns
True if SRS is recognised.
{
         return isSRSRecognised;
     }
References SRSInfo.isSRSRecognised.
isWktDefault()
Boolean isWktDefault ()
Check if the SRS is default for WKT Literals.
Returns
True if CRS84 SRS, i.e. http://www.opengis.net/def/crs/OGC/1.3/CRS84.
{
         return isWktDefault;
     }
References SRSInfo.isWktDefault.
resolveSRS() [1/2]
static SRSInfo resolveSRS (String srsURI, OntModel model) static
{
         SRSInfo result=new SRSInfo();
         String wkt=RDFCRSToWKT.getCRSFromTripleStore(srsURI, model, "wkt");
         CoordinateReferenceSystem crs;
                 try {
                         crs = CRS.fromWKT(wkt);
                 result.crs=crs;
                 result.isAxisXY = checkAxisXY(crs);
                 result.unitsOfMeasure = new UnitsOfMeasure(crs);
                 result.isSRSRecognised = true;
                 result.isGeographic = crs instanceof GeographicCRS;
                 result.isWktDefault = srsURI.equals(SRS_URI.DEFAULT_WKT_CRS84);
                 result.domainEnvelope = buildDomainEnvelope(crs, result.isAxisXY);
                 result.domainRangeX = Math.abs(result.domainEnvelope.getMinX()) + Math.abs(result.domainEnvelope.getMaxX());
                 return result;
                 } catch (FactoryException e) {
                         // TODO Auto-generated catch block
                         return null;
                 }
     }
References SRSInfo.buildDomainEnvelope(), SRSInfo.checkAxisXY(), SRSInfo.crs, SRSInfo.domainEnvelope, SRSInfo.domainRangeX, RDFCRSToWKT.getCRSFromTripleStore(), SRSInfo.isAxisXY, SRSInfo.isGeographic, SRSInfo.isSRSRecognised, SRSInfo.isWktDefault, SRSInfo.SRSInfo(), SRSInfo.srsURI, and SRSInfo.unitsOfMeasure.
Referenced by SRSRegistry.exploreGraphForSRSDefinitions().
resolveSRS() [2/2]
static SRSInfo resolveSRS (String srsURI, String endpointURI) static
{
         SRSInfo result=new SRSInfo();
         String wkt=RDFCRSToWKT.getCRSFromTripleStore(srsURI, endpointURI, "wkt");
         CoordinateReferenceSystem crs;
                 try {
                         crs = CRS.fromWKT(wkt);
                 result.crs=crs;
                 result.isAxisXY = checkAxisXY(crs);
                 result.unitsOfMeasure = new UnitsOfMeasure(crs);
                 result.isSRSRecognised = true;
                 result.isGeographic = crs instanceof GeographicCRS;
                 result.isWktDefault = srsURI.equals(SRS_URI.DEFAULT_WKT_CRS84);
                 result.domainEnvelope = buildDomainEnvelope(crs, result.isAxisXY);
                 result.domainRangeX = Math.abs(result.domainEnvelope.getMinX()) + Math.abs(result.domainEnvelope.getMaxX());
                 return result;
                 } catch (FactoryException e) {
                         // TODO Auto-generated catch block
                         return null;
                 }
     }
References SRSInfo.buildDomainEnvelope(), SRSInfo.checkAxisXY(), SRSInfo.crs, SRSInfo.domainEnvelope, SRSInfo.domainRangeX, RDFCRSToWKT.getCRSFromTripleStore(), SRSInfo.isAxisXY, SRSInfo.isGeographic, SRSInfo.isSRSRecognised, SRSInfo.isWktDefault, SRSInfo.SRSInfo(), SRSInfo.srsURI, and SRSInfo.unitsOfMeasure.
toString()
String toString ()
{
         return "SRSInfo{" + "srsURI=" + srsURI + ", crs=" + crs + ", unitsOfMeasure=" + unitsOfMeasure + ", isAxisXY=" + isAxisXY + ", isGeographic=" + isGeographic + ", isSRSRecognised=" + isSRSRecognised + ", isWktDefault=" + isWktDefault + ", domainEnvelope=" + domainEnvelope + ", domainRangeX=" + domainRangeX + '}';
     }
References SRSInfo.crs, SRSInfo.domainEnvelope, SRSInfo.domainRangeX, SRSInfo.isAxisXY, SRSInfo.isGeographic, SRSInfo.isSRSRecognised, SRSInfo.isWktDefault, SRSInfo.srsURI, and SRSInfo.unitsOfMeasure.
Member Data Documentation
crs
CoordinateReferenceSystem crs =null private
Referenced by SRSInfo.buildDomainEnvelope(), SRSInfo.checkAxisXY(), SRSInfo.equals(), SRSInfo.getCrs(), SRSInfo.getDefaultWktCRS84(), SRSInfo.getUnrecognised(), SRSInfo.resolveSRS(), SRSInfo.SRSInfo(), and SRSInfo.toString().
DEFAULT_WKT_CRS84
final SRSInfo DEFAULT_WKT_CRS84 = getDefaultWktCRS84(SRS_URI.DEFAULT_WKT_CRS84) static
DEFAULT_WKT_CRS84_CODE
final String DEFAULT_WKT_CRS84_CODE = "CRS:84" static
Referenced by SRSInfo.getDefaultWktCRS84(), and SRSInfo.getUnrecognised().
domainEnvelope
Envelope domainEnvelope =null private
Referenced by SRSInfo.equals(), SRSInfo.getDomainEnvelope(), SRSInfo.resolveSRS(), SRSInfo.SRSInfo(), and SRSInfo.toString().
domainRangeX
Double domainRangeX =null private
Referenced by SRSInfo.equals(), SRSInfo.getDomainRangeX(), SRSInfo.resolveSRS(), and SRSInfo.toString().
isAxisXY
Boolean isAxisXY =null private
Referenced by SRSInfo.buildDomainEnvelope(), SRSInfo.equals(), SRSRegistry.getAxisXY(), SRSInfo.isAxisXY(), SRSInfo.resolveSRS(), SRSInfo.SRSInfo(), and SRSInfo.toString().
isGeographic
Boolean isGeographic =null private
Referenced by GeometryWrapper.distance(), GeometryWrapper.distanceGreatCircle(), SRSInfo.equals(), GeometryWrapper.getLatitude(), SRSInfo.isGeographic(), SRSInfo.resolveSRS(), SRSInfo.toString(), and GeometryWrapper.translateXYGeometry().
isSRSRecognised
Boolean isSRSRecognised =false private
Referenced by SRSInfo.equals(), CoverageWrapper.isSRSRecognised(), GeometryWrapper.isSRSRecognised(), SRSInfo.isSRSRecognised(), SRSInfo.resolveSRS(), SRSInfo.SRSInfo(), and SRSInfo.toString().
isWktDefault
Boolean isWktDefault =false private
Referenced by SRSInfo.equals(), SRSInfo.isWktDefault(), SRSInfo.resolveSRS(), and SRSInfo.toString().
OTHER_Y_AXIS_DIRECTIONS
final List<AxisDirection> OTHER_Y_AXIS_DIRECTIONS = Arrays.asList(AxisDirection.NORTH_EAST, AxisDirection.NORTH_WEST, AxisDirection.SOUTH_EAST, AxisDirection.SOUTH_WEST, AxisDirection.NORTH_NORTH_EAST, AxisDirection.NORTH_NORTH_WEST, AxisDirection.SOUTH_SOUTH_EAST, AxisDirection.SOUTH_SOUTH_WEST) static private
Referenced by SRSInfo.checkAxisXY().
srsURI
String srsURI ="" private
Referenced by SRSInfo.equals(), SRSInfo.getDefaultWktCRS84(), SRSInfo.getSrsURI(), SRSInfo.getUnrecognised(), SRSInfo.resolveSRS(), SRSInfo.SRSInfo(), and SRSInfo.toString().
unitsOfMeasure
UnitsOfMeasure unitsOfMeasure =null private
Referenced by SRSInfo.equals(), SRSInfo.getUnitsOfMeasure(), SRSInfo.resolveSRS(), and SRSInfo.toString().