GeoSPARQL SRS Extension: GeometryLiteralIndex Class Reference
GeometryLiteralIndex Class Reference
Classes
enum GeometryIndex
Static Public Member Functions
static final GeometryWrapper retrieve (String geometryLiteral, GeometryDatatype geometryDatatype, GeometryIndex targetIndex)
static final CoverageWrapper retrieve (String geometryLiteral, RasterDataType geometryDatatype, GeometryIndex targetIndex)
static final void clear ()
Empty the Geometry Literal Index.
static final void setMaxSize (int maxSize)
Sets the maximum size of Geometry Literal Index.
static final void setExpiry (long expiryInterval)
Sets the expiry time in milliseconds of the Geometry Literal Indexes, if active.
static final long getPrimaryIndexSize ()
static final long getSecondaryIndexSize ()
static boolean isIndexActive ()
static void setIndexActive (boolean indexActive)
Sets whether the index is active.
static void reset (int maxSize, long expiryInterval)
Reset the indexes to the provided max size and expiry interval.
Static Private Member Functions
static GeometryWrapper retrieveMemoryIndex (String geometryLiteral, GeometryDatatype geometryDatatype, Map< String, SpatialWrapper > index, Map< String, SpatialWrapper > otherIndex)
static CoverageWrapper retrieveMemoryIndex (String geometryLiteral, RasterDataType geometryDatatype, Map< String, SpatialWrapper > index, Map< String, SpatialWrapper > otherIndex)
Static Private Attributes
static boolean INDEX_ACTIVE = false
static final String PRIMARY_INDEX_LABEL = "Primary Geometry Literal Index"
static final String SECONDARY_INDEX_LABEL = "Secondary Geometry Literal Index"
static ExpiringMap< String, SpatialWrapper > PRIMARY_INDEX = new ExpiringMap<>(PRIMARY_INDEX_LABEL, UNLIMITED_MAP, MAP_EXPIRY_INTERVAL)
static ExpiringMap< String, SpatialWrapper > SECONDARY_INDEX = new ExpiringMap<>(SECONDARY_INDEX_LABEL, UNLIMITED_MAP, MAP_EXPIRY_INTERVAL)
Member Function Documentation
clear()
static final void clear () static
Empty the Geometry Literal Index.
{
         PRIMARY_INDEX.clear();
         SECONDARY_INDEX.clear();
     }
References GeometryLiteralIndex.PRIMARY_INDEX, and GeometryLiteralIndex.SECONDARY_INDEX.
getPrimaryIndexSize()
static final long getPrimaryIndexSize () static
Returns
Number of items in the primary index.
{
         return PRIMARY_INDEX.mappingCount();
     }
References GeometryLiteralIndex.PRIMARY_INDEX.
getSecondaryIndexSize()
static final long getSecondaryIndexSize () static
Returns
Number of items in the secondary index.
{
         return SECONDARY_INDEX.mappingCount();
     }
References GeometryLiteralIndex.SECONDARY_INDEX.
isIndexActive()
static boolean isIndexActive () static
Returns
True if index is active.
{
         return INDEX_ACTIVE;
     }
References GeometryLiteralIndex.INDEX_ACTIVE.
reset()
static void reset (int maxSize, long expiryInterval) static
Reset the indexes to the provided max size and expiry interval.
All contents will be lost.
Parameters
maxSize
expiryInterval
{
         PRIMARY_INDEX = new ExpiringMap<>(PRIMARY_INDEX_LABEL, maxSize, expiryInterval);
         SECONDARY_INDEX = new ExpiringMap<>(SECONDARY_INDEX_LABEL, maxSize, expiryInterval);
     }
References GeometryLiteralIndex.PRIMARY_INDEX, GeometryLiteralIndex.PRIMARY_INDEX_LABEL, GeometryLiteralIndex.SECONDARY_INDEX, and GeometryLiteralIndex.SECONDARY_INDEX_LABEL.
retrieve() [1/2]
static final GeometryWrapper retrieve (String geometryLiteral, GeometryDatatype geometryDatatype, GeometryIndex targetIndex) static
{
         GeometryWrapper geometryWrapper;
         switch (targetIndex) {
             case SECONDARY:
                 geometryWrapper = retrieveMemoryIndex(geometryLiteral, geometryDatatype, SECONDARY_INDEX, PRIMARY_INDEX);
                 break;
             default:
                 geometryWrapper = retrieveMemoryIndex(geometryLiteral, geometryDatatype, PRIMARY_INDEX, SECONDARY_INDEX);
         }
         return geometryWrapper;
     }
References GeometryLiteralIndex.PRIMARY_INDEX, GeometryLiteralIndex.retrieveMemoryIndex(), and GeometryLiteralIndex.SECONDARY_INDEX.
Referenced by GeometryDatatype.parse(), and RasterDataType.parse().
retrieve() [2/2]
static final CoverageWrapper retrieve (String geometryLiteral, RasterDataType geometryDatatype, GeometryIndex targetIndex) static
{
         CoverageWrapper geometryWrapper;
         switch (targetIndex) {
             case SECONDARY:
                 geometryWrapper = retrieveMemoryIndex(geometryLiteral, geometryDatatype, SECONDARY_INDEX, PRIMARY_INDEX);
                 break;
             default:
                 geometryWrapper = retrieveMemoryIndex(geometryLiteral, geometryDatatype, PRIMARY_INDEX, SECONDARY_INDEX);
         }
         return geometryWrapper;
     }
References GeometryLiteralIndex.PRIMARY_INDEX, GeometryLiteralIndex.retrieveMemoryIndex(), and GeometryLiteralIndex.SECONDARY_INDEX.
retrieveMemoryIndex() [1/2]
static GeometryWrapper retrieveMemoryIndex (String geometryLiteral, GeometryDatatype geometryDatatype, Map< String, SpatialWrapper > index, Map< String, SpatialWrapper > otherIndex) static private
{
         GeometryWrapper geometryWrapper;
         if (INDEX_ACTIVE) {
             if (index.containsKey(geometryLiteral)) {
                 geometryWrapper = (GeometryWrapper)index.get(geometryLiteral);
             } else {
                 if (otherIndex.containsKey(geometryLiteral)) {
                     geometryWrapper = (GeometryWrapper)otherIndex.get(geometryLiteral);
                 } else {
                     geometryWrapper = geometryDatatype.read(geometryLiteral);
                 }
                 index.put(geometryLiteral, geometryWrapper);
             }
             return geometryWrapper;
         }
         return geometryDatatype.read(geometryLiteral);
     }
References GeometryLiteralIndex.INDEX_ACTIVE, and GeometryDatatype.read().
Referenced by GeometryLiteralIndex.retrieve().
retrieveMemoryIndex() [2/2]
static CoverageWrapper retrieveMemoryIndex (String geometryLiteral, RasterDataType geometryDatatype, Map< String, SpatialWrapper > index, Map< String, SpatialWrapper > otherIndex) static private
{
         CoverageWrapper geometryWrapper;
         if (INDEX_ACTIVE) {
             if (index.containsKey(geometryLiteral)) {
                 geometryWrapper = (CoverageWrapper)index.get(geometryLiteral);
             } else {
                 if (otherIndex.containsKey(geometryLiteral)) {
                     geometryWrapper = (CoverageWrapper) otherIndex.get(geometryLiteral);
                 } else {
                     geometryWrapper = geometryDatatype.read(geometryLiteral);
                 }
                 index.put(geometryLiteral, geometryWrapper);
             }
             return geometryWrapper;
         }
         return geometryDatatype.read(geometryLiteral);
     }
References GeometryLiteralIndex.INDEX_ACTIVE, and RasterDataType.read().
setExpiry()
static final void setExpiry (long expiryInterval) static
Sets the expiry time in milliseconds of the Geometry Literal Indexes, if active.
Parameters
expiryInterval : use 0 or negative for unlimited timeout
{
         PRIMARY_INDEX.setExpiryInterval(expiryInterval);
         SECONDARY_INDEX.setExpiryInterval(expiryInterval);
     }
References GeometryLiteralIndex.PRIMARY_INDEX, and GeometryLiteralIndex.SECONDARY_INDEX.
setIndexActive()
static void setIndexActive (boolean indexActive) static
Sets whether the index is active.
Parameters
indexActive
{
         INDEX_ACTIVE = indexActive;
         if (INDEX_ACTIVE) {
             PRIMARY_INDEX.startExpiry();
             SECONDARY_INDEX.startExpiry();
         } else {
             PRIMARY_INDEX.stopExpiry();
             SECONDARY_INDEX.stopExpiry();
         }
     }
References GeometryLiteralIndex.INDEX_ACTIVE, GeometryLiteralIndex.PRIMARY_INDEX, and GeometryLiteralIndex.SECONDARY_INDEX.
setMaxSize()
static final void setMaxSize (int maxSize) static
Sets the maximum size of Geometry Literal Index.
Parameters
maxSize : use -1 for unlimited size
{
         PRIMARY_INDEX.setMaxSize(maxSize);
         SECONDARY_INDEX.setMaxSize(maxSize);
     }
References GeometryLiteralIndex.PRIMARY_INDEX, and GeometryLiteralIndex.SECONDARY_INDEX.
Member Data Documentation
INDEX_ACTIVE
boolean INDEX_ACTIVE = false static private
Referenced by GeometryLiteralIndex.isIndexActive(), GeometryLiteralIndex.retrieveMemoryIndex(), and GeometryLiteralIndex.setIndexActive().
PRIMARY_INDEX
ExpiringMap<String, SpatialWrapper> PRIMARY_INDEX = new ExpiringMap<>(PRIMARY_INDEX_LABEL, UNLIMITED_MAP, MAP_EXPIRY_INTERVAL) static private
Referenced by GeometryLiteralIndex.clear(), GeometryLiteralIndex.getPrimaryIndexSize(), GeometryLiteralIndex.reset(), GeometryLiteralIndex.retrieve(), GeometryLiteralIndex.setExpiry(), GeometryLiteralIndex.setIndexActive(), and GeometryLiteralIndex.setMaxSize().
PRIMARY_INDEX_LABEL
final String PRIMARY_INDEX_LABEL = "Primary Geometry Literal Index" static private
Referenced by GeometryLiteralIndex.reset().
SECONDARY_INDEX
ExpiringMap<String, SpatialWrapper> SECONDARY_INDEX = new ExpiringMap<>(SECONDARY_INDEX_LABEL, UNLIMITED_MAP, MAP_EXPIRY_INTERVAL) static private
Referenced by GeometryLiteralIndex.clear(), GeometryLiteralIndex.getSecondaryIndexSize(), GeometryLiteralIndex.reset(), GeometryLiteralIndex.retrieve(), GeometryLiteralIndex.setExpiry(), GeometryLiteralIndex.setIndexActive(), and GeometryLiteralIndex.setMaxSize().
SECONDARY_INDEX_LABEL
final String SECONDARY_INDEX_LABEL = "Secondary Geometry Literal Index" static private
Referenced by GeometryLiteralIndex.reset().