GeoSPARQL SRS Extension: GeometryWrapper Class Reference
GeometryWrapper Class Reference
Public Member Functions
GeometryWrapper (Geometry geometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo)
GeometryWrapper (Geometry geometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo, String geometryLiteral)
GeometryWrapper (Geometry geometry, String geometryDatatypeURI)
Default to WGS84 geometry and XY coordinate dimensions.
GeometryWrapper (Geometry geometry, String srsURI, String geometryDatatypeURI)
Default to XY coordinate dimensions.
GeometryWrapper (String srsURI, String geometryDatatypeURI)
Empty geometry with specified parameters.
GeometryWrapper (CustomCoordinateSequence pointCoordinateSequence, String geometryDatatypeURI, String srsURI)
Point geometry with specified SRS.
GeometryWrapper (GeometryWrapper geometryWrapper)
Copy GeometryWrapper.
GeometryWrapper checkTransformSRS (GeometryWrapper targetGeometryWrapper) throws FactoryException, MismatchedDimensionException, TransformException
Transforms, if necessary, the provided target GeometryWrapper according to this GeometryWrapper SRS_URI.
GeometryWrapper transform (String srsURI) throws MismatchedDimensionException, TransformException, FactoryException
Transform the GeometryWrapper into another spatial reference system.
GeometryWrapper transform (SRSInfo srsInfo) throws MismatchedDimensionException, TransformException, FactoryException
Transform the GeometryWrapper into another spatial reference system.
GeometryWrapper convertSRS (String srsURI) throws FactoryException, MismatchedDimensionException, TransformException
Returns this geometry wrapper converted to the SRS_URI URI.
CoordinateReferenceSystem getCRS ()
Geometry getXYGeometry ()
Geometry getParsingGeometry ()
Geometry translateXYGeometry ()
XY geometry translated by the domain range of the SRS, if a Geographic SRS.
String getSrsURI ()
String getSRID ()
SRSInfo getSrsInfo ()
Boolean isSRSRecognised ()
String getGeometryDatatypeURI ()
String getGeometryType ()
GeometryDatatype getGeometryDatatype ()
GeometryWrapper buffer (double distance, String targetDistanceUnitsURI) throws FactoryException, MismatchedDimensionException, TransformException
String getUTMZoneURI () throws FactoryException, MismatchedDimensionException, TransformException
Double getLatitude () throws FactoryException, MismatchedDimensionException, TransformException
Latitude if Geographic SRS or in WGS84.
double distanceEuclidean (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Euclidean) defaulting to metres.
double distanceEuclidean (GeometryWrapper targetGeometry, UnitsOfMeasure unitsOfMeasure) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Euclidean) in the Units of Measure.
double distanceEuclidean (GeometryWrapper targetGeometry, String targetDistanceUnitsURI) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Euclidean) in the Units of Measure stated in URI.
double distanceGreatCircle (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Great Circle) defaulting to metres.
double distanceGreatCircle (GeometryWrapper targetGeometry, UnitsOfMeasure unitsOfMeasure) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Great Circle) in the Units of Measure.
double distanceGreatCircle (GeometryWrapper targetGeometry, String targetDistanceUnitsURI) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Great Circle) in the Units of Measure stated in URI.
double distance (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Euclidean or Great Circle depending on Geometry SRS URI) defaulting to metres.
double distance (GeometryWrapper targetGeometry, UnitsOfMeasure unitsOfMeasure) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Euclidean or Great Circle depending on Geometry SRS URI) in the Units of Measure.
double distance (GeometryWrapper targetGeometry, String targetDistanceUnitsURI) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Euclidean or Great Circle depending on Geometry SRS URI) in the Units of Measure stated in URI.
GeometryWrapper boundary ()
GeometryWrapper convexHull ()
GeometryWrapper difference (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
GeometryWrapper envelope ()
Envelope of GeometryWrapper with original coordinate order.
Envelope getEnvelope ()
Envelope of GeometryWrapper in XY order.
GeometryWrapper intersection (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
IntersectionMatrix relate (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
boolean relate (GeometryWrapper targetGeometry, String intersectionPattern) throws FactoryException, MismatchedDimensionException, TransformException
GeometryWrapper symDifference (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
GeometryWrapper union (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
boolean contains (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
boolean crosses (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
boolean disjoint (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
boolean equalsTopo (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
boolean equalsExact (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
boolean equalsExact (GeometryWrapper targetGeometry, double tolerance) throws FactoryException, MismatchedDimensionException, TransformException
boolean intersects (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
boolean overlaps (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
boolean touches (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
boolean within (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
NodeValue asNodeValue () throws DatatypeFormatException
Node asNode () throws DatatypeFormatException
Literal asLiteral () throws DatatypeFormatException
Literal asLiteral (String outputGeometryDatatypeURI) throws DatatypeFormatException
Literal asLiteral (GeometryDatatype datatype)
int getCoordinateDimension ()
int getSpatialDimension ()
int getTopologicalDimension ()
CoordinateSequenceDimensions getCoordinateSequenceDimensions ()
UnitsOfMeasure getUnitsOfMeasure ()
DimensionInfo getDimensionInfo ()
String getLexicalForm ()
boolean isEmpty ()
boolean isSimple ()
boolean isValid ()
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static final GeometryWrapper extract (NodeValue geometryLiteral, GeometryIndex targetIndex)
Extract Geometry Wrapper from Geometry Literal.
static final GeometryWrapper extract (Node geometryLiteral, GeometryIndex targetIndex) throws DatatypeFormatException
Extract Geometry Wrapper from Geometry Literal.
static final GeometryWrapper extract (NodeValue geometryLiteral)
Extract Geometry Wrapper from Geometry Literal.
static final GeometryWrapper extract (Node geometryLiteral)
Extract Geometry Wrapper from Geometry Literal.
static final GeometryWrapper extract (Literal geometryLiteral, GeometryIndex targetIndex)
Extract Geometry Wrapper from Geometry Literal.
static final GeometryWrapper extract (Literal geometryLiteral)
Extract Geometry Wrapper from Geometry Literal.
static GeometryWrapper extract (String lexicalForm, String datatypeURI)
Extract Geometry Wrapper from Geometry Literal.
static GeometryWrapper extract (String lexicalForm, String datatypeURI, GeometryIndex targetIndex) throws DatatypeFormatException
Extract Geometry Wrapper from Geometry Literal.
static final GeometryWrapper fromPoint (double x, double y, String srsURI)
Builds a WKT Point of Geometry Wrapper.
static final GeometryWrapper getEmptyWKT ()
Protected Member Functions
GeometryWrapper (Geometry parsingGeometry, Geometry xyGeometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo)
GeometryWrapper (Geometry parsingGeometry, Geometry xyGeometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo, String lexicalForm)
GeometryWrapper transform (String srsURI, Boolean storeSRSTransform) throws MismatchedDimensionException, TransformException, FactoryException
Transform the GeometryWrapper into another spatial reference system.
Private Member Functions
void checkPreparedGeometry ()
Checks whether the prepared geometry has been initialised.
Private Attributes
final DimensionInfo dimensionInfo
final SRSInfo srsInfo
final Geometry xyGeometry
final Geometry parsingGeometry
PreparedGeometry preparedGeometry
Envelope envelope
Geometry translateXYGeometry
final String geometryDatatypeURI
GeometryDatatype geometryDatatype
String lexicalForm
String utmURI = null
Double latitude = null
Static Private Attributes
static final long serialVersionUID = 1L
Constructor & Destructor Documentation
GeometryWrapper() [1/9]
GeometryWrapper (Geometry geometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo)
Parameters
geometry In X/Y or Y/X coordinate order of the SRS URI.
srsURI
geometryDatatypeURI
dimensionInfo
{
         this(geometry, srsURI, geometryDatatypeURI, dimensionInfo, null);
     }
References GeometryWrapper.dimensionInfo, and GeometryWrapper.geometryDatatypeURI.
Referenced by GeometryWrapper.boundary(), GeometryWrapper.buffer(), GeometryWrapper.convexHull(), GeometryWrapper.difference(), GeometryWrapper.envelope(), GeometryWrapper.equals(), GeometryWrapper.fromPoint(), GeometryWrapper.intersection(), GeometryWrapper.symDifference(), and GeometryWrapper.union().
GeometryWrapper() [2/9]
GeometryWrapper (Geometry geometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo, String geometryLiteral)
Parameters
geometry In X/Y or Y/X coordinate order of the SRS URI.
srsURI
geometryDatatypeURI
dimensionInfo
geometryLiteral
{
         this(geometry, GeometryReverse.check(geometry, srsURI.isEmpty() ? SRS_URI.DEFAULT_WKT_CRS84 : srsURI), srsURI.isEmpty() ? SRS_URI.DEFAULT_WKT_CRS84 : srsURI, geometryDatatypeURI, dimensionInfo, geometryLiteral);
     }
References GeometryWrapper.dimensionInfo, and GeometryWrapper.geometryDatatypeURI.
GeometryWrapper() [3/9]
GeometryWrapper (Geometry parsingGeometry, Geometry xyGeometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo) protected
{
         this(parsingGeometry, xyGeometry, srsURI, geometryDatatypeURI, dimensionInfo, null);
     }
References GeometryWrapper.dimensionInfo, GeometryWrapper.geometryDatatypeURI, GeometryWrapper.parsingGeometry, and GeometryWrapper.xyGeometry.
GeometryWrapper() [4/9]
GeometryWrapper (Geometry parsingGeometry, Geometry xyGeometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo, String lexicalForm) protected
{
         this.parsingGeometry = parsingGeometry;
         this.xyGeometry = xyGeometry;
         this.preparedGeometry = null; //Initialised when required by spatial relations checkPreparedGeometry.
         this.envelope = null; //Initialised when required by getEnvelope().
         this.translateXYGeometry = null; //Initialised when required by translateGeometry().
         this.geometryDatatypeURI = geometryDatatypeURI;
         this.geometryDatatype = null; //Inilialised when required by getGeometryDatatype().
         if (srsURI.isEmpty()) {
             srsURI = SRS_URI.DEFAULT_WKT_CRS84;
         }
         this.srsInfo = SRSRegistry.getSRSInfo(srsURI);
         this.dimensionInfo = dimensionInfo;
         this.lexicalForm = lexicalForm; //If not Initialised then required by asLiteral() etc.
     }
References GeometryWrapper.dimensionInfo, GeometryWrapper.geometryDatatypeURI, SRSRegistry.getSRSInfo(), GeometryWrapper.lexicalForm, GeometryWrapper.parsingGeometry, and GeometryWrapper.xyGeometry.
GeometryWrapper() [5/9]
GeometryWrapper (Geometry geometry, String geometryDatatypeURI)
Default to WGS84 geometry and XY coordinate dimensions.
Parameters
geometry In X/Y or Y/X coordinate order of WGS84.
geometryDatatypeURI
{
         this(geometry, "", geometryDatatypeURI, DimensionInfo.XY_POINT);
     }
References GeometryWrapper.geometryDatatypeURI.
GeometryWrapper() [6/9]
GeometryWrapper (Geometry geometry, String srsURI, String geometryDatatypeURI)
Default to XY coordinate dimensions.
Parameters
geometry In X/Y or Y/X coordinate order of the SRS URI.
srsURI
geometryDatatypeURI
{
         this(geometry, srsURI, geometryDatatypeURI, DimensionInfo.XY_POINT);
     }
References GeometryWrapper.geometryDatatypeURI.
GeometryWrapper() [7/9]
GeometryWrapper (String srsURI, String geometryDatatypeURI)
Empty geometry with specified parameters.
Parameters
srsURI
geometryDatatypeURI
{
         this(new CustomCoordinateSequence(DimensionInfo.XY_POINT.getDimensions()), geometryDatatypeURI, srsURI);
     }
References GeometryWrapper.geometryDatatypeURI.
GeometryWrapper() [8/9]
GeometryWrapper (CustomCoordinateSequence pointCoordinateSequence, String geometryDatatypeURI, String srsURI)
Point geometry with specified SRS.
Parameters
pointCoordinateSequence
geometryDatatypeURI
srsURI
{
         this(CustomGeometryFactory.theInstance().createPoint(pointCoordinateSequence), srsURI, geometryDatatypeURI, DimensionInfo.XY_POINT);
     }
References GeometryWrapper.geometryDatatypeURI.
GeometryWrapper() [9/9]
GeometryWrapper (GeometryWrapper geometryWrapper)
Copy GeometryWrapper.
Parameters
geometryWrapper
{
         this.xyGeometry = geometryWrapper.xyGeometry;
         this.parsingGeometry = geometryWrapper.parsingGeometry;
         this.preparedGeometry = geometryWrapper.preparedGeometry;
         this.envelope = geometryWrapper.envelope;
         this.translateXYGeometry = geometryWrapper.translateXYGeometry;
         this.utmURI = geometryWrapper.utmURI;
         this.latitude = geometryWrapper.latitude;
         this.geometryDatatypeURI = geometryWrapper.geometryDatatypeURI;
         this.geometryDatatype = geometryWrapper.geometryDatatype;
         this.srsInfo = geometryWrapper.srsInfo;
         this.dimensionInfo = geometryWrapper.dimensionInfo;
         this.lexicalForm = geometryWrapper.lexicalForm;
     }
References GeometryWrapper.dimensionInfo, GeometryWrapper.envelope, GeometryWrapper.geometryDatatype, GeometryWrapper.geometryDatatypeURI, GeometryWrapper.latitude, GeometryWrapper.lexicalForm, GeometryWrapper.parsingGeometry, GeometryWrapper.preparedGeometry, GeometryWrapper.srsInfo, GeometryWrapper.translateXYGeometry, GeometryWrapper.utmURI, and GeometryWrapper.xyGeometry.
Member Function Documentation
asLiteral() [1/3]
Literal asLiteral () throws DatatypeFormatException
Returns
GeometryWrapper as Literal
{
         GeometryDatatype datatype = getGeometryDatatype(); //Datatype is only retrieved when required.
         if (lexicalForm != null) {
             return ResourceFactory.createTypedLiteral(lexicalForm, datatype);
         }
         Literal literal = asLiteral(datatype);
         lexicalForm = literal.getLexicalForm();
         return literal;
     }
References GeometryWrapper.getGeometryDatatype(), and GeometryWrapper.lexicalForm.
Referenced by GeometryWrapper.asLiteral(), GeometryWrapper.asNodeValue(), and GeometryWrapper.getLexicalForm().
asLiteral() [2/3]
Literal asLiteral (GeometryDatatype datatype)
Parameters
datatype
Returns
GeometryWrapper as Literal
{
         String tempLexicalForm = datatype.unparse(this);
         return ResourceFactory.createTypedLiteral(tempLexicalForm, datatype);
     }
asLiteral() [3/3]
Literal asLiteral (String outputGeometryDatatypeURI) throws DatatypeFormatException
Parameters
outputGeometryDatatypeURI
Returns
GeometryWrapper as Literal in datatype form.
{
         GeometryDatatype datatype = GeometryDatatype.get(outputGeometryDatatypeURI);
         return asLiteral(datatype);
     }
References GeometryWrapper.asLiteral(), and GeometryDatatype.get().
asNode()
Node asNode () throws DatatypeFormatException
Returns
GeometryWrapper as Node
{
         return asNodeValue().asNode();
     }
References GeometryWrapper.asNodeValue().
Referenced by GeometryWrapper.extract().
asNodeValue()
NodeValue asNodeValue () throws DatatypeFormatException
Returns
GeometryWrapper as NodeValue
{
         Literal literal = asLiteral();
         return NodeValue.makeNode(literal.getLexicalForm(), literal.getDatatype());
     }
References GeometryWrapper.asLiteral().
Referenced by GeometryWrapper.asNode(), ConvertCRS.exec(), and ConvertCRS2.exec().
boundary()
GeometryWrapper boundary ()
Returns
Boundary of GeometryWrapper
{
         Geometry xyGeo = this.xyGeometry.getBoundary();
         Geometry parsingGeo = GeometryReverse.check(xyGeo, srsInfo);
         return new GeometryWrapper(parsingGeo, xyGeo, srsInfo.getSrsURI(), geometryDatatypeURI, dimensionInfo);
     }
References GeometryWrapper.dimensionInfo, GeometryWrapper.geometryDatatypeURI, GeometryWrapper.GeometryWrapper(), SRSInfo.getSrsURI(), and GeometryWrapper.srsInfo.
buffer()
GeometryWrapper buffer (double distance, String targetDistanceUnitsURI) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
distance
targetDistanceUnitsURI
Returns
Buffer around GeometryWrapper according the provided distance.
Exceptions
FactoryException
MismatchedDimensionException
TransformException
{
         //Check whether the source geometry is linear units for cartesian calculation. If not then transform to relevant UTM SRS GeometryWrapper.
         Boolean isTargetUnitsLinear = UnitsRegistry.isLinearUnits(targetDistanceUnitsURI);
         GeometryWrapper transformedGeometryWrapper;
         Boolean isTransformNeeded;
         if (srsInfo.getUnitsOfMeasure().isLinearUnits() == isTargetUnitsLinear) {
             //Source geometry and target units are both the same.
             transformedGeometryWrapper = this;
             isTransformNeeded = false;
         } else if (isTargetUnitsLinear) {
             //Source geometry is not linear but targets are so convert to linear SRS.
             String sourceUtmURI = getUTMZoneURI();
             transformedGeometryWrapper = transform(sourceUtmURI);
             isTransformNeeded = true;
         } else {
             //Source geometry is linear but targets are not so convert to nonlinear SRS.
             transformedGeometryWrapper = transform(SRS_URI.DEFAULT_WKT_CRS84);
             isTransformNeeded = true;
         }
         //Check whether the units of the distance need converting.
         double transformedDistance = UnitsOfMeasure.conversion(distance, targetDistanceUnitsURI, transformedGeometryWrapper.srsInfo.getUnitsOfMeasure().getUnitURI());
         //Buffer the transformed geometry
         Geometry xyGeo = transformedGeometryWrapper.xyGeometry.buffer(transformedDistance);
         DimensionInfo bufferedDimensionInfo = new DimensionInfo(dimensionInfo.getCoordinate(), dimensionInfo.getSpatial(), xyGeo.getDimension());
         Geometry parsingGeo = GeometryReverse.check(xyGeo, transformedGeometryWrapper.srsInfo);
         GeometryWrapper bufferedGeometryWrapper = new GeometryWrapper(parsingGeo, xyGeo, transformedGeometryWrapper.srsInfo.getSrsURI(), transformedGeometryWrapper.geometryDatatypeURI, bufferedDimensionInfo);
         //Check whether need to transform back to the original srsURI.
         if (isTransformNeeded) {
             //Don't store the buffered geometry as it is dependent upon the target distance and so likely to vary beween calls.
             return bufferedGeometryWrapper.transform(srsInfo.getSrsURI(), false);
         } else {
             return bufferedGeometryWrapper;
         }
     }
References GeometryWrapper.dimensionInfo, GeometryWrapper.distance(), GeometryWrapper.geometryDatatypeURI, GeometryWrapper.GeometryWrapper(), SRSInfo.getSrsURI(), SRSInfo.getUnitsOfMeasure(), GeometryWrapper.getUTMZoneURI(), GeometryWrapper.srsInfo, GeometryWrapper.transform(), and GeometryWrapper.xyGeometry.
checkPreparedGeometry()
void checkPreparedGeometry () private
Checks whether the prepared geometry has been initialised.
Done lazily as expensive.
{
         if (preparedGeometry == null) {
             this.preparedGeometry = PreparedGeometryFactory.prepare(xyGeometry);
         }
     }
References GeometryWrapper.preparedGeometry, and GeometryWrapper.xyGeometry.
Referenced by GeometryWrapper.contains(), GeometryWrapper.crosses(), GeometryWrapper.disjoint(), GeometryWrapper.intersects(), GeometryWrapper.overlaps(), GeometryWrapper.touches(), and GeometryWrapper.within().
checkTransformSRS()
GeometryWrapper checkTransformSRS (GeometryWrapper targetGeometryWrapper) throws FactoryException, MismatchedDimensionException, TransformException
Transforms, if necessary, the provided target GeometryWrapper according to this GeometryWrapper SRS_URI.
Parameters
targetGeometryWrapper
Returns
GeometryWrapper after transformation.
Exceptions
FactoryException
MismatchedDimensionException
TransformException
{
         GeometryWrapper transformedGeometryWrapper;
         String srsURI = srsInfo.getSrsURI();
         if (srsURI.equals(targetGeometryWrapper.srsInfo.getSrsURI())) {
             transformedGeometryWrapper = targetGeometryWrapper;
         } else {
             transformedGeometryWrapper = targetGeometryWrapper.transform(srsURI);
         }
         return transformedGeometryWrapper;
     }
References SRSInfo.getSrsURI(), GeometryWrapper.srsInfo, and GeometryWrapper.transform().
Referenced by GeometryWrapper.contains(), GeometryWrapper.crosses(), GeometryWrapper.difference(), GeometryWrapper.disjoint(), GeometryWrapper.distanceEuclidean(), GeometryWrapper.distanceGreatCircle(), GeometryWrapper.equalsExact(), GeometryWrapper.equalsTopo(), GeometryWrapper.intersection(), GeometryWrapper.intersects(), GeometryWrapper.overlaps(), GeometryWrapper.relate(), GeometryWrapper.symDifference(), GeometryWrapper.touches(), GeometryWrapper.union(), and GeometryWrapper.within().
contains()
boolean contains (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
Returns
sfContains of GeometryWrapper with target.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         this.checkPreparedGeometry();
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         return this.preparedGeometry.contains(transformedGeometry.xyGeometry);
     }
References GeometryWrapper.checkPreparedGeometry(), GeometryWrapper.checkTransformSRS(), and GeometryWrapper.xyGeometry.
convertSRS()
GeometryWrapper convertSRS (String srsURI) throws FactoryException, MismatchedDimensionException, TransformException
Returns this geometry wrapper converted to the SRS_URI URI.
Parameters
srsURI
Returns
GeometryWrapper after conversion.
Exceptions
FactoryException
MismatchedDimensionException
TransformException
{
         return transform(srsURI);
     }
References GeometryWrapper.transform().
Referenced by GeometryWrapper.getLatitude().
convexHull()
GeometryWrapper convexHull ()
Returns
Convex Hull of GeometryWrapper
{
         Geometry xyGeo = this.xyGeometry.convexHull();
         Geometry parsingGeo = GeometryReverse.check(xyGeo, srsInfo);
         return new GeometryWrapper(parsingGeo, xyGeo, srsInfo.getSrsURI(), geometryDatatypeURI, dimensionInfo);
     }
References GeometryWrapper.convexHull(), GeometryWrapper.dimensionInfo, GeometryWrapper.geometryDatatypeURI, GeometryWrapper.GeometryWrapper(), SRSInfo.getSrsURI(), and GeometryWrapper.srsInfo.
Referenced by GeometryWrapper.convexHull().
crosses()
boolean crosses (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
Returns
sfCrosses of GeometryWrapper with target.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         this.checkPreparedGeometry();
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         return this.preparedGeometry.crosses(transformedGeometry.xyGeometry);
     }
References GeometryWrapper.checkPreparedGeometry(), GeometryWrapper.checkTransformSRS(), and GeometryWrapper.xyGeometry.
difference()
GeometryWrapper difference (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
Returns
Difference of GeometryWrapper with target.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         Geometry xyGeo = this.xyGeometry.difference(transformedGeometry.xyGeometry);
         Geometry parsingGeo = GeometryReverse.check(xyGeo, srsInfo);
         return new GeometryWrapper(parsingGeo, xyGeo, srsInfo.getSrsURI(), geometryDatatypeURI, dimensionInfo);
     }
References GeometryWrapper.checkTransformSRS(), GeometryWrapper.dimensionInfo, GeometryWrapper.geometryDatatypeURI, GeometryWrapper.GeometryWrapper(), SRSInfo.getSrsURI(), GeometryWrapper.srsInfo, and GeometryWrapper.xyGeometry.
disjoint()
boolean disjoint (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
Returns
sfDisjoint of GeometryWrapper with target.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         this.checkPreparedGeometry();
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         return this.preparedGeometry.disjoint(transformedGeometry.xyGeometry);
     }
References GeometryWrapper.checkPreparedGeometry(), GeometryWrapper.checkTransformSRS(), and GeometryWrapper.xyGeometry.
distance() [1/3]
double distance (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Euclidean or Great Circle depending on Geometry SRS URI) defaulting to metres.
Parameters
targetGeometry
Returns
Distance
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         return distance(targetGeometry, Unit_URI.METRE_URL);
     }
Referenced by GeometryWrapper.buffer(), GeometryWrapper.distance(), GeometryWrapper.distanceEuclidean(), and GeometryWrapper.distanceGreatCircle().
distance() [2/3]
double distance (GeometryWrapper targetGeometry, String targetDistanceUnitsURI) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Euclidean or Great Circle depending on Geometry SRS URI) in the Units of Measure stated in URI.
Parameters
targetGeometry
targetDistanceUnitsURI
Returns
Distance
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         double targetDistance;
         if (srsInfo.isGeographic()) {
             targetDistance = distanceGreatCircle(targetGeometry, targetDistanceUnitsURI);
         } else {
             targetDistance = distanceEuclidean(targetGeometry, targetDistanceUnitsURI);
         }
         return targetDistance;
     }
References GeometryWrapper.distanceEuclidean(), GeometryWrapper.distanceGreatCircle(), SRSInfo.isGeographic, and GeometryWrapper.srsInfo.
distance() [3/3]
double distance (GeometryWrapper targetGeometry, UnitsOfMeasure unitsOfMeasure) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Euclidean or Great Circle depending on Geometry SRS URI) in the Units of Measure.
Parameters
targetGeometry
unitsOfMeasure
Returns
Distance
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         return distance(targetGeometry, unitsOfMeasure.getUnitURI());
     }
References GeometryWrapper.distance().
distanceEuclidean() [1/3]
double distanceEuclidean (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Euclidean) defaulting to metres.
Parameters
targetGeometry
Returns
Distance
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         return distanceEuclidean(targetGeometry, Unit_URI.METRE_URL);
     }
Referenced by GeometryWrapper.distance(), and GeometryWrapper.distanceEuclidean().
distanceEuclidean() [2/3]
double distanceEuclidean (GeometryWrapper targetGeometry, String targetDistanceUnitsURI) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Euclidean) in the Units of Measure stated in URI.
Parameters
targetGeometry
targetDistanceUnitsURI
Returns
Distance
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         Boolean isUnitsLinear = srsInfo.getUnitsOfMeasure().isLinearUnits();
         Boolean isTargetUnitsLinear = UnitsRegistry.isLinearUnits(targetDistanceUnitsURI);
         GeometryWrapper transformedTargetGeometry = checkTransformSRS(targetGeometry);
         double distance = xyGeometry.distance(transformedTargetGeometry.xyGeometry);
         String unitsURI = srsInfo.getUnitsOfMeasure().getUnitURI();
         double targetDistance;
         if (isUnitsLinear.equals(isTargetUnitsLinear)) {
             //Units are same so straight conversion.
             targetDistance = UnitsOfMeasure.conversion(distance, unitsURI, targetDistanceUnitsURI);
         } else {
             targetDistance = UnitsOfMeasure.convertBetween(distance, unitsURI, targetDistanceUnitsURI, isTargetUnitsLinear, getLatitude());
         }
         return targetDistance;
     }
References GeometryWrapper.checkTransformSRS(), GeometryWrapper.distance(), GeometryWrapper.getLatitude(), SRSInfo.getUnitsOfMeasure(), GeometryWrapper.srsInfo, and GeometryWrapper.xyGeometry.
distanceEuclidean() [3/3]
double distanceEuclidean (GeometryWrapper targetGeometry, UnitsOfMeasure unitsOfMeasure) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Euclidean) in the Units of Measure.
Parameters
targetGeometry
unitsOfMeasure
Returns
Distance
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         return distanceEuclidean(targetGeometry, unitsOfMeasure.getUnitURI());
     }
References GeometryWrapper.distanceEuclidean().
distanceGreatCircle() [1/3]
double distanceGreatCircle (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Great Circle) defaulting to metres.
Parameters
targetGeometry
Returns
Distance
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         return distanceGreatCircle(targetGeometry, Unit_URI.METRE_URL);
     }
Referenced by GeometryWrapper.distance(), and GeometryWrapper.distanceGreatCircle().
distanceGreatCircle() [2/3]
double distanceGreatCircle (GeometryWrapper targetGeometry, String targetDistanceUnitsURI) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Great Circle) in the Units of Measure stated in URI.
Parameters
targetGeometry
targetDistanceUnitsURI
Returns
Distance
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         GeometryWrapper transformedSourceGeometry;
         if (srsInfo.isGeographic()) {
             //Already a geographic SRS.
             transformedSourceGeometry = this;
         } else {
             //Use WGS84 and not CRS84 as assuming WGS8 is more prevalent.
             transformedSourceGeometry = this.transform(SRS_URI.WGS84_CRS);
         }
         GeometryWrapper transformedTargetGeometry = transformedSourceGeometry.checkTransformSRS(targetGeometry);
         //Find the nearest pair of coordinates from each Geometry using Euclidean distance (adjusting for wrap around).
         //These are then used for Great Circle distance.
         CoordinatePair coordinatePair = CoordinatePair.findNearestPair(transformedSourceGeometry, transformedTargetGeometry);
         //Check whether the nearest pair are the same, i.e. the overlap or within each other.
         if (coordinatePair.isEqual()) {
             //Exit early as the distance is zero.
             return 0.0;
         }
         Coordinate coord1 = coordinatePair.getCoord1();
         Coordinate coord2 = coordinatePair.getCoord2();
         //Vincenty Formula is apparently more accurate at the Longitude boundary.
         double distance = GreatCircleDistance.vincentyFormula(coord1.getY(), coord1.getX(), coord2.getY(), coord2.getX());
         //double distance = GreatCircleDistance.haversineFormula(coord1.getY(), coord1.getX(), coord2.getY(), coord2.getX());
         //Convert the Great Circle distance from metres into the requested units.
         Boolean isTargetUnitsLinear = UnitsRegistry.isLinearUnits(targetDistanceUnitsURI);
         double targetDistance;
         if (isTargetUnitsLinear) {
             //Target units are linear so straight conversion. Distance is in metres already.
             targetDistance = UnitsOfMeasure.conversion(distance, Unit_URI.METRE_URL, targetDistanceUnitsURI);
         } else {
             targetDistance = UnitsOfMeasure.convertBetween(distance, Unit_URI.METRE_URL, targetDistanceUnitsURI, isTargetUnitsLinear, transformedSourceGeometry.getLatitude());
         }
         return targetDistance;
     }
References GeometryWrapper.checkTransformSRS(), GeometryWrapper.distance(), GeometryWrapper.getLatitude(), SRSInfo.isGeographic, GeometryWrapper.srsInfo, and GeometryWrapper.transform().
distanceGreatCircle() [3/3]
double distanceGreatCircle (GeometryWrapper targetGeometry, UnitsOfMeasure unitsOfMeasure) throws FactoryException, MismatchedDimensionException, TransformException
Distance (Great Circle) in the Units of Measure.
Parameters
targetGeometry
unitsOfMeasure
Returns
Distance
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         return distanceGreatCircle(targetGeometry, unitsOfMeasure.getUnitURI());
     }
References GeometryWrapper.distanceGreatCircle().
envelope()
GeometryWrapper envelope ()
Envelope of GeometryWrapper with original coordinate order.
Returns
Envelope of GeometryWrapper
{
         GeometryFactory geometryFactory = this.xyGeometry.getFactory();
         Envelope xyEnvelope = this.getEnvelope();
         Geometry xyGeo = geometryFactory.toGeometry(xyEnvelope);
         Geometry parsingGeo = GeometryReverse.check(xyGeo, srsInfo);
         return new GeometryWrapper(parsingGeo, xyGeo, srsInfo.getSrsURI(), geometryDatatypeURI, dimensionInfo);
     }
References GeometryWrapper.dimensionInfo, GeometryWrapper.geometryDatatypeURI, GeometryWrapper.GeometryWrapper(), GeometryWrapper.getEnvelope(), SRSInfo.getSrsURI(), and GeometryWrapper.srsInfo.
equals()
boolean equals (Object obj)
{
         if (this == obj) {
             return true;
         }
         if (obj == null) {
             return false;
         }
         if (getClass() != obj.getClass()) {
             return false;
         }
         final GeometryWrapper other = (GeometryWrapper) obj;
         if (!Objects.equals(this.geometryDatatypeURI, other.geometryDatatypeURI)) {
             return false;
         }
         if (!Objects.equals(this.dimensionInfo, other.dimensionInfo)) {
             return false;
         }
         if (!Objects.equals(this.srsInfo, other.srsInfo)) {
             return false;
         }
         return Objects.equals(this.xyGeometry, other.xyGeometry);
     }
References GeometryWrapper.dimensionInfo, GeometryWrapper.equals(), GeometryWrapper.geometryDatatypeURI, GeometryWrapper.GeometryWrapper(), GeometryWrapper.srsInfo, and GeometryWrapper.xyGeometry.
Referenced by GeometryWrapper.equals().
equalsExact() [1/2]
boolean equalsExact (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
Returns
Equals exactly of GeometryWrapper with target.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         return this.xyGeometry.equalsExact(transformedGeometry.xyGeometry);
     }
References GeometryWrapper.checkTransformSRS(), and GeometryWrapper.xyGeometry.
equalsExact() [2/2]
boolean equalsExact (GeometryWrapper targetGeometry, double tolerance) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
tolerance
Returns
Equals exactly of GeometryWrapper with target using provided tolerance.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         return this.xyGeometry.equalsExact(transformedGeometry.xyGeometry, tolerance);
     }
References GeometryWrapper.checkTransformSRS(), and GeometryWrapper.xyGeometry.
equalsTopo()
boolean equalsTopo (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
Returns
Topology equals of GeometryWrapper with target.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         return this.xyGeometry.equalsTopo(transformedGeometry.xyGeometry);
     }
References GeometryWrapper.checkTransformSRS(), and GeometryWrapper.xyGeometry.
extract() [1/8]
static final GeometryWrapper extract (Literal geometryLiteral) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
geometryLiteral
Returns
Geometry Wrapper of the Geometry Literal.
{
         return extract(geometryLiteral, GeometryIndex.PRIMARY);
     }
References GeometryWrapper.extract(), and GeometryLiteralIndex.GeometryIndex.PRIMARY.
extract() [2/8]
static final GeometryWrapper extract (Literal geometryLiteral, GeometryIndex targetIndex) static
Extract Geometry Wrapper from Geometry Literal.
Returns null if invalid literal provided.
Parameters
geometryLiteral
targetIndex
Returns
Geometry Wrapper of the Geometry Literal.
{
         return extract(geometryLiteral.getLexicalForm(), geometryLiteral.getDatatypeURI(), targetIndex);
     }
References GeometryWrapper.extract().
extract() [3/8]
static final GeometryWrapper extract (Node geometryLiteral) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
geometryLiteral
Returns
Geometry Wrapper of the Geometry Literal.
{
         return extract(geometryLiteral, GeometryIndex.PRIMARY);
     }
References GeometryWrapper.extract(), and GeometryLiteralIndex.GeometryIndex.PRIMARY.
extract() [4/8]
static final GeometryWrapper extract (Node geometryLiteral, GeometryIndex targetIndex) throws DatatypeFormatException static
Extract Geometry Wrapper from Geometry Literal.
Parameters
geometryLiteral
targetIndex
Returns
Geometry Wrapper of the Geometry Literal.
{
         if (!geometryLiteral.isLiteral()) {
             throw new DatatypeFormatException("Not a Literal: " + geometryLiteral);
         }
         String datatypeURI = geometryLiteral.getLiteralDatatypeURI();
         String lexicalForm = geometryLiteral.getLiteralLexicalForm();
         return extract(lexicalForm, datatypeURI, targetIndex);
     }
References GeometryWrapper.extract(), and GeometryWrapper.lexicalForm.
extract() [5/8]
static final GeometryWrapper extract (NodeValue geometryLiteral) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
geometryLiteral
Returns
Geometry Wrapper of the Geometry Literal.
{
         return extract(geometryLiteral, GeometryIndex.PRIMARY);
     }
References GeometryWrapper.extract(), and GeometryLiteralIndex.GeometryIndex.PRIMARY.
extract() [6/8]
static final GeometryWrapper extract (NodeValue geometryLiteral, GeometryIndex targetIndex) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
geometryLiteral
targetIndex
Returns
Geometry Wrapper of the Geometry Literal.
{
         Node node = geometryLiteral.asNode();
         return extract(node, targetIndex);
     }
References GeometryWrapper.asNode().
Referenced by AsGeoJSON.exec(), ConvertCRS.exec(), ConvertCRS2.exec(), HasHorizontalSRS.exec(), IsInCRSAreaOfValidity.exec(), SRIDGetAxis1Name.exec(), SRIDGetAxis1Orientation.exec(), SRIDGetAxis2Name.exec(), SRIDGetAxis2Orientation.exec(), SRIDHasFlippedAxis.exec(), EqualSRS.exec(), IsEligibleConversion.exec(), SetSRID.exec(), GeometryWrapper.extract(), and LiteralUtils.rasterOrVector().
extract() [7/8]
static GeometryWrapper extract (String lexicalForm, String datatypeURI) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
lexicalForm
datatypeURI
Returns
Geometry Wrapper of the Geometry Literal.
{
         return extract(lexicalForm, datatypeURI, GeometryIndex.PRIMARY);
     }
References GeometryWrapper.extract(), GeometryWrapper.lexicalForm, and GeometryLiteralIndex.GeometryIndex.PRIMARY.
extract() [8/8]
static GeometryWrapper extract (String lexicalForm, String datatypeURI, GeometryIndex targetIndex) throws DatatypeFormatException static
Extract Geometry Wrapper from Geometry Literal.
Parameters
lexicalForm
datatypeURI
targetIndex
Returns
Geometry Wrapper of the Geometry Literal.
{
         if (lexicalForm == null || datatypeURI == null) {
             throw new DatatypeFormatException("GeometryWrapper extraction: arguments cannot be null - " + lexicalForm + ", " + datatypeURI);
         }
         GeometryDatatype datatype = GeometryDatatype.get(datatypeURI);
         GeometryWrapper geometry = datatype.parse(lexicalForm, targetIndex);
         return geometry;
     }
References GeometryDatatype.get(), GeometryWrapper.lexicalForm, and GeometryDatatype.parse().
fromPoint()
static final GeometryWrapper fromPoint (double x, double y, String srsURI) static
Builds a WKT Point of Geometry Wrapper.
This method does not use the GeometryLiteralIndex and so is best used for one of Geometry Wrappers.
Returns
Geometry Wrapper of WKT Point.
{
         CustomCoordinateSequence coordSequence = CustomCoordinateSequence.createPoint(x, y);
         GeometryWrapper geometryWrapper = new GeometryWrapper(coordSequence, WKTDatatype.URI, srsURI);
         return geometryWrapper;
     }
References GeometryWrapper.GeometryWrapper().
getCoordinateDimension()
int getCoordinateDimension ()
Returns
Coordinate dimension, i.e. 2 (x,y), 3 (x,y,z or x,y,m) or 4 (x,y,z,m)
{
         return dimensionInfo.getCoordinate();
     }
References GeometryWrapper.dimensionInfo.
getCoordinateSequenceDimensions()
CoordinateSequenceDimensions getCoordinateSequenceDimensions ()
Returns
Enum of coordinate dimensions.
{
         return dimensionInfo.getDimensions();
     }
References GeometryWrapper.dimensionInfo.
getCRS()
CoordinateReferenceSystem getCRS ()
Returns
Coordinate/Spatial reference system of the GeometryWrapper.
{
         return srsInfo.getCrs();
     }
References SRSInfo.getCrs(), and GeometryWrapper.srsInfo.
Referenced by ConvertCRS.exec(), ConvertCRS2.exec(), HasHorizontalSRS.exec(), and IsEligibleConversion.exec().
getDimensionInfo()
DimensionInfo getDimensionInfo ()
Returns
GeometryWrapper's coordinate, spatial and topological dimensions.
{
         return dimensionInfo;
     }
References GeometryWrapper.dimensionInfo.
getEmptyWKT()
static final GeometryWrapper getEmptyWKT () static
Returns
Empty GeometryWrapper in WKT datatype.
{
         return WKTDatatype.INSTANCE.read("");
     }
getEnvelope()
Envelope getEnvelope ()
Envelope of GeometryWrapper in XY order.
Returns
Envelope of GeometryWrapper
{
         if (envelope == null) {
             envelope = this.xyGeometry.getEnvelopeInternal();
         }
         return envelope;
     }
References GeometryWrapper.envelope.
Referenced by GeometryWrapper.envelope().
getGeometryDatatype()
GeometryDatatype getGeometryDatatype ()
Returns
GeometryDatatype of the literal.
{
         if (geometryDatatype == null) {
             geometryDatatype = GeometryDatatype.get(geometryDatatypeURI);
         }
         return geometryDatatype;
     }
References GeometryWrapper.geometryDatatype, GeometryWrapper.geometryDatatypeURI, and GeometryDatatype.get().
Referenced by GeometryWrapper.asLiteral().
getGeometryDatatypeURI()
String getGeometryDatatypeURI ()
Returns
Datatype URI of the literal.
{
         return geometryDatatypeURI;
     }
References GeometryWrapper.geometryDatatypeURI.
Referenced by LiteralUtils.createGeometry(), RDFCRSToWKT.createGeometry(), and SetSRID.exec().
getGeometryType()
String getGeometryType ()
Returns
The name of the parsing Geometry's actual class.
{
         return parsingGeometry.getGeometryType();
     }
References GeometryWrapper.parsingGeometry.
Referenced by ConvertCRS.exec(), and ConvertCRS2.exec().
getLatitude()
Double getLatitude () throws FactoryException, MismatchedDimensionException, TransformException
Latitude if Geographic SRS or in WGS84.
Used to convert between linear and non-linear units of measure.
Returns
Latitude of Geometry.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         if (latitude == null) {
             GeometryWrapper geoGeometryWrapper;
             if (srsInfo.isGeographic()) {
                 //Already a geographic SRS.
                 geoGeometryWrapper = this;
             } else {
                 //Use WGS84 and not CRS84 as assuming WGS8 is more prevalent.
                 geoGeometryWrapper = convertSRS(SRS_URI.WGS84_CRS);
             }
             //Latitude is Y-axis.
             Geometry geometry = geoGeometryWrapper.getXYGeometry();
             Point point = geometry.getCentroid();
             latitude = point.getY();
         }
         return latitude;
     }
References GeometryWrapper.convertSRS(), GeometryWrapper.getXYGeometry(), SRSInfo.isGeographic, GeometryWrapper.latitude, and GeometryWrapper.srsInfo.
Referenced by GeometryWrapper.distanceEuclidean(), and GeometryWrapper.distanceGreatCircle().
getLexicalForm()
String getLexicalForm ()
Returns
String literal of Geometry Wrapper.
{
         if (lexicalForm != null) {
             return lexicalForm;
         } else {
             Literal literal = asLiteral();
             return literal.getLexicalForm();
         }
     }
References GeometryWrapper.asLiteral(), and GeometryWrapper.lexicalForm.
getParsingGeometry()
Geometry getParsingGeometry ()
Returns
Geometry with coordinates as originally provided.
{
         return parsingGeometry;
     }
References GeometryWrapper.parsingGeometry.
getSpatialDimension()
int getSpatialDimension ()
Returns
Spatial dimension, i.e. 2 or 3
{
         return dimensionInfo.getSpatial();
     }
References GeometryWrapper.dimensionInfo.
getSRID()
String getSRID ()
Returns
getSRID used in GeoSPARQL Standard page 22 to refer to srsURI. i.e. getSrsURI and getSRID are the same.
{
         return srsInfo.getSrsURI();
     }
References SRSInfo.getSrsURI(), and GeometryWrapper.srsInfo.
getSrsInfo()
SRSInfo getSrsInfo ()
Returns
SRS information that the Geometry Wrapper is using.
{
         return srsInfo;
     }
References GeometryWrapper.srsInfo.
getSrsURI()
String getSrsURI ()
Returns
Coordinate/Spatial reference system URI.
{
         return srsInfo.getSrsURI();
     }
References SRSInfo.getSrsURI(), and GeometryWrapper.srsInfo.
Referenced by LiteralUtils.createGeometry(), and RDFCRSToWKT.createGeometry().
getTopologicalDimension()
int getTopologicalDimension ()
Returns
Topological dimension, i.e. 0, 1 or 2
{
         return dimensionInfo.getTopological();
     }
References GeometryWrapper.dimensionInfo.
getUnitsOfMeasure()
UnitsOfMeasure getUnitsOfMeasure ()
Returns
Units of Measure for the GeometryWrapper SRS.
{
         return srsInfo.getUnitsOfMeasure();
     }
References SRSInfo.getUnitsOfMeasure(), and GeometryWrapper.srsInfo.
getUTMZoneURI()
String getUTMZoneURI () throws FactoryException, MismatchedDimensionException, TransformException
Returns
URI of the GeometryWrapper's UTM zone
Exceptions
FactoryException
MismatchedDimensionException
TransformException
{
         if (utmURI == null) {
             //Find a point in the parsing geometry so can directly apply the SRS.
             Point coord = parsingGeometry.getCentroid();
             DirectPosition2D point = new DirectPosition2D(coord.getX(), coord.getY());
             //Convert to WGS84. Use WGS84 and not CRS84 as assuming WGS8 is more prevalent.
             CoordinateReferenceSystem wgs84CRS = SRSRegistry.getCRS(SRS_URI.WGS84_CRS);
             MathTransform transform = MathTransformRegistry.getMathTransform(srsInfo.getCrs(), wgs84CRS);
             DirectPosition wgs84Point = transform.transform(point, null);
             //Find the UTM zone.
             utmURI = SRSRegistry.findUTMZoneURIFromWGS84(wgs84Point.getOrdinate(0), wgs84Point.getOrdinate(1));
         }
         return utmURI;
     }
References SRSRegistry.findUTMZoneURIFromWGS84(), SRSInfo.getCrs(), SRSRegistry.getCRS(), GeometryWrapper.parsingGeometry, GeometryWrapper.srsInfo, GeometryWrapper.transform(), and GeometryWrapper.utmURI.
Referenced by GeometryWrapper.buffer().
getXYGeometry()
Geometry getXYGeometry ()
Returns
Geometry with coordinates in x,y order, regardless of SRS_URI.
{
         return xyGeometry;
     }
References GeometryWrapper.xyGeometry.
Referenced by AsGeoJSON.exec(), ConvertCRS.exec(), ConvertCRS2.exec(), IsInCRSAreaOfValidity.exec(), SetSRID.exec(), GeometryWrapper.getLatitude(), EncodedPolylineDatatype.unparse(), GeoJSONDatatype.unparse(), HexWKBDatatype.unparse(), KMLDatatype.unparse(), OSMDatatype.unparse(), and WKBDatatype.unparse().
hashCode()
int hashCode ()
{
         int hash = 3;
         hash = 23 * hash + Objects.hashCode(this.dimensionInfo);
         hash = 23 * hash + Objects.hashCode(this.srsInfo);
         hash = 23 * hash + Objects.hashCode(this.xyGeometry);
         hash = 23 * hash + Objects.hashCode(this.geometryDatatypeURI);
         return hash;
     }
intersection()
GeometryWrapper intersection (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
Returns
Intersection of GeometryWrapper with target.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         Geometry xyGeo = this.xyGeometry.intersection(transformedGeometry.xyGeometry);
         Geometry parsingGeo = GeometryReverse.check(xyGeo, srsInfo);
         return new GeometryWrapper(parsingGeo, xyGeo, srsInfo.getSrsURI(), geometryDatatypeURI, dimensionInfo);
     }
References GeometryWrapper.checkTransformSRS(), GeometryWrapper.dimensionInfo, GeometryWrapper.geometryDatatypeURI, GeometryWrapper.GeometryWrapper(), SRSInfo.getSrsURI(), GeometryWrapper.srsInfo, and GeometryWrapper.xyGeometry.
intersects()
boolean intersects (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
Returns
sfIntersects of GeometryWrapper with target.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         this.checkPreparedGeometry();
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         return this.preparedGeometry.intersects(transformedGeometry.xyGeometry);
     }
References GeometryWrapper.checkPreparedGeometry(), GeometryWrapper.checkTransformSRS(), and GeometryWrapper.xyGeometry.
isEmpty()
boolean isEmpty ()
Returns
Geometry is empty of coordinates.
{
         return this.xyGeometry.isEmpty();
     }
isSimple()
boolean isSimple ()
Returns
Geometry is in simple form.
{
         return this.xyGeometry.isSimple();
     }
isSRSRecognised()
Boolean isSRSRecognised ()
Returns
Whether the SRS URI has been recognised. Operations may fail or not perform correctly when false.
{
         return srsInfo.isSRSRecognised();
     }
References SRSInfo.isSRSRecognised, and GeometryWrapper.srsInfo.
isValid()
boolean isValid ()
Returns
Geometry is topologically valid.
{
         return this.xyGeometry.isValid();
     }
overlaps()
boolean overlaps (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
Returns
sfOverlaps of GeometryWrapper with target.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         this.checkPreparedGeometry();
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         return this.preparedGeometry.overlaps(transformedGeometry.xyGeometry);
     }
References GeometryWrapper.checkPreparedGeometry(), GeometryWrapper.checkTransformSRS(), and GeometryWrapper.xyGeometry.
relate() [1/2]
IntersectionMatrix relate (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
Returns
Intersection Matrix of GeometryWrapper with target.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         return xyGeometry.relate(transformedGeometry.xyGeometry);
     }
References GeometryWrapper.checkTransformSRS(), and GeometryWrapper.xyGeometry.
relate() [2/2]
boolean relate (GeometryWrapper targetGeometry, String intersectionPattern) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
intersectionPattern
Returns
Relation of GeometryWrapper with target.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         return xyGeometry.relate(transformedGeometry.xyGeometry, intersectionPattern);
     }
References GeometryWrapper.checkTransformSRS(), and GeometryWrapper.xyGeometry.
symDifference()
GeometryWrapper symDifference (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
Returns
Symmetric Difference of GeometryWrapper with target.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         Geometry xyGeo = this.xyGeometry.symDifference(transformedGeometry.xyGeometry);
         Geometry parsingGeo = GeometryReverse.check(xyGeo, srsInfo);
         return new GeometryWrapper(parsingGeo, xyGeo, srsInfo.getSrsURI(), geometryDatatypeURI, dimensionInfo, null);
     }
References GeometryWrapper.checkTransformSRS(), GeometryWrapper.dimensionInfo, GeometryWrapper.geometryDatatypeURI, GeometryWrapper.GeometryWrapper(), SRSInfo.getSrsURI(), GeometryWrapper.srsInfo, and GeometryWrapper.xyGeometry.
toString()
String toString ()
{
         return "GeometryWrapper{" + "dimensionInfo=" + dimensionInfo + ", geometryDatatypeURI=" + geometryDatatypeURI + ", lexicalForm=" + lexicalForm + ", utmURI=" + utmURI + ", latitude=" + latitude + ", xyGeometry=" + xyGeometry + ", parsingGeometry=" + parsingGeometry + ", preparedGeometry=" + preparedGeometry + ", srsInfo=" + srsInfo + '}';
     }
References GeometryWrapper.dimensionInfo, GeometryWrapper.geometryDatatypeURI, GeometryWrapper.latitude, GeometryWrapper.lexicalForm, GeometryWrapper.parsingGeometry, GeometryWrapper.preparedGeometry, GeometryWrapper.srsInfo, GeometryWrapper.utmURI, and GeometryWrapper.xyGeometry.
touches()
boolean touches (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
Returns
sfTouches of GeometryWrapper with target.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         this.checkPreparedGeometry();
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         return this.preparedGeometry.touches(transformedGeometry.xyGeometry);
     }
References GeometryWrapper.checkPreparedGeometry(), GeometryWrapper.checkTransformSRS(), and GeometryWrapper.xyGeometry.
transform() [1/3]
GeometryWrapper transform (SRSInfo srsInfo) throws MismatchedDimensionException, TransformException, FactoryException
Transform the GeometryWrapper into another spatial reference system.
Parameters
srsInfo
Returns
New GeometryWrapper after transformation, or this GeometryWrapper if no transformation.
Exceptions
MismatchedDimensionException
TransformException
FactoryException
{
         return transform(srsInfo.getSrsURI(), true);
     }
References SRSInfo.getSrsURI(), GeometryWrapper.srsInfo, and GeometryWrapper.transform().
transform() [2/3]
GeometryWrapper transform (String srsURI) throws MismatchedDimensionException, TransformException, FactoryException
Transform the GeometryWrapper into another spatial reference system.
Parameters
srsURI
Returns
New GeometryWrapper after transformation, or this GeometryWrapper if no transformation.
Exceptions
MismatchedDimensionException
TransformException
FactoryException
{
         return transform(srsURI, true);
     }
Referenced by GeometryWrapper.buffer(), GeometryWrapper.checkTransformSRS(), GeometryWrapper.convertSRS(), GeometryWrapper.distanceGreatCircle(), GeometryWrapper.getUTMZoneURI(), and GeometryWrapper.transform().
transform() [3/3]
GeometryWrapper transform (String srsURI, Boolean storeSRSTransform) throws MismatchedDimensionException, TransformException, FactoryException protected
Transform the GeometryWrapper into another spatial reference system.
Option to store the resulting GeometryWrapper in the index.
Parameters
srsURI
storeSRSTransform
Returns
GeometryWrapper after transformation.
Exceptions
MismatchedDimensionException
TransformException
FactoryException
{
         if (srsInfo.getSrsURI().equals(srsURI)) {
             return this;
         }
         return GeometryTransformIndex.transform(this, srsURI, storeSRSTransform);
     }
References SRSInfo.getSrsURI(), GeometryWrapper.srsInfo, and GeometryWrapper.transform().
translateXYGeometry()
Geometry translateXYGeometry ()
XY geometry translated by the domain range of the SRS, if a Geographic SRS.
Returns XY geometry if not a Geographic SRS.
Returns
Geometry after translation in X direction.
{
         if (translateXYGeometry == null) {
             if (srsInfo.isGeographic()) {
                 double xTranslate = srsInfo.getDomainRangeX();
                 AffineTransformation translation = AffineTransformation.translationInstance(xTranslate, 0);
                 translateXYGeometry = translation.transform(xyGeometry); //Translate seems to be copying Y values into Z and M.
             } else {
                 translateXYGeometry = xyGeometry;
             }
         }
         return translateXYGeometry;
     }
References SRSInfo.getDomainRangeX(), SRSInfo.isGeographic, GeometryWrapper.srsInfo, GeometryWrapper.translateXYGeometry, and GeometryWrapper.xyGeometry.
union()
GeometryWrapper union (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
Returns
Union of GeometryWrapper with target.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         Geometry xyGeo = this.xyGeometry.union(transformedGeometry.xyGeometry);
         Geometry parsingGeo = GeometryReverse.check(xyGeo, srsInfo);
         return new GeometryWrapper(parsingGeo, xyGeo, srsInfo.getSrsURI(), geometryDatatypeURI, dimensionInfo, null);
     }
References GeometryWrapper.checkTransformSRS(), GeometryWrapper.dimensionInfo, GeometryWrapper.geometryDatatypeURI, GeometryWrapper.GeometryWrapper(), SRSInfo.getSrsURI(), GeometryWrapper.srsInfo, and GeometryWrapper.xyGeometry.
within()
boolean within (GeometryWrapper targetGeometry) throws FactoryException, MismatchedDimensionException, TransformException
Parameters
targetGeometry
Returns
sfWithin of GeometryWrapper with target.
Exceptions
org.opengis.util.FactoryException
org.opengis.referencing.operation.TransformException
{
         this.checkPreparedGeometry();
         GeometryWrapper transformedGeometry = checkTransformSRS(targetGeometry);
         return this.preparedGeometry.within(transformedGeometry.xyGeometry);
     }
References GeometryWrapper.checkPreparedGeometry(), GeometryWrapper.checkTransformSRS(), and GeometryWrapper.xyGeometry.
Member Data Documentation
dimensionInfo
final DimensionInfo dimensionInfo private
Referenced by GeometryWrapper.boundary(), GeometryWrapper.buffer(), GeometryWrapper.convexHull(), GeometryWrapper.difference(), GeometryWrapper.envelope(), GeometryWrapper.equals(), GeometryWrapper.GeometryWrapper(), GeometryWrapper.getCoordinateDimension(), GeometryWrapper.getCoordinateSequenceDimensions(), GeometryWrapper.getDimensionInfo(), GeometryWrapper.getSpatialDimension(), GeometryWrapper.getTopologicalDimension(), GeometryWrapper.intersection(), GeometryWrapper.symDifference(), GeometryWrapper.toString(), and GeometryWrapper.union().
envelope
Envelope envelope private
Referenced by GeometryWrapper.GeometryWrapper(), and GeometryWrapper.getEnvelope().
geometryDatatype
GeometryDatatype geometryDatatype private
Referenced by GeometryWrapper.GeometryWrapper(), and GeometryWrapper.getGeometryDatatype().
geometryDatatypeURI
final String geometryDatatypeURI private
Referenced by GeometryWrapper.boundary(), GeometryWrapper.buffer(), GeometryWrapper.convexHull(), GeometryWrapper.difference(), GeometryWrapper.envelope(), GeometryWrapper.equals(), GeometryWrapper.GeometryWrapper(), GeometryWrapper.getGeometryDatatype(), GeometryWrapper.getGeometryDatatypeURI(), GeometryWrapper.intersection(), GeometryWrapper.symDifference(), GeometryWrapper.toString(), and GeometryWrapper.union().
latitude
Double latitude = null private
Referenced by GeometryWrapper.GeometryWrapper(), GeometryWrapper.getLatitude(), and GeometryWrapper.toString().
lexicalForm
String lexicalForm private
Referenced by GeometryWrapper.asLiteral(), GeometryWrapper.extract(), GeometryWrapper.GeometryWrapper(), GeometryWrapper.getLexicalForm(), and GeometryWrapper.toString().
parsingGeometry
final Geometry parsingGeometry private
Referenced by GeometryWrapper.GeometryWrapper(), GeometryWrapper.getGeometryType(), GeometryWrapper.getParsingGeometry(), GeometryWrapper.getUTMZoneURI(), and GeometryWrapper.toString().
preparedGeometry
PreparedGeometry preparedGeometry private
Referenced by GeometryWrapper.checkPreparedGeometry(), GeometryWrapper.GeometryWrapper(), and GeometryWrapper.toString().
serialVersionUID
final long serialVersionUID = 1L static private
srsInfo
final SRSInfo srsInfo private
Referenced by GeometryWrapper.boundary(), GeometryWrapper.buffer(), GeometryWrapper.checkTransformSRS(), GeometryWrapper.convexHull(), GeometryWrapper.difference(), GeometryWrapper.distance(), GeometryWrapper.distanceEuclidean(), GeometryWrapper.distanceGreatCircle(), GeometryWrapper.envelope(), GeometryWrapper.equals(), GeometryWrapper.GeometryWrapper(), GeometryWrapper.getCRS(), GeometryWrapper.getLatitude(), GeometryWrapper.getSRID(), GeometryWrapper.getSrsInfo(), GeometryWrapper.getSrsURI(), GeometryWrapper.getUnitsOfMeasure(), GeometryWrapper.getUTMZoneURI(), GeometryWrapper.intersection(), GeometryWrapper.isSRSRecognised(), GeometryWrapper.symDifference(), GeometryWrapper.toString(), GeometryWrapper.transform(), GeometryWrapper.translateXYGeometry(), and GeometryWrapper.union().
translateXYGeometry
Geometry translateXYGeometry private
Referenced by GeometryWrapper.GeometryWrapper(), and GeometryWrapper.translateXYGeometry().
utmURI
String utmURI = null private
Referenced by GeometryWrapper.GeometryWrapper(), GeometryWrapper.getUTMZoneURI(), and GeometryWrapper.toString().
xyGeometry
final Geometry xyGeometry private
Referenced by GeometryWrapper.buffer(), GeometryWrapper.checkPreparedGeometry(), GeometryWrapper.contains(), GeometryWrapper.crosses(), GeometryWrapper.difference(), GeometryWrapper.disjoint(), GeometryWrapper.distanceEuclidean(), GeometryWrapper.equals(), GeometryWrapper.equalsExact(), GeometryWrapper.equalsTopo(), GeometryWrapper.GeometryWrapper(), GeometryWrapper.getXYGeometry(), GeometryWrapper.intersection(), GeometryWrapper.intersects(), GeometryWrapper.overlaps(), GeometryWrapper.relate(), GeometryWrapper.symDifference(), GeometryWrapper.toString(), GeometryWrapper.touches(), GeometryWrapper.translateXYGeometry(), GeometryWrapper.union(), and GeometryWrapper.within().