GeoSPARQL SRS Extension: WKBRasterBand Class Reference
WKBRasterBand Class Reference
WKB Raster band, used in postGIS 2 but can be used elsewhere.
Public Member Functions
WKBRasterBand ()
int getPixelType ()
void setPixelType (int pixelType)
boolean isOffDatabase ()
void setOffDatabase (boolean offdatabase)
boolean hasNodata ()
void setHasNodata (boolean hasnodata)
boolean isNodata ()
void setIsNodata (boolean isnodata)
boolean getReserved ()
void setReserved (boolean reserved)
void setNoDataValue (Number noDataValue)
Number getNoDataValue ()
void setDatas (byte[] datas)
byte[] getDatas ()
int getNbBytePerPixel ()
int getDataBufferType ()
String toString ()
Private Attributes
int pixelType
boolean offdatabase
boolean hasnodata
boolean isnodata
boolean reserved
Number noDataValue
byte[] datas
Detailed Description
WKB Raster band, used in postGIS 2 but can be used elsewhere.
Author
Johann Sorel (Geomatys)
Constructor & Destructor Documentation
WKBRasterBand()
WKBRasterBand ()
{
     }
Member Function Documentation
getDataBufferType()
int getDataBufferType ()
{
         return WKBRasterConstants.getDataBufferType(pixelType);
     }
References WKBRasterConstants.getDataBufferType(), and WKBRasterBand.pixelType.
Referenced by WKBRasterReader.read().
getDatas()
byte [] getDatas ()
{
         return datas;
     }
References WKBRasterBand.datas.
Referenced by WKBRasterReader.read().
getNbBytePerPixel()
int getNbBytePerPixel ()
{
         return WKBRasterConstants.getNbBytePerPixel(pixelType);
     }
References WKBRasterConstants.getNbBytePerPixel(), and WKBRasterBand.pixelType.
Referenced by WKBRasterReader.read().
getNoDataValue()
Number getNoDataValue ()
{
         return noDataValue;
     }
References WKBRasterBand.noDataValue.
getPixelType()
int getPixelType ()
{
         return pixelType;
     }
References WKBRasterBand.pixelType.
Referenced by WKBRasterReader.read().
getReserved()
boolean getReserved ()
{
         return reserved;
     }
References WKBRasterBand.reserved.
hasNodata()
boolean hasNodata ()
{
         return hasnodata;
     }
References WKBRasterBand.hasnodata.
isNodata()
boolean isNodata ()
{
         return isnodata;
     }
References WKBRasterBand.isnodata.
isOffDatabase()
boolean isOffDatabase ()
{
         return offdatabase;
     }
References WKBRasterBand.offdatabase.
Referenced by WKBRasterReader.read().
setDatas()
void setDatas (byte[] datas)
{
         this.datas = datas;
     }
References WKBRasterBand.datas.
Referenced by WKBRasterReader.read().
setHasNodata()
void setHasNodata (boolean hasnodata)
{
         this.hasnodata = hasnodata;
     }
References WKBRasterBand.hasnodata.
Referenced by WKBRasterReader.read().
setIsNodata()
void setIsNodata (boolean isnodata)
{
         this.isnodata = isnodata;
     }
References WKBRasterBand.isnodata.
Referenced by WKBRasterReader.read().
setNoDataValue()
void setNoDataValue (Number noDataValue)
{
         this.noDataValue = noDataValue;
     }
References WKBRasterBand.noDataValue.
Referenced by WKBRasterReader.read().
setOffDatabase()
void setOffDatabase (boolean offdatabase)
{
         this.offdatabase = offdatabase;
     }
References WKBRasterBand.offdatabase.
Referenced by WKBRasterReader.read().
setPixelType()
void setPixelType (int pixelType)
{
         this.pixelType = pixelType;
     }
References WKBRasterBand.pixelType.
Referenced by WKBRasterReader.read().
setReserved()
void setReserved (boolean reserved)
{
         this.reserved = reserved;
     }
References WKBRasterBand.reserved.
Referenced by WKBRasterReader.read().
toString()
String toString ()
{
         final StringBuilder sb = new StringBuilder("WKB Raster Band :");
         sb.append("\n- pixel type : ").append(pixelType);
         sb.append("\n- offdatabase : ").append(offdatabase);
         sb.append("\n- hasnodata : ").append(hasnodata);
         sb.append("\n- is no data : ").append(isnodata);
         sb.append("\n- reserved : ").append(reserved);
         sb.append("\n- no data value : ").append(noDataValue);
         return sb.toString();
     }
References WKBRasterBand.hasnodata, WKBRasterBand.isnodata, WKBRasterBand.noDataValue, WKBRasterBand.offdatabase, WKBRasterBand.pixelType, and WKBRasterBand.reserved.
Member Data Documentation
datas
byte [] datas private
Referenced by WKBRasterBand.getDatas(), and WKBRasterBand.setDatas().
hasnodata
boolean hasnodata private
Referenced by WKBRasterBand.hasNodata(), WKBRasterBand.setHasNodata(), and WKBRasterBand.toString().
isnodata
boolean isnodata private
Referenced by WKBRasterBand.isNodata(), WKBRasterBand.setIsNodata(), and WKBRasterBand.toString().
noDataValue
Number noDataValue private
Referenced by WKBRasterBand.getNoDataValue(), WKBRasterBand.setNoDataValue(), and WKBRasterBand.toString().
offdatabase
boolean offdatabase private
Referenced by WKBRasterBand.isOffDatabase(), WKBRasterBand.setOffDatabase(), and WKBRasterBand.toString().
pixelType
int pixelType private
Referenced by WKBRasterBand.getDataBufferType(), WKBRasterBand.getNbBytePerPixel(), WKBRasterBand.getPixelType(), WKBRasterBand.setPixelType(), and WKBRasterBand.toString().
reserved
boolean reserved private
Referenced by WKBRasterBand.getReserved(), WKBRasterBand.setReserved(), and WKBRasterBand.toString().