GeoSPARQL SRS Extension: GeometryDatatype Class Reference
GeometryDatatype Class Reference abstract
Public Member Functions
GeometryDatatype (String uri)
abstract GeometryWrapper read (String geometryLiteral)
final GeometryWrapper parse (String lexicalForm) throws DatatypeFormatException
This method Parses the Geometry Literal to the JTS Geometry.
final GeometryWrapper parse (String lexicalForm, GeometryIndex targetIndex) throws DatatypeFormatException
Static Public Member Functions
static final void registerDatatypes ()
static final GeometryDatatype get (RDFDatatype rdfDatatype)
static final GeometryDatatype get (String datatypeURI)
static final boolean checkURI (String datatypeURI)
static final boolean check (RDFDatatype rdfDatatype)
Static Private Attributes
static final TypeMapper TYPE_MAPPER = TypeMapper.getInstance()
static boolean isDatatypesRegistered = false
Constructor & Destructor Documentation
GeometryDatatype()
GeometryDatatype (String uri)
{
         super(uri);
     }
Referenced by GeometryDatatype.checkURI().
Member Function Documentation
check()
static final boolean check (RDFDatatype rdfDatatype) static
{
         //Ensure that the registered datatypes from the type mapper are used.
         return checkURI(rdfDatatype.getURI());
     }
References GeometryDatatype.checkURI().
checkURI()
static final boolean checkURI (String datatypeURI) static
{
         registerDatatypes();
         RDFDatatype rdfDatatype = TYPE_MAPPER.getTypeByName(datatypeURI);
         if (rdfDatatype != null) {
             return rdfDatatype instanceof GeometryDatatype;
         } else {
             throw new DatatypeFormatException("Datatype not found: " + datatypeURI + " Ensure that GeoSPARQL is enabled and Datatype has been registered.");
         }
     }
References GeometryDatatype.GeometryDatatype(), GeometryDatatype.registerDatatypes(), and GeometryDatatype.TYPE_MAPPER.
Referenced by GeometryDatatype.check(), and GeometryDatatype.get().
get() [1/2]
static final GeometryDatatype get (RDFDatatype rdfDatatype) static
{
         registerDatatypes();
         //System.out.println(rdfDatatype);
         //Iterator it=TYPE_MAPPER.listTypes();
         /*while(it.hasNext()) {
                 System.out.println(it.next());
         }*/
         if (rdfDatatype instanceof GeometryDatatype) {
             return (GeometryDatatype) rdfDatatype;
         } else {
             throw new DatatypeFormatException("Unrecognised Geometry Datatype: " + rdfDatatype.getURI() + " Ensure that Datatype is extending GeometryDatatype.");
         }
     }
References GeometryDatatype.registerDatatypes().
Referenced by GeometryWrapper.asLiteral(), GeometryWrapper.extract(), GeometryDatatype.get(), GeometryWrapper.getGeometryDatatype(), and LiteralUtils.rasterOrVector().
get() [2/2]
static final GeometryDatatype get (String datatypeURI) static
{
         checkURI(datatypeURI);
         RDFDatatype rdfDatatype = TYPE_MAPPER.getTypeByName(datatypeURI);
         return GeometryDatatype.get(rdfDatatype);
     }
References GeometryDatatype.checkURI(), GeometryDatatype.get(), and GeometryDatatype.TYPE_MAPPER.
parse() [1/2]
final GeometryWrapper parse (String lexicalForm) throws DatatypeFormatException
This method Parses the Geometry Literal to the JTS Geometry.
Parameters
lexicalForm - the Geometry Literal to be parsed
Returns
geometry - if the Geometry Literal is valid.
empty geometry - if the Geometry Literal is empty.
null - if the Geometry Literal is invalid.
{
         return parse(lexicalForm, GeometryIndex.PRIMARY);
     }
References GeometryLiteralIndex.GeometryIndex.PRIMARY.
Referenced by GeometryWrapper.extract().
parse() [2/2]
final GeometryWrapper parse (String lexicalForm, GeometryIndex targetIndex) throws DatatypeFormatException
{
         //Check the Geometry Literal Index to see if been previously read and cached.
         //DatatypeReader interface used to instruct index on how to obtain the GeometryWrapper.
         try {
             return GeometryLiteralIndex.retrieve(lexicalForm, this, targetIndex);
         } catch (IllegalArgumentException ex) {
             throw new DatatypeFormatException(ex.getMessage() + " - Illegal Geometry Literal: " + lexicalForm);
         }
     }
References GeometryLiteralIndex.retrieve().
read()
abstract GeometryWrapper read (String geometryLiteral) abstract
Reimplemented in WKBDatatype, PolyshapeDatatype, OSMDatatype, KMLDatatype, HexWKBDatatype, GeoURIDatatype, GeoJSONDatatype, and EncodedPolylineDatatype.
Referenced by GeometryLiteralIndex.retrieveMemoryIndex().
registerDatatypes()
static final void registerDatatypes () static
{
         //System.out.println("Is")
         //if (!isDatatypesRegistered) {
             TYPE_MAPPER.registerDatatype(WKTDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GMLDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GeoJSONDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(KMLDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(WKBDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(TWKBDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(TopoJSONDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(GeobufDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(GeoHashDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(EncodedPolylineDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(HexWKBDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GeoURIDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(GPXDatatype.INSTANCE);
             isDatatypesRegistered = true;
         //}
     }
References EncodedPolylineDatatype.INSTANCE, GeoJSONDatatype.INSTANCE, GeoURIDatatype.INSTANCE, HexWKBDatatype.INSTANCE, KMLDatatype.INSTANCE, WKBDatatype.INSTANCE, GeometryDatatype.isDatatypesRegistered, and GeometryDatatype.TYPE_MAPPER.
Referenced by GeometryDatatype.checkURI(), and GeometryDatatype.get().
Member Data Documentation
isDatatypesRegistered
boolean isDatatypesRegistered = false static private
Referenced by GeometryDatatype.registerDatatypes().
TYPE_MAPPER
final TypeMapper TYPE_MAPPER = TypeMapper.getInstance() static private
Referenced by GeometryDatatype.checkURI(), GeometryDatatype.get(), and GeometryDatatype.registerDatatypes().