GeoSPARQL SRS Extension: WKBRastDatatype Class Reference
WKBRastDatatype Class Reference
Public Member Functions
WKBRastDatatype ()
String unparse (Object geometry)
CoverageWrapper read (String geometryLiteral)
String toString ()
final CoverageWrapper parse (String lexicalForm) throws DatatypeFormatException
This method Parses the Geometry Literal to the JTS Geometry.
final CoverageWrapper parse (String lexicalForm, GeometryIndex targetIndex) throws DatatypeFormatException
Static Public Member Functions
static final void registerDatatypes ()
static final RasterDataType get (RDFDatatype rdfDatatype)
static final RasterDataType get (String datatypeURI)
static final boolean checkURI (String datatypeURI)
static final boolean check (RDFDatatype rdfDatatype)
Static Public Attributes
static final String URI = SRSGeo.WKBRaster
static final WKBRastDatatype INSTANCE = new WKBRastDatatype()
Static Private Attributes
static final TypeMapper TYPE_MAPPER = TypeMapper.getInstance()
static boolean isDatatypesRegistered = false
Constructor & Destructor Documentation
WKBRastDatatype()
WKBRastDatatype ()
{
                 super(URI);
         }
References WKBRastDatatype.URI.
Member Function Documentation
check()
static final boolean check (RDFDatatype rdfDatatype) static inherited
{
         //Ensure that the registered datatypes from the type mapper are used.
         return checkURI(rdfDatatype.getURI());
     }
References RasterDataType.checkURI().
checkURI()
static final boolean checkURI (String datatypeURI) static inherited
{
         registerDatatypes();
         RDFDatatype rdfDatatype = TYPE_MAPPER.getTypeByName(datatypeURI);
         if (rdfDatatype != null) {
             return rdfDatatype instanceof GeometryDatatype;
         } else {
             throw new DatatypeFormatException("Datatype not found: " + datatypeURI + " Ensure that GeoSPARQL is enabled and Datatype has been registered.");
         }
     }
References RasterDataType.registerDatatypes(), and RasterDataType.TYPE_MAPPER.
Referenced by RasterDataType.check(), and RasterDataType.get().
get() [1/2]
static final RasterDataType get (RDFDatatype rdfDatatype) static inherited
{
         if (rdfDatatype instanceof RasterDataType) {
             return (RasterDataType) rdfDatatype;
         } else {
             throw new DatatypeFormatException("Unrecognised Raster Datatype: " + rdfDatatype.getURI() + " Ensure that Datatype is extending GeometryDatatype.");
         }
     }
Referenced by CoverageWrapper.asLiteral(), CoverageWrapper.extract(), RasterDataType.get(), CoverageWrapper.getRasterDatatype(), and LiteralUtils.rasterOrVector().
get() [2/2]
static final RasterDataType get (String datatypeURI) static inherited
{
         checkURI(datatypeURI);
         RDFDatatype rdfDatatype = TYPE_MAPPER.getTypeByName(datatypeURI);
         return RasterDataType.get(rdfDatatype);
     }
References RasterDataType.checkURI(), RasterDataType.get(), and RasterDataType.TYPE_MAPPER.
parse() [1/2]
final CoverageWrapper parse (String lexicalForm) throws DatatypeFormatException inherited
This method Parses the Geometry Literal to the JTS Geometry.
Parameters
lexicalForm - the Geometry Literal to be parsed
Returns
geometry - if the Geometry Literal is valid.
empty geometry - if the Geometry Literal is empty.
null - if the Geometry Literal is invalid.
{
         return parse(lexicalForm, GeometryIndex.PRIMARY);
     }
References GeometryLiteralIndex.GeometryIndex.PRIMARY.
Referenced by CoverageWrapper.extract().
parse() [2/2]
final CoverageWrapper parse (String lexicalForm, GeometryIndex targetIndex) throws DatatypeFormatException inherited
{
         //Check the Geometry Literal Index to see if been previously read and cached.
         //DatatypeReader interface used to instruct index on how to obtain the GeometryWrapper.
         try {
             return GeometryLiteralIndex.retrieve(lexicalForm, this, targetIndex);
         } catch (IllegalArgumentException ex) {
                 ex.printStackTrace();
             throw new DatatypeFormatException(ex.getMessage() + " - Illegal Geometry Literal: " + lexicalForm);
         }
     }
References GeometryLiteralIndex.retrieve().
read()
CoverageWrapper read (String geometryLiteral)
Reimplemented from RasterDataType.
{
                 WKBRasterReader reader2=new WKBRasterReader();
                 GridCoverage coverage;
                 try {
                         coverage = reader2.readCoverage(Base64.decode(geometryLiteral), null);
                         System.out.println(coverage);
                         return new CoverageWrapper(coverage, URI);
                 } catch (IOException | FactoryException e) {
                         e.printStackTrace();
                         throw new RuntimeException(e.getMessage());
                 }
         }
References WKBRasterReader.readCoverage(), and WKBRastDatatype.URI.
registerDatatypes()
static final void registerDatatypes () static inherited
{
         if (!isDatatypesRegistered) {
             //TYPE_MAPPER.registerDatatype(CovJSONDatatype.INSTANCE);
                 //TYPE_MAPPER.registerDatatype(GeoTIFFDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(GMLCOVDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(HexWKBRastDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(WKBRastDatatype.INSTANCE);
             isDatatypesRegistered = true;
         }
     }
References WKBRastDatatype.INSTANCE, RasterDataType.isDatatypesRegistered, and RasterDataType.TYPE_MAPPER.
Referenced by RasterDataType.checkURI().
toString()
String toString ()
{
         return "WKBRasterDatatype{" + URI + '}';
     }
References WKBRastDatatype.URI.
unparse()
String unparse (Object geometry)
{
                 if (geometry instanceof CoverageWrapper) {
             CoverageWrapper geometryWrapper = (CoverageWrapper) geometry;
             WKBRasterWriter writer=new WKBRasterWriter();
                         String rasterWKB;
                         try {
                                 rasterWKB = writer.write(geometryWrapper.getGridGeometry()).toString();
                                 return rasterWKB.toString();
                         } catch (IOException | FactoryException e) {
                                 throw new AssertionError(e.getMessage());
                         }
         } else {
             throw new AssertionError("Object passed to WKBRastDatatype is not a CoverageWrapper: " + geometry);
         }
         }
References CoverageWrapper.getGridGeometry(), and WKBRasterWriter.write().
Member Data Documentation
INSTANCE
final WKBRastDatatype INSTANCE = new WKBRastDatatype() static
Referenced by RasterDataType.registerDatatypes().
isDatatypesRegistered
boolean isDatatypesRegistered = false static private inherited
Referenced by RasterDataType.registerDatatypes().
TYPE_MAPPER
final TypeMapper TYPE_MAPPER = TypeMapper.getInstance() static private inherited
Referenced by RasterDataType.checkURI(), RasterDataType.get(), and RasterDataType.registerDatatypes().
URI
final String URI = SRSGeo.WKBRaster static
Referenced by WKBRastDatatype.read(), WKBRastDatatype.toString(), and WKBRastDatatype.WKBRastDatatype().