GeoSPARQL SRS Extension: SRSRegistry Class Reference
SRSRegistry Class Reference
Static Public Member Functions
static final UnitsOfMeasure getUnitsOfMeasure (String srsURI)
static final Boolean getAxisXY (String srsURI)
static final CoordinateReferenceSystem getCRS (String srsURI)
static final SRSInfo getSRSInfo (String srsURI)
static final void setupDefaultSRS ()
static void exploreGraphForSRSDefinitions (OntModel model)
static void exploreGraphForSRSDefinitions (String endpoint)
static final void reset ()
static final String findUTMZoneURIFromWGS84 (double latitude, double longitude)
Find UTM CRS/SRS from WGS84 coordinates.
Static Private Member Functions
static SRSInfo storeSRS (String srsURI)
Static Private Attributes
static final Logger LOGGER = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass())
static final Map< String, SRSInfo > SRS_REGISTRY = Collections.synchronizedMap(new HashMap<>())
static final String NORTH_UTM_EPSG = EPSG_BASE_SRS_URI + "326"
static final String SOUTH_UTM_EPSG = EPSG_BASE_SRS_URI + "327"
static final DecimalFormat ZONE_FORMATTER = new DecimalFormat("##")
Member Function Documentation
exploreGraphForSRSDefinitions() [1/2]
static void exploreGraphForSRSDefinitions (OntModel model) static
{
         List<String> srsToParse=RDFCRSToWKT.getCRSListFromModel(model);
         for(String srsuri:srsToParse) {
                 SRS_REGISTRY.put(srsuri,SRSInfo.resolveSRS(srsuri, model));
         }
     }
References RDFCRSToWKT.getCRSListFromModel(), SRSInfo.resolveSRS(), and SRSRegistry.SRS_REGISTRY.
Referenced by TripleStoreConnection.TripleStoreConnection().
exploreGraphForSRSDefinitions() [2/2]
static void exploreGraphForSRSDefinitions (String endpoint) static
{
         List<String> srsToParse=RDFCRSToWKT.getCRSListFromTripleStore(endpoint);
         for(String srsuri:srsToParse) {
                 SRS_REGISTRY.put(srsuri,SRSInfo.resolveSRS(srsuri, endpoint));
         }
     }
References RDFCRSToWKT.getCRSListFromTripleStore(), SRSInfo.resolveSRS(), and SRSRegistry.SRS_REGISTRY.
findUTMZoneURIFromWGS84()
static final String findUTMZoneURIFromWGS84 (double latitude, double longitude) static
Find UTM CRS/SRS from WGS84 coordinates.
Based on calculation from Stack Overflow.
Parameters
latitude
longitude
Returns
URI of UTM zone CRS/SRS.
See also
Stack Overflow question relating to WGS84 to UTM conversion.
Wikipedia article on UTM.
EPSG for UTM
{
         int zone = (int) Math.floor(longitude / 6 + 31);
         String zoneString = ZONE_FORMATTER.format(zone);
         boolean isNorth = latitude >= 0;
         String epsgURI;
         if (isNorth) {
             epsgURI = NORTH_UTM_EPSG + zoneString;
         } else {
             epsgURI = SOUTH_UTM_EPSG + zoneString;
         }
         return epsgURI;
     }
References SRSRegistry.NORTH_UTM_EPSG, SRSRegistry.SOUTH_UTM_EPSG, and SRSRegistry.ZONE_FORMATTER.
Referenced by GeometryWrapper.getUTMZoneURI().
getAxisXY()
static final Boolean getAxisXY (String srsURI) static
{
         SRSInfo srsInfo = storeSRS(srsURI);
         return srsInfo.isAxisXY();
     }
References SRSInfo.isAxisXY, and SRSRegistry.storeSRS().
getCRS()
static final CoordinateReferenceSystem getCRS (String srsURI) static
{
         SRSInfo srsInfo = storeSRS(srsURI);
         return srsInfo.getCrs();
     }
References SRSInfo.getCrs(), and SRSRegistry.storeSRS().
Referenced by GeometryWrapper.getUTMZoneURI().
getSRSInfo()
static final SRSInfo getSRSInfo (String srsURI) static
{
         return storeSRS(srsURI);
     }
References SRSRegistry.storeSRS().
Referenced by CoverageWrapper.CoverageWrapper(), and GeometryWrapper.GeometryWrapper().
getUnitsOfMeasure()
static final UnitsOfMeasure getUnitsOfMeasure (String srsURI) static
{
         SRSInfo srsInfo = storeSRS(srsURI);
         return srsInfo.getUnitsOfMeasure();
     }
References SRSInfo.getUnitsOfMeasure(), and SRSRegistry.storeSRS().
reset()
static final void reset () static
{
         SRS_REGISTRY.clear();
         setupDefaultSRS();
     }
References SRSRegistry.setupDefaultSRS(), and SRSRegistry.SRS_REGISTRY.
setupDefaultSRS()
static final void setupDefaultSRS () static
{
         //CRS_84
         SRSInfo srsInfo = SRSInfo.getDefaultWktCRS84(SRS_URI.DEFAULT_WKT_CRS84);
         SRS_REGISTRY.put(SRS_URI.DEFAULT_WKT_CRS84, srsInfo);
         //WGS_84 Legacy for CRS_84
         SRS_REGISTRY.put(SRS_URI.WGS84_CRS_GEOSPARQL_LEGACY, SRSInfo.getDefaultWktCRS84(SRS_URI.WGS84_CRS_GEOSPARQL_LEGACY));
         //Add the Units of Measure
         UnitsRegistry.addUnit(srsInfo.getUnitsOfMeasure());
     }
References SRSInfo.getDefaultWktCRS84(), SRSInfo.getUnitsOfMeasure(), and SRSRegistry.SRS_REGISTRY.
Referenced by SRSRegistry.reset().
storeSRS()
static SRSInfo storeSRS (String srsURI) static private
{
         SRSInfo srsInfo;
         if (SRS_REGISTRY.containsKey(srsURI)) {
             srsInfo = SRS_REGISTRY.get(srsURI);
         } else {
             //Find the SRS based on the SRS URI.
             try {
                 srsInfo = new SRSInfo(srsURI);
             } catch (SRSInfoException ex) {
                 LOGGER.warn("SRS URI not recognised so operation results may not be correct or accurate: {} - {}", srsURI, ex.getMessage());
                 srsInfo = SRSInfo.getUnrecognised(srsURI);
             }
             SRS_REGISTRY.put(srsURI, srsInfo);
         }
         return srsInfo;
     }
References SRSInfo.getUnrecognised(), SRSRegistry.LOGGER, and SRSRegistry.SRS_REGISTRY.
Referenced by SRSRegistry.getAxisXY(), SRSRegistry.getCRS(), SRSRegistry.getSRSInfo(), and SRSRegistry.getUnitsOfMeasure().
Member Data Documentation
LOGGER
final Logger LOGGER = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass()) static private
Referenced by SRSRegistry.storeSRS().
NORTH_UTM_EPSG
final String NORTH_UTM_EPSG = EPSG_BASE_SRS_URI + "326" static private
Referenced by SRSRegistry.findUTMZoneURIFromWGS84().
SOUTH_UTM_EPSG
final String SOUTH_UTM_EPSG = EPSG_BASE_SRS_URI + "327" static private
Referenced by SRSRegistry.findUTMZoneURIFromWGS84().
SRS_REGISTRY
final Map<String, SRSInfo> SRS_REGISTRY = Collections.synchronizedMap(new HashMap<>()) static private
Referenced by SRSRegistry.exploreGraphForSRSDefinitions(), SRSRegistry.reset(), SRSRegistry.setupDefaultSRS(), and SRSRegistry.storeSRS().
ZONE_FORMATTER
final DecimalFormat ZONE_FORMATTER = new DecimalFormat("##") static private
Referenced by SRSRegistry.findUTMZoneURIFromWGS84().