GeoSPARQL SRS Extension: CoverageWrapper Class Reference
CoverageWrapper Class Reference
Public Member Functions
CoverageWrapper (GridCoverage geometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo)
CoverageWrapper (GridCoverage geometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo, String geometryLiteral)
CoverageWrapper (GridCoverage geometry, String geometryDatatypeURI)
Default to WGS84 geometry and XY coordinate dimensions.
CoverageWrapper (GridCoverage geometry, String srsURI, String geometryDatatypeURI)
Default to XY coordinate dimensions.
CoverageWrapper (CoverageWrapper geometryWrapper)
Copy GeometryWrapper.
CoordinateReferenceSystem getCRS ()
Transforms, if necessary, the provided target GeometryWrapper according to this GeometryWrapper SRS_URI.
GridCoverage getParsingGeometry ()
GridCoverage getGridGeometry ()
GridCoverage getXYGeometry ()
String getSrsURI ()
String getSRID ()
SRSInfo getSrsInfo ()
Boolean isSRSRecognised ()
String getRasterDatatypeURI ()
RasterDataType getRasterDatatype ()
NodeValue asNodeValue () throws DatatypeFormatException
Node asNode () throws DatatypeFormatException
Literal asLiteral () throws DatatypeFormatException
Literal asLiteral (String outputGeometryDatatypeURI) throws DatatypeFormatException
Literal asLiteral (RasterDataType datatype)
int getCoordinateDimension ()
int getSpatialDimension ()
int getTopologicalDimension ()
CoordinateSequenceDimensions getCoordinateSequenceDimensions ()
UnitsOfMeasure getUnitsOfMeasure ()
DimensionInfo getDimensionInfo ()
String getLexicalForm ()
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static final CoverageWrapper extract (NodeValue geometryLiteral, GeometryIndex targetIndex)
Extract Geometry Wrapper from Geometry Literal.
static final CoverageWrapper extract (Node geometryLiteral, GeometryIndex targetIndex)
Extract Geometry Wrapper from Geometry Literal.
static final CoverageWrapper extract (NodeValue geometryLiteral)
Extract Geometry Wrapper from Geometry Literal.
static final CoverageWrapper extract (Node geometryLiteral)
Extract Geometry Wrapper from Geometry Literal.
static final CoverageWrapper extract (Literal geometryLiteral, GeometryIndex targetIndex)
Extract Geometry Wrapper from Geometry Literal.
static final CoverageWrapper extract (Literal geometryLiteral)
Extract Geometry Wrapper from Geometry Literal.
static CoverageWrapper extract (String lexicalForm, String datatypeURI)
Extract Geometry Wrapper from Geometry Literal.
static CoverageWrapper extract (String lexicalForm, String datatypeURI, GeometryIndex targetIndex)
Extract Geometry Wrapper from Geometry Literal.
static final GeometryWrapper getEmptyWKT ()
static final CoverageWrapper createCoverage (GridCoverage geometry, String srsURI, String geometryDatatypeURI)
Create Geometry GeometryWrapper.
Private Member Functions
CoverageWrapper (GridCoverage parsingGeometry, GridCoverage xyGeometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo)
CoverageWrapper (GridCoverage parsingGeometry, GridCoverage xyGeometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo, String lexicalForm)
Private Attributes
final DimensionInfo dimensionInfo
final SRSInfo srsInfo
final GridCoverage xyGeometry
final GridCoverage parsingGeometry
PreparedGeometry preparedGeometry
Envelope envelope
GridCoverage translateXYGeometry
final String geometryDatatypeURI
RasterDataType geometryDatatype
String lexicalForm
String utmURI = null
Double latitude = null
Static Private Attributes
transient static final GeometryFactory GEOMETRY_FACTORY = CustomGeometryFactory.theInstance()
Constructor & Destructor Documentation
CoverageWrapper() [1/7]
CoverageWrapper (GridCoverage geometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo)
Parameters
coverage In X/Y or Y/X coordinate order of the SRS URI.
srsURI
geometryDatatypeURI
dimensionInfo
{
         this(geometry, srsURI, geometryDatatypeURI, dimensionInfo, null);
     }
References CoverageWrapper.dimensionInfo, and CoverageWrapper.geometryDatatypeURI.
Referenced by CoverageWrapper.createCoverage(), and CoverageWrapper.equals().
CoverageWrapper() [2/7]
CoverageWrapper (GridCoverage geometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo, String geometryLiteral)
Parameters
geometry In X/Y or Y/X coordinate order of the SRS URI.
srsURI
geometryDatatypeURI
dimensionInfo
geometryLiteral
{
         this(geometry, geometry, srsURI.isEmpty() ? SRS_URI.DEFAULT_WKT_CRS84 : srsURI, geometryDatatypeURI, dimensionInfo, geometryLiteral);
     }
References CoverageWrapper.dimensionInfo, and CoverageWrapper.geometryDatatypeURI.
CoverageWrapper() [3/7]
CoverageWrapper (GridCoverage parsingGeometry, GridCoverage xyGeometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo) private
{
         this(parsingGeometry, xyGeometry, srsURI, geometryDatatypeURI, dimensionInfo, null);
     }
References CoverageWrapper.dimensionInfo, CoverageWrapper.geometryDatatypeURI, CoverageWrapper.parsingGeometry, and CoverageWrapper.xyGeometry.
CoverageWrapper() [4/7]
CoverageWrapper (GridCoverage parsingGeometry, GridCoverage xyGeometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo, String lexicalForm) private
{
         this.parsingGeometry = parsingGeometry;
         this.xyGeometry = xyGeometry;
         this.preparedGeometry = null; //Initialised when required by spatial relations checkPreparedGeometry.
         this.envelope = null; //Initialised when required by getEnvelope().
         this.translateXYGeometry = null; //Initialised when required by translateGeometry().
         this.geometryDatatypeURI = geometryDatatypeURI;
         this.geometryDatatype = null; //Inilialised when required by getGeometryDatatype().
         if (srsURI.isEmpty()) {
             srsURI = SRS_URI.DEFAULT_WKT_CRS84;
         }
         this.srsInfo = SRSRegistry.getSRSInfo(srsURI);
         this.dimensionInfo = dimensionInfo;
         this.lexicalForm = lexicalForm; //If not Initialised then required by asLiteral() etc.
     }
References CoverageWrapper.dimensionInfo, CoverageWrapper.geometryDatatypeURI, SRSRegistry.getSRSInfo(), CoverageWrapper.lexicalForm, CoverageWrapper.parsingGeometry, and CoverageWrapper.xyGeometry.
CoverageWrapper() [5/7]
CoverageWrapper (GridCoverage geometry, String geometryDatatypeURI)
Default to WGS84 geometry and XY coordinate dimensions.
Parameters
coverage In X/Y or Y/X coordinate order of WGS84.
geometryDatatypeURI
{
         this(geometry, "", geometryDatatypeURI, DimensionInfo.XY_POINT);
     }
References CoverageWrapper.geometryDatatypeURI.
CoverageWrapper() [6/7]
CoverageWrapper (GridCoverage geometry, String srsURI, String geometryDatatypeURI)
Default to XY coordinate dimensions.
Parameters
geometry In X/Y or Y/X coordinate order of the SRS URI.
srsURI
geometryDatatypeURI
{
         this(geometry, srsURI, geometryDatatypeURI, DimensionInfo.XY_POINT);
     }
References CoverageWrapper.geometryDatatypeURI.
CoverageWrapper() [7/7]
CoverageWrapper (CoverageWrapper geometryWrapper)
Copy GeometryWrapper.
Parameters
geometryWrapper
{
         this.xyGeometry = geometryWrapper.xyGeometry;
         this.parsingGeometry = geometryWrapper.parsingGeometry;
         this.preparedGeometry = geometryWrapper.preparedGeometry;
         this.envelope = geometryWrapper.envelope;
         this.translateXYGeometry = geometryWrapper.translateXYGeometry;
         this.utmURI = geometryWrapper.utmURI;
         this.latitude = geometryWrapper.latitude;
         this.geometryDatatypeURI = geometryWrapper.geometryDatatypeURI;
         this.geometryDatatype = geometryWrapper.geometryDatatype;
         this.srsInfo = geometryWrapper.srsInfo;
         this.dimensionInfo = geometryWrapper.dimensionInfo;
         this.lexicalForm = geometryWrapper.lexicalForm;
     }
References CoverageWrapper.dimensionInfo, CoverageWrapper.envelope, CoverageWrapper.geometryDatatype, CoverageWrapper.geometryDatatypeURI, CoverageWrapper.latitude, CoverageWrapper.lexicalForm, CoverageWrapper.parsingGeometry, CoverageWrapper.preparedGeometry, CoverageWrapper.srsInfo, CoverageWrapper.translateXYGeometry, CoverageWrapper.utmURI, and CoverageWrapper.xyGeometry.
Member Function Documentation
asLiteral() [1/3]
Literal asLiteral () throws DatatypeFormatException
Returns
GeometryWrapper as Literal
{
         RasterDataType datatype = getRasterDatatype(); //Datatype is only retrieved when required.
         if (lexicalForm != null) {
             return ResourceFactory.createTypedLiteral(lexicalForm, datatype);
         }
         Literal literal = asLiteral(datatype);
         lexicalForm = literal.getLexicalForm();
         return literal;
     }
References CoverageWrapper.getRasterDatatype(), and CoverageWrapper.lexicalForm.
Referenced by CoverageWrapper.asLiteral(), CoverageWrapper.asNodeValue(), and CoverageWrapper.getLexicalForm().
asLiteral() [2/3]
Literal asLiteral (RasterDataType datatype)
Parameters
datatype
Returns
GeometryWrapper as Literal
{
         String tempLexicalForm = datatype.unparse(this);
         return ResourceFactory.createTypedLiteral(tempLexicalForm, datatype);
     }
asLiteral() [3/3]
Literal asLiteral (String outputGeometryDatatypeURI) throws DatatypeFormatException
Parameters
outputGeometryDatatypeURI
Returns
GeometryWrapper as Literal in datatype form.
{
         RasterDataType datatype = RasterDataType.get(outputGeometryDatatypeURI);
         return asLiteral(datatype);
     }
References CoverageWrapper.asLiteral(), and RasterDataType.get().
asNode()
Node asNode () throws DatatypeFormatException
Returns
GeometryWrapper as Node
{
         return asNodeValue().asNode();
     }
References CoverageWrapper.asNodeValue().
Referenced by CoverageWrapper.extract().
asNodeValue()
NodeValue asNodeValue () throws DatatypeFormatException
Returns
GeometryWrapper as NodeValue
{
         Literal literal = asLiteral();
         return NodeValue.makeNode(literal.getLexicalForm(), literal.getDatatype());
     }
References CoverageWrapper.asLiteral().
Referenced by CoverageWrapper.asNode(), LiteralUtils.createEmptyRaster(), and LiteralUtils.cropRaster().
createCoverage()
static final CoverageWrapper createCoverage (GridCoverage geometry, String srsURI, String geometryDatatypeURI) static
Create Geometry GeometryWrapper.
Parameters
coverage In X/Y order.
srsURI
geometryDatatypeURI
Returns
GeometryWrapper with SRS URI and GeometryDatatype URI.
{
         GridCoverage xyGeometry = geometry;
         //GridCoverage parsingGeometry = GeometryReverse.check(xyGeometry, srsURI);
         DimensionInfo dimsInfo = DimensionInfo.XY_POINT;
         return new CoverageWrapper(xyGeometry, xyGeometry, srsURI, geometryDatatypeURI, dimsInfo);
     }
References CoverageWrapper.CoverageWrapper(), CoverageWrapper.geometryDatatypeURI, and CoverageWrapper.xyGeometry.
Referenced by LiteralUtils.createEmptyRaster(), and LiteralUtils.cropRaster().
equals()
boolean equals (Object obj)
{
         if (this == obj) {
             return true;
         }
         if (obj == null) {
             return false;
         }
         if (getClass() != obj.getClass()) {
             return false;
         }
         final CoverageWrapper other = (CoverageWrapper) obj;
         if (!Objects.equals(this.geometryDatatypeURI, other.geometryDatatypeURI)) {
             return false;
         }
         if (!Objects.equals(this.dimensionInfo, other.dimensionInfo)) {
             return false;
         }
         if (!Objects.equals(this.srsInfo, other.srsInfo)) {
             return false;
         }
         return Objects.equals(this.xyGeometry, other.xyGeometry);
     }
References CoverageWrapper.CoverageWrapper(), CoverageWrapper.dimensionInfo, CoverageWrapper.equals(), CoverageWrapper.geometryDatatypeURI, CoverageWrapper.srsInfo, and CoverageWrapper.xyGeometry.
Referenced by CoverageWrapper.equals().
extract() [1/8]
static final CoverageWrapper extract (Literal geometryLiteral) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
geometryLiteral
Returns
Geometry Wrapper of the Geometry Literal.
{
         return extract(geometryLiteral, GeometryIndex.PRIMARY);
     }
References CoverageWrapper.extract(), and GeometryLiteralIndex.GeometryIndex.PRIMARY.
extract() [2/8]
static final CoverageWrapper extract (Literal geometryLiteral, GeometryIndex targetIndex) static
Extract Geometry Wrapper from Geometry Literal.
Returns null if invalid literal provided.
Parameters
geometryLiteral
targetIndex
Returns
Geometry Wrapper of the Geometry Literal.
{
         return extract(geometryLiteral.getLexicalForm(), geometryLiteral.getDatatypeURI(), targetIndex);
     }
References CoverageWrapper.extract().
extract() [3/8]
static final CoverageWrapper extract (Node geometryLiteral) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
geometryLiteral
Returns
Geometry Wrapper of the Geometry Literal.
{
         return extract(geometryLiteral, GeometryIndex.PRIMARY);
     }
References CoverageWrapper.extract(), and GeometryLiteralIndex.GeometryIndex.PRIMARY.
extract() [4/8]
static final CoverageWrapper extract (Node geometryLiteral, GeometryIndex targetIndex) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
geometryLiteral
targetIndex
Returns
Geometry Wrapper of the Geometry Literal.
{
         if (!geometryLiteral.isLiteral()) {
             throw new DatatypeFormatException("Not a Literal: " + geometryLiteral);
         }
         String datatypeURI = geometryLiteral.getLiteralDatatypeURI();
         String lexicalForm = geometryLiteral.getLiteralLexicalForm();
         return extract(lexicalForm, datatypeURI, targetIndex);
     }
References CoverageWrapper.extract(), and CoverageWrapper.lexicalForm.
extract() [5/8]
static final CoverageWrapper extract (NodeValue geometryLiteral) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
geometryLiteral
Returns
Geometry Wrapper of the Geometry Literal.
{
         return extract(geometryLiteral, GeometryIndex.PRIMARY);
     }
References CoverageWrapper.extract(), and GeometryLiteralIndex.GeometryIndex.PRIMARY.
extract() [6/8]
static final CoverageWrapper extract (NodeValue geometryLiteral, GeometryIndex targetIndex) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
geometryLiteral
targetIndex
Returns
Geometry Wrapper of the Geometry Literal.
{
         Node node = geometryLiteral.asNode();
         return extract(node, targetIndex);
     }
References CoverageWrapper.asNode().
Referenced by CoverageWrapper.extract(), and LiteralUtils.rasterOrVector().
extract() [7/8]
static CoverageWrapper extract (String lexicalForm, String datatypeURI) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
lexicalForm
datatypeURI
Returns
Geometry Wrapper of the Geometry Literal.
{
         return extract(lexicalForm, datatypeURI, GeometryIndex.PRIMARY);
     }
References CoverageWrapper.extract(), CoverageWrapper.lexicalForm, and GeometryLiteralIndex.GeometryIndex.PRIMARY.
extract() [8/8]
static CoverageWrapper extract (String lexicalForm, String datatypeURI, GeometryIndex targetIndex) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
lexicalForm
datatypeURI
targetIndex
Returns
Geometry Wrapper of the Geometry Literal.
{
         if (lexicalForm == null || datatypeURI == null) {
             throw new DatatypeFormatException("GeometryWrapper extraction: arguments cannot be null - " + lexicalForm + ", " + datatypeURI);
         }
         RasterDataType datatype = RasterDataType.get(datatypeURI);
         CoverageWrapper geometry = datatype.parse(lexicalForm, targetIndex);
         return geometry;
     }
References RasterDataType.get(), CoverageWrapper.lexicalForm, and RasterDataType.parse().
getCoordinateDimension()
int getCoordinateDimension ()
Returns
Coordinate dimension, i.e. 2 (x,y), 3 (x,y,z or x,y,m) or 4 (x,y,z,m)
{
         return dimensionInfo.getCoordinate();
     }
References CoverageWrapper.dimensionInfo.
getCoordinateSequenceDimensions()
CoordinateSequenceDimensions getCoordinateSequenceDimensions ()
Returns
Enum of coordinate dimensions.
{
         return dimensionInfo.getDimensions();
     }
References CoverageWrapper.dimensionInfo.
getCRS()
CoordinateReferenceSystem getCRS ()
Transforms, if necessary, the provided target GeometryWrapper according to this GeometryWrapper SRS_URI.
Parameters
targetGeometryWrapper
Returns
GeometryWrapper after transformation.
Exceptions
FactoryException
MismatchedDimensionException
TransformException Transform the GeometryWrapper into another spatial reference system.
Parameters
srsURI
Returns
New GeometryWrapper after transformation, or this GeometryWrapper if no transformation.
Exceptions
MismatchedDimensionException
TransformException
FactoryException Transform the GeometryWrapper into another spatial reference system.
Parameters
srsInfo
Returns
New GeometryWrapper after transformation, or this GeometryWrapper if no transformation.
Exceptions
MismatchedDimensionException
TransformException
FactoryException Returns this geometry wrapper converted to the SRS_URI URI.
Parameters
srsURI
Returns
GeometryWrapper after conversion.
Exceptions
FactoryException
MismatchedDimensionException
TransformException
Returns
Coordinate/Spatial reference system of the GeometryWrapper.
{
         return srsInfo.getCrs();
     }
References SRSInfo.getCrs(), and CoverageWrapper.srsInfo.
getDimensionInfo()
DimensionInfo getDimensionInfo ()
Returns
GeometryWrapper's coordinate, spatial and topological dimensions.
{
         return dimensionInfo;
     }
References CoverageWrapper.dimensionInfo.
getEmptyWKT()
static final GeometryWrapper getEmptyWKT () static
Returns
Empty GeometryWrapper in WKT datatype.
{
         return WKTDatatype.INSTANCE.read("");
     }
getGridGeometry()
GridCoverage getGridGeometry ()
Returns
Geometry with coordinates as originally provided.
{
        return parsingGeometry;
    }
References CoverageWrapper.parsingGeometry.
Referenced by WKBRastDatatype.unparse().
getLexicalForm()
String getLexicalForm ()
Returns
String literal of Geometry Wrapper.
{
         if (lexicalForm != null) {
             return lexicalForm;
         } else {
             Literal literal = asLiteral();
             return literal.getLexicalForm();
         }
     }
References CoverageWrapper.asLiteral(), and CoverageWrapper.lexicalForm.
getParsingGeometry()
GridCoverage getParsingGeometry ()
Returns
Geometry with coordinates as originally provided.
{
         return parsingGeometry;
     }
References CoverageWrapper.parsingGeometry.
getRasterDatatype()
RasterDataType getRasterDatatype ()
Returns
GeometryDatatype of the literal.
{
         if (geometryDatatype == null) {
             geometryDatatype = RasterDataType.get(geometryDatatypeURI);
         }
         return geometryDatatype;
     }
References CoverageWrapper.geometryDatatype, CoverageWrapper.geometryDatatypeURI, and RasterDataType.get().
Referenced by CoverageWrapper.asLiteral().
getRasterDatatypeURI()
String getRasterDatatypeURI ()
Returns
Datatype URI of the literal.
{
         return geometryDatatypeURI;
     }
References CoverageWrapper.geometryDatatypeURI.
getSpatialDimension()
int getSpatialDimension ()
Returns
Spatial dimension, i.e. 2 or 3
{
         return dimensionInfo.getSpatial();
     }
References CoverageWrapper.dimensionInfo.
getSRID()
String getSRID ()
Returns
getSRID used in GeoSPARQL Standard page 22 to refer to srsURI. i.e. getSrsURI and getSRID are the same.
{
         return srsInfo.getSrsURI();
     }
References SRSInfo.getSrsURI(), and CoverageWrapper.srsInfo.
getSrsInfo()
SRSInfo getSrsInfo ()
Returns
SRS information that the Geometry Wrapper is using.
{
         return srsInfo;
     }
References CoverageWrapper.srsInfo.
getSrsURI()
String getSrsURI ()
Returns
Coordinate/Spatial reference system URI.
{
         return srsInfo.getSrsURI();
     }
References SRSInfo.getSrsURI(), and CoverageWrapper.srsInfo.
getTopologicalDimension()
int getTopologicalDimension ()
Returns
Topological dimension, i.e. 0, 1 or 2
{
         return dimensionInfo.getTopological();
     }
References CoverageWrapper.dimensionInfo.
getUnitsOfMeasure()
UnitsOfMeasure getUnitsOfMeasure ()
Returns
Units of Measure for the GeometryWrapper SRS.
{
         return srsInfo.getUnitsOfMeasure();
     }
References SRSInfo.getUnitsOfMeasure(), and CoverageWrapper.srsInfo.
getXYGeometry()
GridCoverage getXYGeometry ()
Returns
Geometry with coordinates as originally provided.
{
       return parsingGeometry;
   }
References CoverageWrapper.parsingGeometry.
hashCode()
int hashCode ()
{
         int hash = 3;
         hash = 23 * hash + Objects.hashCode(this.dimensionInfo);
         hash = 23 * hash + Objects.hashCode(this.srsInfo);
         hash = 23 * hash + Objects.hashCode(this.xyGeometry);
         hash = 23 * hash + Objects.hashCode(this.geometryDatatypeURI);
         return hash;
     }
isSRSRecognised()
Boolean isSRSRecognised ()
Returns
Whether the SRS URI has been recognised. Operations may fail or not perform correctly when false.
{
         return srsInfo.isSRSRecognised();
     }
References SRSInfo.isSRSRecognised, and CoverageWrapper.srsInfo.
toString()
String toString ()
{
         return "GeometryWrapper{" + "dimensionInfo=" + dimensionInfo + ", geometryDatatypeURI=" + geometryDatatypeURI + ", lexicalForm=" + lexicalForm + ", utmURI=" + utmURI + ", latitude=" + latitude + ", xyGeometry=" + xyGeometry + ", parsingGeometry=" + parsingGeometry + ", preparedGeometry=" + preparedGeometry + ", srsInfo=" + srsInfo + '}';
     }
References CoverageWrapper.dimensionInfo, CoverageWrapper.geometryDatatypeURI, CoverageWrapper.latitude, CoverageWrapper.lexicalForm, CoverageWrapper.parsingGeometry, CoverageWrapper.preparedGeometry, CoverageWrapper.srsInfo, CoverageWrapper.utmURI, and CoverageWrapper.xyGeometry.
Member Data Documentation
dimensionInfo
final DimensionInfo dimensionInfo private
Referenced by CoverageWrapper.CoverageWrapper(), CoverageWrapper.equals(), CoverageWrapper.getCoordinateDimension(), CoverageWrapper.getCoordinateSequenceDimensions(), CoverageWrapper.getDimensionInfo(), CoverageWrapper.getSpatialDimension(), CoverageWrapper.getTopologicalDimension(), and CoverageWrapper.toString().
envelope
Envelope envelope private
Referenced by CoverageWrapper.CoverageWrapper().
GEOMETRY_FACTORY
transient static final GeometryFactory GEOMETRY_FACTORY = CustomGeometryFactory.theInstance() static private
geometryDatatype
RasterDataType geometryDatatype private
Referenced by CoverageWrapper.CoverageWrapper(), and CoverageWrapper.getRasterDatatype().
geometryDatatypeURI
final String geometryDatatypeURI private
Referenced by CoverageWrapper.CoverageWrapper(), CoverageWrapper.createCoverage(), CoverageWrapper.equals(), CoverageWrapper.getRasterDatatype(), CoverageWrapper.getRasterDatatypeURI(), and CoverageWrapper.toString().
latitude
Double latitude = null private
Referenced by CoverageWrapper.CoverageWrapper(), and CoverageWrapper.toString().
lexicalForm
String lexicalForm private
Referenced by CoverageWrapper.asLiteral(), CoverageWrapper.CoverageWrapper(), CoverageWrapper.extract(), CoverageWrapper.getLexicalForm(), and CoverageWrapper.toString().
parsingGeometry
final GridCoverage parsingGeometry private
Referenced by CoverageWrapper.CoverageWrapper(), CoverageWrapper.getGridGeometry(), CoverageWrapper.getParsingGeometry(), CoverageWrapper.getXYGeometry(), and CoverageWrapper.toString().
preparedGeometry
PreparedGeometry preparedGeometry private
Referenced by CoverageWrapper.CoverageWrapper(), and CoverageWrapper.toString().
srsInfo
final SRSInfo srsInfo private
Referenced by CoverageWrapper.CoverageWrapper(), CoverageWrapper.equals(), CoverageWrapper.getCRS(), CoverageWrapper.getSRID(), CoverageWrapper.getSrsInfo(), CoverageWrapper.getSrsURI(), CoverageWrapper.getUnitsOfMeasure(), CoverageWrapper.isSRSRecognised(), and CoverageWrapper.toString().
translateXYGeometry
GridCoverage translateXYGeometry private
Referenced by CoverageWrapper.CoverageWrapper().
utmURI
String utmURI = null private
Referenced by CoverageWrapper.CoverageWrapper(), and CoverageWrapper.toString().
xyGeometry
final GridCoverage xyGeometry private
Referenced by CoverageWrapper.CoverageWrapper(), CoverageWrapper.createCoverage(), CoverageWrapper.equals(), and CoverageWrapper.toString().