GeoSPARQL SRS Extension: LEDataInputStream Class Reference
LEDataInputStream Class Reference
Little endian Data input stream.
Public Member Functions
LEDataInputStream (final InputStream in)
long getPosition ()
Get current stream position from the first written byte.
int available () throws IOException
final short readShort () throws IOException
short[] readShorts (int nbValues) throws IOException
Read multiple values in one call.
final int readUnsignedShort () throws IOException
int[] readUnsignedShorts (int nbValues) throws IOException
Read multiple values in one call.
final char readChar () throws IOException
final int readInt () throws IOException
int[] readInts (int nbValues) throws IOException
Read multiple values in one call.
final long readLong () throws IOException
long[] readLongs (int nbValues) throws IOException
Read multiple values in one call.
final float readFloat () throws IOException
float[] readFloats (int nbValues) throws IOException
Read multiple values in one call.
final double readDouble () throws IOException
double[] readDoubles (int nbValues) throws IOException
Read multiple values in one call.
final int read (byte b[], int off, int len) throws IOException
final void readFully (byte b[]) throws IOException
final void readFully (byte b[], int off, int len) throws IOException
final int skipBytes (int n) throws IOException
final void skipFully (int n) throws IOException
final boolean readBoolean () throws IOException
final byte readByte () throws IOException
int read () throws IOException
final int readUnsignedByte () throws IOException
final String readLine () throws IOException
final String readUTF () throws IOException
int realign (int blockSize) throws IOException
Ralign stream position, skipping any remaining byte to match given block size.
final void close () throws IOException
Static Public Member Functions
static short readUnsignedByte (final byte[] buffer, final int offset)
static short readShort (final byte[] buffer, final int offset)
static int readUnsignedShort (final byte[] buffer, final int offset)
static char readChar (final byte[] buffer, final int offset)
static int readInt (final byte[] buffer, final int offset)
static long readUnsignedInt (final byte[] buffer, final int offset)
static long readLong (final byte[] buffer, final int offset)
static float readFloat (final byte[] buffer, final int offset)
static double readDouble (final byte[] buffer, final int offset)
Private Attributes
final DataInputStream ds
final InputStream in
final byte buffer [] = new byte[8]
long position = 0
Detailed Description
Little endian Data input stream.
Author
Johann Sorel (Geomatys)
Constructor & Destructor Documentation
LEDataInputStream()
LEDataInputStream (final InputStream in)
{
         this.in = in;
         this.ds = new DataInputStream(in);
     }
References LEDataInputStream.in.
Member Function Documentation
available()
int available () throws IOException
{
         return ds.available();
     }
References LEDataInputStream.ds.
close()
final void close () throws IOException
{
         ds.close();
     }
References LEDataInputStream.ds.
getPosition()
long getPosition ()
Get current stream position from the first written byte.
Returns
stream position
{
         return position;
     }
References LEDataInputStream.position.
Referenced by LEDataInputStream.realign().
read() [1/2]
int read () throws IOException
{
         position++;
         return in.read();
     }
References LEDataInputStream.in, and LEDataInputStream.position.
read() [2/2]
final int read (byte b[], int off, int len) throws IOException
{
         int nb = in.read(b, off, len);
         position+=nb;
         return nb;
     }
References LEDataInputStream.in, and LEDataInputStream.position.
readBoolean()
final boolean readBoolean () throws IOException
{
         position++;
         return ds.readBoolean();
     }
References LEDataInputStream.ds, and LEDataInputStream.position.
readByte()
final byte readByte () throws IOException
{
         position++;
         return ds.readByte();
     }
References LEDataInputStream.ds, and LEDataInputStream.position.
readChar() [1/2]
final char readChar () throws IOException
{
         position+=2;
         ds.readFully(buffer, 0, 2);
         return (char) ((buffer[1] & 0xff) << 8
                 | (buffer[0] & 0xff));
     }
References LEDataInputStream.buffer, LEDataInputStream.ds, and LEDataInputStream.position.
readChar() [2/2]
static char readChar (final byte[] buffer, final int offset) static
{
         return (char) ((buffer[offset+1] & 0xff) << 8
                 | (buffer[offset+0] & 0xff));
     }
References LEDataInputStream.buffer.
readDouble() [1/2]
final double readDouble () throws IOException
{
         return Double.longBitsToDouble(readLong());
     }
References LEDataInputStream.readLong().
Referenced by LEDataInputStream.readDoubles().
readDouble() [2/2]
static double readDouble (final byte[] buffer, final int offset) static
{
         return Double.longBitsToDouble(readLong(buffer,offset));
     }
References LEDataInputStream.buffer, and LEDataInputStream.readLong().
readDoubles()
double [] readDoubles (int nbValues) throws IOException
Read multiple values in one call.
Parameters
nbValues number of valeus to read
Returns
array of values
Exceptions
java.io.IOException
{
         final double[] array = new double[nbValues];
         for (int i=0; i<nbValues; i++) {
             array[i] = readDouble();
         }
         return array;
     }
References LEDataInputStream.readDouble().
readFloat() [1/2]
final float readFloat () throws IOException
{
         return Float.intBitsToFloat(readInt());
     }
References LEDataInputStream.readInt().
Referenced by LEDataInputStream.readFloats().
readFloat() [2/2]
static float readFloat (final byte[] buffer, final int offset) static
{
         return Float.intBitsToFloat(readInt(buffer,offset));
     }
References LEDataInputStream.buffer, and LEDataInputStream.readInt().
readFloats()
float [] readFloats (int nbValues) throws IOException
Read multiple values in one call.
Parameters
nbValues number of valeus to read
Returns
array of values
Exceptions
java.io.IOException
{
         final float[] array = new float[nbValues];
         for (int i=0; i<nbValues; i++) {
             array[i] = readFloat();
         }
         return array;
     }
References LEDataInputStream.readFloat().
readFully() [1/2]
final void readFully (byte b[]) throws IOException
{
         ds.readFully(b, 0, b.length);
         position+=b.length;
     }
References LEDataInputStream.ds, and LEDataInputStream.position.
readFully() [2/2]
final void readFully (byte b[], int off, int len) throws IOException
{
         ds.readFully(b, off, len);
         position+=len;
     }
References LEDataInputStream.ds, and LEDataInputStream.position.
readInt() [1/2]
final int readInt () throws IOException
{
         position+=4;
         ds.readFully(buffer, 0, 4);
         return (buffer[3]) << 24
                 | (buffer[2] & 0xff) << 16
                 | (buffer[1] & 0xff) << 8
                 | (buffer[0] & 0xff);
     }
References LEDataInputStream.buffer, LEDataInputStream.ds, and LEDataInputStream.position.
Referenced by LEDataInputStream.readFloat(), and LEDataInputStream.readInts().
readInt() [2/2]
static int readInt (final byte[] buffer, final int offset) static
{
         return    (buffer[offset+3]) << 24
                 | (buffer[offset+2] & 0xff) << 16
                 | (buffer[offset+1] & 0xff) << 8
                 | (buffer[offset+0] & 0xff);
     }
References LEDataInputStream.buffer.
readInts()
int [] readInts (int nbValues) throws IOException
Read multiple values in one call.
Parameters
nbValues number of valeus to read
Returns
array of values
Exceptions
java.io.IOException
{
         final int[] array = new int[nbValues];
         for (int i=0; i<nbValues; i++) {
             array[i] = readInt();
         }
         return array;
     }
References LEDataInputStream.readInt().
readLine()
final String readLine () throws IOException
{
         return ds.readLine();
     }
References LEDataInputStream.ds.
readLong() [1/2]
final long readLong () throws IOException
{
         position+=8;
         ds.readFully(buffer, 0, 8);
         return (long) (buffer[7]) << 56
                 | (long) (buffer[6] & 0xff) << 48
                 | (long) (buffer[5] & 0xff) << 40
                 | (long) (buffer[4] & 0xff) << 32
                 | (long) (buffer[3] & 0xff) << 24
                 | (long) (buffer[2] & 0xff) << 16
                 | (long) (buffer[1] & 0xff) << 8
                 | (long) (buffer[0] & 0xff);
     }
References LEDataInputStream.buffer, LEDataInputStream.ds, and LEDataInputStream.position.
Referenced by LEDataInputStream.readDouble(), and LEDataInputStream.readLongs().
readLong() [2/2]
static long readLong (final byte[] buffer, final int offset) static
{
         return    (long) (buffer[offset+7]) << 56
                 | (long) (buffer[offset+6] & 0xff) << 48
                 | (long) (buffer[offset+5] & 0xff) << 40
                 | (long) (buffer[offset+4] & 0xff) << 32
                 | (long) (buffer[offset+3] & 0xff) << 24
                 | (long) (buffer[offset+2] & 0xff) << 16
                 | (long) (buffer[offset+1] & 0xff) << 8
                 | (long) (buffer[offset+0] & 0xff);
     }
References LEDataInputStream.buffer.
readLongs()
long [] readLongs (int nbValues) throws IOException
Read multiple values in one call.
Parameters
nbValues number of valeus to read
Returns
array of values
Exceptions
java.io.IOException
{
         final long[] array = new long[nbValues];
         for (int i=0; i<nbValues; i++) {
             array[i] = readLong();
         }
         return array;
     }
References LEDataInputStream.readLong().
readShort() [1/2]
final short readShort () throws IOException
{
         position+=2;
         ds.readFully(buffer, 0, 2);
         return (short) ((buffer[1] & 0xff) << 8
                 | (buffer[0] & 0xff));
     }
References LEDataInputStream.buffer, LEDataInputStream.ds, and LEDataInputStream.position.
Referenced by LEDataInputStream.readShorts().
readShort() [2/2]
static short readShort (final byte[] buffer, final int offset) static
{
         return (short) ((buffer[offset+1] & 0xff) << 8
                 | (buffer[offset+0] & 0xff));
     }
References LEDataInputStream.buffer.
readShorts()
short [] readShorts (int nbValues) throws IOException
Read multiple values in one call.
Parameters
nbValues number of valeus to read
Returns
array of values
Exceptions
java.io.IOException
{
         final short[] array = new short[nbValues];
         for (int i=0; i<nbValues; i++) {
             array[i] = readShort();
         }
         return array;
     }
References LEDataInputStream.readShort().
readUnsignedByte() [1/2]
final int readUnsignedByte () throws IOException
{
         position++;
         return ds.readUnsignedByte();
     }
References LEDataInputStream.ds, and LEDataInputStream.position.
readUnsignedByte() [2/2]
static short readUnsignedByte (final byte[] buffer, final int offset) static
{
         return (short) (buffer[offset] & 0xff);
     }
References LEDataInputStream.buffer.
readUnsignedInt()
static long readUnsignedInt (final byte[] buffer, final int offset) static
{
         return    (long) (buffer[offset+3] & 0xff) << 24
                 | (long) (buffer[offset+2] & 0xff) << 16
                 | (long) (buffer[offset+1] & 0xff) << 8
                 | (long) (buffer[offset+0] & 0xff);
     }
References LEDataInputStream.buffer.
readUnsignedShort() [1/2]
final int readUnsignedShort () throws IOException
{
         position+=2;
         ds.readFully(buffer, 0, 2);
         return ((buffer[1] & 0xff) << 8 | (buffer[0] & 0xff));
     }
References LEDataInputStream.buffer, LEDataInputStream.ds, and LEDataInputStream.position.
Referenced by LEDataInputStream.readUnsignedShorts().
readUnsignedShort() [2/2]
static int readUnsignedShort (final byte[] buffer, final int offset) static
{
         return ((buffer[offset+1] & 0xff) << 8 | (buffer[offset+0] & 0xff));
     }
References LEDataInputStream.buffer.
readUnsignedShorts()
int [] readUnsignedShorts (int nbValues) throws IOException
Read multiple values in one call.
Parameters
nbValues number of valeus to read
Returns
array of values
Exceptions
java.io.IOException
{
         final int[] array = new int[nbValues];
         for (int i=0; i<nbValues; i++) {
             array[i] = readUnsignedShort();
         }
         return array;
     }
References LEDataInputStream.readUnsignedShort().
readUTF()
final String readUTF () throws IOException
{
         return ds.readUTF();
     }
References LEDataInputStream.ds.
realign()
int realign (int blockSize) throws IOException
Ralign stream position, skipping any remaining byte to match given block size.
Older formats or javascript buffer requiere to be aligned on 2, 4 or 8 bytes (short,int,float,double) to read datas.
Parameters
blockSize
Returns
number of bytes skipped
{
         final long position = getPosition();
         final long res = position % blockSize;
         if (res == 0) return 0;
         try {
             skipFully((int) (blockSize-res));
         } catch (EOFException ex) {
             return -1;
         }
         return (int) res;
     }
References LEDataInputStream.getPosition(), LEDataInputStream.position, and LEDataInputStream.skipFully().
skipBytes()
final int skipBytes (int n) throws IOException
{
         int nb = ds.skipBytes(n);
         position+=nb;
         return nb;
     }
References LEDataInputStream.ds, and LEDataInputStream.position.
Referenced by LEDataInputStream.skipFully().
skipFully()
final void skipFully (int n) throws IOException
{
         while (n > 0) {
             n -= skipBytes(n);
         }
     }
References LEDataInputStream.skipBytes().
Referenced by LEDataInputStream.realign().
Member Data Documentation
buffer
final byte buffer[] = new byte[8] private
Referenced by LEDataInputStream.readChar(), LEDataInputStream.readDouble(), LEDataInputStream.readFloat(), LEDataInputStream.readInt(), LEDataInputStream.readLong(), LEDataInputStream.readShort(), LEDataInputStream.readUnsignedByte(), LEDataInputStream.readUnsignedInt(), and LEDataInputStream.readUnsignedShort().
ds
final DataInputStream ds private
Referenced by LEDataInputStream.available(), LEDataInputStream.close(), LEDataInputStream.readBoolean(), LEDataInputStream.readByte(), LEDataInputStream.readChar(), LEDataInputStream.readFully(), LEDataInputStream.readInt(), LEDataInputStream.readLine(), LEDataInputStream.readLong(), LEDataInputStream.readShort(), LEDataInputStream.readUnsignedByte(), LEDataInputStream.readUnsignedShort(), LEDataInputStream.readUTF(), and LEDataInputStream.skipBytes().
in
final InputStream in private
Referenced by LEDataInputStream.LEDataInputStream(), and LEDataInputStream.read().
position
long position = 0 private
Referenced by LEDataInputStream.getPosition(), LEDataInputStream.read(), LEDataInputStream.readBoolean(), LEDataInputStream.readByte(), LEDataInputStream.readChar(), LEDataInputStream.readFully(), LEDataInputStream.readInt(), LEDataInputStream.readLong(), LEDataInputStream.readShort(), LEDataInputStream.readUnsignedByte(), LEDataInputStream.readUnsignedShort(), LEDataInputStream.realign(), and LEDataInputStream.skipBytes().