GeoSPARQL SRS Extension: SVGWriter Class Reference
SVGWriter Class Reference
Writes the Well-Known Text representation of a Geometry.
Public Member Functions
SVGWriter ()
Creates a new SVGWriter with default settings.
String write (Geometry geometry)
Converts a Geometry to its Well-known Text representation.
void write (Geometry geometry, Writer writer) throws IOException
Converts a Geometry to its Well-known Text representation.
String writeFormatted (Geometry geometry)
Same as write, but with newlines and spaces to make the well-known text more readable.
void writeFormatted (Geometry geometry, Writer writer) throws IOException
Same as write, but with newlines and spaces to make the well-known text more readable.
Static Public Member Functions
static String stringOfChar (char ch, int count)
Returns a String of repeated characters.
Private Member Functions
void writeFormatted (Geometry geometry, boolean useFormatting, Writer writer) throws IOException
Converts a Geometry to its Well-known Text representation.
void appendGeometryTaggedText (Geometry geometry, int level, Writer writer) throws IOException
Converts a Geometry to <Geometry Tagged Text> format, then appends it to the writer.
void appendPointTaggedText (Coordinate coordinate, int level, Writer writer, PrecisionModel precisionModel) throws IOException
Converts a Coordinate to <Point Tagged Text> format, then appends it to the writer.
void appendLineStringTaggedText (LineString lineString, int level, Writer writer) throws IOException
Converts a LineString to <LineString Tagged Text> format, then appends it to the writer.
void appendLinearRingTaggedText (LinearRing linearRing, int level, Writer writer) throws IOException
Converts a LinearRing to <LinearRing Tagged Text> format, then appends it to the writer.
void appendPolygon (Polygon polygon, int level, Writer writer) throws IOException
Converts a Polygon to <Polygon Tagged Text> format, then appends it to the writer.
void appendMultiPointTaggedText (MultiPoint multipoint, int level, Writer writer) throws IOException
Converts a MultiPoint to <MultiPoint Tagged Text> format, then appends it to the writer.
void appendMultiLineStringTaggedText (MultiLineString multiLineString, int level, Writer writer) throws IOException
Converts a MultiLineString to <MultiLineString Tagged Text> format, then appends it to the writer.
void appendMultiPolygonTaggedText (MultiPolygon multiPolygon, int level, Writer writer) throws IOException
Converts a MultiPolygon to <MultiPolygon Tagged Text> format, then appends it to the writer.
void appendGeometryCollectionTaggedText (GeometryCollection geometryCollection, int level, Writer writer) throws IOException
Converts a GeometryCollection to <GeometryCollection Tagged Text> format, then appends it to the writer.
void appendPoint (Coordinate coordinate, int level, Writer writer, PrecisionModel precisionModel) throws IOException
Converts a Coordinate to <Point Text> format, then appends it to the writer.
void appendCoordinate (CoordinateSequence seq, int i, Writer writer) throws IOException
Appends the i'th coordinate from the sequence to the writer.
void appendCoordinate (Coordinate coordinate, Writer writer) throws IOException
Converts a Coordinate to <Point> format, then appends it to the writer.
String writeNumber (double d)
Converts a double to a String, not in scientific notation.
void appendSequencePath (CoordinateSequence seq, int level, boolean doIndent, Writer writer) throws IOException
Converts a LineString to <LineString Text> format, then appends it to the writer.
void appendSequencePoints (CoordinateSequence seq, int level, boolean doIndent, Writer writer) throws IOException
void appendLineString (LineString lineString, int level, boolean doIndent, Writer writer) throws IOException
Converts a LineString to <LineString Text> format, then appends it to the writer.
void appendPolygonPolygon (Polygon polygon, int level, boolean indentFirst, Writer writer) throws IOException
Converts a Polygon to <Polygon Text> format, then appends it to the writer.
void appendPolygonPath (Polygon polygon, int level, boolean indentFirst, Writer writer) throws IOException
void appendPathStart (boolean useFillRule, Writer writer) throws IOException
void appendPathEnd (Writer writer) throws IOException
void appendMultiPointText (MultiPoint multiPoint, int level, Writer writer) throws IOException
Converts a MultiPoint to <MultiPoint Text> format, then appends it to the writer.
void appendMultiLineStringText (MultiLineString multiLineString, int level, boolean indentFirst, Writer writer) throws IOException
Converts a MultiLineString to <MultiLineString Text> format, then appends it to the writer.
void appendMultiPolygonText (MultiPolygon multiPolygon, int level, Writer writer) throws IOException
Converts a MultiPolygon to <MultiPolygon Text> format, then appends it to the writer.
void appendGeometryCollectionText (GeometryCollection geometryCollection, int level, Writer writer) throws IOException
Converts a GeometryCollection to <GeometryCollectionText> format, then appends it to the writer.
void indentCoords (int coordIndex, int level, Writer writer) throws IOException
void indent (int level, Writer writer) throws IOException
Static Private Member Functions
static DecimalFormat createFormatter (PrecisionModel precisionModel)
Creates the DecimalFormat used to write doubles with a sufficient number of decimal places.
Private Attributes
int outputDimension = 2
DecimalFormat formatter
boolean isFormatted = false
boolean useFormatting = false
int level = 0
int coordsPerLine = -1
String indentTabStr = " "
Static Private Attributes
static final int INDENT = 2
Detailed Description
Writes the Well-Known Text representation of a Geometry.
The Well-Known Text format is defined in the OGC Simple Features Specification for SQL. See WKTReader for a formal specification of the format syntax.
The WKTWriter outputs coordinates rounded to the precision model. Only the maximum number of decimal places necessary to represent the ordinates to the required precision will be output.
The SFS WKT spec does not define a special tag for LinearRings. Under the spec, rings are output as LINESTRINGs. In order to allow precisely specifying constructed geometries, JTS also supports a non-standard LINEARRING tag which is used to output LinearRings.
Version
1.7
See also
WKTReader
Constructor & Destructor Documentation
SVGWriter()
SVGWriter ()
Creates a new SVGWriter with default settings.
   {
   }
Member Function Documentation
appendCoordinate() [1/2]
void appendCoordinate (Coordinate coordinate, Writer writer) throws IOException private
Converts a Coordinate to <Point> format, then appends it to the writer.
Parameters
coordinate the Coordinate to process
writer the output writer to append to
   {
     writer.write(writeNumber(coordinate.x) + " " + writeNumber(coordinate.y));
     if (outputDimension >= 3 && ! Double.isNaN(coordinate.z)) {
       writer.write(" ");
       writer.write(writeNumber(coordinate.z));
     }
   }
References SVGWriter.outputDimension, and SVGWriter.writeNumber().
appendCoordinate() [2/2]
void appendCoordinate (CoordinateSequence seq, int i, Writer writer) throws IOException private
Appends the i'th coordinate from the sequence to the writer.
Parameters
seq the CoordinateSequence to process
i the index of the coordinate to write
writer the output writer to append to
   {
     writer.write(writeNumber(seq.getX(i)) + "," + writeNumber(seq.getY(i)));
   }
References SVGWriter.writeNumber().
Referenced by SVGWriter.appendSequencePath(), and SVGWriter.appendSequencePoints().
appendGeometryCollectionTaggedText()
void appendGeometryCollectionTaggedText (GeometryCollection geometryCollection, int level, Writer writer) throws IOException private
Converts a GeometryCollection to <GeometryCollection Tagged Text> format, then appends it to the writer.
Parameters
geometryCollection the GeometryCollection to process
writer the output writer to append to
   {
     appendGeometryCollectionText(geometryCollection, level, writer);
   }
References SVGWriter.appendGeometryCollectionText(), and SVGWriter.level.
Referenced by SVGWriter.appendGeometryTaggedText().
appendGeometryCollectionText()
void appendGeometryCollectionText (GeometryCollection geometryCollection, int level, Writer writer) throws IOException private
Converts a GeometryCollection to <GeometryCollectionText> format, then appends it to the writer.
Parameters
geometryCollection the GeometryCollection to process
writer the output writer to append to
   {
       int level2 = level;
       for (int i = 0; i < geometryCollection.getNumGeometries(); i++) {
         if (i > 0) {
           level2 = level + 1;
         }
         appendGeometryTaggedText(geometryCollection.getGeometryN(i), level2, writer);
       }
   }
References SVGWriter.appendGeometryTaggedText(), and SVGWriter.level.
Referenced by SVGWriter.appendGeometryCollectionTaggedText().
appendGeometryTaggedText()
void appendGeometryTaggedText (Geometry geometry, int level, Writer writer) throws IOException private
Converts a Geometry to <Geometry Tagged Text> format, then appends it to the writer.
Parameters
geometry the Geometry to process
writer the output writer to append to
   {
     indent(level, writer);
     if (geometry instanceof Point) {
       Point point = (Point) geometry;
       appendPointTaggedText(point.getCoordinate(), level, writer, point.getPrecisionModel());
     }
     else if (geometry instanceof LinearRing) {
       appendLinearRingTaggedText((LinearRing) geometry, level, writer);
     }
     else if (geometry instanceof LineString) {
       appendLineStringTaggedText((LineString) geometry, level, writer);
     }
     else if (geometry instanceof Polygon) {
       appendPolygon((Polygon) geometry, level, writer);
     }
     else if (geometry instanceof MultiPoint) {
       appendMultiPointTaggedText((MultiPoint) geometry, level, writer);
     }
     else if (geometry instanceof MultiLineString) {
       appendMultiLineStringTaggedText((MultiLineString) geometry, level, writer);
     }
     else if (geometry instanceof MultiPolygon) {
       appendMultiPolygonTaggedText((MultiPolygon) geometry, level, writer);
     }
     else if (geometry instanceof GeometryCollection) {
       appendGeometryCollectionTaggedText((GeometryCollection) geometry, level, writer);
     }
     else {
       Assert.shouldNeverReachHere("Unsupported Geometry implementation:"
            + geometry.getClass());
     }
   }
References SVGWriter.appendGeometryCollectionTaggedText(), SVGWriter.appendLinearRingTaggedText(), SVGWriter.appendLineStringTaggedText(), SVGWriter.appendMultiLineStringTaggedText(), SVGWriter.appendMultiPointTaggedText(), SVGWriter.appendMultiPolygonTaggedText(), SVGWriter.appendPointTaggedText(), SVGWriter.appendPolygon(), SVGWriter.indent(), and SVGWriter.level.
Referenced by SVGWriter.appendGeometryCollectionText(), and SVGWriter.writeFormatted().
appendLinearRingTaggedText()
void appendLinearRingTaggedText (LinearRing linearRing, int level, Writer writer) throws IOException private
Converts a LinearRing to <LinearRing Tagged Text> format, then appends it to the writer.
Parameters
linearRing the LinearRing to process
writer the output writer to append to
   {
     appendLineString(linearRing, level, false, writer);
   }
References SVGWriter.appendLineString(), and SVGWriter.level.
Referenced by SVGWriter.appendGeometryTaggedText().
appendLineString()
void appendLineString (LineString lineString, int level, boolean doIndent, Writer writer) throws IOException private
Converts a LineString to <LineString Text> format, then appends it to the writer.
Parameters
lineString the LineString to process
writer the output writer to append to
   {
       if (doIndent) indent(level, writer);
       writer.write("<polyline fill='none' points='");
       appendSequencePoints(lineString.getCoordinateSequence(), level, doIndent, writer);
       writer.write("'/>\n");
   }
References SVGWriter.appendSequencePoints(), SVGWriter.indent(), and SVGWriter.level.
Referenced by SVGWriter.appendLinearRingTaggedText(), SVGWriter.appendLineStringTaggedText(), and SVGWriter.appendMultiLineStringText().
appendLineStringTaggedText()
void appendLineStringTaggedText (LineString lineString, int level, Writer writer) throws IOException private
Converts a LineString to <LineString Tagged Text> format, then appends it to the writer.
Parameters
lineString the LineString to process
writer the output writer to append to
   {
     appendLineString(lineString, level, false, writer);
   }
References SVGWriter.appendLineString(), and SVGWriter.level.
Referenced by SVGWriter.appendGeometryTaggedText().
appendMultiLineStringTaggedText()
void appendMultiLineStringTaggedText (MultiLineString multiLineString, int level, Writer writer) throws IOException private
Converts a MultiLineString to <MultiLineString Tagged Text> format, then appends it to the writer.
Parameters
multiLineString the MultiLineString to process
writer the output writer to append to
   {
     appendMultiLineStringText(multiLineString, level, false, writer);
   }
References SVGWriter.appendMultiLineStringText(), and SVGWriter.level.
Referenced by SVGWriter.appendGeometryTaggedText().
appendMultiLineStringText()
void appendMultiLineStringText (MultiLineString multiLineString, int level, boolean indentFirst, Writer writer) throws IOException private
Converts a MultiLineString to <MultiLineString Text> format, then appends it to the writer.
Parameters
multiLineString the MultiLineString to process
writer the output writer to append to
   {
       int level2 = level;
       boolean doIndent = indentFirst;
       for (int i = 0; i < multiLineString.getNumGeometries(); i++) {
         if (i > 0) {
           level2 = level + 1;
           doIndent = true;
         }
         appendLineString((LineString) multiLineString.getGeometryN(i), level2, doIndent, writer);
       }
   }
References SVGWriter.appendLineString(), and SVGWriter.level.
Referenced by SVGWriter.appendMultiLineStringTaggedText().
appendMultiPointTaggedText()
void appendMultiPointTaggedText (MultiPoint multipoint, int level, Writer writer) throws IOException private
Converts a MultiPoint to <MultiPoint Tagged Text> format, then appends it to the writer.
Parameters
multipoint the MultiPoint to process
writer the output writer to append to
   {
     appendMultiPointText(multipoint, level, writer);
   }
References SVGWriter.appendMultiPointText(), and SVGWriter.level.
Referenced by SVGWriter.appendGeometryTaggedText().
appendMultiPointText()
void appendMultiPointText (MultiPoint multiPoint, int level, Writer writer) throws IOException private
Converts a MultiPoint to <MultiPoint Text> format, then appends it to the writer.
Parameters
multiPoint the MultiPoint to process
writer the output writer to append to
   {
     if (multiPoint.isEmpty()) {
       writer.write(" ");
     }
     else {
       int level2 = level;
       for (int i = 0; i < multiPoint.getNumGeometries(); i++) {
         if (i > 0) {
           level2 = level + 1;
         }
         appendPoint(multiPoint.getGeometryN(i).getCoordinate(), level2, writer, multiPoint.getPrecisionModel());
       }
     }
   }
References SVGWriter.appendPoint(), and SVGWriter.level.
Referenced by SVGWriter.appendMultiPointTaggedText().
appendMultiPolygonTaggedText()
void appendMultiPolygonTaggedText (MultiPolygon multiPolygon, int level, Writer writer) throws IOException private
Converts a MultiPolygon to <MultiPolygon Tagged Text> format, then appends it to the writer.
Parameters
multiPolygon the MultiPolygon to process
writer the output writer to append to
   {
     appendMultiPolygonText(multiPolygon, level, writer);
   }
References SVGWriter.appendMultiPolygonText(), and SVGWriter.level.
Referenced by SVGWriter.appendGeometryTaggedText().
appendMultiPolygonText()
void appendMultiPolygonText (MultiPolygon multiPolygon, int level, Writer writer) throws IOException private
Converts a MultiPolygon to <MultiPolygon Text> format, then appends it to the writer.
Parameters
multiPolygon the MultiPolygon to process
writer the output writer to append to
   {
       int level2 = level;
       boolean doIndent = false;
       for (int i = 0; i < multiPolygon.getNumGeometries(); i++) {
         if (i > 0) {
           level2 = level + 1;
           doIndent = true;
         }
         appendPolygon((Polygon) multiPolygon.getGeometryN(i), level2, writer);
       }
   }
References SVGWriter.appendPolygon(), and SVGWriter.level.
Referenced by SVGWriter.appendMultiPolygonTaggedText().
appendPathEnd()
void appendPathEnd (Writer writer) throws IOException private
{
     writer.write("' />\n");
   }
appendPathStart()
void appendPathStart (boolean useFillRule, Writer writer) throws IOException private
{
     String fillRule = useFillRule ? "fill-rule='evenodd' " :  "";
     writer.write("<path " + fillRule + "d='");
   }
appendPoint()
void appendPoint (Coordinate coordinate, int level, Writer writer, PrecisionModel precisionModel) throws IOException private
Converts a Coordinate to <Point Text> format, then appends it to the writer.
Parameters
coordinate the Coordinate to process
writer the output writer to append to
precisionModel the PrecisionModel to use to convert from a precise coordinate to an external coordinate
   {
     writer.write("<circle cx='" + coordinate.x + "' cy='" + coordinate.y + "' r='1' />\n");
   }
Referenced by SVGWriter.appendMultiPointText(), and SVGWriter.appendPointTaggedText().
appendPointTaggedText()
void appendPointTaggedText (Coordinate coordinate, int level, Writer writer, PrecisionModel precisionModel) throws IOException private
Converts a Coordinate to <Point Tagged Text> format, then appends it to the writer.
Parameters
coordinate the Coordinate to process
writer the output writer to append to
precisionModel the PrecisionModel to use to convert from a precise coordinate to an external coordinate
   {
     appendPoint(coordinate, level, writer, precisionModel);
   }
References SVGWriter.appendPoint(), and SVGWriter.level.
Referenced by SVGWriter.appendGeometryTaggedText().
appendPolygon()
void appendPolygon (Polygon polygon, int level, Writer writer) throws IOException private
Converts a Polygon to <Polygon Tagged Text> format, then appends it to the writer.
Parameters
polygon the Polygon to process
writer the output writer to append to
   {
     if (polygon.getNumInteriorRing() == 0) {
       appendPolygonPolygon(polygon, level, false, writer);
     }
     else {
       appendPolygonPath(polygon, level, false, writer);
     }
   }
References SVGWriter.appendPolygonPath(), SVGWriter.appendPolygonPolygon(), and SVGWriter.level.
Referenced by SVGWriter.appendGeometryTaggedText(), and SVGWriter.appendMultiPolygonText().
appendPolygonPath()
void appendPolygonPath (Polygon polygon, int level, boolean indentFirst, Writer writer) throws IOException private
     {
         if (indentFirst) indent(level, writer);
         writer.write("<path fill-rule='evenodd' d='");
         appendSequencePath(polygon.getExteriorRing().getCoordinateSequence(), level, false, writer);
         for (int i = 0; i < polygon.getNumInteriorRing(); i++) {
           writer.write(" ");
           appendSequencePath(polygon.getInteriorRingN(i).getCoordinateSequence(), level + 1, true, writer);
         }
         writer.write("' />\n");
     }
References SVGWriter.appendSequencePath(), SVGWriter.indent(), and SVGWriter.level.
Referenced by SVGWriter.appendPolygon().
appendPolygonPolygon()
void appendPolygonPolygon (Polygon polygon, int level, boolean indentFirst, Writer writer) throws IOException private
Converts a Polygon to <Polygon Text> format, then appends it to the writer.
Parameters
polygon the Polygon to process
writer the output writer to append to
     {
         if (indentFirst) indent(level, writer);
         writer.write("<polygon points='");
         appendSequencePoints(polygon.getExteriorRing().getCoordinateSequence(), level, false, writer);
         writer.write("' />\n");
     }
References SVGWriter.appendSequencePoints(), SVGWriter.indent(), and SVGWriter.level.
Referenced by SVGWriter.appendPolygon().
appendSequencePath()
void appendSequencePath (CoordinateSequence seq, int level, boolean doIndent, Writer writer) throws IOException private
Converts a LineString to <LineString Text> format, then appends it to the writer.
Parameters
lineString the LineString to process
writer the output writer to append to
     {
       if (seq.size() == 0) {
         //writer.write("EMPTY");
       }
       else {
         if (doIndent) indent(level, writer);
         for (int i = 0; i < seq.size(); i++) {
           writer.write(" " + ((i == 0) ? "M" : "L"));
           if (i > 0) {
             if (coordsPerLine > 0
                 && i % coordsPerLine == 0) {
               indent(level + 1, writer);
             }
           }
           appendCoordinate(seq, i, writer);
         }
       }
     }
References SVGWriter.appendCoordinate(), SVGWriter.coordsPerLine, SVGWriter.indent(), and SVGWriter.level.
Referenced by SVGWriter.appendPolygonPath().
appendSequencePoints()
void appendSequencePoints (CoordinateSequence seq, int level, boolean doIndent, Writer writer) throws IOException private
     {
       if (seq.size() == 0) {
         //writer.write("EMPTY");
       }
       else {
         if (doIndent) indent(level, writer);
         for (int i = 0; i < seq.size(); i++) {
           writer.write(" ");
           if (i > 0) {
             if (coordsPerLine > 0
                 && i % coordsPerLine == 0) {
               indent(level + 1, writer);
             }
           }
           appendCoordinate(seq, i, writer);
         }
       }
     }
References SVGWriter.appendCoordinate(), SVGWriter.coordsPerLine, SVGWriter.indent(), and SVGWriter.level.
Referenced by SVGWriter.appendLineString(), and SVGWriter.appendPolygonPolygon().
createFormatter()
static DecimalFormat createFormatter (PrecisionModel precisionModel) static private
Creates the DecimalFormat used to write doubles with a sufficient number of decimal places.
Parameters
precisionModel the PrecisionModel used to determine the number of decimal places to write.
Returns
a DecimalFormat that write double s without scientific notation.
{
     // the default number of decimal places is 16, which is sufficient
     // to accomodate the maximum precision of a double.
     int decimalPlaces = precisionModel.getMaximumSignificantDigits();
     // specify decimal separator explicitly to avoid problems in other locales
     DecimalFormatSymbols symbols = new DecimalFormatSymbols();
     symbols.setDecimalSeparator('.');
     String fmtString = "0" + (decimalPlaces > 0 ? "." : "")
                  +  stringOfChar('#', decimalPlaces);
     return new DecimalFormat(fmtString, symbols);
   }
References SVGWriter.stringOfChar().
Referenced by SVGWriter.writeFormatted().
indent()
void indent (int level, Writer writer) throws IOException private
   {
     if (! useFormatting || level <= 0)
       return;
     writer.write("\n");
     for (int i = 0; i < level; i++) {
       writer.write(indentTabStr);
     }
   }
References SVGWriter.indentTabStr, SVGWriter.level, and SVGWriter.useFormatting.
Referenced by SVGWriter.appendGeometryTaggedText(), SVGWriter.appendLineString(), SVGWriter.appendPolygonPath(), SVGWriter.appendPolygonPolygon(), SVGWriter.appendSequencePath(), SVGWriter.appendSequencePoints(), and SVGWriter.indentCoords().
indentCoords()
void indentCoords (int coordIndex, int level, Writer writer) throws IOException private
   {
     if (coordsPerLine <= 0
         || coordIndex % coordsPerLine != 0)
       return;
     indent(level, writer);
   }
References SVGWriter.coordsPerLine, SVGWriter.indent(), and SVGWriter.level.
stringOfChar()
static String stringOfChar (char ch, int count) static
Returns a String of repeated characters.
Parameters
ch the character to repeat
count the number of times to repeat the character
Returns
a String of characters
{
     StringBuffer buf = new StringBuffer();
     for (int i = 0; i < count; i++) {
       buf.append(ch);
     }
     return buf.toString();
   }
Referenced by SVGWriter.createFormatter().
write() [1/2]
String write (Geometry geometry)
Converts a Geometry to its Well-known Text representation.
Parameters
geometry a Geometry to process
Returns
a <Geometry Tagged Text> string (see the OpenGIS Simple Features Specification)
   {
     Writer sw = new StringWriter();
     try {
       writeFormatted(geometry, isFormatted, sw);
     }
     catch (IOException ex) {
       Assert.shouldNeverReachHere();
     }
     return sw.toString();
   }
References SVGWriter.isFormatted, and SVGWriter.writeFormatted().
write() [2/2]
void write (Geometry geometry, Writer writer) throws IOException
Converts a Geometry to its Well-known Text representation.
Parameters
geometry a Geometry to process
   {
     writeFormatted(geometry, false, writer);
   }
References SVGWriter.writeFormatted().
writeFormatted() [1/3]
String writeFormatted (Geometry geometry)
Same as write, but with newlines and spaces to make the well-known text more readable.
Parameters
geometry a Geometry to process
Returns
a <Geometry Tagged Text> string (see the OpenGIS Simple Features Specification), with newlines and spaces
   {
     Writer sw = new StringWriter();
     try {
       writeFormatted(geometry, true, sw);
     }
     catch (IOException ex) {
       Assert.shouldNeverReachHere();
     }
     return sw.toString();
   }
Referenced by SVGWriter.write(), and SVGWriter.writeFormatted().
writeFormatted() [2/3]
void writeFormatted (Geometry geometry, boolean useFormatting, Writer writer) throws IOException private
Converts a Geometry to its Well-known Text representation.
Parameters
geometry a Geometry to process
   {
     this.useFormatting = useFormatting;
     formatter = createFormatter(geometry.getPrecisionModel());
     //writer.write("<g>\n");
     appendGeometryTaggedText(geometry, 0, writer);
     //writer.write("</g>\n");
   }
References SVGWriter.appendGeometryTaggedText(), SVGWriter.createFormatter(), SVGWriter.formatter, and SVGWriter.useFormatting.
writeFormatted() [3/3]
void writeFormatted (Geometry geometry, Writer writer) throws IOException
Same as write, but with newlines and spaces to make the well-known text more readable.
Parameters
geometry a Geometry to process
   {
     writeFormatted(geometry, true, writer);
   }
References SVGWriter.writeFormatted().
writeNumber()
String writeNumber (double d) private
Converts a double to a String, not in scientific notation.
Parameters
d the double to convert
Returns
the double as a String, not in scientific notation
{
     return formatter.format(d);
   }
References SVGWriter.formatter.
Referenced by SVGWriter.appendCoordinate().
Member Data Documentation
coordsPerLine
int coordsPerLine = -1 private
Referenced by SVGWriter.appendSequencePath(), SVGWriter.appendSequencePoints(), and SVGWriter.indentCoords().
formatter
DecimalFormat formatter private
Referenced by SVGWriter.writeFormatted(), and SVGWriter.writeNumber().
INDENT
final int INDENT = 2 static private
indentTabStr
String indentTabStr = " " private
Referenced by SVGWriter.indent().
isFormatted
boolean isFormatted = false private
Referenced by SVGWriter.write().
level
int level = 0 private
Referenced by SVGWriter.appendGeometryCollectionTaggedText(), SVGWriter.appendGeometryCollectionText(), SVGWriter.appendGeometryTaggedText(), SVGWriter.appendLinearRingTaggedText(), SVGWriter.appendLineString(), SVGWriter.appendLineStringTaggedText(), SVGWriter.appendMultiLineStringTaggedText(), SVGWriter.appendMultiLineStringText(), SVGWriter.appendMultiPointTaggedText(), SVGWriter.appendMultiPointText(), SVGWriter.appendMultiPolygonTaggedText(), SVGWriter.appendMultiPolygonText(), SVGWriter.appendPointTaggedText(), SVGWriter.appendPolygon(), SVGWriter.appendPolygonPath(), SVGWriter.appendPolygonPolygon(), SVGWriter.appendSequencePath(), SVGWriter.appendSequencePoints(), SVGWriter.indent(), and SVGWriter.indentCoords().
outputDimension
int outputDimension = 2 private
Referenced by SVGWriter.appendCoordinate().
useFormatting
boolean useFormatting = false private
Referenced by SVGWriter.indent(), and SVGWriter.writeFormatted().