GeoSPARQL SRS Extension: Triangle Class Reference
Triangle Class Reference
Triangle.
Public Member Functions
Triangle ()
Default constructor.
Triangle (int id)
Constructor.
Triangle (int id, boolean border)
Constructor.
int getId ()
Returns the ID of the triangle.
void setId (int id)
Defines the ID of the triangle.
boolean isBorder ()
Returns true if the triangle is a border triangle of the triangulation framework, false otherwise.
void setBorder (boolean border)
Defines the indicator to know if the triangle is a border triangle of the triangulation framework.
List< Edge > getEdges ()
Returns the edges which compose the triangle.
void setEdges (List< Edge > edges)
Defines the edges which compose the triangle.
List< Triangle > getNeighbours ()
Returns the neighbour triangles of the triangle.
void setNeighbours (List< Triangle > neighbours)
Defines the neighbour triangles of the triangle.
boolean addEdge (Edge edge)
Add an edge to the triangle.
boolean addEdges (List< Edge > edges)
Add edges to the triangle.
boolean removeEdge (Edge edge)
Remove an edge of the triangle.
boolean removeEdges (List< Edge > edges)
Remove edges of the triangle.
boolean addNeighbour (Triangle triangle)
Add a neighbour triangle to the triangle.
boolean addNeighbours (List< Triangle > triangles)
Add neighbour triangles to the triangle.
boolean removeNeighbour (Triangle triangle)
Remove a neighbour triangle of the triangle.
boolean removeNeighbours (List< Triangle > triangles)
Remove neighbour triangles of the triangle.
Private Attributes
int id
ID of the triangle.
boolean border
Indicator to know if the triangle is a border triangle of the triangulation framework.
List< Edge > edges = new ArrayList<Edge>()
Edges which compose the triangle.
List< Triangle > neighbours = new ArrayList<Triangle>()
Neighbour triangles of this triangle.
Detailed Description
Triangle.
Author
Eric Grosso
Constructor & Destructor Documentation
Triangle() [1/3]
Triangle ()
Default constructor.
                       {
         //
     }
Triangle() [2/3]
Triangle (int id)
Constructor.
Parameters
id ID of the triangle
{
         this.id = id;
     }
References Triangle.id.
Triangle() [3/3]
Triangle (int id, boolean border)
Constructor.
Parameters
id ID of the triangle
border defines if the triangle is a border triangle or not in the triangulation framework
{
         this.id = id;
         this.border = border;
     }
References Triangle.border, and Triangle.id.
Member Function Documentation
addEdge()
boolean addEdge (Edge edge)
Add an edge to the triangle.
Returns
true if added, false otherwise
{
         return getEdges().add(edge);
     }
References Triangle.getEdges().
Referenced by ConcaveHull.concaveHull().
addEdges()
boolean addEdges (List< Edge > edges)
Add edges to the triangle.
Returns
true if added, false otherwise
{
         return getEdges().addAll(edges);
     }
References Triangle.edges, and Triangle.getEdges().
addNeighbour()
boolean addNeighbour (Triangle triangle)
Add a neighbour triangle to the triangle.
Returns
true if added, false otherwise
{
         return getNeighbours().add(triangle);
     }
References Triangle.getNeighbours().
Referenced by ConcaveHull.concaveHull().
addNeighbours()
boolean addNeighbours (List< Triangle > triangles)
Add neighbour triangles to the triangle.
Returns
true if added, false otherwise
{
         return getNeighbours().addAll(triangles);
     }
References Triangle.getNeighbours().
getEdges()
List<Edge> getEdges ()
Returns the edges which compose the triangle.
Returns
the edges of the triangle which compose the triangle
{
         return this.edges;
     }
References Triangle.edges.
Referenced by Triangle.addEdge(), Triangle.addEdges(), ConcaveHull.concaveHull(), Triangle.removeEdge(), and Triangle.removeEdges().
getId()
int getId ()
Returns the ID of the triangle.
Returns
the ID of the triangle
{
         return this.id;
     }
References Triangle.id.
Referenced by ConcaveHull.concaveHull().
getNeighbours()
List<Triangle> getNeighbours ()
Returns the neighbour triangles of the triangle.
Returns
the neighbour triangles of the triangle
{
         return this.neighbours;
     }
References Triangle.neighbours.
Referenced by Triangle.addNeighbour(), Triangle.addNeighbours(), ConcaveHull.concaveHull(), Triangle.removeNeighbour(), and Triangle.removeNeighbours().
isBorder()
boolean isBorder ()
Returns true if the triangle is a border triangle of the triangulation framework, false otherwise.
Returns
true if the triangle is a border triangle, false otherwise
{
         return this.border;
     }
References Triangle.border.
removeEdge()
boolean removeEdge (Edge edge)
Remove an edge of the triangle.
Returns
true if removed, false otherwise
{
         return getEdges().remove(edge);
     }
References Triangle.getEdges().
removeEdges()
boolean removeEdges (List< Edge > edges)
Remove edges of the triangle.
Returns
true if removed, false otherwise
{
         return getEdges().removeAll(edges);
     }
References Triangle.edges, and Triangle.getEdges().
removeNeighbour()
boolean removeNeighbour (Triangle triangle)
Remove a neighbour triangle of the triangle.
Returns
true if removed, false otherwise
{
         return getNeighbours().remove(triangle);
     }
References Triangle.getNeighbours().
Referenced by ConcaveHull.concaveHull().
removeNeighbours()
boolean removeNeighbours (List< Triangle > triangles)
Remove neighbour triangles of the triangle.
Returns
true if removed, false otherwise
{
         return getNeighbours().removeAll(triangles);
     }
References Triangle.getNeighbours().
setBorder()
void setBorder (boolean border)
Defines the indicator to know if the triangle is a border triangle of the triangulation framework.
Parameters
border true if the triangle is a border triangle, false otherwise
{
         this.border = border;
     }
References Triangle.border.
Referenced by ConcaveHull.concaveHull().
setEdges()
void setEdges (List< Edge > edges)
Defines the edges which compose the triangle.
Parameters
edges the edges which compose the triangle
{
         this.edges = edges;
     }
References Triangle.edges.
setId()
void setId (int id)
Defines the ID of the triangle.
Parameters
id ID of the triangle
{
         this.id = id;
     }
References Triangle.id.
setNeighbours()
void setNeighbours (List< Triangle > neighbours)
Defines the neighbour triangles of the triangle.
Parameters
neighbours the neighbour triangles of the triangle
{
         this.neighbours = neighbours;
     }
References Triangle.neighbours.
Member Data Documentation
border
boolean border private
Indicator to know if the triangle is a border triangle of the triangulation framework.
Referenced by Triangle.isBorder(), Triangle.setBorder(), and Triangle.Triangle().
edges
List<Edge> edges = new ArrayList<Edge>() private
Edges which compose the triangle.
Referenced by Triangle.addEdges(), Triangle.getEdges(), Triangle.removeEdges(), and Triangle.setEdges().
id
int id private
ID of the triangle.
Referenced by Triangle.getId(), Triangle.setId(), and Triangle.Triangle().
neighbours
List<Triangle> neighbours = new ArrayList<Triangle>() private
Neighbour triangles of this triangle.
Referenced by Triangle.getNeighbours(), and Triangle.setNeighbours().