GeoSPARQL SRS Extension: LengthSubstring Class Reference
LengthSubstring Class Reference
Computes a substring of a LineString between given distances along the line.
Public Member Functions
LengthSubstring (LineString line)
LineString getSubstring (double startDistance, double endDistance)
Static Public Member Functions
static LineString getSubstring (LineString line, double startLength, double endLength)
Private Member Functions
LineString computeSubstring (double startDistance, double endDistance)
Assumes input is strictly valid (e.g.
Private Attributes
LineString line
Detailed Description
Computes a substring of a LineString between given distances along the line.
The distances are clipped to the actual line length
If the start distance is equal to the end distance, a zero-length line with two identical points is returned
FUTURE: If the start distance is greater than the end distance, an inverted section of the line is returned
FUTURE: should handle startLength > endLength, and flip the returned linestring. Also should handle negative lengths (they are measured from end of line backwards).
Constructor & Destructor Documentation
LengthSubstring()
LengthSubstring (LineString line)
{
     this.line = line;
   }
References LengthSubstring.line.
Referenced by LengthSubstring.getSubstring().
Member Function Documentation
computeSubstring()
LineString computeSubstring (double startDistance, double endDistance) private
Assumes input is strictly valid (e.g.
startDist < endDistance)
Parameters
startDistance
endDistance
Returns
Ensure there is enough coordinates to build a valid line. Make a 2-point line with duplicate coordinates, if necessary There will always be at least one coordinate in the coordList.
   {
     Coordinate[] coordinates = line.getCoordinates();
     CoordinateList newCoordinates = new CoordinateList();
     double segmentStartDistance = 0.0;
     double segmentEndDistance = 0.0;
     boolean started = false;
     int i = 0;
     LineSegment segment = new LineSegment();
     while (i < coordinates.length - 1 && endDistance > segmentEndDistance) {
       segment.p0 = coordinates[i];
       segment.p1 = coordinates[i + 1];
       i++;
       segmentStartDistance = segmentEndDistance;
       segmentEndDistance = segmentStartDistance + segment.getLength();
       if (startDistance > segmentEndDistance)
         continue;
       if (startDistance >= segmentStartDistance
           && startDistance < segmentEndDistance) {
         newCoordinates.add(LocatePoint.pointAlongSegment(segment.p0, segment.p1,
             startDistance - segmentStartDistance), false);
       }
       /*
       if (startDistance >= segmentStartDistance
           && startDistance == segmentEndDistance) {
         newCoordinates.add(new Coordinate(segment.p1), false);
       }
       */
       if (endDistance >= segmentEndDistance) {
         newCoordinates.add(new Coordinate(segment.p1), false);
       }
       if (endDistance >= segmentStartDistance
           && endDistance < segmentEndDistance) {
         newCoordinates.add(LocatePoint.pointAlongSegment(segment.p0, segment.p1,
             endDistance - segmentStartDistance), false);
       }
     }
     Coordinate[] newCoordinateArray = newCoordinates.toCoordinateArray();
     if (newCoordinateArray.length <= 1) {
       newCoordinateArray = new Coordinate[] { newCoordinateArray[0], newCoordinateArray[0]};
     }
     return line.getFactory().createLineString(newCoordinateArray);
   }
References LengthSubstring.line, and LocatePoint.pointAlongSegment().
Referenced by LengthSubstring.getSubstring().
getSubstring() [1/2]
LineString getSubstring (double startDistance, double endDistance)
   {
     // future: if start > end, flip values and return an inverted line
     Assert.isTrue(startDistance <= endDistance, "inverted distances not currently supported");
     Coordinate[] coordinates = line.getCoordinates();
     // check for a zero-length segment and handle appropriately
     if (endDistance <= 0.0) {
       return line.getFactory().createLineString(
           new Coordinate[] { coordinates[0], coordinates[0]});
     }
     if (startDistance >= line.getLength()) { return line.getFactory()
                        .createLineString(
                        new Coordinate[] { coordinates[coordinates.length - 1],
     coordinates[coordinates.length - 1]}); }
     if (startDistance < 0.0) {
       startDistance = 0.0;
     }
     return computeSubstring(startDistance, endDistance);
   }
References LengthSubstring.computeSubstring(), and LengthSubstring.line.
getSubstring() [2/2]
static LineString getSubstring (LineString line, double startLength, double endLength) static
{
     LengthSubstring ls = new LengthSubstring(line);
     return ls.getSubstring(startLength, endLength);
   }
References LengthSubstring.getSubstring(), LengthSubstring.LengthSubstring(), and LengthSubstring.line.
Referenced by LengthSubstring.getSubstring().
Member Data Documentation
line
LineString line private
Referenced by LengthSubstring.computeSubstring(), LengthSubstring.getSubstring(), and LengthSubstring.LengthSubstring().