GeoSPARQL SRS Extension: LocatePoint Class Reference
LocatePoint Class Reference
Provides various ways of computing the actual value of a point a given length along a line.
Public Member Functions
LocatePoint (LineString line, double length)
Coordinate getPoint ()
int getIndex ()
Returns the index of the segment containing the computed point.
Static Public Member Functions
static Coordinate pointAlongSegment (LineSegment seg, double length)
Computes the location of a point a given length along a LineSegment.
static Coordinate pointAlongSegment (Coordinate p0, Coordinate p1, double length)
Computes the location of a point a given length along a line segment.
static Coordinate pointAlongSegmentByFraction (Coordinate p0, Coordinate p1, double frac)
Computes the location of a point a given fraction along a line segment.
static Coordinate pointAlongLine (LineString line, double length)
Computes the Coordinate of the point a given length along a LineString.
Private Member Functions
void compute (LineString line, double length)
Private Attributes
Coordinate pt
int index
Detailed Description
Provides various ways of computing the actual value of a point a given length along a line.
Constructor & Destructor Documentation
LocatePoint()
LocatePoint (LineString line, double length)
   {
     compute(line, length);
   }
References LocatePoint.compute().
Referenced by LocatePoint.pointAlongLine().
Member Function Documentation
compute()
void compute (LineString line, double length) private
   {
     // <TODO> handle negative distances (measure from opposite end of line)
     double totalLength = 0.0;
     Coordinate[] coord = line.getCoordinates();
     for (int i = 0; i < coord.length - 1; i++) {
       Coordinate p0 = coord[i];
       Coordinate p1 = coord[i+1];
       double segLen = p1.distance(p0);
       if (totalLength + segLen > length) {
         pt = pointAlongSegment(p0, p1, length - totalLength);
         index = i;
         return;
       }
       totalLength += segLen;
     }
     // distance is greater than line length
     pt = new Coordinate(coord[coord.length - 1]);
     index = coord.length;
   }
References LocatePoint.index, LocatePoint.pointAlongSegment(), and LocatePoint.pt.
Referenced by LocatePoint.LocatePoint().
getIndex()
int getIndex ()
Returns the index of the segment containing the computed point.
 {    return index;  }
References LocatePoint.index.
getPoint()
Coordinate getPoint ()
 {    return pt;  }
References LocatePoint.pt.
Referenced by LocatePoint.pointAlongLine().
pointAlongLine()
static Coordinate pointAlongLine (LineString line, double length) static
Computes the Coordinate of the point a given length along a LineString.
Parameters
line
length
Returns
the Coordinate of the desired point
   {
     LocatePoint loc = new LocatePoint(line, length);
     return loc.getPoint();
   }
References LocatePoint.getPoint(), and LocatePoint.LocatePoint().
pointAlongSegment() [1/2]
static Coordinate pointAlongSegment (Coordinate p0, Coordinate p1, double length) static
Computes the location of a point a given length along a line segment.
If the length exceeds the length of the line segment the last point of the segment is returned. If the length is negative the first point of the segment is returned.
Parameters
p0 the first point of the line segment
p1 the last point of the line segment
length the length to the desired point
Returns
the Coordinate of the desired point
   {
     double segLen = p1.distance(p0);
     double frac = length / segLen;
     if (frac <= 0.0) return p0;
     if (frac >= 1.0) return p1;
     double x = (p1.x - p0.x) * frac + p0.x;
     double y = (p1.y - p0.y) * frac + p0.y;
     return new Coordinate(x, y);
   }
pointAlongSegment() [2/2]
static Coordinate pointAlongSegment (LineSegment seg, double length) static
Computes the location of a point a given length along a LineSegment.
If the length exceeds the length of the line segment the last point of the segment is returned. If the length is negative the first point of the segment is returned.
Parameters
seg the line segment
length the length to the desired point
Returns
the Coordinate of the desired point
   {
     return pointAlongSegment(seg.p0, seg.p1, length);
   }
Referenced by LocatePoint.compute(), and LengthSubstring.computeSubstring().
pointAlongSegmentByFraction()
static Coordinate pointAlongSegmentByFraction (Coordinate p0, Coordinate p1, double frac) static
Computes the location of a point a given fraction along a line segment.
If the fraction exceeds 1 the last point of the segment is returned. If the fraction is negative the first point of the segment is returned.
Parameters
p0 the first point of the line segment
p1 the last point of the line segment
frac the fraction of the segment to the desired point
Returns
the Coordinate of the desired point
   {
     if (frac <= 0.0) return p0;
     if (frac >= 1.0) return p1;
     double x = (p1.x - p0.x) * frac + p0.x;
     double y = (p1.y - p0.y) * frac + p0.y;
     return new Coordinate(x, y);
   }
Member Data Documentation
index
int index private
Referenced by LocatePoint.compute(), and LocatePoint.getIndex().
pt
Coordinate pt private
Referenced by LocatePoint.compute(), and LocatePoint.getPoint().