GeoSPARQL SRS Extension: ConcaveHull Class Reference
ConcaveHull Class Reference
Computes a concave hull of a Geometry which is a concave Geometry that contains all the points in the input Geometry.
Public Member Functions
ConcaveHull (Geometry geometry, double threshold)
Create a new concave hull construction for the input Geometry.
ConcaveHull (GeometryCollection geometries, double threshold)
Create a new concave hull construction for the input GeometryCollection.
Geometry getConcaveHull ()
Returns a Geometry that represents the concave hull of the input geometry according to the threshold.
Public Attributes
HashMap< LineSegment, Integer > segments = new HashMap<LineSegment, Integer>()
HashMap< Integer, Edge > edges = new HashMap<Integer, Edge>()
HashMap< Integer, Triangle > triangles = new HashMap<Integer, Triangle>()
TreeMap< Integer, Edge > lengths = new TreeMap<Integer, Edge>()
HashMap< Integer, Edge > shortLengths = new HashMap<Integer, Edge>()
HashMap< Coordinate, Integer > coordinates = new HashMap<Coordinate, Integer>()
HashMap< Integer, Vertex > vertices = new HashMap<Integer, Vertex>()
Private Member Functions
Geometry concaveHull ()
Create the concave hull.
Static Private Member Functions
static GeometryCollection transformIntoPointGeometryCollection (Geometry geom)
Transform into GeometryCollection.
static GeometryCollection transformIntoPointGeometryCollection (GeometryCollection gc)
Transform into GeometryCollection.
Private Attributes
GeometryFactory geomFactory
GeometryCollection geometries
double threshold
Detailed Description
Computes a concave hull of a Geometry which is a concave Geometry that contains all the points in the input Geometry.
The concave hull is not be defined as unique; here, it is defined according to a threshold which is the maximum length of border edges of the concave hull.
Uses the Duckham and al. (2008) algorithm defined in the paper untitled "Efficient generation of simple polygons for characterizing the shape of a set of points in the plane".
Author
Eric Grosso
Constructor & Destructor Documentation
ConcaveHull() [1/2]
ConcaveHull (Geometry geometry, double threshold)
Create a new concave hull construction for the input Geometry.
Parameters
geometry
threshold
{
         this.geometries = transformIntoPointGeometryCollection(geometry);
         this.threshold = threshold;
         this.geomFactory = geometry.getFactory();
     }
References ConcaveHull.threshold, and ConcaveHull.transformIntoPointGeometryCollection().
ConcaveHull() [2/2]
ConcaveHull (GeometryCollection geometries, double threshold)
Create a new concave hull construction for the input GeometryCollection.
Parameters
geometries
threshold
{
         this.geometries = transformIntoPointGeometryCollection(geometries);
         this.threshold = threshold;
         this.geomFactory = geometries.getFactory();
     }
References ConcaveHull.geometries, ConcaveHull.threshold, and ConcaveHull.transformIntoPointGeometryCollection().
Member Function Documentation
concaveHull()
Geometry concaveHull () private
Create the concave hull.
Returns
the concave hull
{
         // triangulation: create a DelaunayTriangulationBuilder object
         ConformingDelaunayTriangulationBuilder cdtb = new ConformingDelaunayTriangulationBuilder();
         // add geometry collection
         cdtb.setSites(this.geometries);
         QuadEdgeSubdivision qes = cdtb.getSubdivision();
         Collection<QuadEdge> quadEdges = qes.getEdges();
         List<QuadEdgeTriangle> qeTriangles = QuadEdgeTriangle.createOn(qes);
         Collection<org.locationtech.jts.triangulate.quadedge.Vertex> qeVertices
                 = qes.getVertices(false);
         int iV = 0;
         for (org.locationtech.jts.triangulate.quadedge.Vertex v : qeVertices) {
             this.coordinates.put(v.getCoordinate(), iV);
             this.vertices.put(iV, new Vertex(iV, v.getCoordinate()));
             iV++;
         }
         // border
         List<QuadEdge> qeFrameBorder = new ArrayList<QuadEdge>();
         List<QuadEdge> qeFrame = new ArrayList<QuadEdge>();
         List<QuadEdge> qeBorder = new ArrayList<QuadEdge>();
         for (QuadEdge qe : quadEdges) {
             if (qes.isFrameBorderEdge(qe)) {
                 qeFrameBorder.add(qe);
             }
             if (qes.isFrameEdge(qe)) {
                 qeFrame.add(qe);
             }
         }
         // border
         for (int j = 0; j < qeFrameBorder.size(); j++) {
             QuadEdge q = qeFrameBorder.get(j);
             if (!qeFrame.contains(q)) {
                 qeBorder.add(q);
             }
         }
         // deletion of exterior edges
         for (QuadEdge qe : qeFrame) {
             qes.delete(qe);
         }
         HashMap<QuadEdge, Double> qeDistances = new HashMap<QuadEdge, Double>();
         for (QuadEdge qe : quadEdges) {
             qeDistances.put(qe, qe.toLineSegment().getLength());
         }
         DoubleComparator dc = new DoubleComparator(qeDistances);
         TreeMap<QuadEdge, Double> qeSorted = new TreeMap<QuadEdge, Double>(dc);
         qeSorted.putAll(qeDistances);
         // edges creation
         int i = 0;
         for (QuadEdge qe : qeSorted.keySet()) {
             LineSegment s = qe.toLineSegment();
             s.normalize();
             Integer idS = this.coordinates.get(s.p0);
             Integer idD = this.coordinates.get(s.p1);
             Vertex oV = this.vertices.get(idS);
             Vertex eV = this.vertices.get(idD);
             Edge edge;
             if (qeBorder.contains(qe)) {
                 oV.setBorder(true);
                 eV.setBorder(true);
                 edge = new Edge(i, s, oV, eV, true);
                 if (s.getLength() < this.threshold) {
                     this.shortLengths.put(i, edge);
                 } else {
                     this.lengths.put(i, edge);
                 }
             } else {
                 edge = new Edge(i, s, oV, eV, false);
             }
             this.edges.put(i, edge);
             this.segments.put(s, i);
             i++;
         }
         // hm of linesegment and hm of edges // with id as key
         // hm of triangles using hm of ls and connection with hm of edges
         i = 0;
         for (QuadEdgeTriangle qet : qeTriangles) {
             LineSegment sA = qet.getEdge(0).toLineSegment();
             LineSegment sB = qet.getEdge(1).toLineSegment();
             LineSegment sC = qet.getEdge(2).toLineSegment();
             sA.normalize();
             sB.normalize();
             sC.normalize();
             Edge edgeA = this.edges.get(this.segments.get(sA));
             Edge edgeB = this.edges.get(this.segments.get(sB));
             Edge edgeC = this.edges.get(this.segments.get(sC));
             if (edgeA == null || edgeB == null || edgeC == null) {
                 continue;
             }
             Triangle triangle = new Triangle(i, qet.isBorder() ? true : false);
             triangle.addEdge(edgeA);
             triangle.addEdge(edgeB);
             triangle.addEdge(edgeC);
             edgeA.addTriangle(triangle);
             edgeB.addTriangle(triangle);
             edgeC.addTriangle(triangle);
             this.triangles.put(i, triangle);
             i++;
         }
         // add triangle neighbourood
         for (Edge edge : this.edges.values()) {
             if (edge.getTriangles().size() > 1) {
                 Triangle tA = edge.getTriangles().get(0);
                 Triangle tB = edge.getTriangles().get(1);
                 tA.addNeighbour(tB);
                 tB.addNeighbour(tA);
             }
         }
         // concave hull algorithm
         int index = 0;
         while (index != -1) {
             index = -1;
             Edge e = null;
             // find the max length (smallest id so first entry)
             int si = this.lengths.size();
             if (si != 0) {
                 Entry<Integer, Edge> entry = this.lengths.firstEntry();
                 int ind = entry.getKey();
                 if (entry.getValue().getGeometry().getLength() > this.threshold) {
                     index = ind;
                     e = entry.getValue();
                 }
             }
             if (index != -1) {
                 Triangle triangle = e.getTriangles().get(0);
                 List<Triangle> neighbours = triangle.getNeighbours();
                 // irregular triangle test
                 if (neighbours.size() == 1) {
                     this.shortLengths.put(e.getId(), e);
                     this.lengths.remove(e.getId());
                 } else {
                     Edge e0 = triangle.getEdges().get(0);
                     Edge e1 = triangle.getEdges().get(1);
                     // test if all the vertices are on the border
                     if (e0.getOV().isBorder() && e0.getEV().isBorder()
                             && e1.getOV().isBorder() && e1.getEV().isBorder()) {
                         this.shortLengths.put(e.getId(), e);
                         this.lengths.remove(e.getId());
                     } else {
                         // management of triangles
                         if (neighbours.size() < 1) {
                             continue; //not sure this is safe
                         }
                         Triangle tA = neighbours.get(0);
                         Triangle tB = neighbours.get(1);
                         tA.setBorder(true); // FIXME not necessarily useful
                         tB.setBorder(true); // FIXME not necessarily useful
                         this.triangles.remove(triangle.getId());
                         tA.removeNeighbour(triangle);
                         tB.removeNeighbour(triangle);
                         // new edges
                         List<Edge> ee = triangle.getEdges();
                         Edge eA = ee.get(0);
                         Edge eB = ee.get(1);
                         Edge eC = ee.get(2);
                         if (eA.isBorder()) {
                             this.edges.remove(eA.getId());
                             eB.setBorder(true);
                             eB.getOV().setBorder(true);
                             eB.getEV().setBorder(true);
                             eC.setBorder(true);
                             eC.getOV().setBorder(true);
                             eC.getEV().setBorder(true);
                             // clean the relationships with the triangle
                             eB.removeTriangle(triangle);
                             eC.removeTriangle(triangle);
                             if (eB.getGeometry().getLength() < this.threshold) {
                                 this.shortLengths.put(eB.getId(), eB);
                             } else {
                                 this.lengths.put(eB.getId(), eB);
                             }
                             if (eC.getGeometry().getLength() < this.threshold) {
                                 this.shortLengths.put(eC.getId(), eC);
                             } else {
                                 this.lengths.put(eC.getId(), eC);
                             }
                             this.lengths.remove(eA.getId());
                         } else if (eB.isBorder()) {
                             this.edges.remove(eB.getId());
                             eA.setBorder(true);
                             eA.getOV().setBorder(true);
                             eA.getEV().setBorder(true);
                             eC.setBorder(true);
                             eC.getOV().setBorder(true);
                             eC.getEV().setBorder(true);
                             // clean the relationships with the triangle
                             eA.removeTriangle(triangle);
                             eC.removeTriangle(triangle);
                             if (eA.getGeometry().getLength() < this.threshold) {
                                 this.shortLengths.put(eA.getId(), eA);
                             } else {
                                 this.lengths.put(eA.getId(), eA);
                             }
                             if (eC.getGeometry().getLength() < this.threshold) {
                                 this.shortLengths.put(eC.getId(), eC);
                             } else {
                                 this.lengths.put(eC.getId(), eC);
                             }
                             this.lengths.remove(eB.getId());
                         } else {
                             this.edges.remove(eC.getId());
                             eA.setBorder(true);
                             eA.getOV().setBorder(true);
                             eA.getEV().setBorder(true);
                             eB.setBorder(true);
                             eB.getOV().setBorder(true);
                             eB.getEV().setBorder(true);
                             // clean the relationships with the triangle
                             eA.removeTriangle(triangle);
                             eB.removeTriangle(triangle);
                             if (eA.getGeometry().getLength() < this.threshold) {
                                 this.shortLengths.put(eA.getId(), eA);
                             } else {
                                 this.lengths.put(eA.getId(), eA);
                             }
                             if (eB.getGeometry().getLength() < this.threshold) {
                                 this.shortLengths.put(eB.getId(), eB);
                             } else {
                                 this.lengths.put(eB.getId(), eB);
                             }
                             this.lengths.remove(eC.getId());
                         }
                     }
                 }
             }
         }
         // concave hull creation
         List<LineString> edges = new ArrayList<LineString>();
         for (Edge e : this.lengths.values()) {
             LineString l = e.getGeometry().toGeometry(this.geomFactory);
             edges.add(l);
         }
         for (Edge e : this.shortLengths.values()) {
             LineString l = e.getGeometry().toGeometry(this.geomFactory);
             edges.add(l);
         }
         // merge
         LineMerger lineMerger = new LineMerger();
         lineMerger.add(edges);
         LineString merge = (LineString) lineMerger.getMergedLineStrings().iterator().next();
         if (merge.isRing()) {
             LinearRing lr = new LinearRing(merge.getCoordinateSequence(), this.geomFactory);
             Polygon concaveHull = new Polygon(lr, null, this.geomFactory);
             return concaveHull;
         }
         return merge;
     }
References Triangle.addEdge(), Triangle.addNeighbour(), Edge.addTriangle(), ConcaveHull.edges, Triangle.getEdges(), Edge.getEV(), Edge.getGeometry(), Edge.getId(), Triangle.getId(), Triangle.getNeighbours(), Edge.getOV(), Edge.getTriangles(), Edge.isBorder(), Vertex.isBorder(), Triangle.removeNeighbour(), Edge.removeTriangle(), Edge.setBorder(), Triangle.setBorder(), and Vertex.setBorder().
Referenced by ConcaveHull.getConcaveHull().
getConcaveHull()
Geometry getConcaveHull ()
Returns a Geometry that represents the concave hull of the input geometry according to the threshold.
The returned geometry contains the minimal number of points needed to represent the concave hull.
Returns
if the concave hull contains 3 or more points, a Polygon; 2 points, a LineString; 1 point, a Point; 0 points, an empty GeometryCollection.
{
         if (this.geometries.getNumGeometries() == 0) {
             return this.geomFactory.createGeometryCollection(null);
         }
         if (this.geometries.getNumGeometries() == 1) {
             return this.geometries.getGeometryN(0);
         }
         if (this.geometries.getNumGeometries() == 2) {
             return this.geomFactory.createLineString(this.geometries.getCoordinates());
         }
         return concaveHull();
     }
References ConcaveHull.concaveHull().
transformIntoPointGeometryCollection() [1/2]
static GeometryCollection transformIntoPointGeometryCollection (Geometry geom) static private
Transform into GeometryCollection.
Parameters
geom input geometry
Returns
a geometry collection
{
         UniqueCoordinateArrayFilter filter = new UniqueCoordinateArrayFilter();
         geom.apply(filter);
         Coordinate[] coord = filter.getCoordinates();
         Geometry[] geometries = new Geometry[coord.length];
         for (int i = 0; i < coord.length; i++) {
             Coordinate[] c = new Coordinate[]{coord[i]};
             CoordinateArraySequence cs = new CoordinateArraySequence(c);
             geometries[i] = new Point(cs, geom.getFactory());
         }
         return new GeometryCollection(geometries, geom.getFactory());
     }
References ConcaveHull.geometries.
Referenced by ConcaveHull.ConcaveHull().
transformIntoPointGeometryCollection() [2/2]
static GeometryCollection transformIntoPointGeometryCollection (GeometryCollection gc) static private
Transform into GeometryCollection.
Parameters
geom input geometry
Returns
a geometry collection
{
         UniqueCoordinateArrayFilter filter = new UniqueCoordinateArrayFilter();
         gc.apply(filter);
         Coordinate[] coord = filter.getCoordinates();
         Geometry[] geometries = new Geometry[coord.length];
         for (int i = 0; i < coord.length; i++) {
             Coordinate[] c = new Coordinate[]{coord[i]};
             CoordinateArraySequence cs = new CoordinateArraySequence(c);
             geometries[i] = new Point(cs, gc.getFactory());
         }
         return new GeometryCollection(geometries, gc.getFactory());
     }
References ConcaveHull.geometries.
Member Data Documentation
coordinates
HashMap<Coordinate, Integer> coordinates = new HashMap<Coordinate, Integer>()
edges
HashMap<Integer, Edge> edges = new HashMap<Integer, Edge>()
Referenced by ConcaveHull.concaveHull().
geometries
GeometryCollection geometries private
Referenced by ConcaveHull.ConcaveHull(), and ConcaveHull.transformIntoPointGeometryCollection().
geomFactory
GeometryFactory geomFactory private
lengths
TreeMap<Integer, Edge> lengths = new TreeMap<Integer, Edge>()
segments
HashMap<LineSegment, Integer> segments = new HashMap<LineSegment, Integer>()
shortLengths
HashMap<Integer, Edge> shortLengths = new HashMap<Integer, Edge>()
threshold
double threshold private
Referenced by ConcaveHull.ConcaveHull().
triangles
HashMap<Integer, Triangle> triangles = new HashMap<Integer, Triangle>()
vertices
HashMap<Integer, Vertex> vertices = new HashMap<Integer, Vertex>()