GeoSPARQL SRS Extension: WKBRasterImageWriter Class Reference
WKBRasterImageWriter Class Reference
Classes
class Spi
Public Member Functions
WKBRasterImageWriter (ImageWriterSpi spi)
IIOMetadata getDefaultStreamMetadata (ImageWriteParam param)
IIOMetadata getDefaultImageMetadata (ImageTypeSpecifier imageType, ImageWriteParam param)
IIOMetadata convertStreamMetadata (IIOMetadata inData, ImageWriteParam param)
IIOMetadata convertImageMetadata (IIOMetadata inData, ImageTypeSpecifier imageType, ImageWriteParam param)
boolean canWriteRasters ()
void write (IIOImage image) throws IOException
void write (IIOMetadata streamMetadata, IIOImage image, ImageWriteParam param) throws IOException
Detailed Description
Author
Johann Sorel (Geomatys)
Constructor & Destructor Documentation
WKBRasterImageWriter()
WKBRasterImageWriter (ImageWriterSpi spi)
{
         super(spi);
     }
Referenced by WKBRasterImageWriter.Spi.createWriterInstance().
Member Function Documentation
canWriteRasters()
boolean canWriteRasters ()
{
         return true;
     }
convertImageMetadata()
IIOMetadata convertImageMetadata (IIOMetadata inData, ImageTypeSpecifier imageType, ImageWriteParam param)
{
         return null;//new SpatialMetadata(false, this, null);
     }
convertStreamMetadata()
IIOMetadata convertStreamMetadata (IIOMetadata inData, ImageWriteParam param)
{
         return null;//new SpatialMetadata(true, this, null);
     }
getDefaultImageMetadata()
IIOMetadata getDefaultImageMetadata (ImageTypeSpecifier imageType, ImageWriteParam param)
{
        return null;//new SpatialMetadata(false, this, null);
     }
getDefaultStreamMetadata()
IIOMetadata getDefaultStreamMetadata (ImageWriteParam param)
{
         return null;//new SpatialMetadata(true, this, null);
     }
write() [1/2]
void write (IIOImage image) throws IOException
{
         final Raster ri = image.getRaster();
         final WKBRasterWriter writer = new WKBRasterWriter();
         final Object out = getOutput();
         if(out instanceof ImageOutputStream){
             final ImageOutputStream stream = (ImageOutputStream) out;
             final byte[] data = writer.write(ri, new AffineTransform(), 0);
             stream.write(data);
         }else{
             final OutputStream stream = IOUtilities.toOutputStream((AutoCloseable) getOutput());
             writer.write(ri, new AffineTransform(), 0, stream);
             stream.flush();
             stream.close();
         }
     }
References WKBRasterWriter.write().
write() [2/2]
void write (IIOMetadata streamMetadata, IIOImage image, ImageWriteParam param) throws IOException
{
         final RenderedImage ri = image.getRenderedImage();
         final WKBRasterWriter writer = new WKBRasterWriter();
         final Object out = getOutput();
         if(out instanceof ImageOutputStream){
             final ImageOutputStream stream = (ImageOutputStream) out;
             final byte[] data = writer.write(ri, new AffineTransform(), 0);
             stream.write(data);
         }else{
             final OutputStream stream = IOUtilities.toOutputStream((AutoCloseable) getOutput());
             writer.write(ri, new AffineTransform(), 0, stream);
             stream.flush();
             stream.close();
         }
     }
References WKBRasterWriter.write().