GeoSPARQL SRS Extension: LengthToPoint Class Reference
LengthToPoint Class Reference
Computes the length along a LineString to the point on the line nearest a given point.
Public Member Functions
LengthToPoint (LineString line, Coordinate inputPt)
double getLength ()
Static Public Member Functions
static double lengthAlongSegment (LineSegment seg, Coordinate pt)
static double length (LineString line, Coordinate inputPt)
Computes the length along a LineString to the point on the line nearest a given point.
Private Member Functions
void computeLength (LineString line, Coordinate inputPt)
void updateLength (LineSegment seg, Coordinate inputPt, double segStartLocationDistance)
Private Attributes
double minDistanceToPoint
double locationLength
Detailed Description
Computes the length along a LineString to the point on the line nearest a given point.
Constructor & Destructor Documentation
LengthToPoint()
LengthToPoint (LineString line, Coordinate inputPt)
   {
     computeLength(line, inputPt);
   }
References LengthToPoint.computeLength().
Referenced by LengthToPoint.length().
Member Function Documentation
computeLength()
void computeLength (LineString line, Coordinate inputPt) private
   {
     minDistanceToPoint = Double.MAX_VALUE;
     double baseLocationDistance = 0.0;
     Coordinate[] pts = line.getCoordinates();
     LineSegment seg = new LineSegment();
     for (int i = 0; i < pts.length - 1; i++) {
       seg.p0 = pts[i];
       seg.p1 = pts[i + 1];
       updateLength(seg, inputPt, baseLocationDistance);
       baseLocationDistance += seg.getLength();
     }
   }
References LengthToPoint.minDistanceToPoint, and LengthToPoint.updateLength().
Referenced by LengthToPoint.LengthToPoint().
getLength()
double getLength ()
   {
     return locationLength;
   }
References LengthToPoint.locationLength.
Referenced by LengthToPoint.length().
length()
static double length (LineString line, Coordinate inputPt) static
Computes the length along a LineString to the point on the line nearest a given point.
   {
     LengthToPoint lp = new LengthToPoint(line, inputPt);
     return lp.getLength();
   }
References LengthToPoint.getLength(), and LengthToPoint.LengthToPoint().
lengthAlongSegment()
static double lengthAlongSegment (LineSegment seg, Coordinate pt) static
   {
     double projFactor = seg.projectionFactor(pt);
     double len = 0.0;
     if (projFactor <= 0.0)
       len = 0.0;
     else if (projFactor <= 1.0)
       len = projFactor * seg.getLength();
     else
       len = seg.getLength();
     return len;
   }
updateLength()
void updateLength (LineSegment seg, Coordinate inputPt, double segStartLocationDistance) private
   {
     double dist = seg.distance(inputPt);
     if (dist > minDistanceToPoint) return;
     minDistanceToPoint = dist;
     // found new minimum, so compute location distance of point
     double projFactor = seg.projectionFactor(inputPt);
     if (projFactor <= 0.0)
       locationLength = segStartLocationDistance;
     else if (projFactor <= 1.0)
       locationLength = segStartLocationDistance + projFactor * seg.getLength();
     else
       locationLength = segStartLocationDistance + seg.getLength();
   }
References LengthToPoint.locationLength, and LengthToPoint.minDistanceToPoint.
Referenced by LengthToPoint.computeLength().
Member Data Documentation
locationLength
double locationLength private
Referenced by LengthToPoint.getLength(), and LengthToPoint.updateLength().
minDistanceToPoint
double minDistanceToPoint private
Referenced by LengthToPoint.computeLength(), and LengthToPoint.updateLength().