GeoSPARQL SRS Extension: Edge Class Reference
Edge Class Reference
Edge.
Public Member Functions
Edge ()
Default constructor.
Edge (int id)
Constructor.
Edge (int id, LineSegment geometry)
Constructor.
Edge (int id, boolean border)
Constructor.
Edge (int id, LineSegment geometry, boolean border)
Constructor.
Edge (int id, LineSegment geometry, Vertex oV, Vertex eV, boolean border)
Constructor.
int getId ()
Returns the ID of the edge.
void setId (int id)
Defines the ID of the edge.
LineSegment getGeometry ()
Returns the geometry of the edge.
void setGeometry (LineSegment geometry)
Defines the geometry of the edge.
boolean isBorder ()
Returns true if the edge is a border edge of the triangulation framework, false otherwise.
void setBorder (boolean border)
Defines the indicator to know if the edge is a border edge of the triangulation framework.
Vertex getOV ()
Returns the origin vertex of the edge.
void setOV (Vertex oV)
Defines the origin vertex of the edge.
Vertex getEV ()
Returns the end vertex of the edge.
void setEV (Vertex eV)
Defines the end vertex of the edge.
List< Triangle > getTriangles ()
Returns the triangles in relationship with the edge.
void setTriangles (List< Triangle > triangles)
Defines the triangles in relationship with the edge.
List< Edge > getIncidentEdges ()
Returns the edges in relationship with the edge.
void setIncidentEdges (List< Edge > edges)
Defines the edges in relationship with the edge.
boolean addTriangle (Triangle triangle)
Add a triangle in relationship with the edge.
boolean addTriangles (List< Triangle > triangles)
Add triangles in relationship with the edge.
boolean removeTriangle (Triangle triangle)
Remove a triangle in relationship with the edge.
boolean removeTriangles (List< Triangle > triangles)
Remove triangles in relationship with the edge.
boolean addIncidentEdge (Edge edge)
Add an incident edge in relationship with the edge.
boolean addIncidentEdges (List< Edge > edges)
Add incident edges in relationship with the edge.
boolean removeIncidentEdge (Edge edge)
Remove an incident edge in relationship with the edge.
boolean removeAllIncidentEdges (List< Edge > edges)
Remove incident edges in relationship with the edge.
Private Attributes
int id
ID of the edge.
LineSegment geometry
Geometry of the edge.
boolean border
Indicator to know if the edge is a border edge of the triangulation framework.
Vertex oV
Origin vertex of the edge.
Vertex eV
End vertex of the edge.
List< Triangle > triangles = new ArrayList<Triangle>()
Triangles in relationship with this edge.
List< Edge > incidentEdges = new ArrayList<Edge>()
Edges in relationship with this edge.
Detailed Description
Edge.
Author
Eric Grosso
Constructor & Destructor Documentation
Edge() [1/6]
Edge ()
Default constructor.
                   {
         //
     }
Edge() [2/6]
Edge (int id)
Constructor.
Parameters
id ID of the edge
{
         this.id = id;
     }
References Edge.id.
Edge() [3/6]
Edge (int id, LineSegment geometry)
Constructor.
Parameters
id ID of the edge
geometry geometry of the edge (segment)
{
         this.id = id;
         this.geometry = geometry;
     }
References Edge.geometry, and Edge.id.
Edge() [4/6]
Edge (int id, boolean border)
Constructor.
Parameters
id ID of the edge
border defines if the edge is a border edge or not in the triangulation framework
{
         this.id = id;
         this.border = border;
     }
References Edge.border, and Edge.id.
Edge() [5/6]
Edge (int id, LineSegment geometry, boolean border)
Constructor.
Parameters
id ID of the edge
geometry geometry of the edge (segment)
border defines if the edge is a border edge or not in the triangulation framework
{
         this.id = id;
         this.geometry = geometry;
         this.border = border;
     }
References Edge.border, Edge.geometry, and Edge.id.
Edge() [6/6]
Edge (int id, LineSegment geometry, Vertex oV, Vertex eV, boolean border)
Constructor.
Parameters
id ID of the edge
geometry geometry of the edge (segment)
oV origin vertex
eV end vertex
border defines if the edge is a border edge or not in the triangulation framework
{
         this.id = id;
         this.geometry = geometry;
         this.oV = oV;
         this.eV = eV;
         this.border = border;
     }
References Edge.border, Edge.eV, Edge.geometry, Edge.id, and Edge.oV.
Member Function Documentation
addIncidentEdge()
boolean addIncidentEdge (Edge edge)
Add an incident edge in relationship with the edge.
Returns
true if added, false otherwise
{
         return getIncidentEdges().add(edge);
     }
References Edge.getIncidentEdges().
addIncidentEdges()
boolean addIncidentEdges (List< Edge > edges)
Add incident edges in relationship with the edge.
Returns
true if added, false otherwise
{
         return getIncidentEdges().addAll(edges);
     }
References Edge.getIncidentEdges().
addTriangle()
boolean addTriangle (Triangle triangle)
Add a triangle in relationship with the edge.
Returns
true if added, false otherwise
{
         return getTriangles().add(triangle);
     }
References Edge.getTriangles().
Referenced by ConcaveHull.concaveHull().
addTriangles()
boolean addTriangles (List< Triangle > triangles)
Add triangles in relationship with the edge.
Returns
true if added, false otherwise
{
         return getTriangles().addAll(triangles);
     }
References Edge.getTriangles(), and Edge.triangles.
getEV()
Vertex getEV ()
Returns the end vertex of the edge.
Returns
the end vertex of the edge
{
         return this.eV;
     }
References Edge.eV.
Referenced by ConcaveHull.concaveHull().
getGeometry()
LineSegment getGeometry ()
Returns the geometry of the edge.
Returns
the geometry of the edge
{
         return this.geometry;
     }
References Edge.geometry.
Referenced by ConcaveHull.concaveHull().
getId()
int getId ()
Returns the ID of the edge.
Returns
the ID of the edge
{
         return this.id;
     }
References Edge.id.
Referenced by ConcaveHull.concaveHull().
getIncidentEdges()
List<Edge> getIncidentEdges ()
Returns the edges in relationship with the edge.
Returns
the edges in relationship with the edge
{
         return this.incidentEdges;
     }
References Edge.incidentEdges.
Referenced by Edge.addIncidentEdge(), Edge.addIncidentEdges(), Edge.removeAllIncidentEdges(), and Edge.removeIncidentEdge().
getOV()
Vertex getOV ()
Returns the origin vertex of the edge.
Returns
the origin vertex of the edge
{
         return this.oV;
     }
References Edge.oV.
Referenced by ConcaveHull.concaveHull().
getTriangles()
List<Triangle> getTriangles ()
Returns the triangles in relationship with the edge.
Returns
the triangles in relationship with the edge
{
         return this.triangles;
     }
References Edge.triangles.
Referenced by Edge.addTriangle(), Edge.addTriangles(), ConcaveHull.concaveHull(), Edge.removeTriangle(), and Edge.removeTriangles().
isBorder()
boolean isBorder ()
Returns true if the edge is a border edge of the triangulation framework, false otherwise.
Returns
true if the edge is a border edge, false otherwise
{
         return this.border;
     }
References Edge.border.
Referenced by ConcaveHull.concaveHull().
removeAllIncidentEdges()
boolean removeAllIncidentEdges (List< Edge > edges)
Remove incident edges in relationship with the edge.
Returns
true if removed, false otherwise
{
         return getIncidentEdges().removeAll(edges);
     }
References Edge.getIncidentEdges().
removeIncidentEdge()
boolean removeIncidentEdge (Edge edge)
Remove an incident edge in relationship with the edge.
Returns
true if removed, false otherwise
{
         return getIncidentEdges().remove(edge);
     }
References Edge.getIncidentEdges().
removeTriangle()
boolean removeTriangle (Triangle triangle)
Remove a triangle in relationship with the edge.
Returns
true if removed, false otherwise
{
         return getTriangles().remove(triangle);
     }
References Edge.getTriangles().
Referenced by ConcaveHull.concaveHull().
removeTriangles()
boolean removeTriangles (List< Triangle > triangles)
Remove triangles in relationship with the edge.
Returns
true if removed, false otherwise
{
         return getTriangles().removeAll(triangles);
     }
References Edge.getTriangles(), and Edge.triangles.
setBorder()
void setBorder (boolean border)
Defines the indicator to know if the edge is a border edge of the triangulation framework.
Parameters
border true if the edge is a border edge, false otherwise
{
         this.border = border;
     }
References Edge.border.
Referenced by ConcaveHull.concaveHull().
setEV()
void setEV (Vertex eV)
Defines the end vertex of the edge.
Parameters
eV end vertex of the edge
{
         this.eV = eV;
     }
References Edge.eV.
setGeometry()
void setGeometry (LineSegment geometry)
Defines the geometry of the edge.
Parameters
geometry geometry of the edge (segment)
{
         this.geometry = geometry;
     }
References Edge.geometry.
setId()
void setId (int id)
Defines the ID of the edge.
Parameters
id ID of the edge
{
         this.id = id;
     }
References Edge.id.
setIncidentEdges()
void setIncidentEdges (List< Edge > edges)
Defines the edges in relationship with the edge.
Parameters
edges the edges in relationship with the edge
{
         this.incidentEdges = edges;
     }
setOV()
void setOV (Vertex oV)
Defines the origin vertex of the edge.
Parameters
oV origin vertex of the edge
{
         this.oV = oV;
     }
References Edge.oV.
setTriangles()
void setTriangles (List< Triangle > triangles)
Defines the triangles in relationship with the edge.
Parameters
triangles the triangles in relationship with the edge
{
         this.triangles = triangles;
     }
References Edge.triangles.
Member Data Documentation
border
boolean border private
Indicator to know if the edge is a border edge of the triangulation framework.
Referenced by Edge.Edge(), Edge.isBorder(), and Edge.setBorder().
eV
Vertex eV private
End vertex of the edge.
Referenced by Edge.Edge(), Edge.getEV(), and Edge.setEV().
geometry
LineSegment geometry private
Geometry of the edge.
Referenced by Edge.Edge(), Edge.getGeometry(), and Edge.setGeometry().
id
int id private
ID of the edge.
Referenced by Edge.Edge(), Edge.getId(), and Edge.setId().
incidentEdges
List<Edge> incidentEdges = new ArrayList<Edge>() private
Edges in relationship with this edge.
Referenced by Edge.getIncidentEdges().
oV
Vertex oV private
Origin vertex of the edge.
Referenced by Edge.Edge(), Edge.getOV(), and Edge.setOV().
triangles
List<Triangle> triangles = new ArrayList<Triangle>() private
Triangles in relationship with this edge.
Referenced by Edge.addTriangles(), Edge.getTriangles(), Edge.removeTriangles(), and Edge.setTriangles().