GeoSPARQL SRS Extension: WKBRasterReader Class Reference
WKBRasterReader Class Reference
WKB Raster Reader, used in postGIS 2 but can be used elsewhere.
Public Member Functions
WKBRasterReader ()
void reset ()
Reset values before new read call.
AffineTransform2D getGridToCRS ()
Get the Grid to CRS transform, can be called after read only.
int getSRID ()
Get the postgis srid, can be called after read only.
GridCoverage readCoverage (byte[] data, CRSAuthorityFactory authorityFactory) throws IOException, NoSuchAuthorityCodeException, FactoryException
Parse given byte[] and rebuild a GridCoverage2D.
GridCoverage readCoverage (final InputStream stream, CRSAuthorityFactory authorityFactory) throws IOException, NoSuchAuthorityCodeException, FactoryException
Parse given InputStream and rebuild a GridCoverage2D.
BufferedImage read (byte[] data) throws IOException
Parse given byte[] and rebuild RenderedImage.
BufferedImage read (final InputStream stream) throws IOException
Parse given InputStream and rebuild RenderedImage.
Private Attributes
AffineTransform2D gridToCRS = null
int srid = 0
Detailed Description
WKB Raster Reader, used in postGIS 2 but can be used elsewhere.
Author
Johann Sorel (Geomatys)
Constructor & Destructor Documentation
WKBRasterReader()
WKBRasterReader ()
{
     }
Member Function Documentation
getGridToCRS()
AffineTransform2D getGridToCRS ()
Get the Grid to CRS transform, can be called after read only.
Returns
AffineTransform2D
{
         return gridToCRS;
     }
References WKBRasterReader.gridToCRS.
Referenced by WKBRasterReader.readCoverage().
getSRID()
int getSRID ()
Get the postgis srid, can be called after read only.
Returns
int, postgid srid
{
         return srid;
     }
References WKBRasterReader.srid.
read() [1/2]
BufferedImage read (byte[] data) throws IOException
Parse given byte[] and rebuild RenderedImage.
Parameters
data
Returns
Exceptions
IOException
{
         final InputStream stream = new ByteArrayInputStream(data);
         return read(stream);
     }
Referenced by WKBRasterImageReader.read(), and WKBRasterReader.readCoverage().
read() [2/2]
BufferedImage read (final InputStream stream) throws IOException
Parse given InputStream and rebuild RenderedImage.
Parameters
stream
Returns
Exceptions
IOException
{
         final DataInput ds;
         final boolean littleEndian = stream.read() == 1;
         if(littleEndian){
             //big endian
             ds = new LEDataInputStream(stream);
         }else{
             //little endian
             ds = new DataInputStream(stream);
         }
         final int version = ds.readUnsignedShort();
         final int nbBand = ds.readUnsignedShort();
         //grid to crs
         final double scaleX = ds.readDouble();
         final double scaleY = ds.readDouble();
         final double ipX = ds.readDouble();
         final double ipY = ds.readDouble();
         final double skewX = ds.readDouble();
         final double skewY = ds.readDouble();
         gridToCRS = new AffineTransform2D(scaleX, skewY, skewX, scaleY, ipX, ipY);
         srid = ds.readInt();
         final int width = ds.readUnsignedShort();
         final int height = ds.readUnsignedShort();
         if(nbBand == 0){
             //possible for empty raster
             return null;
         }
         final WKBRasterBand[] bands = new WKBRasterBand[nbBand];
         for(int i=0;i<nbBand;i++){
             final WKBRasterBand band = new WKBRasterBand();
             final byte b = ds.readByte();
             band.setPixelType(b & BANDTYPE_PIXTYPE_MASK);
             band.setOffDatabase( (b & BANDTYPE_FLAG_OFFDB) != 0);
             band.setHasNodata( (b & BANDTYPE_FLAG_HASNODATA) != 0);
             band.setIsNodata( (b & BANDTYPE_FLAG_ISNODATA) != 0);
             band.setReserved( (b & BANDTYPE_FLAG_RESERVED3) != 0);
             /* read nodata value */
             switch (band.getPixelType()) {
                 case PT_1BB:
                 case PT_2BUI:
                 case PT_4BUI:
                 case PT_8BUI:
                     band.setNoDataValue(ds.readUnsignedByte());
                     break;
                 case PT_8BSI:
                     band.setNoDataValue(ds.readByte());
                     break;
                 case PT_16BSI:
                     band.setNoDataValue(ds.readShort());
                     break;
                 case PT_16BUI:
                     band.setNoDataValue(ds.readUnsignedShort());
                     break;
                 case PT_32BSI:
                     band.setNoDataValue(ds.readInt());
                     break;
                 case PT_32BUI:
                     band.setNoDataValue(ds.readInt() & 0x00000000ffffffffL);
                     break;
                 case PT_32BF:
                     band.setNoDataValue(ds.readFloat());
                     break;
                 case PT_64BF:
                     band.setNoDataValue(ds.readDouble());
                     break;
                 default:
                     throw new IOException("unknowned pixel type : "+band.getPixelType());
             }
             if(band.isOffDatabase()){
                 throw new IOException("can not access data which are off database");
             }else{
                 //read values
                 final int nbBytePerPixel = band.getNbBytePerPixel();
                 final byte[] datas = new byte[width*height*band.getNbBytePerPixel()];
                 ds.readFully(datas);
                 if(littleEndian && nbBytePerPixel > 1){
                     //image databank expect values in big endian so we must flip bytes
                     byte temp;
                     for(int k=0;k<datas.length;k+=nbBytePerPixel){
                         for(int p=0,n=nbBytePerPixel/2; p<n ;p++){
                             final int index1 = k+p;
                             final int index2 = k+(nbBytePerPixel-p-1);
                             temp = datas[index1];
                             datas[index1] = datas[index2];
                             datas[index2] = temp;
                         }
                     }
                 }
                 band.setDatas(datas);
             }
             bands[i] = band;
         }
         //we expect all bands to have the same type
         final int dataBufferType = bands[0].getDataBufferType();
         //rebuild raster
         final WritableRaster raster;
         double min = Double.MAX_VALUE;
         double max = Double.MIN_VALUE;
         if(dataBufferType == DataBuffer.TYPE_BYTE){
             //more efficient but only works for byte type bands
             //check all band have the same sample model and rebuild data buffer
             Integer dataType = null;
             final byte[][] dataArray = new byte[nbBand][0];
             final int[] bankIndices = new int[nbBand];
             final int[] bankOffsets = new int[nbBand];
             for(int i=0;i<bands.length;i++){
                 final WKBRasterBand band = bands[i];
                 if(dataType == null){
                     dataType = band.getDataBufferType();
                 }else if(dataType != band.getDataBufferType()){
                     throw new IOException("Band type differ, can not be mapped to java image.");
                 }
                 dataArray[i] = band.getDatas();
                 bankIndices[i] = i;
                 bankOffsets[i] = 0;
             }
             min = -100.0;
             max = 100.0;
             //rebuild data buffer
             final DataBuffer db = new DataBufferByte(dataArray, dataArray[0].length);
             final int scanlineStride = width;
             raster = RasterFactory.createBandedRaster(
                     db, width, height, scanlineStride, bankIndices, bankOffsets, new Point(0,0));
         }else{
             raster = RasterFactory.createBandedRaster(dataBufferType,width,height,nbBand,new Point(0,0));
             for(int i=0;i<bands.length;i++){
                 final byte[] datas = bands[i].getDatas();
                 final DataInputStream dds = new DataInputStream(new ByteArrayInputStream(datas));
                 for(int y=0;y<height;y++){
                     for(int x=0;x<width;x++){
                         switch (dataBufferType) {
                             case DataBuffer.TYPE_SHORT:
                                 short d1 = dds.readShort();
                                 raster.setSample(x, y, i, d1);
                                 min = Math.min(min, (double)d1);
                                 max = Math.max(max, (double)d1);
                                 break;
                             case DataBuffer.TYPE_USHORT:
                                 int d2 = dds.readUnsignedShort();
                                 raster.setSample(x, y, i, d2);
                                 min = Math.min(min, (double)d2);
                                 max = Math.max(max, (double)d2);
                                 break;
                             case DataBuffer.TYPE_INT:
                                 int d3 = dds.readInt();
                                 raster.setSample(x, y, i, d3);
                                 min = Math.min(min, (double)d3);
                                 max = Math.max(max, (double)d3);
                                 break;
                             case DataBuffer.TYPE_FLOAT:
                                 float d4 = dds.readFloat();
                                 raster.setSample(x, y, i, d4);
                                 min = Math.min(min, (double)d4);
                                 max = Math.max(max, (double)d4);
                                 break;
                             case DataBuffer.TYPE_DOUBLE:
                                 double d5 = dds.readDouble();
                                 raster.setSample(x, y, i, d5);
                                 min = Math.min(min, d5);
                                 max = Math.max(max, d5);
                                 break;
                             default:
                                 throw new IllegalArgumentException("unknowned data buffer type : " + dataBufferType);
                         }
                     }
                 }
             }
         }
         //rebuild image
         final SampleModel sm = raster.getSampleModel();
         ColorModel cm = PlanarImage.getDefaultColorModel(sm.getDataType(), raster.getNumBands());
         if(cm==null){
             //fallback
             cm = (ColorModel) ColorModelFactory.GRAYSCALE;  //createGrayScale(sm.getDataType(), raster.getNumBands(), 0, min, max);
         }
         return new BufferedImage(cm, raster, false, null);
     }
References WKBRasterBand.getDataBufferType(), WKBRasterBand.getDatas(), WKBRasterBand.getNbBytePerPixel(), WKBRasterBand.getPixelType(), WKBRasterReader.gridToCRS, WKBRasterBand.isOffDatabase(), WKBRasterBand.setDatas(), WKBRasterBand.setHasNodata(), WKBRasterBand.setIsNodata(), WKBRasterBand.setNoDataValue(), WKBRasterBand.setOffDatabase(), WKBRasterBand.setPixelType(), WKBRasterBand.setReserved(), and WKBRasterReader.srid.
readCoverage() [1/2]
GridCoverage readCoverage (byte[] data, CRSAuthorityFactory authorityFactory) throws IOException, NoSuchAuthorityCodeException, FactoryException
Parse given byte[] and rebuild a GridCoverage2D.
Parameters
data
Returns
Exceptions
IOException
{
         final InputStream stream = new ByteArrayInputStream(data);
         return readCoverage(stream,authorityFactory);
     }
Referenced by WKBRastDatatype.read().
readCoverage() [2/2]
GridCoverage readCoverage (final InputStream stream, CRSAuthorityFactory authorityFactory) throws IOException, NoSuchAuthorityCodeException, FactoryException
Parse given InputStream and rebuild a GridCoverage2D.
Parameters
stream
Returns
Exceptions
IOException
{
         final BufferedImage image = read(stream);
         final String epsgCode = "EPSG:"+srid;
         final CoordinateReferenceSystem crs;
         if (authorityFactory != null) {
             crs = authorityFactory.createCoordinateReferenceSystem(epsgCode);
         } else {
             crs = CRS.forCode(epsgCode);
         }
         GridExtent extent=new GridExtent(image.getWidth(), image.getHeight());
         GridGeometry gridgeom=new GridGeometry(extent, PixelInCell.CELL_CENTER, getGridToCRS(), crs);
         List<SampleDimension> dimensions=new LinkedList<SampleDimension>();
         DefaultNameFactory fac=new DefaultNameFactory();
         for(int i=0;i<image.getRaster().getNumBands();i++) {
                 dimensions.add(new SampleDimension(fac.createGenericName(null,  "Dimension "+i),0.,new LinkedList<Category>()));
         }
         BufferedGridCoverage cov=new BufferedGridCoverage(
                         gridgeom, dimensions, image.getData().getDataBuffer());
         return cov;
     }
References WKBRasterReader.getGridToCRS(), WKBRasterReader.read(), and WKBRasterReader.srid.
reset()
void reset ()
Reset values before new read call.
{
         gridToCRS = null;
         srid = 0;
     }
References WKBRasterReader.gridToCRS, and WKBRasterReader.srid.
Member Data Documentation
gridToCRS
AffineTransform2D gridToCRS = null private
Referenced by WKBRasterReader.getGridToCRS(), WKBRasterReader.read(), and WKBRasterReader.reset().
srid
int srid = 0 private
Referenced by WKBRasterReader.getSRID(), WKBRasterReader.read(), WKBRasterReader.readCoverage(), and WKBRasterReader.reset().