GeoSPARQL SRS Extension: ConversionOperation Class Reference
ConversionOperation Class Reference
Public Member Functions
String toProj ()
JSONObject toProjJSON ()
String toGML ()
String toWKT ()
Public Attributes
String methodName
String projectionName
Map< String, String > parameters =new TreeMap<String,String>()
String scope
Member Function Documentation
toGML()
String toGML ()
{
                 XMLOutputFactory factory = XMLOutputFactory.newInstance();
                 StringWriter strwriter=new StringWriter();
                 XMLStreamWriter writer;
                 try {
                         writer = new IndentingXMLStreamWriter(factory.createXMLStreamWriter(strwriter));
                         writer.writeStartElement("gml:Conversion");
                         for(String key:parameters.keySet()) {
                                 writer.writeStartElement("gml:usesParameterValue");
                                 writer.writeStartElement("gml:value");
                                 writer.writeCharacters(parameters.get(key));
                                 writer.writeEndElement();
                                 writer.writeEndElement();
                         }
                         writer.writeEndElement();
                         writer.flush();
                 } catch (XMLStreamException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 }
                 return strwriter.toString();
         }
References ConversionOperation.parameters.
Referenced by CoordinateReferenceSystem.toGML().
toProj()
String toProj ()
{
                 StringBuilder builder=new StringBuilder();
                 return builder.toString();
         }
toProjJSON()
JSONObject toProjJSON ()
{
                 JSONObject cs=new JSONObject();
                 return cs;
         }
toWKT()
String toWKT ()
{
                 StringBuilder builder=new StringBuilder();
                 if(projectionName==null && methodName==null) {
                         return builder.toString();
                 }
                 builder.append("CONVERSION[\""+projectionName+"\",METHOD[\""+methodName+"\","+System.lineSeparator());
                 for(String para:parameters.keySet()) {
                         builder.append("PARAMETER[\""+para+"\","+parameters.get(para)+"],");
                 }
                 builder.delete(builder.length()-1, builder.length());
                 builder.append("]]"+System.lineSeparator());
                 return builder.toString();
         }
References ConversionOperation.methodName, ConversionOperation.parameters, and ConversionOperation.projectionName.
Referenced by CoordinateReferenceSystem.toWKT().
Member Data Documentation
methodName
String methodName
Referenced by RDFCRSToWKT.downliftSystem(), and ConversionOperation.toWKT().
parameters
Map<String,String> parameters =new TreeMap<String,String>()
Referenced by RDFCRSToWKT.downliftSystem(), ConversionOperation.toGML(), and ConversionOperation.toWKT().
projectionName
String projectionName
Referenced by RDFCRSToWKT.downliftSystem(), and ConversionOperation.toWKT().
scope
String scope
Referenced by RDFCRSToWKT.downliftSystem().