GeoSPARQL SRS Extension: Vertex Class Reference
Vertex Class Reference
Vertex.
Public Member Functions
Vertex ()
Default constructor.
Vertex (int id)
Constructor.
Vertex (int id, Coordinate coordinate)
Constructor.
Vertex (int id, boolean border)
Constructor.
Vertex (int id, Coordinate coordinate, boolean border)
Constructor.
int getId ()
Returns the ID of the vertex.
void setId (int id)
Defines the ID of the vertex.
Coordinate getCoordinate ()
Returns the coordinate of the vertex.
void setCoordinate (Coordinate c)
Defines the coordinate of the vertex.
boolean isBorder ()
Returns true if the vertex is a border vertex of the triangulation framework, false otherwise.
void setBorder (boolean border)
Defines the indicator to know if the edge is a border edge of the triangulation framework.
Private Attributes
int id
ID of the vertex.
Coordinate coordinate
Coordinate of the vertex.
boolean border
Indicator to know if the vertex is a border vertex of the triangulation framework.
Detailed Description
Vertex.
Author
Eric Grosso
Constructor & Destructor Documentation
Vertex() [1/5]
Vertex ()
Default constructor.
                     {
         //
     }
Vertex() [2/5]
Vertex (int id)
Constructor.
Parameters
id ID of the vertex
{
         this.id = id;
     }
References Vertex.id.
Vertex() [3/5]
Vertex (int id, Coordinate coordinate)
Constructor.
Parameters
id ID of the vertex
coordinate coordinate of the vertex
{
         this.id = id;
         this.setCoordinate(coordinate);
     }
References Vertex.id, and Vertex.setCoordinate().
Vertex() [4/5]
Vertex (int id, boolean border)
Constructor.
Parameters
id ID of the vertex
border defines if the vertex is a border vertex or not in the triangulation framework
{
         this.id = id;
         this.border = border;
     }
References Vertex.border, and Vertex.id.
Vertex() [5/5]
Vertex (int id, Coordinate coordinate, boolean border)
Constructor.
Parameters
id ID of the vertex
coordinate coordinate of the vertex
border defines if the vertex is a border vertex or not in the triangulation framework
{
         this.id = id;
         this.border = border;
         this.setCoordinate(coordinate);
     }
References Vertex.border, Vertex.id, and Vertex.setCoordinate().
Member Function Documentation
getCoordinate()
Coordinate getCoordinate ()
Returns the coordinate of the vertex.
Returns
the coordinate of the vertex
{
         return this.coordinate;
     }
References Vertex.coordinate.
getId()
int getId ()
Returns the ID of the vertex.
Returns
the ID of the vertex
{
         return this.id;
     }
References Vertex.id.
isBorder()
boolean isBorder ()
Returns true if the vertex is a border vertex of the triangulation framework, false otherwise.
Returns
true if the vertex is a border vertex, false otherwise
{
         return this.border;
     }
References Vertex.border.
Referenced by ConcaveHull.concaveHull().
setBorder()
void setBorder (boolean border)
Defines the indicator to know if the edge is a border edge of the triangulation framework.
Parameters
border true if the edge is a border edge, false otherwise
{
         this.border = border;
     }
References Vertex.border.
Referenced by ConcaveHull.concaveHull().
setCoordinate()
void setCoordinate (Coordinate c)
Defines the coordinate of the vertex.
Parameters
c the coordinate of the vertex
{
         this.coordinate = c;
     }
Referenced by Vertex.Vertex().
setId()
void setId (int id)
Defines the ID of the vertex.
Parameters
id the ID of the vertex
{
         this.id = id;
     }
References Vertex.id.
Member Data Documentation
border
boolean border private
Indicator to know if the vertex is a border vertex of the triangulation framework.
Referenced by Vertex.isBorder(), Vertex.setBorder(), and Vertex.Vertex().
coordinate
Coordinate coordinate private
Coordinate of the vertex.
Referenced by Vertex.getCoordinate().
id
int id private
ID of the vertex.
Referenced by Vertex.getId(), Vertex.setId(), and Vertex.Vertex().