GeoSPARQL SRS Extension: ConvertCRS2 Class Reference
ConvertCRS2 Class Reference
Public Member Functions
NodeValue exec (NodeValue geomliteral, NodeValue crsURI, NodeValue endpoint, NodeValue crsURI2)
Member Function Documentation
exec()
NodeValue exec (NodeValue geomliteral, NodeValue crsURI, NodeValue endpoint, NodeValue crsURI2)
{
                 GeometryWrapper geomwrap=GeometryWrapper.extract(geomliteral);
                 String res = RDFCRSToWKT.getCRSFromTripleStore(crsURI.getString(), endpoint.getString(), "WKT");
                 try {
                         CoordinateReferenceSystem targetCRS = CRS.fromWKT(res);
                         CoordinateOperation op;
                         op = CRS.findOperation(geomwrap.getCRS(), targetCRS, null);
                         List<Coordinate> coords=new LinkedList<Coordinate>();
                         for(Coordinate coord:geomwrap.getXYGeometry().getCoordinates()) {
                                  DirectPosition pos;
                                         pos = op.getMathTransform().transform(new DirectPosition2D(coord.x,coord.y), null);
                                  Coordinate curcor=new Coordinate(pos.getCoordinate()[0],pos.getCoordinate()[1]);
                                  coords.add(curcor);
                         }
                         return RDFCRSToWKT.createGeometry(coords.toArray(new Coordinate[0]), geomwrap.getGeometryType(), geomwrap).asNodeValue();
                 } catch (FactoryException | MismatchedDimensionException | TransformException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
                 }
         }
References GeometryWrapper.asNodeValue(), RDFCRSToWKT.createGeometry(), GeometryWrapper.extract(), GeometryWrapper.getCRS(), RDFCRSToWKT.getCRSFromTripleStore(), GeometryWrapper.getGeometryType(), and GeometryWrapper.getXYGeometry().