GeoSPARQL SRS Extension: Datum Class Reference
Datum Class Reference
Representation of a geodetic datum.
Public Member Functions
String toProj ()
JSONObject toProjJSON ()
String toGML ()
String toString ()
String toWKT ()
ResultSet datumQuery ()
Public Attributes
String datumType
The type of the datum.
String datumName
An identifier for the datum.
Ellipsoid ellipsoid
The description of the ellipsoid/geoid which this datum uses.
PrimeMeridian primeMeridian
Optional description of a prime meridian.
String interstellarbody
List< String > usagescope
Detailed Description
Representation of a geodetic datum.
Member Function Documentation
datumQuery()
ResultSet datumQuery ()
{
                 return null;
         }
toGML()
String toGML ()
{
                 XMLOutputFactory factory = XMLOutputFactory.newInstance();
                 StringWriter strwriter=new StringWriter();
                 XMLStreamWriter writer;
                 try {
                         writer = new IndentingXMLStreamWriter(factory.createXMLStreamWriter(strwriter));
                         if(datumType.contains("ReferenceFrame")) {
                                 writer.writeStartElement("gml:"+datumType.replace("ReferenceFrame", "Datum"));
                         }else {
                                 writer.writeStartElement("gml:"+datumType);
                         }
                         writer.writeStartElement("gml:datumName");
                         writer.writeCharacters(this.datumName);
                         writer.writeEndElement();
                         if(primeMeridian!=null) {
                                 writer.writeStartElement("gml:usesPrimeMeridian");
                                 writer.writeCharacters(System.lineSeparator());
                                 writer.flush();
                                 strwriter.write(primeMeridian.toGML()+System.lineSeparator());
                                 writer.writeEndElement();
                         }
                         if(ellipsoid!=null) {
                                 writer.writeStartElement("gml:usesEllipsoid");
                                 writer.writeCharacters(System.lineSeparator());
                                 writer.flush();
                                 strwriter.write(this.ellipsoid.toGML()+System.lineSeparator());
                                 writer.writeEndElement();
                         }
                         writer.writeEndElement();
                         writer.flush();
                 } catch (XMLStreamException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 }
                 return strwriter.toString();
         }
References Datum.datumType, Datum.ellipsoid, Datum.primeMeridian, Ellipsoid.toGML(), and PrimeMeridian.toGML().
Referenced by CoordinateReferenceSystem.toGML().
toProj()
String toProj ()
{
                 StringBuilder builder=new StringBuilder();
                 return builder.toString();
         }
toProjJSON()
JSONObject toProjJSON ()
{
                 JSONObject result=new JSONObject();
                 result.put("name",datumName);
                 result.put("type",datumType);
                 result.put("ellipsoid", ellipsoid.toProjJSON());
                 return result;
         }
References Datum.datumName, Datum.datumType, Datum.ellipsoid, and Ellipsoid.toProjJSON().
Referenced by CoordinateReferenceSystem.toProjJSON().
toString()
String toString ()
{
                 return "Datum [datumType=" + datumType + ", datumName=" + datumName + ", ellipsoid=" + ellipsoid + "]";
         }
References Datum.datumName, Datum.datumType, and Datum.ellipsoid.
toWKT()
String toWKT ()
{
                 StringBuilder builder=new StringBuilder();
                 if(datumName==null)
                         return builder.toString();
                 builder.append("DATUM["+"\""+datumName.replace("Datum:","").trim()+"\","+System.lineSeparator());
                 builder.append(ellipsoid.toWKT()+"]"+System.lineSeparator());
                 if(primeMeridian!=null) {
                         builder.append(","+primeMeridian.toWKT()+System.lineSeparator());
                 }
                 //builder.append("]");
                 return builder.toString();
         }
References Datum.datumName, Datum.ellipsoid, Datum.primeMeridian, Ellipsoid.toWKT(), and PrimeMeridian.toWKT().
Referenced by CoordinateReferenceSystem.toWKT().
Member Data Documentation
datumName
String datumName
An identifier for the datum.
Referenced by RDFCRSToWKT.downliftSystem(), Datum.toProjJSON(), Datum.toString(), and Datum.toWKT().
datumType
String datumType
The type of the datum.
Referenced by RDFCRSToWKT.downliftSystem(), Datum.toGML(), Datum.toProjJSON(), and Datum.toString().
ellipsoid
Ellipsoid ellipsoid
The description of the ellipsoid/geoid which this datum uses.
Referenced by RDFCRSToWKT.downliftSystem(), Datum.toGML(), Datum.toProjJSON(), Datum.toString(), and Datum.toWKT().
interstellarbody
String interstellarbody
primeMeridian
PrimeMeridian primeMeridian
Optional description of a prime meridian.
Referenced by RDFCRSToWKT.downliftSystem(), Datum.toGML(), and Datum.toWKT().
usagescope
List<String> usagescope