GeoSPARQL SRS Extension: CoordinateSystem Class Reference
CoordinateSystem Class Reference
Representation of a coordinate system as a part of a SRS.
Public Member Functions
String toString ()
String toProj ()
JSONObject toProjJSON ()
String toGML ()
String toWKT ()
Public Attributes
List< Axis > axisList =new LinkedList<Axis>()
String coordinateSystemType
Integer numberDimensions
String coordinateSystemName
Detailed Description
Representation of a coordinate system as a part of a SRS.
Member Function Documentation
toGML()
String toGML ()
{
                 XMLOutputFactory factory = XMLOutputFactory.newInstance();
                 StringWriter strwriter=new StringWriter();
                 XMLStreamWriter writer;
                 try {
                         writer = new IndentingXMLStreamWriter(factory.createXMLStreamWriter(strwriter));
                         if(coordinateSystemType.contains("PlanarCoordinateSystem")) {
                                 writer.writeStartElement("gml:CartesianCS");
                         }else {
                                 writer.writeStartElement("gml:"+coordinateSystemType);
                         }
                         if(this.coordinateSystemName!=null) {
                                 writer.writeStartElement("gml:csName");
                                 writer.writeCharacters(this.coordinateSystemName);
                                 writer.writeEndElement();
                         }
                         for(Axis ax:axisList) {
                                 writer.writeStartElement("gml:usesAxis");
                                 writer.writeCharacters(System.lineSeparator());
                                 writer.flush();
                                 strwriter.write(ax.toGML()+System.lineSeparator());
                                 writer.writeEndElement();
                         }
                         writer.writeEndElement();
                         writer.flush();
                 } catch (XMLStreamException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 }
                 return strwriter.toString();
         }
References CoordinateSystem.axisList, and CoordinateSystem.coordinateSystemType.
Referenced by CoordinateReferenceSystem.toGML().
toProj()
String toProj ()
{
                 StringBuilder builder=new StringBuilder();
                 return builder.toString();
         }
toProjJSON()
JSONObject toProjJSON ()
{
                 JSONObject cs=new JSONObject();
                 cs.put("type", "CoordinateSystem");
                 cs.put("subtype", coordinateSystemType);
                 cs.put("axis", new JSONArray());
                 for(Axis axis:axisList) {
                         cs.getJSONArray("axis").put(axis.toProjJSON());
                 }
                 return cs;
         }
References CoordinateSystem.axisList, and CoordinateSystem.coordinateSystemType.
Referenced by CoordinateReferenceSystem.toProjJSON().
toString()
String toString ()
{
                 return "CoordinateSystem [axisList=" + axisList + ", coordinateSystemType=" + coordinateSystemType
                                 + ", numberDimensions=" + numberDimensions + "]";
         }
References CoordinateSystem.axisList, CoordinateSystem.coordinateSystemType, and CoordinateSystem.numberDimensions.
toWKT()
String toWKT ()
{
                 StringBuilder builder=new StringBuilder();
                 if(coordinateSystemType==null)
                         return builder.toString();
                 builder.append("CS["+System.lineSeparator());
                 if(coordinateSystemType.contains("CS:")) {
                         builder.append(coordinateSystemType.substring(coordinateSystemType.lastIndexOf(':')+1).trim()+System.lineSeparator());
                 }else {
                         builder.append(coordinateSystemType+System.lineSeparator());
                 }
                 builder.append(","+numberDimensions+"],");
                 for(Axis axis:axisList) {
                         builder.append(axis.toWKT()+",");
                 }
                 builder.delete(builder.length()-1, builder.length());
                 return builder.toString()+System.lineSeparator();
         }
References CoordinateSystem.axisList, CoordinateSystem.coordinateSystemType, and CoordinateSystem.numberDimensions.
Referenced by CoordinateReferenceSystem.toWKT().
Member Data Documentation
axisList
List<Axis> axisList =new LinkedList<Axis>()
Referenced by RDFCRSToWKT.downliftSystem(), CoordinateSystem.toGML(), CoordinateSystem.toProjJSON(), CoordinateSystem.toString(), and CoordinateSystem.toWKT().
coordinateSystemName
String coordinateSystemName
Referenced by RDFCRSToWKT.downliftSystem().
coordinateSystemType
String coordinateSystemType
Referenced by RDFCRSToWKT.downliftSystem(), CoordinateSystem.toGML(), CoordinateSystem.toProjJSON(), CoordinateSystem.toString(), and CoordinateSystem.toWKT().
numberDimensions
Integer numberDimensions
Referenced by RDFCRSToWKT.downliftSystem(), CoordinateSystem.toString(), and CoordinateSystem.toWKT().