GeoSPARQL SRS Extension: CoordinateReferenceSystem Class Reference
CoordinateReferenceSystem Class Reference
Public Member Functions
String toString ()
String toProj ()
JSONObject toProjJSON ()
String toGML ()
String toWKT ()
Static Public Member Functions
static OntModel WKTToRDF (String wkt) throws FactoryException, IOException
static OntModel GMLToRDF (String gml) throws FactoryException
static OntModel fromWKT (String wktString)
static void main (String[] args) throws NoSuchAuthorityCodeException, UnsupportedOperationException, FactoryException, IOException
Public Attributes
CoordinateReferenceSystem sourceCRS
String crsName
String crsType
String id
String authority
String scope
String area
String remarks
AreaOfValidity areaOfValidity
ConversionOperation conv
Datum datum
CoordinateSystem cSystem
Member Function Documentation
fromWKT()
static OntModel fromWKT (String wktString) static
{
                 OntModel result=ModelFactory.createOntologyModel();
                 List<String> parts=new LinkedList<String>();
                 System.out.println("{"+wktString+"}");
                 String lastWord="";
                 int bracketopencounter=0,bracketclosecounter=0;
                 for(int i=0;i<wktString.length();i++) {
                         System.out.println(wktString.charAt(i));
                         if(wktString.charAt(i)==' ') {
                                 lastWord="";
                         }else {
                                 lastWord+=wktString.charAt(i);
                         }
                         if(wktString.charAt(i)=='[') {
                                 //System.out.println("Bracket open!!!");
                                 bracketopencounter++;
                                 if(parts.size()<bracketopencounter) {
                                         parts.add(lastWord);
                                 }
                         }
                         //System.out.println(parts);
                         for(int j=0;j<bracketopencounter;j++) {
                                 parts.set(j, parts.get(j)+wktString.charAt(i));
                         }
                 }
                 for(String p:parts) {
                         System.out.println("====");
                         System.out.println(p);
                 }
                 return result;
         }
Referenced by CoordinateReferenceSystem.main().
GMLToRDF()
static OntModel GMLToRDF (String gml) throws FactoryException static
{
                 CRS.fromXML(gml);
                 OntModel result=ModelFactory.createOntologyModel();
                 return result;
         }
main()
static void main (String[] args) throws NoSuchAuthorityCodeException, UnsupportedOperationException, FactoryException, IOException static
{
                 fromWKT(CRS.forCode("EPSG:4326").toWKT());
         }
References CoordinateReferenceSystem.fromWKT().
toGML()
String toGML ()
{
                 XMLOutputFactory factory = XMLOutputFactory.newInstance();
                 StringWriter strwriter=new StringWriter();
                 XMLStreamWriter writer;
                 try {
                         writer = new IndentingXMLStreamWriter(factory.createXMLStreamWriter(strwriter));
                         writer.writeStartDocument();
                         switch(crsType) {
                         case "PROJCRS": writer.writeStartElement("gml:ProjectedCRS");
                         break;
                         case "GEODCRS": writer.writeStartElement("gml:GeodeticCRS");
                         break;
                         case "BOUNDCRS": writer.writeStartElement("gml:BoundCRS");
                         break;
                         case "COMPOUNDCRS": writer.writeStartElement("gml:CompoundCRS");
                         break;
                         case "VERTCRS": writer.writeStartElement("gml:VerticalCRS");
                         break;
                         case "ENGCRS": writer.writeStartElement("gml:EngineeringCRS");
                         break;
                         case "PARAMETRICCRS": writer.writeStartElement("gml:ParametricCRS");
                         break;
                         case "TIMECRS": writer.writeStartElement("gml:TimeCRS");
                         break;
                         default:
                                 writer.writeStartElement("gml:GeographicCRS");
                         }
                         writer.writeStartElement("gml:srsName");
                         writer.writeCharacters(this.crsName);
                         writer.writeEndElement();
                         if(this.sourceCRS!=null) {
                                 writer.writeStartElement("gml:sourceCRS");
                                 writer.writeCharacters(System.lineSeparator());
                                 writer.flush();
                                 strwriter.write(this.sourceCRS.toGML());
                                 writer.writeEndElement();
                         }
                         if(this.cSystem!=null) {
                                 writer.writeStartElement("gml:usesEllipsoidalCS");
                                 writer.writeCharacters(System.lineSeparator());
                                 writer.flush();
                                 strwriter.write(this.cSystem.toGML()+System.lineSeparator());
                                 writer.writeEndElement();
                         }
                         if(this.datum!=null) {
                                 writer.writeStartElement("gml:usesGeodeticDatum");
                                 writer.writeCharacters(System.lineSeparator());
                                 writer.flush();
                                 strwriter.write(this.datum.toGML()+System.lineSeparator());
                                 writer.writeEndElement();
                         }
                         if(this.conv!=null) {
                                 writer.writeStartElement("gml:definedByConversion");
                                 writer.writeCharacters(System.lineSeparator());
                                 writer.flush();
                                 strwriter.write(this.conv.toGML()+System.lineSeparator());
                                 writer.writeEndElement();
                         }
                         writer.writeEndElement();
                         writer.writeEndDocument();
                 } catch (XMLStreamException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 }
                 return strwriter.toString();
         }
References CoordinateReferenceSystem.crsType, ConversionOperation.toGML(), CoordinateReferenceSystem.toGML(), CoordinateSystem.toGML(), and Datum.toGML().
Referenced by RDFCRSToWKT.getCRSFromTripleStore(), RDFCRSToWKT.main(), and CoordinateReferenceSystem.toGML().
toProj()
String toProj ()
{
                 StringBuilder builder=new StringBuilder();
                 return builder.toString();
         }
Referenced by RDFCRSToWKT.getCRSFromTripleStore().
toProjJSON()
JSONObject toProjJSON ()
{
                 JSONObject result=new JSONObject();
                 result.put("name", crsName);
                 result.put("type",crsType);
                 result.put("scope", scope);
                 result.put("area", area);
                 result.put("datum", datum.toProjJSON());
                 result.put("coordinate_system",cSystem.toProjJSON());
                 if(areaOfValidity!=null)
                         result.put("bbox", areaOfValidity.toProjJSON());
                 result.put("id", new JSONObject());
                 result.getJSONObject("id").put("code",id);
                 result.getJSONObject("id").put("authority",authority);
                 return result;
         }
References CoordinateReferenceSystem.area, CoordinateReferenceSystem.areaOfValidity, CoordinateReferenceSystem.authority, CoordinateReferenceSystem.crsName, CoordinateReferenceSystem.crsType, CoordinateReferenceSystem.cSystem, CoordinateReferenceSystem.datum, CoordinateReferenceSystem.scope, AreaOfValidity.toProjJSON(), CoordinateSystem.toProjJSON(), and Datum.toProjJSON().
Referenced by RDFCRSToWKT.getCRSFromTripleStore(), and RDFCRSToWKT.main().
toString()
String toString ()
{
                 return "CoordinateReferenceSystem [sourceCRS=" + sourceCRS + ", crsName=" + crsName + ", crsType=" + crsType
                                 + ", id=" + id + ", authority=" + authority + ", scope=" + scope + ", area=" + area + ", remarks="
                                 + remarks + ", areaOfValidity=" + areaOfValidity + ", conv=" + conv + ", datum=" + datum + ", cSystem="
                                 + cSystem + "]";
         }
References CoordinateReferenceSystem.area, CoordinateReferenceSystem.areaOfValidity, CoordinateReferenceSystem.authority, CoordinateReferenceSystem.conv, CoordinateReferenceSystem.crsName, CoordinateReferenceSystem.crsType, CoordinateReferenceSystem.cSystem, CoordinateReferenceSystem.datum, CoordinateReferenceSystem.remarks, CoordinateReferenceSystem.scope, and CoordinateReferenceSystem.sourceCRS.
toWKT()
String toWKT ()
{
                 StringBuilder builder=new StringBuilder();
                 builder.append(crsType+"[");
                 builder.append("\""+crsName+"\","+System.lineSeparator());
                 if(sourceCRS!=null) {
                         builder.append(sourceCRS.toWKT()+","+System.lineSeparator());
                 }
                 if(datum!=null) {
                         builder.append(datum.toWKT()+","+System.lineSeparator());
                 }
                 if(cSystem!=null) {
                         builder.append(cSystem.toWKT()+System.lineSeparator());
                 }
                 if(conv!=null) {
                         builder.append(conv.toWKT()+System.lineSeparator());
                 }
                 if(areaOfValidity!=null) {
                         builder.append(areaOfValidity.toWKT()+System.lineSeparator());
                 }
                 builder.append("]");
                 return builder.toString();
         }
References CoordinateReferenceSystem.areaOfValidity, CoordinateReferenceSystem.conv, CoordinateReferenceSystem.crsName, CoordinateReferenceSystem.crsType, CoordinateReferenceSystem.cSystem, CoordinateReferenceSystem.datum, CoordinateReferenceSystem.sourceCRS, AreaOfValidity.toWKT(), ConversionOperation.toWKT(), CoordinateReferenceSystem.toWKT(), CoordinateSystem.toWKT(), and Datum.toWKT().
Referenced by RDFCRSToWKT.getCRSFromTripleStore(), RDFCRSToWKT.main(), and CoordinateReferenceSystem.toWKT().
WKTToRDF()
static OntModel WKTToRDF (String wkt) throws FactoryException, IOException static
{
                 OntModel result=ModelFactory.createOntologyModel();
                 Set<String> resultset=new TreeSet<String>();
                 org.opengis.referencing.crs.CoordinateReferenceSystem res = CRS.fromWKT(wkt);
                 String crsid="geocrs:"+res.getName().getCode().replace(" ", "_");
                 String csid=crsid+"_cs";//geocrs:"+res.getCoordinateSystem().getName().getCode().replace(" ", "_").replace(".", "").replace(",", "").replace(":", "");
                 resultset.add(crsid+" rdf:type geocrs:"+res.ALIAS_KEY+" ."+System.lineSeparator());
                 resultset.add(crsid+" rdfs:label \""+res.getName()+"\"@en ."+System.lineSeparator());
                 resultset.add(crsid+" geocrs:coordinateSystem "+csid+" ."+System.lineSeparator());
                 resultset.add(crsid+" geocrs:scope \""+res.getScope()+"\"@en ."+System.lineSeparator());
                 resultset.add(crsid+" geocrs:area_of_use geocrs:"+crsid+"_aou ."+System.lineSeparator());
                 resultset.add(crsid+"_aou rdf:type geocrs:AreaOfUse ."+System.lineSeparator());
                 resultset.add(crsid+"_aou geo:asWKT \"ENVELOPE()\"^^geo:wktLiteral ."+System.lineSeparator());
                 resultset.add(csid+" rdf:type geocrs:CoordinateSystem ."+System.lineSeparator());
                 resultset.add(csid+" rdfs:label \""+res.getCoordinateSystem().getName()+"\"@en ."+System.lineSeparator());
                 resultset.add("geocrs:coordinateSystem rdf:type owl:ObjectProperty ."+System.lineSeparator());
                 resultset.add("geocrs:area_of_use rdf:type owl:ObjectProperty ."+System.lineSeparator());
                 resultset.add("geocrs:axis rdf:type owl:ObjectProperty ."+System.lineSeparator());
                 for(int i=0;i<res.getCoordinateSystem().getDimension();i++) {
                         String axisid=csid+"_axis"+i;
                         resultset.add(csid+" geocrs:axis "+axisid+" ."+System.lineSeparator());
                         resultset.add(axisid+" rdf:type geocrs:CoordinateSystemAxis ."+System.lineSeparator());
                         resultset.add(axisid+" geocrs:abbreviation \""+res.getCoordinateSystem().getAxis(i).getAbbreviation()+"\" ."+System.lineSeparator());
                         resultset.add(axisid+" geocrs:direction geocrs:"+res.getCoordinateSystem().getAxis(i).getDirection().identifier()+" ."+System.lineSeparator());
                         resultset.add(axisid+" geocrs:unit om:"+res.getCoordinateSystem().getAxis(i).getUnit().getName()+" ."+System.lineSeparator());
                         resultset.add("geocrs:"+res.getCoordinateSystem().getAxis(i).getDirection().identifier()+" rdf:type geocrs:AxisDirection ."+System.lineSeparator());
                 }
                 StringBuilder builder=new StringBuilder();
                 builder.append("@prefix geocrs:<http://www.opengis.net/ont/crs/> ."+System.lineSeparator());
                 builder.append("@prefix geo:<http://www.opengis.net/ont/> ."+System.lineSeparator());
                 builder.append("@prefix rdfs:<http://www.w3.org/2000/01/rdf-schema#> ."+System.lineSeparator());
                 builder.append("@prefix rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#> ."+System.lineSeparator());
                 builder.append("@prefix owl:<http://www.w3.org/2002/07/owl#> ."+System.lineSeparator());
                 builder.append("@prefix om:<http://www.ontology-of-units-of-measure.org/resource/om-2/> ."+System.lineSeparator());
                 for(String trip:resultset) {
                         builder.append(trip);
                 }
                 System.out.println(builder.toString());
                 FileWriter writer=new FileWriter(new File("importtest.ttl"));
                 writer.write(builder.toString());
                 writer.close();
                 return result;
         }
Referenced by WebService.convertFeaturetoCRSDefinedinRDF().
Member Data Documentation
area
String area
Referenced by CoordinateReferenceSystem.toProjJSON(), and CoordinateReferenceSystem.toString().
areaOfValidity
AreaOfValidity areaOfValidity
Referenced by RDFCRSToWKT.downliftSystem(), CoordinateReferenceSystem.toProjJSON(), CoordinateReferenceSystem.toString(), and CoordinateReferenceSystem.toWKT().
authority
String authority
Referenced by CoordinateReferenceSystem.toProjJSON(), and CoordinateReferenceSystem.toString().
conv
ConversionOperation conv
Referenced by RDFCRSToWKT.downliftSystem(), CoordinateReferenceSystem.toString(), and CoordinateReferenceSystem.toWKT().
crsName
String crsName
Referenced by RDFCRSToWKT.downliftSystem(), CoordinateReferenceSystem.toProjJSON(), CoordinateReferenceSystem.toString(), and CoordinateReferenceSystem.toWKT().
crsType
String crsType
Referenced by RDFCRSToWKT.downliftSystem(), CoordinateReferenceSystem.toGML(), CoordinateReferenceSystem.toProjJSON(), CoordinateReferenceSystem.toString(), and CoordinateReferenceSystem.toWKT().
cSystem
CoordinateSystem cSystem
Referenced by RDFCRSToWKT.downliftSystem(), CoordinateReferenceSystem.toProjJSON(), CoordinateReferenceSystem.toString(), and CoordinateReferenceSystem.toWKT().
datum
Datum datum
Referenced by RDFCRSToWKT.downliftSystem(), CoordinateReferenceSystem.toProjJSON(), CoordinateReferenceSystem.toString(), and CoordinateReferenceSystem.toWKT().
id
String id
remarks
String remarks
Referenced by CoordinateReferenceSystem.toString().
scope
String scope
Referenced by RDFCRSToWKT.downliftSystem(), CoordinateReferenceSystem.toProjJSON(), and CoordinateReferenceSystem.toString().
sourceCRS
CoordinateReferenceSystem sourceCRS
Referenced by CoordinateReferenceSystem.toString(), and CoordinateReferenceSystem.toWKT().