GeoSPARQL SRS Extension: SRSGeo Class Reference
SRSGeo Class Reference
Classes
class Nodes
Static Public Member Functions
static void main (String[] args) throws IllegalArgumentException, IllegalAccessException
Static Public Attributes
static String uri = "http://www.opengis.net/ont/geosparql#"
static String uri2 = "http://www.opengis.net/ont/geosparqlplus#"
static final Resource SpatialObject = resource("SpatialObject")
static final Resource Feature = resource("Feature")
static final Property st_3ddwithin = property("ST_3DDWithin")
static final Property st_3dclosestpoint = property("ST_3DClosestPoint")
static final Property st_3dlongestLine = property("ST_3dLongestLine")
static final Property st_3dmaxDistance = property("ST_3DMaxDistance")
static final Property st_3dshortestline = property("ST_3DShortestLine")
static final Property st_accum = property("ST_Accum")
static final Property st_addband = property("ST_AddBand")
static final Property st_addgeometry = property("ST_AddGeometry")
static final Property st_addpoint = property("ST_AddPoint")
static final Property st_addRing = property("ST_AddRing")
static final Property st_addz = property("ST_AddZ")
static final Property st_angle = property("ST_Angle")
static final Property st_area = property("ST_Area")
static final Property st_areasimilarity = property("ST_AreaSimilarity")
static final Property st_asbinary = property("ST_AsBinary")
static final Property st_asencodedpolyline = property("ST_AsEncodedPolyline")
static final Property st_askml = property("ST_AsKML")
static final Property st_asgml = property("ST_AsGML")
static final Property st_asgeobuf = property("ST_AsGeoBuf")
static final Property st_asgeojson = property("ST_AsGeoJSON")
static final Property st_asgeojsonld = property("ST_AsGeoJSONLD")
static final Property st_asgeorss = property("ST_AsGeoRSS")
static final Property st_asgeouri = property("ST_AsGeoURI")
static final Property st_asgpx = property("ST_AsGPX")
static final Property st_ashexewkb = property("ST_AsHexEWKB")
static final Property st_asjpg = property("ST_AsJPG")
static final Property st_aslatlontext = property("ST_AsLatLonText")
static final Property st_asmvt = property("ST_AsMVT")
static final Property st_asmvtgeom = property("ST_AsMVTGeom")
static final Property st_aspect = property("ST_Aspect")
static final Property st_aspng = property("ST_AsPNG")
static final Property st_aspolyshape = property("ST_AsPolyshape")
static final Property st_assvg = property("ST_AsSVG")
static final Property st_astext = property("ST_AsText")
static final Property st_astextraw = property("ST_AsTextRaw")
static final Property st_astextround = property("ST_AsTextRound")
static final Property st_astiff = property("ST_AsTIFF")
static final Property st_astopojson = property("ST_AsTopoJSON")
static final Property st_astwkb = property("ST_AsTWKB")
static final Property st_aswkb = property("ST_AsWKB")
static final Property st_aswkt = property("ST_AsWKT")
static final Property st_asx3d = property("ST_AsX3D")
static final Property st_azimuth = property("ST_Azimuth")
static final Property st_band = property("ST_Band")
static final Property st_bandmetadata = property("ST_BandMetaData")
static final Property st_bandnodatavalue = property("ST_BandNoDataValue")
static final Property st_bandpixeltype = property("ST_BandPixelType")
static final Property st_bboxabove = property("ST_BBOXAbove")
static final Property st_bboxbelow = property("ST_BBOXBelow")
static final Property st_bboxcontains = property("ST_BBOXContains")
static final Property st_bboxdistance = property("ST_BBOXDistance")
static final Property st_bboxequals = property("ST_BBOXEquals")
static final Property st_bboxfpintersects = property("ST_BBOXFPIntersects")
static final Property st_bboxintersect = property("ST_BBOXIntersect")
static final Property st_bboxiscontainedby = property("ST_BBOXIsContainedBy")
static final Property st_bboxleftof = property("ST_BBOXLeftOf")
static final Property st_bboxoverlapsabove = property("ST_BBOXOverlapsAbove")
static final Property st_bboxoverlapsbelow = property("ST_BBOXOverlapsBelow")
static final Property st_bboxoverlapsleft = property("ST_BBOXOverlapsLeft")
static final Property st_bboxoverlapsright = property("ST_BBOXOverlapsRight")
static final Property st_bboxrightof = property("ST_BBOXRightOf")
static final Property st_bezierSmoothing = property("ST_BezierSmoothing")
static final Property st_boundary = property("ST_Boundary")
static final Property st_boundingdiagonal = property("ST_BoundingDiagonal")
static final Property st_centroid = property("ST_Centroid")
static final Property st_centroidDistance = property("ST_CentroidDistance")
static final Property st_circularity = property("ST_Circularity")
static final Property st_chaikinSmooting = property("ST_ChaikinSmoothing")
static final Property st_clip = property("ST_Clip")
static final Property st_clipByBox2D = property("ST_ClipByBox2D")
static final Property st_closestCooordinate = property("ST_ClosestCoordinate")
static final Property st_closestPoint = property("ST_ClosestPoint")
static final Property st_closestPoint3d = property("ST_3DClosestPoint")
static final Property st_closestPointOfApproach = property("ST_ClosestPointOfApproach")
static final Property st_clusterIntersecting = property("ST_ClusterIntersecting")
static final Property st_clusterKMeans = property("ST_ClusterKMeans")
static final Property st_clusterWithin = property("ST_ClusterWithin")
static final Property st_collectionExtract = property("ST_CollectionExtract")
static final Property st_collectionHomogenize = property("ST_CollectionHomogenize")
static final Property st_compactnessRatio = property("ST_CompactnessRatio")
static final Property st_convexHull = property("ST_ConvexHull")
static final Property st_concaveHull = property("ST_ConcaveHull")
static final Property st_contains = property("ST_Contains")
static final Property st_containsProperly = property("ST_ContainsProperly")
static final Property st_count = property("ST_Count")
static final Property st_curveToLine = property("ST_CurveToLine")
static final Property st_densify = property("ST_Densify")
static final Property st_delaunayTriangles = property("ST_DelaunayTriangles")
static final Property st_dimension = property("ST_Dimension")
static final Property st_distance = property("ST_Distance")
static final Property st_distance3d = property("ST_3DDistance")
static final Property st_distancesphere = property("ST_DistanceSphere")
static final Property st_dumpRings = property("ST_DumpRings")
static final Property st_dWithin = property("ST_DWithin")
static final Property st_dwithin3d = property("ST_DWithin3D")
static final Property st_endPoint = property("ST_EndPoint")
static final Property st_ensureClosed = property("ST_EnsureClosed")
static final Property st_envelope = property("ST_Envelope")
static final Property st_epsgToSRID = property("ST_EPSGToSRID")
static final Property st_epsgToGML = property("ST_EPSGToGML")
static final Property st_epsgToWKT = property("ST_EPSGToWKT")
static final Property st_equals = property("ST_Equals")
static final Property st_equalSRS = property("ST_EqualSRS")
static final Property st_equalsNorm = property("ST_EqualsNorm")
static final Property st_equalsTopo = property("ST_EqualsTopo")
static final Property st_equalType = property("ST_EqualType")
static final Property st_explode = property("ST_Explode")
static final Property st_filterByM = property("ST_FilterByM")
static final Property st_filterByT = property("ST_FilterByT")
static final Property st_flipCoordinates = property("ST_FlipCoordinates")
static final Property st_force2d = property("ST_Force2D")
static final Property st_force3d = property("ST_Force3D")
static final Property st_force3dm = property("ST_Force3DM")
static final Property st_force3dz = property("ST_Force3DZ")
static final Property st_force4d = property("ST_Force4D")
static final Property st_forceCollection = property("ST_ForceCollection")
static final Property st_forceCurve = property("ST_ForceCurve")
static final Property st_forceLHR = property("ST_ForceLHR")
static final Property st_forcePolygonCW = property("ST_ForcePolygonCW")
static final Property st_forcePolygonCCW = property("ST_ForcePolygonCCW")
static final Property st_forceSFS = property("ST_ForceSFS")
static final Property st_frechetDistance = property("ST_FrechetDistance")
static final Property st_furthestCoordinate = property("ST_FurthestCoordinate")
static final Property st_generatePoints = property("ST_GeneratePoints")
static final Property st_geohash = property("ST_GeoHash")
static final Property st_geomCollFromText = property("ST_CollFromText")
static final Property st_geomFromGeoHash = property("ST_GeomFromGeoHash")
static final Property st_geomFromGeoJSON = property("ST_GeomFromGeoJSON")
static final Property st_geomFromKML = property("ST_GeomFromKML")
static final Property st_geomFromGML = property("ST_GeomFromGML")
static final Property st_geomFromWKB = property("ST_GeomFromWKB")
static final Property st_geomFromText = property("ST_GeomFromText")
static final Property st_geometricMedian = property("ST_GeometricMedian")
static final Property st_geometryN = property("ST_GeometryN")
static final Property st_geometryType = property("ST_GeometryType")
static final Property st_gmlToSQL = property("ST_GMLToSQL")
static final Property st_grayscale = property("ST_Grayscale")
static final Property st_hasHorizontalCRS = property("ST_HasHorizontalCRS")
static final Property st_hasNoBand = property("ST_HasNoBand")
static final Property st_hasRepeatedPoints = property("ST_HasRepeatedPoints")
static final Property st_hausdorffDistance = property("ST_HausdorffDistance")
static final Property st_height = property("ST_Height")
static final Property st_interiorRingN = property("ST_InteriorRingN")
static final Property st_interpolatePoint = property("ST_InterpolatePoint")
static final Property st_intersectionMatrix = property("ST_IntersectionMatrix")
static final Property st_intersectionPercentage = property("ST_IntersectionPercentage")
static final Property st_is3D = property("ST_Is3D")
static final Property st_isAcute = property("ST_IsAcute")
static final Property st_isClosed = property("ST_IsClosed")
static final Property st_isCollection = property("ST_IsCollection")
static final Property st_isConvex = property("ST_IsConvex")
static final Property st_isEligibleConversion = property("ST_IsEligibleConversion")
static final Property st_isEmpty = property("ST_IsEmpty")
static final Property st_isEquilateralTriangle = property("ST_IsEquilateralTriangle")
static final Property st_isGrayscale = property("ST_IsGrayscale")
static final Property st_isIndexed = property("ST_IsIndexed")
static final Property st_isInSRSAreaOfValidity = property("ST_IsInSRSAreaOfValidity")
static final Property st_isIsocelesTriangle = property("ST_IsIsocelesTriangle")
static final Property st_isMeasured = property("ST_IsMeasured")
static final Property st_isMorePrecise = property("ST_IsMorePrecise")
static final Property st_isNodingValid = property("ST_IsNodingValid")
static final Property st_isPlanar = property("ST_IsPlanar")
static final Property st_isPointOnLine = property("ST_IsPointOnLine")
static final Property st_isPointInRing = property("ST_IsPointInRing")
static final Property st_isPolygonCW = property("ST_IsPolygonCW")
static final Property st_isPolygonCCW = property("ST_IsPolygonCCW")
static final Property st_isRectangle = property("ST_IsRectangle")
static final Property st_isRightTriangle = property("ST_IsRightTriangle")
static final Property st_isRing = property("ST_IsRing")
static final Property st_isSimple = property("ST_IsSimple")
static final Property st_isSolid = property("ST_IsSolid")
static final Property st_isSquare = property("ST_IsSquare")
static final Property st_isTiled = property("ST_IsTiled")
static final Property st_isTranslucent = property("ST_IsTranslucent")
static final Property st_isTriangle = property("ST_IsTriangle")
static final Property st_isValid = property("ST_IsValid")
static final Property st_isValidDetail = property("ST_IsValidDetail")
static final Property st_isValidReason = property("ST_IsValidReason")
static final Property st_isValidTrajectory = property("ST_IsValidTrajectory")
static final Property st_Length = property("ST_Length")
static final Property st_Length2D = property("ST_Length2D")
static final Property st_Length3D = property("ST_Length3D")
static final Property st_LengthToPoint = property("ST_LengthToPoint")
static final Property st_locateAlong = property("ST_LocateAlong")
static final Property st_locateBetween = property("ST_LocateBetween")
static final Property st_locateBetweenElevations = property("ST_LocateBetweenElevations")
static final Property st_longestLine = property("ST_LongestLine")
static final Property st_longestLine3D = property("ST_LongestLine3D")
static final Property st_lineCrossingDirection =property("ST_LineCrossingDirection")
static final Property st_lineFromEncodedPolyline =property("ST_LineFromEncodedPolyline")
static final Property st_lineFromMultiPoint =property("ST_LineFromMultiPoint")
static final Property st_lineFromWKB = property("ST_LineFromWKB")
static final Property st_lineFromWKT = property("ST_LineFromWKT")
static final Property st_lineFromText = property("ST_LineFromText")
static final Property st_lineInterpolatePoint = property("ST_LineInterpolatePoint")
static final Property st_lineInterpolatePoints = property("ST_LineInterpolatePoints")
static final Property st_lineLength3D = property("ST_LineLength3D")
static final Property st_lineLocatePoint = property("ST_LineLocatePoint")
static final Property st_lineMerge = property("ST_LineMerge")
static final Property st_lineSelfIntersectionPoint = property("ST_LineSelfIntersectionPoint")
static final Property st_lineSubstring = property("ST_LineSubstring")
static final Property st_lineToCurve = property("ST_LineToCurve")
static final Property st_m = property("ST_M")
static final Property st_makeCircle = property("ST_MakeCircle")
static final Property st_makeEllipse = property("ST_MakeEllipse")
static final Property st_makeEmptyCoverage = property("ST_MakeEmptyCoverage")
static final Property st_makeEmptyRaster = property("ST_MakeEmptyRaster")
static final Property st_makeEnvelope = property("ST_MakeEnvelope")
static final Property st_makeLine = property("ST_MakeLine")
static final Property st_makePoint = property("ST_MakePoint")
static final Property st_makePointM = property("ST_MakePointM")
static final Property st_makePolygon = property("ST_MakePolygon")
static final Property st_makeValid = property("ST_MakeValid")
static final Property st_maxDistance = property("ST_MaxDistance")
static final Property st_maxDistance3D = property("ST_MaxDistance3D")
static final Property st_memsize = property("ST_MemSize")
static final Property st_minimumBoundingCircle = property("ST_MinimumBoundingCircle")
static final Property st_minimumBoundingCircleCenter = property("ST_MinimumBoundingCircleCenter")
static final Property st_minimumBoundingRadius = property("ST_MinimumBoundingRadius")
static final Property st_minimumClearance = property("ST_MinimumClearance")
static final Property st_minimumClearanceLine = property("ST_MinimumClearanceLine")
static final Property st_minimumDiameter = property("ST_MinimumDiameter")
static final Property st_minimumDiameterLine = property("ST_MinimumDiameterLine")
static final Property st_minimumRectangle = property("ST_MinimumRectangle")
static final Property st_minConvexHull = property("ST_MinConvexHull")
static final Property st_mintilex = property("ST_MinTileX")
static final Property st_mintiley = property("ST_MinTileY")
static final Property st_mMin = property("ST_MMin")
static final Property st_mMax = property("ST_MMax")
static final Property st_multi = property("ST_Multi")
static final Property st_multiplyz = property("ST_MultiplyZ")
static final Property st_mPointFromText = property("ST_MPointFromText")
static final Property st_mLineFromText = property("ST_MLineFromText")
static final Property st_mPolyFromText = property("ST_MPolyFromText")
static final Property st_nearestValue = property("ST_NearestValue")
static final Property st_node = property("ST_Node")
static final Property st_normalize = property("ST_Normalize")
static final Property st_notSameAlignmentReason = property("ST_NotSameAlignmentReason")
static final Property st_nDims = property("ST_NDims")
static final Property st_nRings = property("ST_NRings")
static final Property st_numBands = property("ST_NumBands")
static final Property st_numDistinctPoints =property("ST_NumDistinctPoints")
static final Property st_numGeometries = property("ST_NumGeometries")
static final Property st_numDistinctGeometries =property("ST_NumDistinctGeometries")
static final Property st_numInteriorRings = property("ST_NumInteriorRings")
static final Property st_numPatches = property("ST_NumPatches")
static final Property st_numPoints = property("ST_NumPoints")
static final Property st_numXTiles = property("ST_NumXTiles")
static final Property st_numYTiles = property("ST_NumYTiles")
static final Property st_nPoints = property("ST_NPoints")
static final Property st_octogonalEnvelope = property("ST_OctogonalEnvelope")
static final Property st_orientation = property("ST_Orientation")
static final Property st_offsetCurve = property("ST_OffsetCurve")
static final Property st_orderingEquals = property("ST_OrderingEquals")
static final Property st_osmlink = property("ST_OSMLink")
static final Property st_partOfGeometryAfter = property("ST_PartOfGeometryAfter")
static final Property st_partOfGeometryBefore = property("ST_PartOfGeometryBefore")
static final Property st_patchN = property("ST_PatchN")
static final Property st_pixelAsCentroid = property("ST_PixelAsCentroid")
static final Property st_pixelAsCentroids = property("ST_PixelAsCentroids")
static final Property st_pixelAsPoint = property("ST_PixelAsPoint")
static final Property st_pixelAsPoints = property("ST_PixelAsPoints")
static final Property st_pixelAsPolygon = property("ST_PixelAsPolygon")
static final Property st_pixelAsPolygons = property("ST_PixelAsPolygons")
static final Property st_pixelHeight = property("ST_PixelHeight")
static final Property st_pixelOfValue = property("ST_PixelOfValue")
static final Property st_pixelWidth = property("ST_PixelWidth")
static final Property st_perimeter = property("ST_Perimeter")
static final Property st_perimeter2D = property("ST_Perimeter2D")
static final Property st_perimeter3D = property("ST_Perimeter3D")
static final Property st_pointFromGeoHash = property("ST_PointFromGeoHash")
static final Property st_pointFromWKB = property("ST_PointFromWKB")
static final Property st_pointFromText = property("ST_PointFromText")
static final Property st_pointInsideCircle = property("ST_PointInsideCircle")
static final Property st_pointN = property("ST_PointN")
static final Property st_points = property("ST_Points")
static final Property st_pointOnSurface = property("ST_PointOnSurface")
static final Property st_polygon = property("ST_Polygon")
static final Property st_polygonize = property("ST_Polygonize")
static final Property st_polygonFromText = property("ST_PolygonFromText")
static final Property st_polygonFromWKB = property("ST_PolygonFromWKB")
static final Property st_precisionReducer = property("ST_PrecisionReducer")
static final Property st_rastFromHexWKB = property("ST_RastFromHexWKB")
static final Property st_rastFromWKB = property("ST_RastFromWKB")
static final Property st_rast_algebra_add = property("ST_Add")
static final Property st_rast_algebra_addconst = property("ST_AddConst")
static final Property st_rast_algebra_and = property("ST_And")
static final Property st_rast_algebra_andconst = property("ST_AndConst")
static final Property st_rast_algebra_binarize = property("ST_Binarize")
static final Property st_rast_algebra_clamp = property("ST_Clamp")
static final Property st_rast_algebra_constant = property("ST_Constant")
static final Property st_rast_algebra_crop = property("ST_Crop")
static final Property st_rast_algebra_dct = property("ST_DCT")
static final Property st_rast_algebra_div = property("ST_Div")
static final Property st_rast_algebra_divconst = property("ST_DivConst")
static final Property st_rast_algebra_exp = property("ST_Exp")
static final Property st_rast_algebra_idct = property("ST_IDCT")
static final Property st_rast_algebra_log = property("ST_Log")
static final Property st_rast_algebra_max = property("ST_Max")
static final Property st_rast_algebra_maxfilter = property("ST_MaxFilter")
static final Property st_rast_algebra_mean = property("ST_Mean")
static final Property st_rast_algebra_medianfilter = property("ST_MedianFilter")
static final Property st_rast_algebra_min = property("ST_Min")
static final Property st_rast_algebra_minfilter = property("ST_MinFilter")
static final Property st_rast_algebra_mult = property("ST_Mult")
static final Property st_rast_algebra_multconst = property("ST_MultConst")
static final Property st_rast_algebra_not = property("ST_Not")
static final Property st_rast_algebra_or = property("ST_Or")
static final Property st_rast_algebra_orconst = property("ST_OrConst")
static final Property st_rast_algebra_subtract = property("ST_Subtract")
static final Property st_rast_algebra_subtractconst = property("ST_SubtractConst")
static final Property st_rast_algebra_subtractfromconst = property("ST_SubtractFromConst")
static final Property st_rast_algebra_threshold = property("ST_Threshold")
static final Property st_rast_algebra_xor = property("ST_Xor")
static final Property st_rast_algebra_xorconst = property("ST_XorConst")
static final Property st_rast_isEmpty = property("ST_isEmpty")
static final Property st_rast_Contains = property("ST_Contains")
static final Property st_rast_Covers = property("ST_Covers")
static final Property st_rast_CoveredBy = property("ST_CoveredBy")
static final Property st_rast_Crosses = property("ST_Crosses")
static final Property st_rast_Disjoint = property("ST_Disjoint")
static final Property st_rast_Intersects = property("ST_Intersects")
static final Property st_rast_Intersection =property("ST_Intersection")
static final Property st_rast_Overlaps = property("ST_Overlaps")
static final Property st_rast_Touches = property("ST_Touches")
static final Property st_rast_Within = property("ST_Within")
static final Property st_rast_srid = property("ST_SRID")
static final Property st_rasterToWorldCoord = property("ST_RasterToWorldCoord")
static final Property st_rasterToWorldCoordX = property("ST_RasterToWorldCoordX")
static final Property st_rasterToWorldCoordY = property("ST_RasterToWorldCoordY")
static final Property st_removePoint = property("ST_RemovePoint")
static final Property st_removePoints = property("ST_RemovePoints")
static final Property st_removeRepeatedPoints = property("ST_RemoveRepeatedPoints")
static final Property st_reflect = property("ST_Reflect")
static final Property st_removegeometry = property("ST_RemoveGeometry")
static final Property st_removeRing = property("ST_RemoveRing")
static final Property st_relate = property("ST_Relate")
static final Property st_relateMatch = property("ST_RelateMatch")
static final Property st_resize = property("ST_Resize")
static final Property st_reskew = property("ST_Reskew")
static final Property st_retile = property("ST_Retile")
static final Property st_reverse = property("ST_Reverse")
static final Property st_reverseRing = property("ST_ReverseRing")
static final Property st_rotate = property("ST_Rotate")
static final Property st_rotateX = property("ST_RotateX")
static final Property st_rotateY = property("ST_RotateY")
static final Property st_rotateZ = property("ST_RotateZ")
static final Property st_rotation = property("ST_Rotation")
static final Property st_roughness = property("ST_Roughness")
static final Property st_sameAlignment = property("ST_SameAlignment")
static final Property st_scale = property("ST_Scale")
static final Property st_scaleX = property("ST_ScaleX")
static final Property st_scaleY = property("ST_ScaleY")
static final Property st_segmentize = property("ST_Segmentize")
static final Property st_selfIntersections = property("ST_SelfIntersections")
static final Property st_setEndPoint = property("ST_SetEndPoint")
static final Property st_setGeometry = property("ST_SetGeometry")
static final Property st_setGeoReference = property("ST_SetGeoReference")
static final Property st_setPoint = property("ST_SetPoint")
static final Property st_setRing = property("ST_SetRing")
static final Property st_setStartPoint = property("ST_SetStartPoint")
static final Property st_setSRID = property("ST_SetSRID")
static final Property st_sharedPaths = property("ST_SharedPaths")
static final Property st_shearTransformation = property("ST_ShearTransformation")
static final Property st_shiftLongitude = property("ST_ShiftLongitude")
static final Property st_shortestLine = property("ST_ShortestLine")
static final Property st_shortestLine3D = property("ST_3DShortestLine")
static final Property st_simplify = property("ST_Simplify")
static final Property st_simplifyPreserveTopology = property("ST_SimplifyPreserveTopology")
static final Property st_simplifyVW = property("ST_SimplifyVW")
static final Property st_skewX = property("ST_SkewX")
static final Property st_skewY = property("ST_SkewY")
static final Property st_slope = property("ST_Slope")
static final Property st_snap = property("ST_Snap")
static final Property st_snapToGrid = property("ST_SnapToGrid")
static final Property st_split = property("ST_Split")
static final Property st_srid = property("ST_SRID")
static final Property st_sridToEPSG = property("ST_SRIDToEPSG")
static final Property st_sridToWKT = property("ST_SRIDToWKT")
static final Property st_sridToGML = property("ST_SRIDToGML")
static final Property st_sridGetAxis1Name = property("ST_SRIDGetAxis1Name")
static final Property st_sridGetAxis1Orientation = property("ST_SRIDGetAxis1Orientation")
static final Property st_sridGetAxis2Name = property("ST_SRIDGetAxis2Name")
static final Property st_sridGetAxis2Orientation = property("ST_SRIDGetAxis2Orientation")
static final Property st_sridHasFlippedAxis = property("ST_SRIDHasFlippedAxis")
static final Property st_srsAreaOfValidity = property("ST_SRSAreaOfValidity")
static final Property st_srsURIToWKT = property("ST_SRSURIToWKT")
static final Property st_srsURIToGML = property("ST_SRSURIToGML")
static final Property st_startPoint = property("ST_StartPoint")
static final Property st_straightSkeleton = property("ST_StraightSkeleton")
static final Property st_suggestProjection = property("ST_SuggestProjection")
static final Property st_summary = property("ST_Summary")
static final Property st_summaryStats = property("ST_SummaryStats")
static final Property st_swapOrdinates = property("ST_SwapOrdinates")
static final Property st_symDifference = property("ST_SymDifference")
static final Property st_tesselate = property("ST_Tesselate")
static final Property st_t = property("ST_T")
static final Property st_tilegridxoffset = property("ST_TileGridXOffset")
static final Property st_tilegridyoffset = property("ST_TileGridYOffset")
static final Property st_tileheight = property("ST_TileHeight")
static final Property st_tilewidth = property("ST_TileWidth")
static final Property st_tMax = property("ST_TMax")
static final Property st_tMin = property("ST_TMin")
static final Property st_toDegrees =property("ST_ToDegrees")
static final Property st_toRadians =property("ST_ToRadians")
static final Property st_tpi = property("ST_TPI")
static final Property st_tri = property("ST_TRI")
static final Property st_transform = property("ST_Transform")
static final Property st_translate = property("ST_Translate")
static final Property st_transscale = property("ST_TransScale")
static final Property st_upperLeftX = property("ST_UpperLeftX")
static final Property st_upperLeftY = property("ST_UpperLeftY")
static final Property st_union = property("ST_Union")
static final Property st_unaryUnion = property("ST_UnaryUnion")
static final Property st_value = property("ST_Value")
static final Property st_vectorize = property("ST_Vectorize")
static final Property st_voronoiLines = property("ST_VoronoiLines")
static final Property st_voronoiPolygons = property("ST_VoronoiPolygons")
static final Property st_width = property("ST_Width")
static final Property st_wkbToSQL = property("ST_WKBToSQL")
static final Property st_wktToSQL = property("ST_WKTToSQL")
static final Property st_worldToRasterCoord = property("ST_WorldToRasterCoord")
static final Property st_worldToRasterCoordX = property("ST_WorldToRasterCoordX")
static final Property st_worldToRasterCoordY = property("ST_WorldToRasterCoordY")
static final Property st_x = property("ST_X")
static final Property st_xMin = property("ST_XMin")
static final Property st_xMax = property("ST_XMax")
static final Property st_y = property("ST_Y")
static final Property st_yMin = property("ST_YMin")
static final Property st_yMax = property("ST_YMax")
static final Property st_z = property("ST_Z")
static final Property st_zMin = property("ST_ZMin")
static final Property st_zMax = property("ST_ZMax")
static final Property st_zmFlag = property("ST_ZmFlag")
static final String WKB = "http://www.opengis.net/ont/geosparqlplus#wkbLiteral"
static final String GeoJSON = "http://www.opengis.net/ont/geosparqlplus#GeoJSONLiteral"
static final String GeoJSONLD = "http://www.opengis.net/ont/geosparqlplus#GeoJSONLDLiteral"
static final String GeoHash = "http://www.opengis.net/ont/geosparqlplus#GeoHashLiteral"
static final String GeoBuf = "http://www.opengis.net/ont/geosparqlplus#GeoBufLiteral"
static final String GeoURI ="http://www.opengis.net/ont/geosparqlplus#GeoURILiteral"
static final String GeoRSS ="http://www.opengis.net/ont/geosparqlplus#GeoRSSLiteral"
static final String GMLCOV ="http://www.opengis.net/ont/geosparqlplus#GMLCOVLiteral"
static final String KML = "http://www.opengis.net/ont/geosparqlplus#KMLLiteral"
static final String WKBRaster = "http://www.opengis.net/ont/geosparqlplus#WKBRasterLiteral"
static final String GEOTIFF = "http://www.opengis.net/ont/geosparqlplus#GeoTIFFLiteral"
static final String EncodedPolyline = "http://www.opengis.net/ont/geosparqlplus#EncodedPolylineLiteral"
static final String Polyshape = "http://www.opengis.net/ont/geosparqlplus#PolyshapeLiteral"
static final String TWKB = "http://www.opengis.net/ont/geosparqlplus#TWKBLiteral"
static final String HEXWKB = "http://www.opengis.net/ont/geosparqlplus#HEXWKBLiteral"
static final String DXF ="http://www.opengis.net/ont/geosparqlplus#DXFLiteral"
static final String MVT = "http://www.opengis.net/ont/geosparqlplus#MVTLiteral"
static final String X3D = "http://www.opengis.net/ont/geosparqlplus#X3DLiteral"
static final String OSM = "http://www.opengis.net/ont/geosparqlplus#OSMLiteral"
static final String NetCDF ="http://www.opengis.net/ont/geosparqlplus#NetCDFLiteral"
static final String HexWKBRaster = "http://www.opengis.net/ont/geosparqlplus#HexWKBRasterLiteral"
static final String TopoJSON = "http://www.opengis.net/ont/geosparqlplus#TopoJSON"
static final String TemporalRange ="TemporalRange"
static final String CoverageJSON = "http://www.opengis.net/ont/geosparqlplus#covJSONLiteral"
static final String XYZASCII = "http://www.opengis.net/ont/geosparqlplus#XYZASCIILiteral"
Static Protected Member Functions
static final Resource resource (String local)
static final Property property (String local)
Member Function Documentation
main()
static void main (String[] args) throws IllegalArgumentException, IllegalAccessException static
{
         SRSGeo go=new SRSGeo();
         go.uri="http://www.opengis.net/ont/geosparqlplus#";
     for (Field field : go.getClass().getDeclaredFields()) {
         //field.setAccessible(true); // if you want to modify private fields
         System.out.println("<"+field.get(go)+"> rdf:type geo2:Function ; rdfs:label \""+field.getName()+"\" . ");
     }
 }
References SRSGeo.uri.
property()
static final Property property (String local) static protected
{
       return ResourceFactory.createProperty(uri2, local);
    }
References SRSGeo.uri2.
resource()
static final Resource resource (String local) static protected
{
       return ResourceFactory.createResource(uri + local);
    }
References SRSGeo.uri.
Member Data Documentation
CoverageJSON
final String CoverageJSON = "http://www.opengis.net/ont/geosparqlplus#covJSONLiteral" static
DXF
final String DXF ="http://www.opengis.net/ont/geosparqlplus#DXFLiteral" static
EncodedPolyline
final String EncodedPolyline = "http://www.opengis.net/ont/geosparqlplus#EncodedPolylineLiteral" static
Feature
final Resource Feature = resource("Feature") static
GeoBuf
final String GeoBuf = "http://www.opengis.net/ont/geosparqlplus#GeoBufLiteral" static
GeoHash
final String GeoHash = "http://www.opengis.net/ont/geosparqlplus#GeoHashLiteral" static
GeoJSON
final String GeoJSON = "http://www.opengis.net/ont/geosparqlplus#GeoJSONLiteral" static
GeoJSONLD
final String GeoJSONLD = "http://www.opengis.net/ont/geosparqlplus#GeoJSONLDLiteral" static
GeoRSS
final String GeoRSS ="http://www.opengis.net/ont/geosparqlplus#GeoRSSLiteral" static
GEOTIFF
final String GEOTIFF = "http://www.opengis.net/ont/geosparqlplus#GeoTIFFLiteral" static
GeoURI
final String GeoURI ="http://www.opengis.net/ont/geosparqlplus#GeoURILiteral" static
GMLCOV
final String GMLCOV ="http://www.opengis.net/ont/geosparqlplus#GMLCOVLiteral" static
HEXWKB
final String HEXWKB = "http://www.opengis.net/ont/geosparqlplus#HEXWKBLiteral" static
HexWKBRaster
final String HexWKBRaster = "http://www.opengis.net/ont/geosparqlplus#HexWKBRasterLiteral" static
KML
final String KML = "http://www.opengis.net/ont/geosparqlplus#KMLLiteral" static
MVT
final String MVT = "http://www.opengis.net/ont/geosparqlplus#MVTLiteral" static
NetCDF
final String NetCDF ="http://www.opengis.net/ont/geosparqlplus#NetCDFLiteral" static
OSM
final String OSM = "http://www.opengis.net/ont/geosparqlplus#OSMLiteral" static
Polyshape
final String Polyshape = "http://www.opengis.net/ont/geosparqlplus#PolyshapeLiteral" static
SpatialObject
final Resource SpatialObject = resource("SpatialObject") static
st_3dclosestpoint
final Property st_3dclosestpoint = property("ST_3DClosestPoint") static
st_3ddwithin
final Property st_3ddwithin = property("ST_3DDWithin") static
st_3dlongestLine
final Property st_3dlongestLine = property("ST_3dLongestLine") static
st_3dmaxDistance
final Property st_3dmaxDistance = property("ST_3DMaxDistance") static
st_3dshortestline
final Property st_3dshortestline = property("ST_3DShortestLine") static
st_accum
final Property st_accum = property("ST_Accum") static
st_addband
final Property st_addband = property("ST_AddBand") static
st_addgeometry
final Property st_addgeometry = property("ST_AddGeometry") static
st_addpoint
final Property st_addpoint = property("ST_AddPoint") static
st_addRing
final Property st_addRing = property("ST_AddRing") static
st_addz
final Property st_addz = property("ST_AddZ") static
st_angle
final Property st_angle = property("ST_Angle") static
st_area
final Property st_area = property("ST_Area") static
st_areasimilarity
final Property st_areasimilarity = property("ST_AreaSimilarity") static
st_asbinary
final Property st_asbinary = property("ST_AsBinary") static
st_asencodedpolyline
final Property st_asencodedpolyline = property("ST_AsEncodedPolyline") static
st_asgeobuf
final Property st_asgeobuf = property("ST_AsGeoBuf") static
st_asgeojson
final Property st_asgeojson = property("ST_AsGeoJSON") static
st_asgeojsonld
final Property st_asgeojsonld = property("ST_AsGeoJSONLD") static
st_asgeorss
final Property st_asgeorss = property("ST_AsGeoRSS") static
st_asgeouri
final Property st_asgeouri = property("ST_AsGeoURI") static
st_asgml
final Property st_asgml = property("ST_AsGML") static
st_asgpx
final Property st_asgpx = property("ST_AsGPX") static
st_ashexewkb
final Property st_ashexewkb = property("ST_AsHexEWKB") static
st_asjpg
final Property st_asjpg = property("ST_AsJPG") static
st_askml
final Property st_askml = property("ST_AsKML") static
st_aslatlontext
final Property st_aslatlontext = property("ST_AsLatLonText") static
st_asmvt
final Property st_asmvt = property("ST_AsMVT") static
st_asmvtgeom
final Property st_asmvtgeom = property("ST_AsMVTGeom") static
st_aspect
final Property st_aspect = property("ST_Aspect") static
st_aspng
final Property st_aspng = property("ST_AsPNG") static
st_aspolyshape
final Property st_aspolyshape = property("ST_AsPolyshape") static
st_assvg
final Property st_assvg = property("ST_AsSVG") static
st_astext
final Property st_astext = property("ST_AsText") static
st_astextraw
final Property st_astextraw = property("ST_AsTextRaw") static
st_astextround
final Property st_astextround = property("ST_AsTextRound") static
st_astiff
final Property st_astiff = property("ST_AsTIFF") static
st_astopojson
final Property st_astopojson = property("ST_AsTopoJSON") static
st_astwkb
final Property st_astwkb = property("ST_AsTWKB") static
st_aswkb
final Property st_aswkb = property("ST_AsWKB") static
st_aswkt
final Property st_aswkt = property("ST_AsWKT") static
st_asx3d
final Property st_asx3d = property("ST_AsX3D") static
st_azimuth
final Property st_azimuth = property("ST_Azimuth") static
st_band
final Property st_band = property("ST_Band") static
st_bandmetadata
final Property st_bandmetadata = property("ST_BandMetaData") static
st_bandnodatavalue
final Property st_bandnodatavalue = property("ST_BandNoDataValue") static
st_bandpixeltype
final Property st_bandpixeltype = property("ST_BandPixelType") static
st_bboxabove
final Property st_bboxabove = property("ST_BBOXAbove") static
st_bboxbelow
final Property st_bboxbelow = property("ST_BBOXBelow") static
st_bboxcontains
final Property st_bboxcontains = property("ST_BBOXContains") static
st_bboxdistance
final Property st_bboxdistance = property("ST_BBOXDistance") static
st_bboxequals
final Property st_bboxequals = property("ST_BBOXEquals") static
st_bboxfpintersects
final Property st_bboxfpintersects = property("ST_BBOXFPIntersects") static
st_bboxintersect
final Property st_bboxintersect = property("ST_BBOXIntersect") static
st_bboxiscontainedby
final Property st_bboxiscontainedby = property("ST_BBOXIsContainedBy") static
st_bboxleftof
final Property st_bboxleftof = property("ST_BBOXLeftOf") static
st_bboxoverlapsabove
final Property st_bboxoverlapsabove = property("ST_BBOXOverlapsAbove") static
st_bboxoverlapsbelow
final Property st_bboxoverlapsbelow = property("ST_BBOXOverlapsBelow") static
st_bboxoverlapsleft
final Property st_bboxoverlapsleft = property("ST_BBOXOverlapsLeft") static
st_bboxoverlapsright
final Property st_bboxoverlapsright = property("ST_BBOXOverlapsRight") static
st_bboxrightof
final Property st_bboxrightof = property("ST_BBOXRightOf") static
st_bezierSmoothing
final Property st_bezierSmoothing = property("ST_BezierSmoothing") static
st_boundary
final Property st_boundary = property("ST_Boundary") static
st_boundingdiagonal
final Property st_boundingdiagonal = property("ST_BoundingDiagonal") static
st_centroid
final Property st_centroid = property("ST_Centroid") static
st_centroidDistance
final Property st_centroidDistance = property("ST_CentroidDistance") static
st_chaikinSmooting
final Property st_chaikinSmooting = property("ST_ChaikinSmoothing") static
st_circularity
final Property st_circularity = property("ST_Circularity") static
st_clip
final Property st_clip = property("ST_Clip") static
st_clipByBox2D
final Property st_clipByBox2D = property("ST_ClipByBox2D") static
st_closestCooordinate
final Property st_closestCooordinate = property("ST_ClosestCoordinate") static
st_closestPoint
final Property st_closestPoint = property("ST_ClosestPoint") static
st_closestPoint3d
final Property st_closestPoint3d = property("ST_3DClosestPoint") static
st_closestPointOfApproach
final Property st_closestPointOfApproach = property("ST_ClosestPointOfApproach") static
st_clusterIntersecting
final Property st_clusterIntersecting = property("ST_ClusterIntersecting") static
st_clusterKMeans
final Property st_clusterKMeans = property("ST_ClusterKMeans") static
st_clusterWithin
final Property st_clusterWithin = property("ST_ClusterWithin") static
st_collectionExtract
final Property st_collectionExtract = property("ST_CollectionExtract") static
st_collectionHomogenize
final Property st_collectionHomogenize = property("ST_CollectionHomogenize") static
st_compactnessRatio
final Property st_compactnessRatio = property("ST_CompactnessRatio") static
st_concaveHull
final Property st_concaveHull = property("ST_ConcaveHull") static
st_contains
final Property st_contains = property("ST_Contains") static
st_containsProperly
final Property st_containsProperly = property("ST_ContainsProperly") static
st_convexHull
final Property st_convexHull = property("ST_ConvexHull") static
st_count
final Property st_count = property("ST_Count") static
st_curveToLine
final Property st_curveToLine = property("ST_CurveToLine") static
st_delaunayTriangles
final Property st_delaunayTriangles = property("ST_DelaunayTriangles") static
st_densify
final Property st_densify = property("ST_Densify") static
st_dimension
final Property st_dimension = property("ST_Dimension") static
st_distance
final Property st_distance = property("ST_Distance") static
st_distance3d
final Property st_distance3d = property("ST_3DDistance") static
st_distancesphere
final Property st_distancesphere = property("ST_DistanceSphere") static
st_dumpRings
final Property st_dumpRings = property("ST_DumpRings") static
st_dWithin
final Property st_dWithin = property("ST_DWithin") static
st_dwithin3d
final Property st_dwithin3d = property("ST_DWithin3D") static
st_endPoint
final Property st_endPoint = property("ST_EndPoint") static
st_ensureClosed
final Property st_ensureClosed = property("ST_EnsureClosed") static
st_envelope
final Property st_envelope = property("ST_Envelope") static
st_epsgToGML
final Property st_epsgToGML = property("ST_EPSGToGML") static
st_epsgToSRID
final Property st_epsgToSRID = property("ST_EPSGToSRID") static
st_epsgToWKT
final Property st_epsgToWKT = property("ST_EPSGToWKT") static
Referenced by CRSConfig.setup().
st_equals
final Property st_equals = property("ST_Equals") static
st_equalsNorm
final Property st_equalsNorm = property("ST_EqualsNorm") static
st_equalSRS
final Property st_equalSRS = property("ST_EqualSRS") static
st_equalsTopo
final Property st_equalsTopo = property("ST_EqualsTopo") static
st_equalType
final Property st_equalType = property("ST_EqualType") static
st_explode
final Property st_explode = property("ST_Explode") static
st_filterByM
final Property st_filterByM = property("ST_FilterByM") static
st_filterByT
final Property st_filterByT = property("ST_FilterByT") static
st_flipCoordinates
final Property st_flipCoordinates = property("ST_FlipCoordinates") static
st_force2d
final Property st_force2d = property("ST_Force2D") static
st_force3d
final Property st_force3d = property("ST_Force3D") static
st_force3dm
final Property st_force3dm = property("ST_Force3DM") static
st_force3dz
final Property st_force3dz = property("ST_Force3DZ") static
st_force4d
final Property st_force4d = property("ST_Force4D") static
st_forceCollection
final Property st_forceCollection = property("ST_ForceCollection") static
st_forceCurve
final Property st_forceCurve = property("ST_ForceCurve") static
st_forceLHR
final Property st_forceLHR = property("ST_ForceLHR") static
st_forcePolygonCCW
final Property st_forcePolygonCCW = property("ST_ForcePolygonCCW") static
st_forcePolygonCW
final Property st_forcePolygonCW = property("ST_ForcePolygonCW") static
st_forceSFS
final Property st_forceSFS = property("ST_ForceSFS") static
st_frechetDistance
final Property st_frechetDistance = property("ST_FrechetDistance") static
st_furthestCoordinate
final Property st_furthestCoordinate = property("ST_FurthestCoordinate") static
st_generatePoints
final Property st_generatePoints = property("ST_GeneratePoints") static
st_geohash
final Property st_geohash = property("ST_GeoHash") static
st_geomCollFromText
final Property st_geomCollFromText = property("ST_CollFromText") static
st_geometricMedian
final Property st_geometricMedian = property("ST_GeometricMedian") static
st_geometryN
final Property st_geometryN = property("ST_GeometryN") static
st_geometryType
final Property st_geometryType = property("ST_GeometryType") static
st_geomFromGeoHash
final Property st_geomFromGeoHash = property("ST_GeomFromGeoHash") static
st_geomFromGeoJSON
final Property st_geomFromGeoJSON = property("ST_GeomFromGeoJSON") static
st_geomFromGML
final Property st_geomFromGML = property("ST_GeomFromGML") static
st_geomFromKML
final Property st_geomFromKML = property("ST_GeomFromKML") static
st_geomFromText
final Property st_geomFromText = property("ST_GeomFromText") static
st_geomFromWKB
final Property st_geomFromWKB = property("ST_GeomFromWKB") static
st_gmlToSQL
final Property st_gmlToSQL = property("ST_GMLToSQL") static
st_grayscale
final Property st_grayscale = property("ST_Grayscale") static
st_hasHorizontalCRS
final Property st_hasHorizontalCRS = property("ST_HasHorizontalCRS") static
Referenced by CRSConfig.setup().
st_hasNoBand
final Property st_hasNoBand = property("ST_HasNoBand") static
st_hasRepeatedPoints
final Property st_hasRepeatedPoints = property("ST_HasRepeatedPoints") static
st_hausdorffDistance
final Property st_hausdorffDistance = property("ST_HausdorffDistance") static
st_height
final Property st_height = property("ST_Height") static
st_interiorRingN
final Property st_interiorRingN = property("ST_InteriorRingN") static
st_interpolatePoint
final Property st_interpolatePoint = property("ST_InterpolatePoint") static
st_intersectionMatrix
final Property st_intersectionMatrix = property("ST_IntersectionMatrix") static
st_intersectionPercentage
final Property st_intersectionPercentage = property("ST_IntersectionPercentage") static
st_is3D
final Property st_is3D = property("ST_Is3D") static
st_isAcute
final Property st_isAcute = property("ST_IsAcute") static
st_isClosed
final Property st_isClosed = property("ST_IsClosed") static
st_isCollection
final Property st_isCollection = property("ST_IsCollection") static
st_isConvex
final Property st_isConvex = property("ST_IsConvex") static
st_isEligibleConversion
final Property st_isEligibleConversion = property("ST_IsEligibleConversion") static
Referenced by CRSConfig.setup().
st_isEmpty
final Property st_isEmpty = property("ST_IsEmpty") static
st_isEquilateralTriangle
final Property st_isEquilateralTriangle = property("ST_IsEquilateralTriangle") static
st_isGrayscale
final Property st_isGrayscale = property("ST_IsGrayscale") static
st_isIndexed
final Property st_isIndexed = property("ST_IsIndexed") static
st_isInSRSAreaOfValidity
final Property st_isInSRSAreaOfValidity = property("ST_IsInSRSAreaOfValidity") static
Referenced by CRSConfig.setup().
st_isIsocelesTriangle
final Property st_isIsocelesTriangle = property("ST_IsIsocelesTriangle") static
st_isMeasured
final Property st_isMeasured = property("ST_IsMeasured") static
st_isMorePrecise
final Property st_isMorePrecise = property("ST_IsMorePrecise") static
st_isNodingValid
final Property st_isNodingValid = property("ST_IsNodingValid") static
st_isPlanar
final Property st_isPlanar = property("ST_IsPlanar") static
st_isPointInRing
final Property st_isPointInRing = property("ST_IsPointInRing") static
st_isPointOnLine
final Property st_isPointOnLine = property("ST_IsPointOnLine") static
st_isPolygonCCW
final Property st_isPolygonCCW = property("ST_IsPolygonCCW") static
st_isPolygonCW
final Property st_isPolygonCW = property("ST_IsPolygonCW") static
st_isRectangle
final Property st_isRectangle = property("ST_IsRectangle") static
st_isRightTriangle
final Property st_isRightTriangle = property("ST_IsRightTriangle") static
st_isRing
final Property st_isRing = property("ST_IsRing") static
st_isSimple
final Property st_isSimple = property("ST_IsSimple") static
st_isSolid
final Property st_isSolid = property("ST_IsSolid") static
st_isSquare
final Property st_isSquare = property("ST_IsSquare") static
st_isTiled
final Property st_isTiled = property("ST_IsTiled") static
st_isTranslucent
final Property st_isTranslucent = property("ST_IsTranslucent") static
st_isTriangle
final Property st_isTriangle = property("ST_IsTriangle") static
st_isValid
final Property st_isValid = property("ST_IsValid") static
st_isValidDetail
final Property st_isValidDetail = property("ST_IsValidDetail") static
st_isValidReason
final Property st_isValidReason = property("ST_IsValidReason") static
st_isValidTrajectory
final Property st_isValidTrajectory = property("ST_IsValidTrajectory") static
st_Length
final Property st_Length = property("ST_Length") static
st_Length2D
final Property st_Length2D = property("ST_Length2D") static
st_Length3D
final Property st_Length3D = property("ST_Length3D") static
st_LengthToPoint
final Property st_LengthToPoint = property("ST_LengthToPoint") static
st_lineCrossingDirection
final Property st_lineCrossingDirection =property("ST_LineCrossingDirection") static
st_lineFromEncodedPolyline
final Property st_lineFromEncodedPolyline =property("ST_LineFromEncodedPolyline") static
st_lineFromMultiPoint
final Property st_lineFromMultiPoint =property("ST_LineFromMultiPoint") static
st_lineFromText
final Property st_lineFromText = property("ST_LineFromText") static
st_lineFromWKB
final Property st_lineFromWKB = property("ST_LineFromWKB") static
st_lineFromWKT
final Property st_lineFromWKT = property("ST_LineFromWKT") static
st_lineInterpolatePoint
final Property st_lineInterpolatePoint = property("ST_LineInterpolatePoint") static
st_lineInterpolatePoints
final Property st_lineInterpolatePoints = property("ST_LineInterpolatePoints") static
st_lineLength3D
final Property st_lineLength3D = property("ST_LineLength3D") static
st_lineLocatePoint
final Property st_lineLocatePoint = property("ST_LineLocatePoint") static
st_lineMerge
final Property st_lineMerge = property("ST_LineMerge") static
st_lineSelfIntersectionPoint
final Property st_lineSelfIntersectionPoint = property("ST_LineSelfIntersectionPoint") static
st_lineSubstring
final Property st_lineSubstring = property("ST_LineSubstring") static
st_lineToCurve
final Property st_lineToCurve = property("ST_LineToCurve") static
st_locateAlong
final Property st_locateAlong = property("ST_LocateAlong") static
st_locateBetween
final Property st_locateBetween = property("ST_LocateBetween") static
st_locateBetweenElevations
final Property st_locateBetweenElevations = property("ST_LocateBetweenElevations") static
st_longestLine
final Property st_longestLine = property("ST_LongestLine") static
st_longestLine3D
final Property st_longestLine3D = property("ST_LongestLine3D") static
st_m
final Property st_m = property("ST_M") static
st_makeCircle
final Property st_makeCircle = property("ST_MakeCircle") static
st_makeEllipse
final Property st_makeEllipse = property("ST_MakeEllipse") static
st_makeEmptyCoverage
final Property st_makeEmptyCoverage = property("ST_MakeEmptyCoverage") static
st_makeEmptyRaster
final Property st_makeEmptyRaster = property("ST_MakeEmptyRaster") static
st_makeEnvelope
final Property st_makeEnvelope = property("ST_MakeEnvelope") static
st_makeLine
final Property st_makeLine = property("ST_MakeLine") static
st_makePoint
final Property st_makePoint = property("ST_MakePoint") static
st_makePointM
final Property st_makePointM = property("ST_MakePointM") static
st_makePolygon
final Property st_makePolygon = property("ST_MakePolygon") static
st_makeValid
final Property st_makeValid = property("ST_MakeValid") static
st_maxDistance
final Property st_maxDistance = property("ST_MaxDistance") static
st_maxDistance3D
final Property st_maxDistance3D = property("ST_MaxDistance3D") static
st_memsize
final Property st_memsize = property("ST_MemSize") static
st_minConvexHull
final Property st_minConvexHull = property("ST_MinConvexHull") static
st_minimumBoundingCircle
final Property st_minimumBoundingCircle = property("ST_MinimumBoundingCircle") static
st_minimumBoundingCircleCenter
final Property st_minimumBoundingCircleCenter = property("ST_MinimumBoundingCircleCenter") static
st_minimumBoundingRadius
final Property st_minimumBoundingRadius = property("ST_MinimumBoundingRadius") static
st_minimumClearance
final Property st_minimumClearance = property("ST_MinimumClearance") static
st_minimumClearanceLine
final Property st_minimumClearanceLine = property("ST_MinimumClearanceLine") static
st_minimumDiameter
final Property st_minimumDiameter = property("ST_MinimumDiameter") static
st_minimumDiameterLine
final Property st_minimumDiameterLine = property("ST_MinimumDiameterLine") static
st_minimumRectangle
final Property st_minimumRectangle = property("ST_MinimumRectangle") static
st_mintilex
final Property st_mintilex = property("ST_MinTileX") static
st_mintiley
final Property st_mintiley = property("ST_MinTileY") static
st_mLineFromText
final Property st_mLineFromText = property("ST_MLineFromText") static
st_mMax
final Property st_mMax = property("ST_MMax") static
st_mMin
final Property st_mMin = property("ST_MMin") static
st_mPointFromText
final Property st_mPointFromText = property("ST_MPointFromText") static
st_mPolyFromText
final Property st_mPolyFromText = property("ST_MPolyFromText") static
st_multi
final Property st_multi = property("ST_Multi") static
st_multiplyz
final Property st_multiplyz = property("ST_MultiplyZ") static
st_nDims
final Property st_nDims = property("ST_NDims") static
st_nearestValue
final Property st_nearestValue = property("ST_NearestValue") static
st_node
final Property st_node = property("ST_Node") static
st_normalize
final Property st_normalize = property("ST_Normalize") static
st_notSameAlignmentReason
final Property st_notSameAlignmentReason = property("ST_NotSameAlignmentReason") static
st_nPoints
final Property st_nPoints = property("ST_NPoints") static
st_nRings
final Property st_nRings = property("ST_NRings") static
st_numBands
final Property st_numBands = property("ST_NumBands") static
st_numDistinctGeometries
final Property st_numDistinctGeometries =property("ST_NumDistinctGeometries") static
st_numDistinctPoints
final Property st_numDistinctPoints =property("ST_NumDistinctPoints") static
st_numGeometries
final Property st_numGeometries = property("ST_NumGeometries") static
st_numInteriorRings
final Property st_numInteriorRings = property("ST_NumInteriorRings") static
st_numPatches
final Property st_numPatches = property("ST_NumPatches") static
st_numPoints
final Property st_numPoints = property("ST_NumPoints") static
st_numXTiles
final Property st_numXTiles = property("ST_NumXTiles") static
st_numYTiles
final Property st_numYTiles = property("ST_NumYTiles") static
st_octogonalEnvelope
final Property st_octogonalEnvelope = property("ST_OctogonalEnvelope") static
st_offsetCurve
final Property st_offsetCurve = property("ST_OffsetCurve") static
st_orderingEquals
final Property st_orderingEquals = property("ST_OrderingEquals") static
st_orientation
final Property st_orientation = property("ST_Orientation") static
st_osmlink
final Property st_osmlink = property("ST_OSMLink") static
st_partOfGeometryAfter
final Property st_partOfGeometryAfter = property("ST_PartOfGeometryAfter") static
st_partOfGeometryBefore
final Property st_partOfGeometryBefore = property("ST_PartOfGeometryBefore") static
st_patchN
final Property st_patchN = property("ST_PatchN") static
st_perimeter
final Property st_perimeter = property("ST_Perimeter") static
st_perimeter2D
final Property st_perimeter2D = property("ST_Perimeter2D") static
st_perimeter3D
final Property st_perimeter3D = property("ST_Perimeter3D") static
st_pixelAsCentroid
final Property st_pixelAsCentroid = property("ST_PixelAsCentroid") static
st_pixelAsCentroids
final Property st_pixelAsCentroids = property("ST_PixelAsCentroids") static
st_pixelAsPoint
final Property st_pixelAsPoint = property("ST_PixelAsPoint") static
st_pixelAsPoints
final Property st_pixelAsPoints = property("ST_PixelAsPoints") static
st_pixelAsPolygon
final Property st_pixelAsPolygon = property("ST_PixelAsPolygon") static
st_pixelAsPolygons
final Property st_pixelAsPolygons = property("ST_PixelAsPolygons") static
st_pixelHeight
final Property st_pixelHeight = property("ST_PixelHeight") static
st_pixelOfValue
final Property st_pixelOfValue = property("ST_PixelOfValue") static
st_pixelWidth
final Property st_pixelWidth = property("ST_PixelWidth") static
st_pointFromGeoHash
final Property st_pointFromGeoHash = property("ST_PointFromGeoHash") static
st_pointFromText
final Property st_pointFromText = property("ST_PointFromText") static
st_pointFromWKB
final Property st_pointFromWKB = property("ST_PointFromWKB") static
st_pointInsideCircle
final Property st_pointInsideCircle = property("ST_PointInsideCircle") static
st_pointN
final Property st_pointN = property("ST_PointN") static
st_pointOnSurface
final Property st_pointOnSurface = property("ST_PointOnSurface") static
st_points
final Property st_points = property("ST_Points") static
st_polygon
final Property st_polygon = property("ST_Polygon") static
st_polygonFromText
final Property st_polygonFromText = property("ST_PolygonFromText") static
st_polygonFromWKB
final Property st_polygonFromWKB = property("ST_PolygonFromWKB") static
st_polygonize
final Property st_polygonize = property("ST_Polygonize") static
st_precisionReducer
final Property st_precisionReducer = property("ST_PrecisionReducer") static
st_rast_algebra_add
final Property st_rast_algebra_add = property("ST_Add") static
st_rast_algebra_addconst
final Property st_rast_algebra_addconst = property("ST_AddConst") static
st_rast_algebra_and
final Property st_rast_algebra_and = property("ST_And") static
st_rast_algebra_andconst
final Property st_rast_algebra_andconst = property("ST_AndConst") static
st_rast_algebra_binarize
final Property st_rast_algebra_binarize = property("ST_Binarize") static
st_rast_algebra_clamp
final Property st_rast_algebra_clamp = property("ST_Clamp") static
st_rast_algebra_constant
final Property st_rast_algebra_constant = property("ST_Constant") static
st_rast_algebra_crop
final Property st_rast_algebra_crop = property("ST_Crop") static
st_rast_algebra_dct
final Property st_rast_algebra_dct = property("ST_DCT") static
st_rast_algebra_div
final Property st_rast_algebra_div = property("ST_Div") static
st_rast_algebra_divconst
final Property st_rast_algebra_divconst = property("ST_DivConst") static
st_rast_algebra_exp
final Property st_rast_algebra_exp = property("ST_Exp") static
st_rast_algebra_idct
final Property st_rast_algebra_idct = property("ST_IDCT") static
st_rast_algebra_log
final Property st_rast_algebra_log = property("ST_Log") static
st_rast_algebra_max
final Property st_rast_algebra_max = property("ST_Max") static
st_rast_algebra_maxfilter
final Property st_rast_algebra_maxfilter = property("ST_MaxFilter") static
st_rast_algebra_mean
final Property st_rast_algebra_mean = property("ST_Mean") static
st_rast_algebra_medianfilter
final Property st_rast_algebra_medianfilter = property("ST_MedianFilter") static
st_rast_algebra_min
final Property st_rast_algebra_min = property("ST_Min") static
st_rast_algebra_minfilter
final Property st_rast_algebra_minfilter = property("ST_MinFilter") static
st_rast_algebra_mult
final Property st_rast_algebra_mult = property("ST_Mult") static
st_rast_algebra_multconst
final Property st_rast_algebra_multconst = property("ST_MultConst") static
st_rast_algebra_not
final Property st_rast_algebra_not = property("ST_Not") static
st_rast_algebra_or
final Property st_rast_algebra_or = property("ST_Or") static
st_rast_algebra_orconst
final Property st_rast_algebra_orconst = property("ST_OrConst") static
st_rast_algebra_subtract
final Property st_rast_algebra_subtract = property("ST_Subtract") static
st_rast_algebra_subtractconst
final Property st_rast_algebra_subtractconst = property("ST_SubtractConst") static
st_rast_algebra_subtractfromconst
final Property st_rast_algebra_subtractfromconst = property("ST_SubtractFromConst") static
st_rast_algebra_threshold
final Property st_rast_algebra_threshold = property("ST_Threshold") static
st_rast_algebra_xor
final Property st_rast_algebra_xor = property("ST_Xor") static
st_rast_algebra_xorconst
final Property st_rast_algebra_xorconst = property("ST_XorConst") static
st_rast_Contains
final Property st_rast_Contains = property("ST_Contains") static
st_rast_CoveredBy
final Property st_rast_CoveredBy = property("ST_CoveredBy") static
st_rast_Covers
final Property st_rast_Covers = property("ST_Covers") static
st_rast_Crosses
final Property st_rast_Crosses = property("ST_Crosses") static
st_rast_Disjoint
final Property st_rast_Disjoint = property("ST_Disjoint") static
st_rast_Intersection
final Property st_rast_Intersection =property("ST_Intersection") static
st_rast_Intersects
final Property st_rast_Intersects = property("ST_Intersects") static
st_rast_isEmpty
final Property st_rast_isEmpty = property("ST_isEmpty") static
st_rast_Overlaps
final Property st_rast_Overlaps = property("ST_Overlaps") static
st_rast_srid
final Property st_rast_srid = property("ST_SRID") static
st_rast_Touches
final Property st_rast_Touches = property("ST_Touches") static
st_rast_Within
final Property st_rast_Within = property("ST_Within") static
st_rasterToWorldCoord
final Property st_rasterToWorldCoord = property("ST_RasterToWorldCoord") static
st_rasterToWorldCoordX
final Property st_rasterToWorldCoordX = property("ST_RasterToWorldCoordX") static
st_rasterToWorldCoordY
final Property st_rasterToWorldCoordY = property("ST_RasterToWorldCoordY") static
st_rastFromHexWKB
final Property st_rastFromHexWKB = property("ST_RastFromHexWKB") static
st_rastFromWKB
final Property st_rastFromWKB = property("ST_RastFromWKB") static
st_reflect
final Property st_reflect = property("ST_Reflect") static
st_relate
final Property st_relate = property("ST_Relate") static
st_relateMatch
final Property st_relateMatch = property("ST_RelateMatch") static
st_removegeometry
final Property st_removegeometry = property("ST_RemoveGeometry") static
st_removePoint
final Property st_removePoint = property("ST_RemovePoint") static
st_removePoints
final Property st_removePoints = property("ST_RemovePoints") static
st_removeRepeatedPoints
final Property st_removeRepeatedPoints = property("ST_RemoveRepeatedPoints") static
st_removeRing
final Property st_removeRing = property("ST_RemoveRing") static
st_resize
final Property st_resize = property("ST_Resize") static
st_reskew
final Property st_reskew = property("ST_Reskew") static
st_retile
final Property st_retile = property("ST_Retile") static
st_reverse
final Property st_reverse = property("ST_Reverse") static
st_reverseRing
final Property st_reverseRing = property("ST_ReverseRing") static
st_rotate
final Property st_rotate = property("ST_Rotate") static
st_rotateX
final Property st_rotateX = property("ST_RotateX") static
st_rotateY
final Property st_rotateY = property("ST_RotateY") static
st_rotateZ
final Property st_rotateZ = property("ST_RotateZ") static
st_rotation
final Property st_rotation = property("ST_Rotation") static
st_roughness
final Property st_roughness = property("ST_Roughness") static
st_sameAlignment
final Property st_sameAlignment = property("ST_SameAlignment") static
st_scale
final Property st_scale = property("ST_Scale") static
st_scaleX
final Property st_scaleX = property("ST_ScaleX") static
st_scaleY
final Property st_scaleY = property("ST_ScaleY") static
st_segmentize
final Property st_segmentize = property("ST_Segmentize") static
st_selfIntersections
final Property st_selfIntersections = property("ST_SelfIntersections") static
st_setEndPoint
final Property st_setEndPoint = property("ST_SetEndPoint") static
st_setGeometry
final Property st_setGeometry = property("ST_SetGeometry") static
st_setGeoReference
final Property st_setGeoReference = property("ST_SetGeoReference") static
Referenced by CRSConfig.setup().
st_setPoint
final Property st_setPoint = property("ST_SetPoint") static
st_setRing
final Property st_setRing = property("ST_SetRing") static
st_setSRID
final Property st_setSRID = property("ST_SetSRID") static
st_setStartPoint
final Property st_setStartPoint = property("ST_SetStartPoint") static
st_sharedPaths
final Property st_sharedPaths = property("ST_SharedPaths") static
st_shearTransformation
final Property st_shearTransformation = property("ST_ShearTransformation") static
st_shiftLongitude
final Property st_shiftLongitude = property("ST_ShiftLongitude") static
st_shortestLine
final Property st_shortestLine = property("ST_ShortestLine") static
st_shortestLine3D
final Property st_shortestLine3D = property("ST_3DShortestLine") static
st_simplify
final Property st_simplify = property("ST_Simplify") static
st_simplifyPreserveTopology
final Property st_simplifyPreserveTopology = property("ST_SimplifyPreserveTopology") static
st_simplifyVW
final Property st_simplifyVW = property("ST_SimplifyVW") static
st_skewX
final Property st_skewX = property("ST_SkewX") static
st_skewY
final Property st_skewY = property("ST_SkewY") static
st_slope
final Property st_slope = property("ST_Slope") static
st_snap
final Property st_snap = property("ST_Snap") static
st_snapToGrid
final Property st_snapToGrid = property("ST_SnapToGrid") static
st_split
final Property st_split = property("ST_Split") static
st_srid
final Property st_srid = property("ST_SRID") static
st_sridGetAxis1Name
final Property st_sridGetAxis1Name = property("ST_SRIDGetAxis1Name") static
Referenced by CRSConfig.setup().
st_sridGetAxis1Orientation
final Property st_sridGetAxis1Orientation = property("ST_SRIDGetAxis1Orientation") static
Referenced by CRSConfig.setup().
st_sridGetAxis2Name
final Property st_sridGetAxis2Name = property("ST_SRIDGetAxis2Name") static
Referenced by CRSConfig.setup().
st_sridGetAxis2Orientation
final Property st_sridGetAxis2Orientation = property("ST_SRIDGetAxis2Orientation") static
Referenced by CRSConfig.setup().
st_sridHasFlippedAxis
final Property st_sridHasFlippedAxis = property("ST_SRIDHasFlippedAxis") static
Referenced by CRSConfig.setup().
st_sridToEPSG
final Property st_sridToEPSG = property("ST_SRIDToEPSG") static
Referenced by CRSConfig.setup().
st_sridToGML
final Property st_sridToGML = property("ST_SRIDToGML") static
Referenced by CRSConfig.setup().
st_sridToWKT
final Property st_sridToWKT = property("ST_SRIDToWKT") static
Referenced by CRSConfig.setup().
st_srsAreaOfValidity
final Property st_srsAreaOfValidity = property("ST_SRSAreaOfValidity") static
Referenced by CRSConfig.setup().
st_srsURIToGML
final Property st_srsURIToGML = property("ST_SRSURIToGML") static
Referenced by CRSConfig.setup().
st_srsURIToWKT
final Property st_srsURIToWKT = property("ST_SRSURIToWKT") static
Referenced by CRSConfig.setup().
st_startPoint
final Property st_startPoint = property("ST_StartPoint") static
st_straightSkeleton
final Property st_straightSkeleton = property("ST_StraightSkeleton") static
st_suggestProjection
final Property st_suggestProjection = property("ST_SuggestProjection") static
Referenced by CRSConfig.setup().
st_summary
final Property st_summary = property("ST_Summary") static
st_summaryStats
final Property st_summaryStats = property("ST_SummaryStats") static
st_swapOrdinates
final Property st_swapOrdinates = property("ST_SwapOrdinates") static
st_symDifference
final Property st_symDifference = property("ST_SymDifference") static
st_t
final Property st_t = property("ST_T") static
st_tesselate
final Property st_tesselate = property("ST_Tesselate") static
st_tilegridxoffset
final Property st_tilegridxoffset = property("ST_TileGridXOffset") static
st_tilegridyoffset
final Property st_tilegridyoffset = property("ST_TileGridYOffset") static
st_tileheight
final Property st_tileheight = property("ST_TileHeight") static
st_tilewidth
final Property st_tilewidth = property("ST_TileWidth") static
st_tMax
final Property st_tMax = property("ST_TMax") static
st_tMin
final Property st_tMin = property("ST_TMin") static
st_toDegrees
final Property st_toDegrees =property("ST_ToDegrees") static
st_toRadians
final Property st_toRadians =property("ST_ToRadians") static
st_tpi
final Property st_tpi = property("ST_TPI") static
st_transform
final Property st_transform = property("ST_Transform") static
Referenced by CRSConfig.setup().
st_translate
final Property st_translate = property("ST_Translate") static
st_transscale
final Property st_transscale = property("ST_TransScale") static
st_tri
final Property st_tri = property("ST_TRI") static
st_unaryUnion
final Property st_unaryUnion = property("ST_UnaryUnion") static
st_union
final Property st_union = property("ST_Union") static
st_upperLeftX
final Property st_upperLeftX = property("ST_UpperLeftX") static
st_upperLeftY
final Property st_upperLeftY = property("ST_UpperLeftY") static
st_value
final Property st_value = property("ST_Value") static
st_vectorize
final Property st_vectorize = property("ST_Vectorize") static
st_voronoiLines
final Property st_voronoiLines = property("ST_VoronoiLines") static
st_voronoiPolygons
final Property st_voronoiPolygons = property("ST_VoronoiPolygons") static
st_width
final Property st_width = property("ST_Width") static
st_wkbToSQL
final Property st_wkbToSQL = property("ST_WKBToSQL") static
st_wktToSQL
final Property st_wktToSQL = property("ST_WKTToSQL") static
st_worldToRasterCoord
final Property st_worldToRasterCoord = property("ST_WorldToRasterCoord") static
st_worldToRasterCoordX
final Property st_worldToRasterCoordX = property("ST_WorldToRasterCoordX") static
st_worldToRasterCoordY
final Property st_worldToRasterCoordY = property("ST_WorldToRasterCoordY") static
st_x
final Property st_x = property("ST_X") static
st_xMax
final Property st_xMax = property("ST_XMax") static
st_xMin
final Property st_xMin = property("ST_XMin") static
st_y
final Property st_y = property("ST_Y") static
st_yMax
final Property st_yMax = property("ST_YMax") static
st_yMin
final Property st_yMin = property("ST_YMin") static
st_z
final Property st_z = property("ST_Z") static
st_zMax
final Property st_zMax = property("ST_ZMax") static
st_zmFlag
final Property st_zmFlag = property("ST_ZmFlag") static
st_zMin
final Property st_zMin = property("ST_ZMin") static
TemporalRange
final String TemporalRange ="TemporalRange" static
TopoJSON
final String TopoJSON = "http://www.opengis.net/ont/geosparqlplus#TopoJSON" static
TWKB
final String TWKB = "http://www.opengis.net/ont/geosparqlplus#TWKBLiteral" static
uri
String uri = "http://www.opengis.net/ont/geosparql#" static
Referenced by SRSGeo.main(), and SRSGeo.resource().
uri2
String uri2 = "http://www.opengis.net/ont/geosparqlplus#" static
Referenced by SRSGeo.property().
WKB
final String WKB = "http://www.opengis.net/ont/geosparqlplus#wkbLiteral" static
WKBRaster
final String WKBRaster = "http://www.opengis.net/ont/geosparqlplus#WKBRasterLiteral" static
X3D
final String X3D = "http://www.opengis.net/ont/geosparqlplus#X3DLiteral" static
XYZASCII
final String XYZASCII = "http://www.opengis.net/ont/geosparqlplus#XYZASCIILiteral" static