GeoSPARQL SRS Extension: ResultFormatter Class Reference
ResultFormatter Class Reference abstract
Abstract class to downlift query results.
Public Member Functions
abstract String formatter (ResultSet results, Writer out) throws IOException
Static Public Member Functions
static ResultFormatter getFormatter (String formatString)
Public Attributes
Integer lastQueriedElemCount =0
String mimeType ="text/plain"
String exposedType ="application/vnd.geojson"
String urlformat ="json"
String label ="JSON"
String definition =""
String fileextension ="json"
Boolean constructQuery =false
Static Public Attributes
static Map< String, ResultFormatter > resultMap =new TreeMap<String, ResultFormatter>()
static Map< String, String > labelMap =new TreeMap<String, String>()
static final Integer FLUSHTHRESHOLD =20
static final String[] mediatypes
Static Package Functions
static void addToMaps (String key, ResultFormatter format)
[static initializer]
Detailed Description
Abstract class to downlift query results.
Member Function Documentation
[static initializer]()
[static initializer] static package
References ResultFormatter.label, ResultFormatter.labelMap, ResultFormatter.mimeType, and ResultFormatter.resultMap.
addToMaps()
static void addToMaps (String key, ResultFormatter format) static package
{
                 resultMap.put(key, format);
                 labelMap.put(key,format.label);
                 resultMap.put(format.mimeType, format);
         }
formatter()
abstract String formatter (ResultSet results, Writer out) throws IOException abstract
Reimplemented in WKTCRSFormatter, ProjJSONFormatter, and ProjFormatter.
getFormatter()
static ResultFormatter getFormatter (String formatString) static
{
                 formatString=formatString.toLowerCase();
                 if(resultMap.containsKey(formatString)) {
                         return resultMap.get(formatString);
                 }
                 if(formatString.contains("proj")) {
                         return resultMap.get("proj");
                 }
                 if(formatString.contains("projjson")) {
                         return resultMap.get("projjson");
                 }
                 if(formatString.contains("wktcrs")) {
                         return resultMap.get("wktcrs");
                 }
                 return resultMap.get("projjson");
         }
References ResultFormatter.resultMap.
Member Data Documentation
constructQuery
Boolean constructQuery =false
definition
String definition =""
exposedType
String exposedType ="application/vnd.geojson"
fileextension
String fileextension ="json"
FLUSHTHRESHOLD
final Integer FLUSHTHRESHOLD =20 static
label
String label ="JSON"
Referenced by ResultFormatter.[static initializer]().
labelMap
Map<String, String> labelMap =new TreeMap<String, String>() static
Referenced by ResultFormatter.[static initializer]().
lastQueriedElemCount
Integer lastQueriedElemCount =0
mediatypes
final String [] mediatypes static
Initial value:
= {
                        "application/vnd.geo+json+ld",
                        "text/csv",
        }
mimeType
String mimeType ="text/plain"
Referenced by ResultFormatter.[static initializer]().
resultMap
Map<String,ResultFormatter> resultMap =new TreeMap<String, ResultFormatter>() static
Referenced by ResultFormatter.[static initializer](), and ResultFormatter.getFormatter().
urlformat
String urlformat ="json"