GeoSPARQL SRS Extension: WebService Class Reference
WebService Class Reference
Implements OGC API Features and WFS webservice functionality.
Public Member Functions
WebService () throws IOException
Constructor for this class.
Response openapiJSON ()
String queryService (@QueryParam("query") String query, @QueryParam("dataset") String dataset)
String queryService2 (@QueryParam("query") String query, @QueryParam("endpoint") String dataset)
String queryService2 (@QueryParam("query") String query, @QueryParam("endpoint") String dataset, @QueryParam("geojson") String geojson)
Response getCRSByURI (@Parameter(description="The URI of the CRS defined in RDF") @QueryParam("crsuri") String crsuri, @Parameter(description="The endpoint of the CRS definition") @QueryParam("endpoint") String crsendpoint, @Parameter(description="The return format") @QueryParam("returnformat") String returnformat)
Response getEligibleCRS (@Parameter(description="boundingbox to check the area of validity") @QueryParam("bbox") String bbox, @Parameter(description="The return format") @QueryParam("returnformat") String returnformat)
Response convertFeaturetoCRSDefinedinRDF (@Parameter(description="The URI of the CRS defined in RDF") @QueryParam("crsuri") String crsuri, @Parameter(description="The endpoint of the CRS definition") @QueryParam("endpoint") String crsendpoint, @Parameter(description="The return format") @QueryParam("returnformat") String returnformat)
Response convertFeaturetoCRSDefinedinRDF (@Parameter(description="The WKT String to convert") @QueryParam("wktstring") String wktstring)
Public Attributes
XMLStreamWriter xmlwriter
Static Public Attributes
static JSONObject triplestoreconf = null
static JSONObject wfsconf = null
static final MediaType openapijson =new MediaType("application", "vnd.oai.openapi+json;version=3.0")
static long milliesInDays = 24 * 60 * 60 * 1000
Package Attributes
String htmlHead
Detailed Description
Implements OGC API Features and WFS webservice functionality.
Constructor & Destructor Documentation
WebService()
WebService () throws IOException
Constructor for this class.
Loads configuration files and performs initializations.
Exceptions
IOException on error
{
         }
Member Function Documentation
convertFeaturetoCRSDefinedinRDF() [1/2]
Response convertFeaturetoCRSDefinedinRDF (@Parameter(description="The URI of the CRS defined in RDF") @QueryParam("crsuri") String crsuri, @Parameter(description="The endpoint of the CRS definition") @QueryParam("endpoint") String crsendpoint, @Parameter(description="The return format") @QueryParam("returnformat") String returnformat)
{
                 return null;
         }
convertFeaturetoCRSDefinedinRDF() [2/2]
Response convertFeaturetoCRSDefinedinRDF (@Parameter(description="The WKT String to convert") @QueryParam("wktstring") String wktstring)
{
                 try {
                         return Response.ok(CoordinateReferenceSystem.WKTToRDF(wktstring)).build();
                 } catch (FactoryException | IOException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 }
                 return Response.ok("").build();
         }
References CoordinateReferenceSystem.WKTToRDF().
getCRSByURI()
Response getCRSByURI (@Parameter(description="The URI of the CRS defined in RDF") @QueryParam("crsuri") String crsuri, @Parameter(description="The endpoint of the CRS definition") @QueryParam("endpoint") String crsendpoint, @Parameter(description="The return format") @QueryParam("returnformat") String returnformat)
{
                 return Response.ok(RDFCRSToWKT.getCRSFromTripleStore(crsuri, crsendpoint, returnformat)).build();
         }
References RDFCRSToWKT.getCRSFromTripleStore().
getEligibleCRS()
Response getEligibleCRS (@Parameter(description="boundingbox to check the area of validity") @QueryParam("bbox") String bbox, @Parameter(description="The return format") @QueryParam("returnformat") String returnformat)
{
                 return Response.ok(RDFCRSToWKT.getEligibleCRSFromTripleStore(bbox)).build();
                 //return getFeatureById(collectionid, featureid, style, format);
         }
References RDFCRSToWKT.getEligibleCRSFromTripleStore().
openapiJSON()
Response openapiJSON ()
{
                 System.out.println("OpenAPI JSON");
                 CloseableHttpClient httpClient = HttpClients.createDefault();
                 HttpGet request = new HttpGet(wfsconf.get("baseurl")+"/openapi.json");
                 CloseableHttpResponse response;
                 try {
                         response = httpClient.execute(request);
                         HttpEntity entity = response.getEntity();
                         String result = EntityUtils.toString(entity);
                         System.out.println(result);
                         response.close();
                         httpClient.close();
                         Response res=Response.status(Response.Status.OK).entity(result).build();//.type(OpenAPIMediaType.OA3_TYPE).build();
                         return res;
                 } catch (IOException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                         return null;//Response.ok("",OpenAPIMediaType.OA3_TYPE).build();
                 }
         }
queryService()
String queryService (@QueryParam("query") String query, @QueryParam("dataset") String dataset)
{
                 final String dir = System.getProperty("user.dir");
         System.out.println("current dir = " + dir);
                 return TripleStoreConnection.executeQuery(query,dataset);
         }
References TripleStoreConnection.executeQuery().
queryService2() [1/2]
String queryService2 (@QueryParam("query") String query, @QueryParam("endpoint") String dataset)
{
                 final String dir = System.getProperty("user.dir");
         System.out.println("current dir = " + dir);
                 return TripleStoreConnection.executeQuery(query,dataset);
         }
References TripleStoreConnection.executeQuery().
queryService2() [2/2]
String queryService2 (@QueryParam("query") String query, @QueryParam("endpoint") String dataset, @QueryParam("geojson") String geojson)
{
                 final String dir = System.getProperty("user.dir");
         System.out.println("current dir = " + dir);
                 return TripleStoreConnection.executeQuery(query,dataset,true);
         }
References TripleStoreConnection.executeQuery().
Member Data Documentation
htmlHead
String htmlHead package
milliesInDays
long milliesInDays = 24 * 60 * 60 * 1000 static
openapijson
final MediaType openapijson =new MediaType("application", "vnd.oai.openapi+json;version=3.0") static
triplestoreconf
JSONObject triplestoreconf = null static
wfsconf
JSONObject wfsconf = null static
xmlwriter
XMLStreamWriter xmlwriter