GeoSPARQL SRS Extension: AsGeoJSON Class Reference
AsGeoJSON Class Reference
Return the geometry as a GeoJSON element.
Public Member Functions
NodeValue exec (NodeValue arg0)
Detailed Description
Return the geometry as a GeoJSON element.
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0)
{
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(arg0);
             GeoJSONWriter writer = new GeoJSONWriter();
             GeoJSON json = writer.write(geometry.getXYGeometry());
             String jsonstring = json.toString();
             return NodeValue.makeString(jsonstring);
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
         }
References GeometryWrapper.extract(), and GeometryWrapper.getXYGeometry().
Referenced by TripleStoreConnection.executeQuery().